Reporting docs
postmanlabs/postman-docs pull request #2603
Opened 2020-08-21 09:05 UTC by sowmyaraj92

New branch updated with the reporting feature documentation.

2020-08-24 09:35 UTC, SueSmith requested changes
ok this looks like a lot of comments but it's basically language edits to match the docs style - the way the info is structured etc lgtm

give me a shout if you need any more info 🙂

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Open vs used slots__ used slots include any pending invitations sent or approved by a team admin
Not quite understanding this one, do the used ones include both pending and approved? If so can we reword to something like:

__Open vs used slots__ indicates unused slots vs invitations that are either pending or approved by a team admin

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +<img alt="active users" src="https://assets.postman.com/postman-docs/active-users.jpg" width="400px" height="300px"/>
the img looks stretched to me, could you try just setting the width and not the height to see if that sorts it?

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Team size over time__ is the size of the team over a period of time
let's either have periods at the end of all list items or none

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __SSO identity provider__ SSO services permit a user to use one set of login credentials (e.g., name/email and password) to access multiple applications. Specifies the SSO identity provider.
I'd reword to something like (and maybe link to /docs/administration/sso/intro-sso/):
__SSO identity provider__ is any SSO login you have configured for your team to access their Postman accounts.

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Plan__ is the current active plan the user has subscribed
"the user" > "you"

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Publicly documented collection__
"__Publicly documented collection__ indicates any collections or which your team has published the documentation"

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Active monitors__ is the total number of active monitors in team workspaces including private workspaces. "Active" monitors refer to any monitor that is scheduled to run.
Second sentence: "Any monitor currently scheduled to run is _active_."

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Requests sent in Postman__ is the requests sent manually in Postman and not any requests sent via Newmans, monitoring runs or the collection runner
* "and" > "but"
* "Newmans" > "Newman"
* comma before "or", so "...runs, or the..."

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +<img alt="request sent in postman" src="https://assets.postman.com/postman-docs/request-sent-in-postman.jpg" width="400px" height="450px"/>
same again for img if you lose the height attribute

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +<img alt="request sent in postman" src="https://assets.postman.com/postman-docs/request-sent-in-postman.jpg" width="400px" height="450px"/>
if you can do the same for all imgs

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Views of private documentation__ is the number of private documentation views
"is the number of times people have viewed your team's private documentation"

then similar for the public one, just making it more active

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +> In this example, the number of private documentation views for May 2020 is 1616 where as the number of public documentation views is 74,364.
"where as" > "while"
also I'd lose the comma in 74,364 because it looks inconsistent with the other number if that makes sense

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Empty workspaces__ with no collections in them
"are workspaces with no collections in them"

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Active workspaces__ with at least one revision during a recent period, not including personal workspaces
"with at least one" > "have at least one.."

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +The __Reports__ &gt; __All APIs__ report provides metrics, including API overview, total APIs, visualization on API development, and details of APIs with and without mocks, monitors, tests and docume
If we can reword the first sentence e.g. "The __Reports__ &gt; __All APIs__ report provides metrics including an overview of your total APIs, a visualization of API creation over time, and a separate view of your APIs with and without mocks, monitors, tests, and documentation."

"2" > "two"

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +API overview provides the following information:
"The API overview.."

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Total APIs__ is the total number of APIs created on Postman in all the team workspaces
"in Postman"

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __APIs updated in last 24 hours__ APIs ars considered active if there is some kind of activity/updation in the last 1 day
typo "ars"

if we can lose "updation"

"1" > "one"

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +For APIs created over a period of time, the user can access the total count of APIs on a monthly basis.
"the user" > "you"

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __APIs by schema type__ The information of defined APIs that are present(How many are OpenAPI3, GraphQL, Swagger etc) visualized using a pie chart
If you can try to standardize how you're doing these lists, for example make every one a complete sentence (e.g. this one starts capitalized after the bold bits but the previous ones don't) - and keep an eye open for typos like the missing space before the bracket 🙃 

In this case I'd change to "__APIs by schema type__ indicates APIs by the type of schema used to define them (OpenAPI, GraphQL, Swagger, etc) visualized as a pie chart."

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +## Team activity
If you can add "reports" to all headings in case people skim straight to a section, so "Team activity reports" here and similar in the other headings

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __APIs with mocks__ is the number of APIs associated with the team having mocks
"is the number of APIs your team has added mocks to"

- if you can try rewording all of these to be active like that

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +> In this example, the APIs with/without mocks, monitors, tests and documentation is visualized in percentages. Hover on the chart to view the API data in figures. From the chart, you can observe tha
"is visualized in percentages" > "are visualized by percentage"

"hover over"

"you can see that 20% of the APIs have documentation"

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +The __Reports__ &gt; __Private Network APIs__ provide an insight into total published APIs, pie-chart depicting APIs categorised by schema type and details of APIs with and without mocks, monitors, t
Can you try splitting this sentence up, it's a little long and confusing.. if you look at my suggestion for the "all apis" intro and try something similar

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __APIs by schema type__ The information of defined APIs that are present(How many are OpenAPI3, GraphQL etc) visualized using a pie chart
see note for previous schema type item - if you can apply the same changes I've suggested for that list here 👍

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +The __View reports by API__ provide the individual API view where you can enter the API name in the search box and generate the API report.
"generate a report on the API"

2020-08-24 09:35 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +> Click on __View reports by API__ > Enter __Reporting__ in the search box to view the above report.
"click on" > "click"

2020-08-24 12:11 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +API reports are different for users in the [Postman Business](#postman-business-plan) and [Enterprise](#postman-enterprise-plan) plans.
Done.

2020-08-24 12:12 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +## Postman enterprise plan
Done.

2020-08-24 12:15 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +The left navigation displays the different dashboard views to access the reports:
Done.

2020-08-24 12:15 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +The __Reports__ &gt; __Team Activity__ report provides team level metrics, including team overview, team size, billing details, team activity and workspaces. Click to view the details on a particular
Done.

2020-08-24 12:17 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Team overview__
Done.

2020-08-24 12:19 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Invitations sent__ is the total number of invitations which was sent
Done

2020-08-24 12:20 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Open vs used slots__ used slots include any pending invitations sent or approved by a team admin
done

2020-08-24 12:23 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Team size over time__ is the size of the team over a period of time
Will remove the periods at the end of all list items. 
Done.

2020-08-24 12:23 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __SSO identity provider__ SSO services permit a user to use one set of login credentials (e.g., name/email and password) to access multiple applications. Specifies the SSO identity provider.
Done.

2020-08-24 12:24 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Plan__ is the current active plan the user has subscribed
Done

2020-08-24 12:24 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Publicly documented collection__
Changes made.

2020-08-24 12:25 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Requests sent in Postman__ is the requests sent manually in Postman and not any requests sent via Newmans, monitoring runs or the collection runner
Done

2020-08-24 12:27 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Active monitors__ is the total number of active monitors in team workspaces including private workspaces. "Active" monitors refer to any monitor that is scheduled to run.
done

2020-08-24 12:28 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Views of private documentation__ is the number of private documentation views
Done.

2020-08-24 12:28 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +> In this example, the number of private documentation views for May 2020 is 1616 where as the number of public documentation views is 74,364.
Done.

2020-08-24 12:28 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Empty workspaces__ with no collections in them
Done.

2020-08-24 12:29 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Active workspaces__ with at least one revision during a recent period, not including personal workspaces
Done

2020-08-24 12:29 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +The __Reports__ &gt; __All APIs__ report provides metrics, including API overview, total APIs, visualization on API development, and details of APIs with and without mocks, monitors, tests and docume
Done

2020-08-24 12:30 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +API overview provides the following information:
Done

2020-08-24 12:31 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __APIs updated in last 24 hours__ APIs ars considered active if there is some kind of activity/updation in the last 1 day
Done

2020-08-24 12:31 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +For APIs created over a period of time, the user can access the total count of APIs on a monthly basis.
done

2020-08-24 12:32 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __APIs by schema type__ The information of defined APIs that are present(How many are OpenAPI3, GraphQL, Swagger etc) visualized using a pie chart
Changes made.

2020-08-24 12:33 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __APIs with mocks__ is the number of APIs associated with the team having mocks
done

2020-08-24 12:34 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +> In this example, the APIs with/without mocks, monitors, tests and documentation is visualized in percentages. Hover on the chart to view the API data in figures. From the chart, you can observe tha
done

2020-08-24 12:34 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __APIs by schema type__ The information of defined APIs that are present(How many are OpenAPI3, GraphQL etc) visualized using a pie chart
done

2020-08-24 12:35 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +The __View reports by API__ provide the individual API view where you can enter the API name in the search box and generate the API report.
done

2020-08-24 12:35 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +> Click on __View reports by API__ > Enter __Reporting__ in the search box to view the above report.
done

2020-08-24 12:36 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +The __Reports__ &gt; __Private Network APIs__ provide an insight into total published APIs, pie-chart depicting APIs categorised by schema type and details of APIs with and without mocks, monitors, t
done

2020-08-24 12:37 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +The __View reports by API__ provide the individual API view where you can enter the API name in the search box and generate the API report.
done

2020-08-24 12:37 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +> Click on __View reports by API__ > Enter __Reporting__ in the search box to view the above report.
done

2020-08-24 12:37 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __APIs by schema type__ The information of defined APIs that are present(How many are OpenAPI3, GraphQL etc) visualized using a pie chart
done

2020-08-24 12:37 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +The __Reports__ &gt; __Private Network APIs__ provide an insight into total published APIs, pie-chart depicting APIs categorised by schema type and details of APIs with and without mocks, monitors, t
done

2020-08-24 12:37 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +> In this example, the APIs with/without mocks, monitors, tests and documentation is visualized in percentages. Hover on the chart to view the API data in figures. From the chart, you can observe tha
done

2020-08-24 12:38 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +For APIs created over a period of time, the user can access the total count of APIs on a monthly basis.
done

2020-08-24 12:38 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __APIs updated in last 24 hours__ APIs ars considered active if there is some kind of activity/updation in the last 1 day
done

2020-08-24 12:38 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __APIs with mocks__ is the number of APIs associated with the team having mocks
done

2020-08-24 12:40 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Total APIs__ is the total number of APIs created on Postman in all the team workspaces
done

2020-08-24 12:40 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +API overview provides the following information:
done

2020-08-24 12:41 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +The __Reports__ &gt; __All APIs__ report provides metrics, including API overview, total APIs, visualization on API development, and details of APIs with and without mocks, monitors, tests and docume
done

2020-08-24 12:41 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Active workspaces__ with at least one revision during a recent period, not including personal workspaces
done

2020-08-24 12:41 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Empty workspaces__ with no collections in them
done

2020-08-24 12:47 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +> In this example, the number of private documentation views for May 2020 is 1616 where as the number of public documentation views is 74,364.
done

2020-08-24 12:54 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Views of private documentation__ is the number of private documentation views
done

2020-08-24 12:55 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Requests sent in Postman__ is the requests sent manually in Postman and not any requests sent via Newmans, monitoring runs or the collection runner
done

2020-08-24 12:55 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Active monitors__ is the total number of active monitors in team workspaces including private workspaces. "Active" monitors refer to any monitor that is scheduled to run.
done

2020-08-24 12:55 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Publicly documented collection__
done

2020-08-24 12:56 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Plan__ is the current active plan the user has subscribed
done

2020-08-24 12:56 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __SSO identity provider__ SSO services permit a user to use one set of login credentials (e.g., name/email and password) to access multiple applications. Specifies the SSO identity provider.
done

2020-08-24 12:58 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Team size over time__ is the size of the team over a period of time
done

2020-08-24 13:20 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +<img alt="request sent in postman" src="https://assets.postman.com/postman-docs/request-sent-in-postman.jpg" width="400px" height="450px"/>
done

2020-08-24 13:35 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +<img alt="active users" src="https://assets.postman.com/postman-docs/active-users.jpg" width="400px" height="300px"/>
done

2020-08-24 13:35 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +## Team activity
done

2020-08-25 09:06 UTC, SueSmith requested changes
thanks for working through all those @sowmyaraj92 🏆 just a couple wee additional requests mainly on the search keyword..

2020-08-25 09:06 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +The reporting feature enables you to access reports on your APIs. Your API reports will include different information if you're on an [Enterprise](#enterprise-reports) or [Business](#business-reports
If you could just lose this first sentence - if we're adding keywords let's try and just build them in naturally to the existing text 👍

2020-08-25 09:06 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +## All APIs reports
this heading reads a bit weirdly using the exact ui text so if we can just go for "All API reports" even though it's not what's in the ui

2020-08-25 09:06 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +## Private Network APIs reports
same as prev heading if we can just use "Private Network API reports"

2020-08-25 09:06 UTC, SueSmith commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +Billing provides the following information:
on each of these you could change it to e.g. "Billing reporting provides..."

same for "Team activity reporting" and the rest if you don't mind

2020-08-25 09:20 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +Billing provides the following information:
done

2020-08-25 09:21 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +## Private Network APIs reports
done

2020-08-25 09:22 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +## All APIs reports
even I felt the same, changes have been made

2020-08-25 09:22 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +> [__API reports are available on Postman Enterprise and Business plans.__](https://www.postman.com/pricing)
woop woop! Done

2020-08-25 09:27 UTC, SueSmith approved these changes
lgtm! 🎉

2020-08-25 09:27 UTC, merged