Add github bulk import
postmanlabs/postman-docs pull request #2642
Opened 2020-09-18 08:10 UTC by claireriley

Added section for release coming up early next week.

@umeshp7 I used the screenshot with the failed import as a placeholder—do you mind sending me a fully successful screenshot?

2020-09-18 08:18 UTC, umeshp7 commented
Yes, I will send the screenshot for successful Import completed screen.

2020-09-18 09:59 UTC, sowmyaraj92 commented on src/pages/docs/getting-started/importing-and-exporting-data.md
> +You will receive confirmation once the import has completed.
I'd change "receive confirmation" to "receive a confirmation once the import is complete"

2020-09-18 10:00 UTC, sowmyaraj92 requested changes
Hey @claireriley! This looks great 🥳 Just one tiny suggestion.

2020-09-22 05:28 UTC, umeshp7 commented on src/pages/docs/getting-started/importing-and-exporting-data.md
> +    * [Importing GitHub repositories](#importing-github-repositories)
Should this be "Importing `via` GitHub repositories" ? @claireriley

2020-09-22 05:28 UTC, umeshp7 commented
Added a small comment, see if it makes to you. Everything else looks good to me! 🎉 @claireriley

2020-09-22 05:52 UTC, sowmyaraj92 approved these changes
Lgtm! 🥳👏🏻

2020-09-22 12:14 UTC, merged