New direct link for API key creation added on top of alternative dash…
postmanlabs/postman-docs pull request #2647
Opened 2020-09-22 13:24 UTC by carmelag

I added the direct link to the API Key page on top of the section "Generating a Postman API Key". The procedure is the same as the dashboard's one, so the pictures previously used for the dashboard procedure are still valid also for the direct link. 

I moved the dashboard procedure at the end of the section, considering it as an alternative way to achieve the purpose of creating a new API Key.

@SueSmith please let me know what you think and if this approach works for you.
Thanks!

2020-09-23 08:54 UTC, SueSmith requested changes
Thank you so much for the contribution @carmelag! 🙌 A couple of wee requests if you don't mind.. 🙏 

Also if you add "Fixes #2635" to your PR description text that will automatically close the issue when we get your great PR merged.. 🙂

2020-09-23 08:54 UTC, SueSmith commented on src/pages/docs/developer/intro-api.md
> +## Generating a Postman API Key
We tend to use sentence case for subheadings so if you could revert this change that would be great

2020-09-23 08:54 UTC, SueSmith commented on src/pages/docs/developer/intro-api.md
> +To generate a new API Key go to the [Postman API keys page](https://web.postman.co/settings/me/api-keys).
I think I'd keep the instructions in the same place so that the flow is reliable regardless of how the person chooses to access the key it if that makes sense, the link isn't the preferred route or anything, just one option..

2020-09-25 21:35 UTC, carmelag commented on src/pages/docs/developer/intro-api.md
> +To generate a new API Key go to the [Postman API keys page](https://web.postman.co/settings/me/api-keys).
Hi @SueSmith I will apply the required changes during the weekend. Thanks for your quick feedback.
So the order will stay the same:  "UI approach" and "Direct Link approach" (as an alternative).
Is that correct?

2020-09-28 09:27 UTC, SueSmith commented on src/pages/docs/developer/intro-api.md
> +To generate a new API Key go to the [Postman API keys page](https://web.postman.co/settings/me/api-keys).
Hi! Yep I think I'd just build it into the existing text, e.g. starting the section with something like:

```
You can generate an API key directly from your [Postman API Keys](https://go.postman.co/settings/me/api-keys) page or by navigating to your dashboard.
```

Then just continuing with the original instructions.. 

(Also I think the link shortcut may have changed 😭 so if you don't mind changing the link from `web.postman` to `go.postman` as I have in this example that would be great.) 

Sound reasonable? Thanks again!

2020-09-29 12:02 UTC, carmelag commented on src/pages/docs/developer/intro-api.md
> +To generate a new API Key go to the [Postman API keys page](https://web.postman.co/settings/me/api-keys).
Hi @SueSmith I applied the changes as you suggested. Could you please have a look at the final version after last commits? 

Thanks

2020-09-30 09:45 UTC, SueSmith approved these changes
LGTM! 👍

2020-09-30 09:46 UTC, SueSmith commented
Thanks so much for contributing @carmelag! 🙌 🎉 🚀

2020-09-30 09:46 UTC, merged