Team merge
postmanlabs/postman-docs pull request #2662
Opened 2020-10-02 09:07 UTC by SueSmith

Not sure why the changes pushed to a new branch, something to do with collaborator status on the fork/branch maybe..

Anyway @carolin-postman and @claireriley could you give this a once over? cc @lashcrafty

2020-10-02 15:25 UTC, carolin-postman requested changes
Thank you for reviewing @SueSmith. Just found something minor.

2020-10-02 15:25 UTC, carolin-postman commented on src/pages/docs/administration/team-merge.md
> +* Mocks and monitors—you would need to be recreate these.
remove the extra "be"

2020-10-02 15:38 UTC, SueSmith commented on src/pages/docs/administration/team-merge.md
> +* Mocks and monitors—you would need to be recreate these.
gah sorted

2020-10-07 22:24 UTC, carolin-postman commented
@claireriley - can this be reviewed and published by latest EOW? Let me know what I can do to help move this along. Thanks. 
cc @SueSmith

2020-10-10 02:04 UTC, claireriley requested changes
@SueSmith let me know if I can help with edits!

2020-10-10 02:04 UTC, claireriley commented on src/pages/docs/administration/team-merge.md
> +Your previous links will break since the old team is disabled. New documentation URLs will need to be generated when collections are [re-published from your new team pages](/docs/publishing-your-api/
@carolin-postman do admins need to remove custom domains from their old teams prior to moving to a new team if they want to use the same URL for same docs? will there be an issue if they don't?

2020-10-10 02:04 UTC, claireriley commented on src/pages/docs/administration/team-merge.md
> +Once the last person has left, the team is automatically disabled. If there is only one admin remaining on the team, they will automatically inherit all the team workspaces data (collections and envi
"in which they" -> "and" ?

2020-10-10 02:04 UTC, claireriley commented on src/pages/docs/administration/team-merge.md
> +All collections in your personal workspace and any workspaces that you have joined, in addition to environments, globals, and header presets, are included when you export a data-dump.
We could link /docs/getting-started/importing-and-exporting-data/#exporting-data-dumps again here

2020-10-10 02:04 UTC, claireriley commented on src/pages/docs/administration/team-merge.md
> +> Feel free to reach out to [Postman support](http://postman.com/support) if you have any questions or run into any issues setting up Postman for your team.
I'd remove "Feel free to"

2020-10-10 02:04 UTC, claireriley commented on src/pages/docs/administration/team-merge.md
> +[Configure SSO](/docs/administration/sso/admin-sso/) if you are subscribed to the Business or Enterprise plan.
"to the Business or Enterprise plan" -> "to a Postman Business or Enterprise plan"

2020-10-13 21:47 UTC, carolin-postman commented on src/pages/docs/administration/team-merge.md
> +Your previous links will break since the old team is disabled. New documentation URLs will need to be generated when collections are [re-published from your new team pages](/docs/publishing-your-api/
@claireriley  - Good question. 

If they are moving to a new team and want to take the domain with them then they have to remove the domain and change it to anything else for it to be free for them to claim on the new team. 

Feel free to reword that and include in the next version.

2020-10-27 10:03 UTC, SueSmith commented
@carolin-postman sorry this keeps slipping down the list.. I've added you as a collaborator to the repo, can you access this pr now?

2020-10-28 22:47 UTC, carolin-postman commented
@SueSmith I can access now, that did it, thank you! I managed to make some of the smaller edits. I trust you and @claireriley on modifying the rest as you see fit and publishing afterwards. Thanks again for your help.

2020-11-02 12:37 UTC, SueSmith commented
@claireriley almost all resolved with a handful of little outstanding things, think you could take a last pass so we can get this published?

2020-11-11 15:39 UTC, carolin-postman commented
@claireriley @SueSmith - just checking in on this.

2020-11-16 02:26 UTC, claireriley approved these changes

2020-11-16 02:29 UTC, merged

2020-11-16 02:30 UTC, claireriley commented
@SueSmith @carolin-postman made a couple last changes and merged—it'll be published early this week with the v2 and public workspaces releases!

2020-11-16 17:40 UTC, carolin-postman commented
Thanks @claireriley !