PR settings
postmanlabs/postman-docs pull request #2664
Opened 2020-10-05 16:55 UTC by sowmyaraj92

Assign merge checks for a pull request before approving changes.

2020-10-07 00:47 UTC, claireriley requested changes
Looks good! Few suggested changes

2020-10-07 00:47 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +If you are on a business or enterprise plan, the pull request settings will be available in the __Manage roles__ section of a collection.
I would make this a bit more direct, like the first sentence [here](https://learning.postman.com/docs/designing-and-developing-your-api/monitoring-your-api/setting-up-monitor/#using-static-ip).

Also want to capitalize Business and Enterprise

2020-10-07 00:47 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +In the Postman app, select the collection in the __Collections__ sidebar and click the __View more actions (...)__ button. Select __Manage roles__. Choose __Editor__ option for the users you want to
`click the __View more actions (...)__ button.`

->

`click __View more actions (...)__.`

2020-10-07 00:47 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +In the Postman app, select the collection in the __Collections__ sidebar and click the __View more actions (...)__ button. Select __Manage roles__. Choose __Editor__ option for the users you want to
I would combine the last two sentences to be 

`Select __Manage roles__, then select __Editor__ for the users you want to provide editor access to`

2020-10-07 00:47 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +You need to have __Editor__ access on a collection to merge changes. If you have __Viewer__ access to a collection, you will see a warning icon while adding the reviewers to a pull request.
I might use "must" instead of "need to" here, optional though

2020-10-07 00:47 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +You need to have __Editor__ access on a collection to merge changes. If you have __Viewer__ access to a collection, you will see a warning icon while adding the reviewers to a pull request.
Remove "the" before "reviewers"

2020-10-07 00:47 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +Once you've created the pull request, you can assign merge checks before approving changes.
Remove contraction -> "you've" to "you have"

2020-10-07 00:47 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +* __Up to date with all changes to this collection__ : You can't merge the pull request if a forked branch is behind the destination branch.
Remove contraction

2020-10-07 00:47 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +You have three different types of checks that you can enable for a pull request, and they are:
I would adjust this to make it a bit more succinct

> There are three different types of checks that you can enable for a pull request:

2020-10-07 00:47 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +* __Approved once__: You need atleast one approval to merge the pull request.
Add space

2020-10-07 00:47 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +* __Approved once__: You need atleast one approval to merge the pull request.
Could we change "you" to "users" in this list? Would that make sense? or "team members" or "viewers" if applicable

2020-10-07 00:47 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +> If you do not have editor access to the collection, the __Merge__ icon will be disabled.
`the __Merge__ icon will be disabled` -> `__Merge__ will be disabled`

2020-10-08 06:18 UTC, sowmyaraj92 reviewed
Hey @claireriley, I have made the requested changes : )

2020-10-10 03:07 UTC, claireriley approved these changes
Hey @sowmyaraj92 ! Few very small edits, I'll approve now so you'll be good to merge once you've made those.

2020-10-10 03:07 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +Pull request settings are available on Postman Business and Enterprise plans in the __Manage roles__ section of a collection.
Small thing but I'd capitalize "roles" like how it is in the screenshot

2020-10-10 03:07 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +* __Approved once__ : You need atleast one approval to merge the pull request.
add space to "atleast"

2020-10-10 03:07 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +> If you do not have editor access to the collection, the __Merge__ will be disabled.
I'm wondering if "the __Merge__" might be better stated as "the option to __Merge__" ?

2020-12-03 03:58 UTC, claireriley commented
@sowmyaraj92 are we ready to merge this one or are we waiting on a release?

2020-12-03 05:08 UTC, sowmyaraj92 commented
> @sowmyaraj92 are we ready to merge this one or are we waiting on a release?

@claireriley We are waiting for the release, minor enhancement is coming up for this- will add that as well before we go ahead and merge.

2020-12-16 11:27 UTC, sowmyaraj92 commented
> > @sowmyaraj92 are we ready to merge this one or are we waiting on a release?
> 
> @claireriley We are waiting for the release, minor enhancement is coming up for this- will add that as well before we go ahead and merge.

@claireriley I have updated the flow and screenshots, do give it a quick look - need to merge the PR as this is up on production.

2020-12-16 11:40 UTC, merged