Added info for public workspaces
postmanlabs/postman-docs pull request #2665
Opened 2020-10-07 16:15 UTC by arlemi

I've added a couple of line in the collaboration section for managing workspaces, will add more as we add new features.

2020-10-07 16:34 UTC, SueSmith commented
@arlemi I'm confused, is the stuff in this PR publicly available to users right now? Or is this for a future release?

2020-10-08 09:09 UTC, arlemi commented
@SueSmith My understanding was that it was going to be available today but looks like I was wrong...

2020-10-08 09:13 UTC, SueSmith commented
😂 I am so confused rn

2020-10-10 03:22 UTC, claireriley requested changes
Few small items to look into before publishing (which I assume will be a bit later due to the segmented release but 🤷‍♀️ )

2020-10-10 03:22 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +You can access Personal, Team, and Private workspaces using the Workspace selector at the top of the Postman app.
I might not capitalize "Workspace selector"

2020-10-10 03:22 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +To see and edit your workspace details (e.g. name, description...), from the Postman app workspace selector, hover over a workspace, click **...**, and select **View Details**. You can also view the
I might adjust the first sentence to something like 

`To view and edit your workspace details (e.g. name, description), navigate to the workspace selector and hover over a workspace. Then, click **...** and select **View Details**.`

2020-10-10 03:22 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +You can access Public workspaces from the [**Workspace** category in the API Network](https://explore.postman.com/workspaces).
are we branding "Public workspaces"/have we decided on a capitalization? May want to ask Brandon if we should add to https://postmanlabs.atlassian.net/l/c/9eiXG281 and we can update mentions in this doc/others for consistency

2020-10-10 03:22 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +You can access Public workspaces from the [**Workspace** category in the API Network](https://explore.postman.com/workspaces).
`**Workspace** category` -> `**Workspaces** category`

2020-10-10 03:22 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +You can access Personal, Team, and Private workspaces using the Workspace selector at the top of the Postman app.
I'd probably also remove capitals from "Personal, Team, and Private" as they aren't capitalized earlier in the page

2021-03-10 09:41 UTC, closed without merging