Update intro-integrations.md
postmanlabs/postman-docs pull request #2678
Opened 2020-10-16 23:31 UTC by jerry-li-dev

Added information on static IP address support.

2020-10-19 04:35 UTC, shashankawasthi88 commented on src/pages/docs/integrations/intro-integrations.md
> +- [GitLab Custom Domain Backup](https://learning.postman.com/docs/integrations/available-integrations/gitlab/#backup-your-postman-collections-to-gitlab-on-a-custom-domain)
Can we have general instructions here too? As it is common across all the Integrations which support static IPs.

2020-10-20 06:07 UTC, shashankawasthi88 commented on src/pages/docs/integrations/intro-integrations.md
> +You can use static IP addresses to enable integrations that need to access hosted (private) networks behind firewalls that require whitelisted IP addresses. You will need to whitelist the static IP `
Same comment for All Postman network calls.

2020-10-21 18:13 UTC, claireriley requested changes
Looks good—few small notes! 😄

2020-10-21 18:13 UTC, claireriley commented on src/pages/docs/integrations/intro-integrations.md
> +All calls for each integration will come from this IP address. Whitelisting this IP address will allow the integrations work as expected.
"allow the integrations work" -> "allow the integrations to work"

2020-10-21 18:13 UTC, claireriley commented on src/pages/docs/integrations/intro-integrations.md
> +US East: `3.212.102.200`
I might put this in a bullet point just so it's indented

2020-10-21 18:13 UTC, claireriley commented on src/pages/docs/integrations/intro-integrations.md
> +Postman supports implementing static IP addresses for the following integration services:
"integration services" I'd consider just "integrations"

2020-10-21 18:13 UTC, claireriley commented on src/pages/docs/integrations/intro-integrations.md
> +All calls for each integration will come from this IP address. Whitelisting this IP address will allow the integrations work as expected.
I might clarify the first sentence—I assume in order for this to happen they need to select this option when setting up the integration? I would briefly mention that's a condition e.g. "Once you ..., all calls ..."

2020-10-23 00:21 UTC, claireriley approved these changes
Two letters to adjust! Looks good so I'm approving, you can make that small change and then merge to develop!

2020-10-23 00:21 UTC, claireriley commented on src/pages/docs/integrations/intro-integrations.md
> +You can use static IP addresses to enable integrations and custom webhooks for Postman collections backups that need to access hosted (private) networks behind firewalls that require whitelisted IP a
Two tiny things—

- I think the rule is if "collections" is preceded by "Postman", we want to capitalize the C
- I think we want to remove the s on "collections"

2020-10-23 19:32 UTC, merged