Update github.md
postmanlabs/postman-docs pull request #2679
Opened 2020-10-17 00:19 UTC by jerry-li-dev

- Added section to call out static ip support.

- Need instructions for public users

2020-10-19 04:32 UTC, shashankawasthi88 commented on src/pages/docs/integrations/available-integrations/github.md
> +> If your network is behind a firewall that requires preapproved IP addresses, you will need to use a static IP address to enable backups to Github on custom domains.
Can we reword it saying that "you will need to whitelist the static IP XXX in your firewall to enable the backup... " - "need to use does not give a very clear idea"

2020-10-20 06:04 UTC, shashankawasthi88 commented on src/pages/docs/integrations/available-integrations/github.md
> +> If your network is behind a firewall that requires whitelisted IP addresses, you will need to use a static IP address to enable backups to Github on custom domains.
Same comments as the other file, All network calls needs to be corrected everywhere. Also "backup to Github" - it should be GitHub, I believe.

2020-10-21 18:24 UTC, claireriley requested changes
Just formatting 😄

2020-10-21 18:24 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/github.md
> +
Same recommendation as the GitLab one—I think we want to break this into a subsection so it's not all condensed in a note

2020-10-23 00:24 UTC, claireriley approved these changes
One small suggestion! LGTM and feel free to merge when ready

2020-10-23 00:24 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/github.md
> +  Contact your IT team to whitelist the following static IP in your firewall to enable collection backup integrations:
Could we switch
> to enable collection backup integrations:

to

> to enable collection backups to GitHub

2020-10-23 19:31 UTC, merged