Update gitlab.md
postmanlabs/postman-docs pull request #2680
Opened 2020-10-17 00:24 UTC by jerry-li-dev

- Added called call out about static ip

- Need instructions for public users

2020-10-19 04:33 UTC, shashankawasthi88 commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +> If your network is behind a firewall that requires preapproved IP addresses, you will need to use a static IP address to enable backups to GitLab on custom domains.
Same as the GitHub comment

2020-10-20 06:01 UTC, shashankawasthi88 commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +You will need to whitelist the static IP `3.212.102.200` in your firewall to enable data backup integrations. All Postman network calls to your domain will come from this IP address. Whitelisting thi
"to enable data back up..." - we should position this as collection backup and not data backup, also "allow the integrations work as expected " - I think it should be Integrations with capitalized "I" - you might want to check this with others in the doc team.

2020-10-21 18:23 UTC, claireriley requested changes
I think we'll want to adjust styling on this one a bit, try it out and ping me to re-review!

2020-10-21 18:23 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +>All calls for this integration will come from this IP address. Whitelisting this IP address will allow the integrations work as expected.
This is quite long as a note and a bit confusing on the page since it all squishes together. Maybe you could break it into a subsection or consider cutting it down and linking to the section on the main integrations page? I'd probably go with the first option, but whatever looks/reads best is good!

2020-10-23 00:30 UTC, claireriley requested changes
Few small changes, slack me when you've got them in and I'll approve 😄

2020-10-23 00:30 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +  [![gitlab add](https://assets.postman.com/postman-docs/GitLab_Custom_Add1.png)](https://assets.postman.com/postman-docs/GitLab_Custom_Add1.png)
Could you add a tiny border to the screenshots on this page? See https://github.com/postmanlabs/postman-docs/blob/develop/DOCS_STYLE_GUIDE.md#images

2020-10-23 00:30 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +    Contact your IT team to whitelist the following static IP in your firewall to enable collection backup integrations:
Would also update end to "to enable collection backups to GitLab" to be specific for the page

2020-10-23 00:30 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +1. Click the **Add Integration** button to enter your Gitlab token to start the integration.
No "button"! Just 

> Click **Add Integration** to

2020-10-23 00:30 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +1. Click the **Add Integration** button to enter your Gitlab token to start the integration.
Also missed the "Gitlab" last time around, we'll want that to be "GitLab"

2020-10-26 23:30 UTC, claireriley approved these changes
LGTM!

2020-10-26 23:31 UTC, merged