Update webhooks.md
postmanlabs/postman-docs pull request #2682
Opened 2020-10-19 20:40 UTC by jerry-li-dev

Added instructions for static IP

2020-10-20 05:56 UTC, shashankawasthi88 commented on src/pages/docs/integrations/webhooks.md
> +   You will need to whitelist the static IP `3.212.102.200` in your firewall to enable data backup integrations. All Postman network calls to your domain will come from this IP address. Whitelisting
"All Postman network calls to your domain...." - this might be misleading, not all calls are coming from this IP. We might want to say that all calls to the webhook will be coming from this IP

2020-10-20 10:28 UTC, shashankawasthi88 commented on src/pages/docs/integrations/webhooks.md
> +   You will need to whitelist the static IP `3.212.102.200` in your firewall to enable data backup integrations. All Postman network calls to your domain will come from this IP address. Whitelisting
@jerry-li-dev we should use this format for listing the static IP - https://learning.postman.com/docs/designing-and-developing-your-api/monitoring-your-api/using-static-IPs-to-monitor/ - this specifies the region with the IP. This should be followed across all places we add the IP in documentation

2020-10-21 18:26 UTC, claireriley requested changes
Let me know if you would like any help/feedback and you can re-request my review 🙂

2020-10-21 18:26 UTC, claireriley commented on src/pages/docs/integrations/webhooks.md
> +   >All calls for this webhook will come from this IP address. Whitelisting this IP address will allow the integrations work as expected.
And same format thing as the other two 😅

2020-10-22 07:47 UTC, jerry-li-dev commented on src/pages/docs/integrations/webhooks.md
> +   >All calls for this webhook will come from this IP address. Whitelisting this IP address will allow the integrations work as expected.
I have moved this set of information to the top since it is information that is relevant to the entire topic of using custom webhooks.

2020-10-23 00:32 UTC, claireriley approved these changes
Minor wording change, feel free to add then merge!

2020-10-23 00:32 UTC, claireriley commented on src/pages/docs/integrations/webhooks.md
> +Contact your IT team to whitelist the following static IP in your firewall to enable collection backup integrations:
"to enable collection backup integrations" -> "to enable backups to webhooks"

2020-10-23 03:05 UTC, merged