Public workspaces docs
postmanlabs/postman-docs pull request #2700
Opened 2020-11-12 16:14 UTC by sowmyaraj92

* Creating workspaces
* Creating and managing public workspaces
* Fork Information

2020-11-16 03:33 UTC, claireriley requested changes
Big PR 😮 I know it looks like a lot of comments, but it's largely just minor wording suggestions. These additions look great!

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md
> +[![Email notification](https://assets.postman.com/postman-docs/email-notification-public-workspace.jpg)](https://assets.postman.com/postman-docs/email-notification-public-workspace.jpg)
Can we blur out the "beta" part of the link?

Whoever owns these emails really needs to update that address and company name 😂 that's like 4 years old

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md
> +Once you make a workspace public, all entities within that workspace become public through the workspace. You need to be a workspace __admin__ to change the visibility of a workspace to public. Withi
"become public" -> "become publicly accessible" maybe?

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md
> +Once you make a workspace public, all entities within that workspace become public through the workspace. You need to be a workspace __admin__ to change the visibility of a workspace to public. Withi
Can you add a link to "workspace admin" that goes to the workspace roles section on the roles page?

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md
> +> You cannot convert a private workspace directly to public, but you can change a private workspace into regular team workspace and then make it public.
"into regular" -> "into a regular"

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +You can access personal, team, and private workspaces using the workspace selector at the top of the Postman app.
"at the top of the Postman app" -> "at the top of Postman"

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +You can access Public workspaces from the [**Workspaces** category in the API Network](https://explore.postman.com/workspaces).
I think we want no capitalization on "Public" here

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +You can access Public workspaces from the [**Workspaces** category in the API Network](https://explore.postman.com/workspaces).
"from" maybe "via"?

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +Open your workspace in the Postman app by selecting it from the workspace dropdown in the left. To add collaborators, go ahead and click __Invite__ at the top in the right.
", go ahead and click __Invite__ at the top in the right."

I'd adjust to

", click __Invite__ at the top right."

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +You can share a Public workspace by sharing its URL directly. To access the public profile URL, navigate to __Your Team__ > Click __View Team Settings__.
Since it's short, I might adjust "navigate to __Your Team__ > Click __View Team Settings__." to "navigate to __Your Team__, then click __View Team Settings__."

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +> To leave a public workspace, select the `...` on the right corner of the workspace overview and select __Leave workspace__. Click __Leave__ button to leave the workspace.
"and select __Leave workspace__" -> "and __Leave workspace__"

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +> To leave a public workspace, select the `...` on the right corner of the workspace overview and select __Leave workspace__. Click __Leave__ button to leave the workspace.
"Click __Leave__ button to leave the workspace."

maybe instead something like

"Click __Leave__ to finalize leaving the workspace."

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +To share a collection, open it in __Collections__ on the left of the app, and choose __Share Collection__ from the drop-down menu or overview.
I might say "via" instead of "in"

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +To share a collection, open it in __Collections__ on the left of the app, and choose __Share Collection__ from the drop-down menu or overview.
I'd remove "of the app" (if left looks odd alone, could consider "left-hand side", I think both would work here)

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +Click the `...` on the right corner of the workspace overview you want to delete and select __Delete Workspace__.
" you want to delete and "

maybe ->

" , then "

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +Confirm that you wish to delete the workspace — it will no longer be available.
maybe "following this action" or something of the like at the end?

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +> Public workspaces cannot be deleted, you need to change its visibility and then delete it.
"Public workspaces cannot be deleted, you need to change its visibility and then delete it"

maybe this? ->

"Public workspaces must have their visibility reverted in order to be deleted."

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +If you try to delete a public workspace by clicking `...` on the right corner of the workspace overview, the option to delete will be greyed out.
I'm not sure this line is necessary, hopefully the app UI will eventually have a note to suggest the above

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +Click `...` next to the workspace you want to update, and select __Manage Members__.
I think we still want "..."s as bold versus formatted as inline code, but we can talk about this and decide officially for the style guide

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +Being an admin, you have the permission to add/remove any member from a public workspace. To add members to a public workspace, navigate to the __Members__ section, enter an email address, click __Ad
"add/remove" -> "add and remove"

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
> +Being an admin, you have the permission to add/remove any member from a public workspace. To add members to a public workspace, navigate to the __Members__ section, enter an email address, click __Ad
"click __Add__ to the team and click __Save__"

->

"click __Add__ to the team, then __Save__"

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +To fork a collection within a public workspace, you must enable your public profile. Navigate to __Edit Profile__ and enable __Make Profile Public__. The username should consist of only alphabets, hy
"The username" -> "Your username"

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +To fork a collection within a public workspace, you must enable your public profile. Navigate to __Edit Profile__ and enable __Make Profile Public__. The username should consist of only alphabets, hy
"only alphabets, hyphens and numbers"

->

"only alphanumeric characters and hyphens."

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +To fork a collection within a public workspace, you must enable your public profile. Navigate to __Edit Profile__ and enable __Make Profile Public__. The username should consist of only alphabets, hy
I think " -" needs to be "—"

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +<img src="https://assets.postman.com/postman-docs/enable-public-profile.jpg" alt="Enable public profile" width="350px"/>
I would blur out "beta" here as well!

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +Fork information provides information about forks and the users who have created them. You will be able to identify the users who are actively consuming/contributing to your APIs. Click the fork coun
I might adjust this to avoid saying "information" twice if possible

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +Fork information provides information about forks and the users who have created them. You will be able to identify the users who are actively consuming/contributing to your APIs. Click the fork coun
"consuming/contributing" -> "consuming and contributing"

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +Fork information provides information about forks and the users who have created them. You will be able to identify the users who are actively consuming/contributing to your APIs. Click the fork coun
"the active forks" -> "active forks"

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +Under forked by, clicking on a user takes you to their public profile.
I'd consider making this a note (>) and switch it around to something like "You can click on a user under **Forked by** to view their public profile."

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/getting-started/creating-your-first-workspace.md
> +To access your workspaces, use the dropdown menu at the left of Postman. You can search for existing workspaces using the __search bar__ present below the __Workspaces__ dropdown.
I think no bold on "search bar"

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/getting-started/creating-your-first-workspace.md
> +You can choose a __Team__ workspace if you plan to invite collaborators, or a __Personal__ workspace or a __Private__ workspace which is only visible to the user who created it, plus team members who
"or a __Personal__ workspace or" -> ", a __Personal__ workspace, or"

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/getting-started/creating-your-first-workspace.md
> +You can choose a __Team__ workspace if you plan to invite collaborators, or a __Personal__ workspace or a __Private__ workspace which is only visible to the user who created it, plus team members who
", plus" -> " and "

2020-11-16 03:33 UTC, claireriley commented on src/pages/docs/getting-started/creating-your-first-workspace.md
> +You can choose a __Team__ workspace if you plan to invite collaborators, or a __Personal__ workspace or a __Private__ workspace which is only visible to the user who created it, plus team members who
"select access levels" -> "select their access level"

2020-11-17 04:38 UTC, sowmyaraj92 commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +To fork a collection within a public workspace, you must enable your public profile. Navigate to __Edit Profile__ and enable __Make Profile Public__. The username should consist of only alphabets, hy
Making the fork information changes in the version-control branch.

2020-11-18 06:22 UTC, sankalp0o commented on src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md
> +[![Create workspace homepage](https://assets.postman.com/postman-docs/create-workspace-homepage.jpg)](https://assets.postman.com/postman-docs/create-workspace-homepage.jpg)
No, this will only be possible in v8 onwards.

2020-11-18 06:23 UTC, sankalp0o commented on src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md
> +Once you've saved the changes, you will see notifications whenever changes are made to the public workspace. Click the notification bell in the top right corner to view notifications.
You will not get notifications whenever changes are made to the public workspace. The notification in question is sent to workspace members when a workspace becomes public.

2020-11-18 06:24 UTC, sankalp0o commented on src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md
> +[![Email notification](https://assets.postman.com/postman-docs/email-notification-public-workspace.jpg)](https://assets.postman.com/postman-docs/email-notification-public-workspace.jpg)
We might need to change the screenshot here since we are updating the template to use a different link. We can check with Soubhir or Arjun from collab squad to get the latest one.

2020-11-18 08:52 UTC, sowmyaraj92 reviewed
Hey @claireriley, Have made the requested changes. Let me know if this looks good to go.

2020-11-18 08:52 UTC, sowmyaraj92 commented on src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md
> +[![Email notification](https://assets.postman.com/postman-docs/email-notification-public-workspace.jpg)](https://assets.postman.com/postman-docs/email-notification-public-workspace.jpg)
Screenshot updated 👍🏻

2020-11-18 18:52 UTC, claireriley approved these changes
Looks great @sowmyaraj92 ! Just a heads up I made a few tiny edits (making links relative, removing spaces around an emdash, etc). We can get this published today! 😄

2020-11-18 18:53 UTC, merged