Version control docs
postmanlabs/postman-docs pull request #2701
Opened 2020-11-13 07:14 UTC by sowmyaraj92

* PR in build mode
* Merge in build mode
* Trash in build mode

2020-11-16 03:48 UTC, claireriley requested changes
Looks great! Few small things then should be good to go 😄

2020-11-16 03:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +To fork a collection in Postman, select the collection in the __Collections__ sidebar and click the __View more actions__ (__...__) button. Select __Create a Fork__. To provide a uniform forking expe
~button~ (and ~the~)

2020-11-16 03:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +To fork a collection in Postman, select the collection in the __Collections__ sidebar and click the __View more actions__ (__...__) button. Select __Create a Fork__. To provide a uniform forking expe
I'd spell out "3"

2020-11-16 03:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +To fork a collection in Postman, select the collection in the __Collections__ sidebar and click the __View more actions__ (__...__) button. Select __Create a Fork__. To provide a uniform forking expe
"Login" -> "login"

2020-11-16 03:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +### Fork information
I think you can add this header to contents above (we can adjust formatting of that later but just to have it)

2020-11-16 03:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +To fork a collection within a public workspace, you must enable your public profile. Navigate to __Edit Profile__ and enable __Make Profile Public__. The username should consist of only alphabets, hy
"The username should consist of only alphabets, hyphens and numbers."

maybe

"Your username should consist of only alphanumeric characters and hyphens."

2020-11-16 03:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +To fork a collection within a public workspace, you must enable your public profile. Navigate to __Edit Profile__ and enable __Make Profile Public__. The username should consist of only alphabets, hy
" -" -> "—"

2020-11-16 03:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +<img src="https://assets.postman.com/postman-docs/enable-public-profile.jpg" alt="Enable public profile" width="350px"/>
Blur "beta"

2020-11-16 03:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +Fork information provides information about forks and the users who have created them. You will be able to identify the users who are actively consuming/contributing to your APIs. Click the fork coun
Same as other page may want to adjust a little. Could also consider having this section on one page and linking to it on another, whichever looks best!

2020-11-16 03:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +Under forked by, clicking on a user takes you to their public profile.
Same as other PR, would make this a note

2020-11-16 03:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +You can merge changes from a collection fork (the _source_) into the parent (the _destination_) using a pull request process, tagging reviewers who can comment on your changes and decide to merge or
"using a pull request process, tagging" maybe "using a pull request process, by tagging"

"merge" -> "merge them"

2020-11-16 03:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +You can merge changes from a collection fork (the _source_) into the parent (the _destination_) using a pull request process, tagging reviewers who can comment on your changes and decide to merge or
Super minor but "__Create pull request__" is all caps in the screenshot

2020-11-16 03:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +You can approve changes on a fork (the source) into the parent fork (the destination). Once the pull request is created, navigate to the collection in Postman and click on the **Pull Requests** icon
I would format the () same as above (or above same as below, either works)

2020-11-16 03:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +To compare your fork to its parent, choose __Merge Changes__ in the forked collection in Postman.
"Merge Changes" is "Merge changes" in screenshot (maybe we can talk with Mary about inconsistent capitalization in menus..)

2020-11-18 04:48 UTC, claireriley requested changes
This looks great! Few wording and formatting suggestions to check out

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +You can use version control with your Postman collections, to fork and merge using a standard pull request process. Version control allows you to collaborate with teammates by working on different fo
I'd consider adjust "You can use version control with your Postman collections, to fork and merge using a standard pull request process" 

to something like 

"You can use version control with your Postman Collections by forking and merging and utilizing a standard pull request process."

or even

"Version control in Postman allows you to collaborate on Postman Collections with forking, merging, and a standard pull request process."

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +To fork a collection in Postman, select the collection in the __Collections__ sidebar and click __View more actions__ (__...__) and select __Create a fork__. To provide a uniform forking experience,
I'd surround "and click __View more actions__ (__...__)" by commas as it's a list of steps

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +To fork a collection in Postman, select the collection in the __Collections__ sidebar and click __View more actions__ (__...__) and select __Create a fork__. To provide a uniform forking experience,
"-" -> "—"

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +Fork information provides details about forks and the users who have created them. You will be able to identify the users who are actively consuming and contributing to your APIs. Click the fork coun
I think we can remove "created" in the last sentence

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +### Fork information
Can we adjust this header to something more specific like "Forking requirements" (if that works?)

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +### Fork to send request
I'm wondering if this needs to be a separate section—do you think we could condense and add to the requirements one above? As it sounds like an account and being logged in is required to do these actions, I think we can say that and include the first screenshot versus walking through logging in.

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +<img alt="Create Pull Request" src="https://assets.postman.com/postman-docs/pull-request-overview-v2.jpg" width="850px"/>
If full screen I think you can remove the "width="850px"

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +To create a pull request on a public collection, you need to fork the collection to a public workspace and you should have either viewer or editor access on the source collection.
I'd use "must" instead of "need to".

For "and you should have either viewer or editor access on the source collection." is this necessary for public collections? Is everyone automatically a viewer (if not editor)?

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +The pull request author and the users with viewer or editor access on the destination collection can do the following:
Remove "the" before "users"

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +* Edit the metadata (updating the title and description)
I'd use "update" vs "updating" to match tense

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +* Approve or unapprove a pull request
"unapprove" - maybe "reject" is more common?

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +<img src="https://assets.postman.com/postman-docs/make-source-collection-public-v2.jpg" alt="Source Collection Public" width="850px"/>
I'd make this smaller than 850px

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +Once you create the pull request, you will get a notification - __Shared to public workspace__.
I'd remove " - " and instead say something like "you will get a notification that it has been __Shared to public workspace__."

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +<img src="https://assets.postman.com/postman-docs/source-collection-shared-v2.jpg" alt="Source Collection Shared" width="850px"/>
For all "850px" images let's remove width as the LC design is a bit finicky

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +![Open Pull Request](https://assets.postman.com/postman-docs/open-pull-request-list-v2.jpg)
I think we could make this width smaller

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +![Merged PR](https://assets.postman.com/postman-docs/pull-request-list-v2.jpg)
I'd make width a bit smaller

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +![Pull Changes](https://assets.postman.com/postman-docs/conflicts-pull-changes-v2.jpg)
I'd make width a bit smaller

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/designing-and-developing-your-api/validating-elements-against-schema.md
> +The pane below the schema editing area will indicate issues—you can hide and show the error view as you work.
I'd use just a period instead of "—" here.

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/publishing-your-api/run-in-postman/introduction-run-button.md
> +The Run in Postman button is one way to share a Postman collection (and optional environment) with your users. This button is found in the [Postman API Network](/docs/publishing-your-api/add-api-netw
I think we can remove "in the web"

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/publishing-your-api/run-in-postman/introduction-run-button.md
> +![Cisco button in network](https://assets.postman.com/postman-docs/ciscoRIPnetwork.png)
Can we switch this to jpg and remove the top bar?

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/publishing-your-api/run-in-postman/introduction-run-button.md
> +![button in readme](https://assets.postman.com/postman-docs/foursquareRIPreadme.png)
Can we switch to jpg?

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/publishing-your-api/run-in-postman/introduction-run-button.md
> +When a user comes across your button, they can choose to view the collection in their web browser or import the collection into their Postman app. Then, they can begin interacting with your API.
"into their Postman app" -> "into Postman"

2020-11-18 04:48 UTC, claireriley commented on src/pages/docs/publishing-your-api/run-in-postman/introduction-run-button.md
> +![Modal display](https://assets.postman.com/postman-docs/imgurModalRIP.png)
jpg

2020-11-18 05:02 UTC, sowmyaraj92 commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +### Fork to send request
It's actually a separate feature, that goes with the PR flow. Had a doubt where to put that out - can keep it under Forking a collection with a minor header so that the context is clear. Or will add it without any header under forking a collection. 
What do you think?

2020-11-18 05:03 UTC, sowmyaraj92 commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +To create a pull request on a public collection, you need to fork the collection to a public workspace and you should have either viewer or editor access on the source collection.
Yes, you need permissions to create public PRs.

2020-11-18 05:07 UTC, sowmyaraj92 commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +* Approve or unapprove a pull request
The pull request can either be approved or unapproved, thats how the buttons are designed. We have decline option too. Should we change to reject?

2020-11-18 05:21 UTC, sowmyaraj92 commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +### Fork information
Forking information works?

2020-11-18 05:23 UTC, sowmyaraj92 commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +<img src="https://assets.postman.com/postman-docs/make-source-collection-public-v2.jpg" alt="Source Collection Public" width="850px"/>
Set to 400px

2020-11-18 05:37 UTC, sowmyaraj92 commented on src/pages/docs/publishing-your-api/run-in-postman/introduction-run-button.md
> +The Run in Postman button is one way to share a Postman collection (and optional environment) with your users. This button is found in the [Postman API Network](/docs/publishing-your-api/add-api-netw
Is this in the same branch? Can you confirm?

2020-11-18 07:20 UTC, sowmyaraj92 reviewed
Hey @claireriley, Requested changes have been made. Would be great if you could go ahead and approve the PR if everything looks good to go.

2020-11-19 22:46 UTC, claireriley approved these changes
LGTM!

2020-11-20 03:00 UTC, merged