Updated steps and screenshots for integrations.
postmanlabs/postman-docs pull request #2724
Opened 2020-12-01 14:14 UTC by jerry-li-dev

- intro integrations page is fully updated.

- custom webhooks page needs a valid webhook to update steps and screenshots for backing up Postman Collections

2020-12-01 14:19 UTC, jerry-li-dev commented
The remaining screenshots and steps for integrations under https://learning.postman.com/docs/integrations/available-integrations/ section need to be manually updated one at a time.

2020-12-02 15:31 UTC, shashankawasthi88 approved these changes

2020-12-02 15:31 UTC, shashankawasthi88 commented on src/pages/docs/integrations/intro-integrations.md
> +You can access integrations by navigating to the [integrations](https://postman.postman.co/integrations/browse), search page. Search and select the integration you wish to add to your workspace.
Jerry this all looks good. We might want to add a section explaining the configured Integration page, where we can see all the Integration configured by the team members. I don't see current documentation having that page at all. Also we would then need to explain the subsequent page where we can see the Integration run logs. The Integration run log page is still being updated, hence we can wait for that page

2020-12-03 00:20 UTC, jerry-li-dev commented on src/pages/docs/integrations/intro-integrations.md
> +You can access integrations by navigating to the [integrations](https://postman.postman.co/integrations/browse), search page. Search and select the integration you wish to add to your workspace.
I have added the section on reviewing integrations added by the teammates. I will get the Integration run log page updated in a different PR.

2020-12-03 05:10 UTC, shashankawasthi88 commented on src/pages/docs/integrations/intro-integrations.md
> +You can access integrations by navigating to the [integrations](https://postman.postman.co/integrations/browse), search page. Search and select the integration you wish to add to your workspace.
Jerry, it might be useful for us to show the navigation. The user will not directly land on the browse Integration page. They would go via Home Page > Integrations (configured Integration) > Browse Integration.

Also, I can see the section for the added Integration by teammates, is it another PR?

2021-01-05 02:26 UTC, claireriley requested changes
Hey @jerry-li-dev ! Added a few suggestions to improve clarity. For the webhooks page in particular, I think that needs a bit more cleanup. Check out [this section of our style guide](https://github.com/postmanlabs/postman-docs/blob/develop/DOCS_STYLE_GUIDE.md#document-sections) and see if you can reorganize it a bit, perhaps with subsections. We'll also want a TOC at the top of each page, which will help us make sure the flow makes sense.

2021-01-05 02:26 UTC, claireriley commented on src/pages/docs/integrations/webhooks.md
> +1. On the [Integrations](https://postman.postman.co/integrations/browse) page, search and select Webhooks from the list of third party integrations.
I would just say "integrations" vs "third party integrations"

2021-01-05 02:26 UTC, claireriley commented on src/pages/docs/integrations/webhooks.md
> +The integration details page explains how to use the integration and what it could do. If available, you can select **View** or **View All** to view previously configured integrations for the selecte
I would adjust this mention of "integrations details page" to "Each integration's page"

2021-01-05 02:26 UTC, claireriley commented on src/pages/docs/integrations/webhooks.md
> +On the details page, select __Add Integration__ to configure your integration. If required, enter the required information for account and access authorization. Select the workspace you need to add t
Remove "On the details page,"

2021-01-05 02:26 UTC, claireriley commented on src/pages/docs/integrations/webhooks.md
> +On the details page, select __Add Integration__ to configure your integration. If required, enter the required information for account and access authorization. Select the workspace you need to add t
As this is a specific type of integration, I'd add a screenshot of the setup page if possible.

2021-01-05 02:26 UTC, claireriley commented on src/pages/docs/integrations/webhooks.md
> +On the details page, select __Add Integration__ to configure your integration. If required, enter the required information for account and access authorization. Select the workspace you need to add t
I'd reduce "If required, enter the required information for account and access authorization." to "Enter the required information for account and access authorization."

2021-01-05 02:26 UTC, claireriley commented on src/pages/docs/integrations/intro-integrations.md
> +On the details page, select __Add Integration__ to configure your integration. If required, enter the required information for account and access authorization. Select the workspace you need to add t
I'd reduce "If required, enter the required information for account and access authorization." to "Enter the required information for account and access authorization."

2021-01-05 02:26 UTC, claireriley commented on src/pages/docs/integrations/webhooks.md
>  ## Configuring custom webhook URL
I'm looking at the page layout and this section appears a bit redundant, and it doesn't really clearly explain what the header says it does—configuring a custom webhook URL.

I'd consider adjusting the layout or division of information between sections on the page, or even removing this section or cutting it down to a line or two.

2021-01-05 02:26 UTC, claireriley commented on src/pages/docs/integrations/webhooks.md
> +[![configured integrations](https://assets.postman.com/postman-docs/view-view-all.jpg)](https://assets.postman.com/postman-docs/view-view-all.jpg)
Let's remove the highlighting with red here and stick to unaltered screenshots aside from blurring + the thin grey outline

2021-01-07 01:16 UTC, claireriley requested changes
Hey @jerry-li-dev ! Looks great, just a few minor adjustments and then we can get this published!

2021-01-07 01:16 UTC, claireriley commented on src/pages/docs/integrations/intro-integrations.md
> +You can access integrations by navigating to [Browse Integrations](https://postman.postman.co/integrations/browse), search page. Search and select the integration you wish to add to your workspace.
I recommend removing ", search page"

2021-01-07 01:16 UTC, claireriley commented on src/pages/docs/integrations/intro-integrations.md
> +>You can access integrations by navigating to [Browse Integrations](https://postman.postman.co/integrations/browse) from your [Home page](http://go.postman.co/) and select "Integrations" from the men
I would combine this with the sentence above and remove the note, something like

"You can access integrations by navigating to [Browse Integrations](https://postman.postman.co/integrations/browse) from your [Home page](http://go.postman.co/) and select**ing** "Integrations" from the menu on the left. Search and select the integration you wish to add to your workspace."

2021-01-07 01:16 UTC, claireriley commented on src/pages/docs/integrations/webhooks.md
> +* []
Remove extra []

2021-01-07 01:16 UTC, claireriley commented on src/pages/docs/integrations/webhooks.md
> +Each integration's page explains how to use the integration and what it could do. If available, you can view previously configured integrations for the selected integration.
"could" -> "can"

2021-01-07 01:16 UTC, claireriley commented on src/pages/docs/integrations/webhooks.md
> +### Configuring custom webhook URL
Should this be nested under static ip or just a ##?

2021-01-07 01:16 UTC, claireriley commented on src/pages/docs/integrations/webhooks.md
> +Once the integration has been created, you can view the integration you just created in addition to the other integrations created by your team:
I might add "active" here 

"in addition to the other **active** integrations created by your team"

2021-01-08 23:49 UTC, jerry-li-dev commented on src/pages/docs/integrations/webhooks.md
> +### Configuring custom webhook URL
Reverted to a ##

2021-01-11 23:21 UTC, jerry-li-dev commented
The docs are ready for reviews. :)

2021-01-12 00:14 UTC, claireriley approved these changes
Looks good to go! Go ahead and merge/delete branch and I'll include it in a push to prod tomorrow.

2021-01-12 00:15 UTC, merged