Getting Started docs
postmanlabs/postman-docs pull request #2725
Opened 2020-12-02 10:05 UTC by sowmyaraj92

Updated the screenshots and flow for the 3 pages below:
* **Introduction** - /docs/getting-started/introduction/
* **Discovering templates** - /docs/getting-started/importing-templates/
* **Settings** -/docs/getting-started/settings/

2021-01-09 00:39 UTC, jerry-li-dev requested changes
Line 20 needs to be changed to link to Publishing public API
Line 21 needs to be changed to link to "/docs/publishing-your-api/publish-public-api/"

2021-01-09 01:14 UTC, jerry-li-dev requested changes

2021-01-09 01:14 UTC, jerry-li-dev commented on src/pages/docs/getting-started/importing-templates.md
Creating Templates and API Network features will be removed in v8. We need to remove this page or revise to cover how to import projects from public workspaces from [https://www.postman.com/explore](https://www.postman.com/explore)

The contextual links should include a link to `/docs/publishing-your-api/publish-public-api/` and `/docs/collaborating-in-postman/using-workspaces/creating-workspaces/`

We will need to remove 
`  name: "Publishing to the API Network" `
`  url: "/docs/publishing-your-api/add-api-network/" `

2021-01-13 09:25 UTC, sowmyaraj92 commented on src/pages/docs/getting-started/importing-templates.md
I have removed the `Publishing to API network` link on the right side. We can revise this page and add how to import from public workspaces.

2021-02-03 21:57 UTC, claireriley commented
@sowmyaraj92 @jerry-li-dev let's get this merged asap as it include the opening page of the docs

2021-02-03 22:12 UTC, jerry-li-dev approved these changes

2021-02-03 22:12 UTC, jerry-li-dev commented
Lgmt

2021-02-04 05:06 UTC, merged