Reporting docs
postmanlabs/postman-docs pull request #2751
Opened 2020-12-15 12:43 UTC by sowmyaraj92

Updated screenshot

2021-02-05 12:07 UTC, tirth055 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +You can access reports on your APIs in [Postman dashboard](hhttps://postman.postman.co/reports/team). API reports visualize data on API activities including creation, collection execution, test runs,
hhttps? - typo.
Also this should be go.postman.co - AFAIK - since the postman team is accessible only by internal postman users.

2021-02-05 12:15 UTC, tirth055 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Exposed tokens over time__ indicates the exposed tokens over a period of time visualized as a column chart
We might want to mention that this consolidates the findings of the Postman token scanner from public documentation. More details of how this works is mentioned on the blog here:
https://blog.postman.com/postman-security-scans/

2021-02-05 12:16 UTC, tirth055 reviewed
Added a couple points that we should look at.

2021-02-05 14:13 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +You can access reports on your APIs in [Postman dashboard](hhttps://postman.postman.co/reports/team). API reports visualize data on API activities including creation, collection execution, test runs,
Oops! 🙊 Fixing it.

2021-02-06 02:49 UTC, claireriley requested changes
Looks good @sowmyaraj92 ! Few suggestions to check out

2021-02-06 02:49 UTC, claireriley commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +You can access reports on your APIs in [Postman dashboard](hhttps://postman.postman.co/reports/team). API reports visualize data on API activities including creation, collection execution, test runs,
Maybe add a "your" before "Postman dashboard"

2021-02-06 02:49 UTC, claireriley commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +> In this example, the open slots for the month of Nov 2020 is 306 whereas the used slots is 44.
I think "open" and "used" are switched here

2021-02-06 02:49 UTC, claireriley commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Active workspaces__ have at least one revision during a recent period, not including personal workspaces
have -> have had

can we define "recent period" - is it 30 days?

2021-02-06 02:49 UTC, claireriley commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
>  <img alt="request sent in postman" src="https://assets.postman.com/postman-docs/request-sent-in-postman.jpg" width="400px"/>
I think this changed from a bar chart to graphed points (no idea what to call it 😅 ). Can we update and include the total APIs in it as well?

2021-02-06 02:49 UTC, claireriley commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Total collections__ are the total number of collections in the team and personal workspaces including private workspaces
I think remove "the" in front of team

2021-02-06 02:49 UTC, claireriley commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Total collections__ are the total number of collections in the team and personal workspaces including private workspaces
maybe comma after "personal workspaces"

2021-02-06 02:49 UTC, claireriley commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __Collection runs__ is the number of collection runs made in team workspaces including private workspaces
I'd add a comma here as well before "including private workspaces"

2021-02-06 02:49 UTC, claireriley commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +> In this example, the collections created for the month of Nov 2020 is 1,179 whereas the collection runs is 848.
in my dashboard the numbers show up in the chart—this screenshot looks cleaner, but may be confusing as to where you got those specific numbers

2021-02-06 02:49 UTC, claireriley commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
>  * __Monitoring requests__
Since everything else has a definition can we add one here?

2021-02-06 02:49 UTC, claireriley commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
>  <img alt="Monitoring requests" src="https://assets.postman.com/postman-docs/monitoring-requests.jpg" width="400px"/>
I think the chart type may have changed here as well

2021-02-06 02:49 UTC, claireriley commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +* __APIs created over time__ is the total number of APIs created over a period of time on a monthly level
the end of this might be smoother as something like "created during the month"

2021-02-08 10:25 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +> In this example, the collections created for the month of Nov 2020 is 1,179 whereas the collection runs is 848.
If you hover on the chart, you will be able to see the values. Adding that point too.

2021-02-11 08:49 UTC, tirth055 approved these changes
Looks good to me!

2021-02-12 03:46 UTC, claireriley approved these changes
Looks great! Once small comment but ready to go regardless

2021-02-12 03:46 UTC, claireriley commented on src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
> +The __Reports__ &gt; __Security Audit__ report provides metrics including an overview of your total collections scanned, collections with exposed tokens, total exposed token and separate visualizatio
"the findings of Postman token scanner" I'd add a the so "the findings of the Postman token scanner"

and a "the" in front of it in the next sentence as well

2021-02-12 05:18 UTC, merged