Created new publishing public API doc and updated links in old articles
postmanlabs/postman-docs pull request #2768
Opened 2020-12-23 06:52 UTC by jerry-li-dev

**Need help with deprecating /docs/publishing-your-api/add-templates/**

**Need help with the order number for the new doc**

- Created new publishing public API doc
- Updated links in older docs to redirect to this doc

-

2020-12-23 06:53 UTC, jerry-li-dev commented
@SueSmith could you please help me with the order number and having the  /docs/publishing-your-api/add-templates/ links redirect to /docs/publishing-your-api/publish-public-api

2020-12-23 06:57 UTC, jerry-li-dev commented
CC: @gitThingsDone

2020-12-23 09:14 UTC, SueSmith commented
Sure! So for the redirect:

* If you add it in `redirects.json` in the repo root dir (you can also just delete the file for the page you're removing)

And for the order number:

* It's the `order` field in the frontmatter for the page (at the top in the yaml) and sequential through the whole site (not per folder), and we can do e.g. 107.1, 106.9 etc if you need to insert in between pages or whatever - I would have a play with it and rebuild locally to get a feel for how it works.. 🙂

2020-12-23 10:33 UTC, SueSmith requested changes
looking good @jerry-li-dev! a few minor language suggestions but good to go otherwise imo

2020-12-23 10:33 UTC, SueSmith commented on src/pages/docs/publishing-your-api/publish-public-api.md
> +Public workspaces allow you to quickly share your Postman projects with your teammates and others who may be interested in integrating your API technology into their own projects. Adding your collect
I would lose the promotional language here and end the sentence after "community"

2020-12-23 10:33 UTC, SueSmith commented on src/pages/docs/publishing-your-api/publish-public-api.md
> +Collections and public workspaces provide easy to read documentation, requirements, and guidance for people interested in learning and using your APIs. Your document can outline how to use a single e
I would lose "easy to read"

2020-12-23 10:33 UTC, SueSmith commented on src/pages/docs/publishing-your-api/publish-public-api.md
> +Check out steps at [Creating workspaces](/docs/collaborating-in-postman/using-workspaces/creating-workspaces/) to your public workspace to start sharing your collections and documentation.
I think I'd reword a wee bit here, maybe "Check out how to [create a public workspace](/docs/collaborating-in-postman/using-workspaces/creating-workspaces/) to start sharing...."

2020-12-23 11:01 UTC, gitThingsDone requested changes

2021-01-09 00:15 UTC, jerry-li-dev commented on src/pages/docs/publishing-your-api/publish-public-api.md
> +Public workspaces allow you to quickly share your Postman projects with your teammates and others who may be interested in integrating your API technology into their own projects. Adding your collect
Removed the promotional language.

2021-01-09 00:22 UTC, jerry-li-dev commented on src/pages/docs/publishing-your-api/custom-doc-domains.md
> +You can make your documentation more discoverable by adding it to the [API Network](/docs/publishing-your-api/add-api-network/) or [Postman public workspaces](/docs/publishing-your-api/publish-public
- Pending removal of `add-api-network`

2021-01-14 01:58 UTC, jerry-li-dev commented on src/pages/docs/publishing-your-api/publish-public-api.md
> +Public workspaces allow you to quickly share your Postman projects with your teammates and others who may be interested in integrating your API technology into their own projects. Adding your collect
Updated with wording as described in the blog post.

2021-01-14 02:01 UTC, jerry-li-dev commented on src/pages/docs/getting-started/importing-templates.md
>      url: "/docs/publishing-your-api/add-api-network/"
Removed add to api network links and updated submission guidelines.

2021-01-16 00:29 UTC, jerry-li-dev commented
Pending updated links to template examples.

2021-01-18 14:22 UTC, gitThingsDone commented on src/pages/docs/publishing-your-api/api-submission-guidelines.md
> +Your listing should provide the information developers need to know in order to decide whether they want to try the API or collection out. Try to choose a descriptive name that conveys the purpose of
Can we include steps about how you can add summaries and categories for your public workspaces, APIs, and collections from the profile page. 
we can also update this to something like "use a descriptive name and summary for your public workspaces, APIs, and collections to help consumers develop more context about your APIs, this also helps users get to your public APIs faster through search" 
Categories: Add relevant categories for your public workspaces, APIs, and collections to help your target users find them

2021-01-18 14:22 UTC, gitThingsDone commented on src/pages/docs/publishing-your-api/api-submission-guidelines.md
> +When you publish to the API Network, potential users will initially see your team profile, with APIs listed under it. Taking the time to fill out your team profile gives consumers a clear sense of wh
Users can also add github and twitter links to their user/team profiles.

2021-02-05 08:58 UTC, jerry-li-dev commented
This pr is recreated with https://github.com/postmanlabs/postman-docs/pull/2830 to resolve conflicts

2021-05-21 16:43 UTC, jkonrath-postman commented
Closing this without merge, because this PR contains the same changes and will supersede this: https://github.com/postmanlabs/postman-docs/pull/2830

2021-05-21 16:43 UTC, closed without merging