Update viewing monitor results for v8
postmanlabs/postman-docs pull request #2810
Opened 2021-01-25 05:12 UTC by claireriley

2021-01-28 05:27 UTC, ArjunSingh-PM requested changes
The path to reach monitoring 'Activity feed' needs edits. Looks good otherwise!

2021-01-28 05:27 UTC, ArjunSingh-PM commented on src/pages/docs/designing-and-developing-your-api/monitoring-your-api/faqs-monitors.md
> +Your monitor's timezone is automatically set to the timezone of your computer at the time of the monitor's creation, unless you [define the regions](/docs/postman/monitors/setting-up-monitor/#adding-
The schedule that the monitor runs at is set to the timezone of the computer the monitor was created from. I doubt regions have a role to play in this. 

@godfrzero Can you please confirm this?

2021-01-28 05:27 UTC, ArjunSingh-PM commented on src/pages/docs/designing-and-developing-your-api/monitoring-your-api/viewing-monitor-results.md
>  You can view a monitor's activity logs by selecting **...** in the upper-right corner > **View activity logs**.
This is not true.

A user can access the monitor "Activity feed" by clicking on the 'clock' icon in the context bar.

2021-01-28 05:27 UTC, ArjunSingh-PM commented on src/pages/docs/designing-and-developing-your-api/monitoring-your-api/viewing-monitor-results.md
>  You can view a monitor's activity logs by selecting **...** in the upper-right corner > **View activity logs**.
We should also add that the user can view monitor details by clicking on the 'info' icon in the context bar. Also, we can explain its content.

2021-01-28 05:27 UTC, ArjunSingh-PM commented on src/pages/docs/designing-and-developing-your-api/monitoring-your-api/viewing-monitor-results.md
>  ### Console log
We can also highlight that the requests in the console log are linked to quickly view the request in a tab and make edits if needed.

2021-01-28 05:29 UTC, godfrzero commented on src/pages/docs/designing-and-developing-your-api/monitoring-your-api/faqs-monitors.md
> +Your monitor's timezone is automatically set to the timezone of your computer at the time of the monitor's creation, unless you [define the regions](/docs/postman/monitors/setting-up-monitor/#adding-
Yep, the schedule is set based on the timezone from which it was created. Regions don't matter.

2021-02-01 17:23 UTC, ArjunSingh-PM approved these changes
Looks good!

2021-02-01 17:23 UTC, ArjunSingh-PM commented on src/pages/docs/designing-and-developing-your-api/monitoring-your-api/viewing-monitor-results.md
> +You can view a monitor's activity logs by selecting the clock icon in the upper-right corner > **View activity logs**.
Not sure if we should call this the 'clock' icon. Can we use the actual icon/picture instead?

2021-02-02 01:56 UTC, jerry-li-dev approved these changes

2021-02-03 18:25 UTC, merged