create-opsgenie
postmanlabs/postman-docs pull request #2820
Opened 2021-01-30 12:09 UTC by jerry-li-dev

New page for opsgenie

2021-02-01 12:41 UTC, jotsarup requested changes

2021-02-01 12:41 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +This integration allows you to configure [Postman Monitors](/docs/designing-and-developing-your-api/monitoring-your-api/intro-monitors/) to trigger incidents on Opsgenie whenever it fails.
We trigger "alerts" and not "incidents"

2021-02-01 12:41 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +## Incidents on VictorOps
Should be Opsgenie and not victorops

2021-02-01 12:41 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +An alert on Opsgenie consists of the basic information of which monitor failed, with the number of errors and failed tests. It also provides a direct link to the failing monitor. This integration aut
Lets not say "basic information". 

We send the following information. You should mention all the following. 

Description of failing tests - Exact failures in the test script written in Postman
Number of failed tests
Number of passed tests
Number of errors ( errors occur when we are not able to fetch response from your API )
Response time

2021-02-01 12:41 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +An alert on Opsgenie consists of the basic information of which monitor failed, with the number of errors and failed tests. It also provides a direct link to the failing monitor. This integration aut
We close the alert (not acknowledge) when we have a subsequent success. 
Mention this in a separate line, that we close the alert. Also mention that the failures from the same monitor is clubbed under a single Opsgenie alert.

2021-02-01 12:41 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +Opsgenie is a real-time incident management platform that allows you to monitor system incidents and alert the correct team members as soon as possible.
Please write the following description

"Opsgenie is an incident management and alerting tool that allows you to effectively manage alerts across the infrastructure. It has several communication features such as SMS, phone calls, and iOS & Android push notifications and collaboration features such as escalations, schedules etc."


Also include the link for Opsgenie

2021-02-01 12:41 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +From the list of integrations, select the `API` Integration option.
Link the following page.
"https://docs.opsgenie.com/docs/api-integration"

2021-02-01 12:41 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +![add Opsgenie integration](https://assets.postman.com/postman-docs/opsgenie-add-integration.jpg)
For this image can you select an image where "Loading added integrations" is not visible.

2021-02-01 12:41 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +  The name of the monitor you want to send to Opsgenie.
Mention "The results of the selected monitor will be sent to Opsgenie"

2021-02-01 12:41 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +  The name of the workspace where the monitor you are adding is located.
Can you copy the exact lines from the "Add Integration Page"
![image](https://user-images.githubusercontent.com/72457782/106460042-bea24e00-64b8-11eb-83d6-f608798725bb.png)

2021-02-02 14:42 UTC, jotsarup requested changes

2021-02-02 14:42 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +![add Opsgenie API key](https://assets.postman.com/postman-docs/opsgenie-run-log.jpg)
Can we put up an image where there are some run logs available.

2021-02-02 14:42 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +## Incidents on Opsgenie
This should be "Alerts" and not "Incidents"

2021-02-02 14:42 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +  Give a nickname to your integration
I think we should remove the descriptions from these names. The information is already shown in the image.  

Just the following text should be fine. 
"
Nickname
Workspace Name
Monitor Name
Tags 
Alert Priority
"

2021-02-02 14:42 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +![add Opsgenie API key](https://assets.postman.com/postman-docs/opsgenie-alerts-details.jpg)
At the end please mention that we already always listening to the community for any issues or newer workflows. You can reach us at Github (https://github.com/postmanlabs/postman-app-support/issues) and email (https://www.postman.com/company/contact-us/).

2021-02-04 10:57 UTC, jotsarup approved these changes

2021-02-05 00:51 UTC, claireriley requested changes
Hey @jerry-li-dev ! Added some comments, mostly related to style guide

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +[Opsgenie](https://www.atlassian.com/software/opsgenie) is an incident management and alerting tool that allows you to effectively manage alerts across the infrastructure. It has several communicatio
I think the second sentence needs another comma and let's remove the "etc":

"It has several communication features such as SMS, phone calls, and iOS & Android push notifications, and collaboration features such as escalations and schedules."

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +This integration allows you to configure [Postman Monitors](/docs/designing-and-developing-your-api/monitoring-your-api/intro-monitors/) to trigger alerts on Opsgenie whenever it fails.
Let's specify what "it" is here

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +Functionality of the Integration
Let's make intros to lists full sentences—see [style guide](https://github.com/postmanlabs/postman-docs/blob/develop/DOCS_STYLE_GUIDE.md#formatting-and-structure)

Also no caps on "integrations" unless it's a button or something similar being referenced—see [comments here](https://postmanlabs.atlassian.net/l/c/yzCkDW3C)

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +  1. Alert is automatically closed on the first success after failure(s).
I'm not sure if this information needs to be presented as a list—it suggests that there are more features than there are to me. I think it can be reduced to a direct sentence or two, maybe something like 

"This Opsgenie integration functions by triggering an alert... This alert is automatically closed..."

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +![log in to Opsgenie](https://assets.postman.com/postman-docs/opsgenie-teams-select.jpg)
Let's keep the Chrome header out of all screenshots

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +From the left nav, select `Integrations` and then Select `Add integration`.
"From the left nav, select `Integrations` and then Select `Add integration`."

->

"From the left nav, select `Integrations` > `Add integration`."

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +![log in to Opsgenie](https://assets.postman.com/postman-docs/opsgenie-teams-add-integration.jpg)
Can we add more specific alt text to these screenshots?

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +Log in to your Opsgenie account and go to the `Teams` tab and select the team you will add an integration for.
Let's make all buttons, tabs, etc on this page bold vs inline code snippets

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +Log in to your Opsgenie account and go to the `Teams` tab and select the team you will add an integration for.
for -> to

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +![log in to Opsgenie](https://assets.postman.com/postman-docs/opsgenie-teams-add-integration.jpg)
Looks like there's a bit of the Chrome header to crop out on this one

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +From the list of integrations, select the [`API` Integration](https://docs.opsgenie.com/docs/api-integration) option.
Same as above with this link—let's make "API" bold and lowercase integration as it's not a button here

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +On the configuration page, fill in the your information and select `Save Integration`.
~~the~~

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +Copy the API Key and save it for later.
Let's change "the API Key" to "your API key"

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +
Let's add a TOC for style guide

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +## Configuring Postman Integration
Lowercase integration here -> headers are sentence case

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +On the integration authentication page, enter the Opsgenie API key you saved from the Opsgenie console. Select the `Opsgenie site` region for your Opsgenie account.
"the Opsgenie console" -> "your Opsgenie console"

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +On the integration authentication page, enter the Opsgenie API key you saved from the Opsgenie console. Select the `Opsgenie site` region for your Opsgenie account.
Can we link "Opsgenie site" to their docs on how to find that info?

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +On the integration configuration page, enter the following information for your integration:
I don't know if this needs to be a list. Thoughts on condensing it to something like

"On the integration configuration page, give your integration a nickname, select the workspace,..."

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +![add Opsgenie API key](https://assets.postman.com/postman-docs/opsgenie-save-configuration-b.jpg)
Let's add a width to make this image a tiny bit smaller, on my screen it spans more than a page

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +After you create the integration, you can see all of the integrations created by your team. Select the integration to see the run logs for it.
"Select the integration" -> "Select an integration"

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +* Description of failing tests - Exact failures in the test script written in Postman
For the two items in this list that have descriptions, I think it would be cleaner to describe these two factoids in a note > right below the list

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +This integration automatically closes a triggered alert if the subsequent run succeeds. All failures from the same monitor are grouped under the a single Opsgenie alert.
"if the subsequent run succeeds" is it "the" or "a" ?

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +![add Opsgenie API key](https://assets.postman.com/postman-docs/opsgenie-alerts-list.jpg)
Let's remove the Chrome header here

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +![add Opsgenie API key](https://assets.postman.com/postman-docs/opsgenie-alerts-details.jpg)
Above this screenshot perhaps you could add something like "Click into the alert in Opsgenie to see more information."

2021-02-05 00:51 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +We are always listening to the community for any issues or newer workflows. You can reach us at [Github](https://github.com/postmanlabs/postman-app-support/issues) and by [email](https://www.postman.
We want to avoid using "we" or "us" in docs—see [bottom note here](https://github.com/postmanlabs/postman-docs/blob/develop/DOCS_STYLE_GUIDE.md#tone) 

I would use next steps here to point to some of the other integrations a user who just set up this one might be interested in

2021-03-04 03:22 UTC, claireriley commented
@jerry-li-dev It looks like my earlier comments were resolved however no changes were pushed, can you please check if those are still local or redo and push? I can then do a final review.

2021-03-04 03:54 UTC, jerry-li-dev commented
It looks like it was pushed to the repo. 

![Screenshot_20210303-195418.png](https://user-images.githubusercontent.com/21134325/109909054-4a470000-7c5a-11eb-8b3d-1a9d15b08487.png)

2021-03-04 05:02 UTC, claireriley commented
@jerry-li-dev I can see the TOC, but if you open up my comments you resolved I'm not seeing those changes

2021-03-05 05:26 UTC, jerry-li-dev commented
@claireriley  The push finally went through. I don't know why it did not include it last time.

2021-03-09 03:57 UTC, claireriley requested changes
Few small changes — biggest thing is making button titles **bold** vs using `this format`. Should be quick, ping me when ready and I'll approve

2021-03-09 03:57 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +This integration allows you to configure [Postman Monitors](/docs/designing-and-developing-your-api/monitoring-your-api/intro-monitors/) to trigger alerts on Opsgenie whenever it fails.
Let's change "it" here to something like "your monitor"

2021-03-09 03:57 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +Log in to your Opsgenie account and go to the `Teams` tab and select the team you will add an integration to.
Everywhere there is inline code formatting used for buttons, let's change it to bold to align with other pages

i.e. `Teams` becomes **Teams** (surround by double ** or double __)

2021-03-09 03:57 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +On configuration page, fill in the your information and select `Save Integration`.
Remove "the" and add one after "On"

2021-03-09 03:57 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +On the integration configuration page, enter the nickname for your integration, your workspace, alert tags, and alert priorities.
"the nickname" -> "a nickname"

2021-03-09 03:57 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +>Number of errors ( errors occur when we are not able to fetch response from your API )
Let's move these back to the above list and format them similarly, something like

```
* Description of failing tests (failures in your test scripts you have written in Postman)
* Number of errors (errors occur when Postman is unable to fetch a response from your API)
```

(also want to avoid using "we" in docs)

2021-03-10 20:28 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +From the left nav, select `Integrations` > `Add integration`.
@jerry-li-dev one last line to fix ` -> **

2021-03-10 20:59 UTC, jerry-li-dev commented on src/pages/docs/integrations/available-integrations/opsgenie.md
> +From the left nav, select `Integrations` > `Add integration`.
All fixed :)

2021-03-12 05:43 UTC, claireriley approved these changes
Looks good to go!

2021-03-12 05:49 UTC, merged