Update gitlab.md
postmanlabs/postman-docs pull request #2823
Opened 2021-01-31 08:27 UTC by jerry-li-dev

Updated steps and screenshots

2021-02-05 01:08 UTC, claireriley requested changes
Hey @jerry-li-dev — few notes and we can get this pushed shortly!

2021-02-05 01:08 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +![gitlab dashboard](https://assets.postman.com/postman-docs/gitlab-save-token.jpg)
Let's update alt text for these screenshots as well

2021-02-05 01:08 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +You can select `View` or `View All`to see all integrations created by your team.
Let's bold buttons vs using inline code formatting

2021-02-05 01:08 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/gitlab.md
>      The above screen provides you the following two options:
This is showing up as oddly formatted on my end—can we remove indents and see if that helps?

2021-02-05 01:08 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +Choose an existing Postman Collection and your GitLab Project, and enter a filename for your backup. Select `Add Integration` to save your integration configuration.
Can we add a screenshot here?

2021-02-05 01:08 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +  Now every change that is saved to your Postman Collection automatically commits changes to your GitLab project in real time. Your Collections and code can exist in the same repository.
Second "Collections" should be lowercase, see [here](https://postmanlabs.atlassian.net/l/c/cHHEaJVG)

2021-02-05 01:08 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +    * US East: `3.212.102.200`
This one is showing up as a code block — might be indenting?

2021-02-05 01:08 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +In the **Backup your Postman Collections** page, choose an existing Postman Collection and your GitLab Project, enter a filename for your backup.
"enter a filename" -> "then enter a filename"

2021-02-05 01:08 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +Your Collection is pushed to your GitLab project under the directory that you specified and saved as a single JSON file.
Lowercase collection here

2021-02-05 01:08 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +Select `Add Integrations`.
Bold vs inline code

2021-03-26 05:03 UTC, shashankawasthi88 commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +From the [Integrations search page](https://go.postman.co/integrations/browse?category=all) search and select Gitlab.
Are we using Integration search page as the nomenclature everywhere? I think we should stick to using "Browse Integration" page just to maintain consistency on the UI and docs

2021-03-26 05:04 UTC, shashankawasthi88 reviewed
Added comments

2021-06-15 01:44 UTC, jerry-li-dev commented on src/pages/docs/integrations/available-integrations/gitlab.md
> +From the [Integrations search page](https://go.postman.co/integrations/browse?category=all) search and select Gitlab.
Changed to "Browse Integration."

2021-06-15 02:41 UTC, closed without merging

2021-06-16 15:48 UTC, jkonrath-postman commented
(This is now PR #3127)