Update microsoft-teams.md
postmanlabs/postman-docs pull request #2828
Opened 2021-02-05 01:47 UTC by jerry-li-dev

updated steps and screenshots

2021-02-06 02:57 UTC, claireriley requested changes
Looks great @jerry-li-dev ! Few small suggestions

2021-02-06 02:57 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/microsoft-teams.md
> +1. From the [Integrations](go.postman.co/integrations/browse?category=all) search page, search and select Microsoft Teams from the results.
I think we can remove the 1. here as you removed the below numbers

2021-02-06 02:57 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/microsoft-teams.md
> +Give your integration a nickname and provide your [incoming webhook URL](#create-a-microsoft-teams-webhook-url) to receive team updates in Microsoft Teams.
Maybe we can specify the differing names - "..provide your [incoming webhook URL]() as the **Notification URL** to receive.."

2021-02-06 02:57 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/microsoft-teams.md
>     [![ms_teams monRun](https://assets.postman.com/postman-docs/WS-integration-msTeams-monRun.png)](https://assets.postman.com/postman-docs/WS-integration-msTeams-monRun.png)
Can we update this one? I think cropping to the form and adding a width would make the text a little larger

2021-02-06 02:57 UTC, claireriley commented on src/pages/docs/integrations/available-integrations/microsoft-teams.md
> +Select the **Add Integration** button to see your monitors in the "Configured Integrations" view. You can also click the "Advanced Options" link to indicate if you want notifications when all monitor
"Select the **Add Integration** button" -> "Select **Add Integration**"

2021-06-07 20:50 UTC, jkonrath-postman approved these changes
LGTM

2021-06-08 02:38 UTC, claireriley approved these changes
LGTM

2021-06-08 14:38 UTC, merged