Adds training workspaces
postmanlabs/postman-docs pull request #2852
Opened 2021-02-22 14:39 UTC by SueSmith

@claireriley just adding links to the training workspaces 🙂

2021-02-25 04:25 UTC, claireriley requested changes

2021-02-25 04:25 UTC, claireriley commented on src/pages/docs/getting-started/introduction.md
> +    * [**Postman Training**](https://bit.ly/postman-training)–Learn APIs 101, Testing and Automation, API Adoption, and API First, earning [Postman badges](https://postman-api-badges).
@SueSmith I think badges is only a partial link here?

2021-02-25 10:03 UTC, SueSmith commented on src/pages/docs/getting-started/introduction.md
> +    * [**Postman Training**](https://bit.ly/postman-training)–Learn APIs 101, Testing and Automation, API Adoption, and API First, earning [Postman badges](https://postman-api-badges).
gah fixed 🤪

2021-03-04 02:49 UTC, claireriley approved these changes
Thanks @SueSmith ! ❤️

2021-03-04 02:49 UTC, merged