Environment Forking
postmanlabs/postman-docs pull request #2876
Opened 2021-03-05 12:22 UTC by sowmyaraj92

2021-03-10 05:00 UTC, ankit-m requested changes

2021-03-10 05:00 UTC, ankit-m commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +Click **View all forks** to reveal the list of fork labels and users who have active forks.
This is not entirely correct. Replace with something like

`Click View all forks to reveal the detailed list of forks along with information about users who created them`

2021-03-15 07:05 UTC, ankit-m approved these changes

2021-03-18 02:52 UTC, claireriley approved these changes
Looks great! Two very tiny edits

2021-03-18 02:52 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +To fork an environment in Postman, select the environment in the __Environments__ sidebar, click __View more actions__ (__...__), and select __Create a fork__. You can also fork an environment by cli
Let's remove "button"

2021-03-18 02:52 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/version-control-for-collections.md
> +Forks icon <img alt="Fork icon on context bar for v8" src="https://assets.postman.com/postman-docs/fork-icon-right-panel-v8.jpg" height="30px"/> on the context bar provides details about the forks cr
Let's add a "The" at the front

2021-03-18 04:32 UTC, merged