Merging v8 docs to master
postmanlabs/postman-docs pull request #2880
Opened 2021-03-08 05:30 UTC by sowmyaraj92

2021-03-08 07:17 UTC, tristandenyer requested changes
We need to clean up the rest the v7 redirects as well.

2021-03-08 07:17 UTC, tristandenyer commented on redirects.json
> +		"to": "/docs/administration/upgrading-to-v8/"
There are 5 or 6 other places in this redirects file that point to `"to": "/docs/administration/migrating-to-v7/"` that should also be updated to `"to": "/docs/administration/upgrading-to-v8/"` so we don't create a redirect chain.

2021-03-08 07:17 UTC, tristandenyer commented on src/pages/docs/administration/upgrading-to-v8.md
> +<img alt="non-admin user" src="https://assets.postman.com/postman-docs/non-admin-migrate-v8.jpg"/>
Not a PR-stopper, but in the future, all alt tags should be descriptive of what the image is. Example for this image could be "Dialog box for v6 to v8 users telling them to contact their admin. Screen shot."

2021-03-08 07:56 UTC, tristandenyer commented on redirects.json
> +		"to": "/docs/administration/upgrading-to-v8/"
Resolved in #2881

2021-03-09 02:59 UTC, claireriley approved these changes
Looks good to me! I'll add a note about image description to the style guide.

2021-03-09 16:49 UTC, tristandenyer approved these changes
LGTM

2021-03-10 03:14 UTC, merged