Feat #2877: updated the docs of into-api.md
postmanlabs/postman-docs pull request #2886
Opened 2021-03-10 10:58 UTC by Cronus1007

## Fixes
Fixes #2877 by @loopDelicious 

## Description 
Updated the documentation as per the instructions given in the issue

## Additional Context 
I would like to add two images for more details regarding the forking for more clarity to the end user but the images in the repo are controlled via `https://assets.postman.com/postman-docs` so gave these images in the description of the PR.
![oie_10114829lITl0DO2](https://user-images.githubusercontent.com/56436023/110618990-49afeb80-81bd-11eb-9ac7-d2fe66798bd9.png)
![oie_DW0nvLWakotY](https://user-images.githubusercontent.com/56436023/110618997-4c124580-81bd-11eb-91cb-ffe32bdc65f5.png)

## Tests

NO need of testing .

2021-03-15 04:38 UTC, sowmyaraj92 commented on src/pages/docs/developer/intro-api.md
> +You can get started by forking the collection. For more details regarding the __Forking__ navigate to the [Postman API](https://www.postman.com/postman/workspace/postman-public-workspace/documentatio
A missing period at the end of the sentence.

2021-03-15 04:43 UTC, sowmyaraj92 commented on src/pages/docs/developer/intro-api.md
> +The [Postman API](https://www.postman.com/postman/workspace/postman-public-workspace/documentation/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a) endpoints to help you integrate Postman within your d
Change "endpoints to help" > "endpoints help you integrate".

2021-03-15 04:46 UTC, sowmyaraj92 requested changes
Just a few minor changes and we are good to go!

2021-03-15 04:46 UTC, sowmyaraj92 commented on src/pages/docs/developer/intro-api.md
> +The [Postman API](https://www.postman.com/postman/workspace/postman-public-workspace/documentation/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a) endpoints to help you integrate Postman within your d
Change "endpoints to help" > "endpoints help you to integrate".

2021-03-15 04:46 UTC, sowmyaraj92 commented on src/pages/docs/developer/intro-api.md
> +You can get started by forking the collection. For more details regarding the __Forking__ navigate to the [Postman API](https://www.postman.com/postman/workspace/postman-public-workspace/documentatio
A missing period at the end of the sentence.

2021-03-16 03:31 UTC, sowmyaraj92 approved these changes
@Cronus1007 Looks great! 👍

2021-03-16 03:48 UTC, tristandenyer approved these changes

2021-03-16 04:03 UTC, Cronus1007 commented
@sowmyaraj92 @tristandenyer Thanks.

2021-03-16 05:10 UTC, merged