add steps - need screenshots
postmanlabs/postman-docs pull request #2951
Opened 2021-04-03 00:12 UTC by jerry-li-dev

add steps - need screenshots

2021-04-05 04:45 UTC, jerry-li-dev commented
@shashankawasthi88

Pending screenshots. Still need the steps from here. But, way too much content to copy over. Please specify which specific content to copy over.

https://portswigger.net/burp/documentation/desktop/getting-started/proxy-setup/certificate

2021-04-05 05:23 UTC, jerry-li-dev commented
@abhishekc23

2021-04-05 09:59 UTC, shashankawasthi88 commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +1. Double click on **rootCA.crt**
@jerry-li-dev the name of the file is changed. Refer to the docs earlier to find updated file names and screen shots

2021-04-05 10:03 UTC, shashankawasthi88 commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +1. Right click on the **rootCA.crt** file and select **Install Certificate**.
Same as above

2021-04-05 10:03 UTC, shashankawasthi88 commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +Please follow the steps in this discussion thread [here](https://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate).
Please copy the steps here as well

2021-04-05 15:32 UTC, jkonrath-postman requested changes
I left some minor changes - see comments

2021-04-05 15:32 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
>  **Note:** For the Postman native apps, request captures over HTTPS will not work if the website has HSTS enabled. Most websites have this check in place.
Change "HSTS" to "HTTP Strict Transport Security (HSTS)"

2021-04-05 15:32 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +You can use the Postman's proxy to inspect HTTPS communication from your Android, iOS, Linux, MacOS, and Windows devices. After you enable the proxy feature, follow the instructions below to install
Should be "macOS" (change this globally)

2021-04-05 15:32 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +After these steps, you should be able to capture HTTPS Requests with the Postman proxy.
Change "should" to "will" (don't indicate probability - assume our code always works...)

2021-04-05 15:32 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +1. Right click on the **rootCA.crt** file and select **Install Certificate**.
Change "right click" to "right-click" (check globally)

2021-04-05 15:32 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +### CentOS and RHEL distros
Spell out RHEL to Red Hat Enterprise Linux (we should honor their trademark)

2021-04-05 15:32 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +    When the certificate is installed, your device should show an installation confirmation screen like the one below.
should/will

2021-04-05 15:32 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +Openssl is generally already installed for MacOs and Linux (there can be cases where it is not installed). For windows systems, **OpenSSL** is to be installed if not installed previously.
* Change openssl to OpenSSL
* Change MacOs to macOS

2021-04-05 15:32 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +1. Go to where the oppssl.exe is. **This PC > Windows (C:) > Program Files > OpenSSL - Win64 > bin**.
Is that the right .exe name?

2021-04-05 19:22 UTC, abhishekc23 commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +1. Go to where the oppssl.exe is. **This PC > Windows (C:) > Program Files > OpenSSL - Win64 > bin**.
The exe part can be ignored completely as we are just asking the user to select the bin directory

2021-04-05 19:27 UTC, abhishekc23 commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
>  **Note:** For the Postman native apps, request captures over HTTPS will not work if the website has HSTS enabled. Most websites have this check in place.
This Note can be removed, now that we will be supporting HSTS via HTTPS Proxy

2021-04-05 21:37 UTC, jerry-li-dev commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +1. Go to where the oppssl.exe is. **This PC > Windows (C:) > Program Files > OpenSSL - Win64 > bin**.
I have removed this detail from the document.

2021-04-05 21:44 UTC, jerry-li-dev commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
>  **Note:** For the Postman native apps, request captures over HTTPS will not work if the website has HSTS enabled. Most websites have this check in place.
Note has been removed.

2021-04-07 10:20 UTC, shashankawasthi88 reviewed
Looks good to me!

2021-04-07 10:20 UTC, shashankawasthi88 commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +## Use Interceptor to capture requests
We should move the Interceptor section at the end of this page. Lets complete everything about proxy first and then have Interceptor

2021-04-07 20:11 UTC, jkonrath-postman approved these changes
Looks good to me

2021-04-07 20:13 UTC, merged

2021-04-08 05:48 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +## Use Interceptor to capture requests
@jerry-li-dev Looks like this comment wasn't addressed. Please ensure we make this change and push it in the next release to prod.