initial link and order update
postmanlabs/postman-docs pull request #2997
Opened 2021-04-16 21:06 UTC by jerry-li-dev

initial link and order update

2021-04-19 15:19 UTC, jkonrath-postman requested changes
One minor suggestion: should the bulleted list after line 45 be a numbered list? Looks like a procedure, but I wasn't sure.

2021-04-29 07:22 UTC, shashankawasthi88 reviewed
Added comments

2021-04-29 07:22 UTC, shashankawasthi88 commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +> There are multiple API key types in New Relic. The account level API Keys cannot be used for inserting  data into New Relic. Insights Insert Keys must be used.
Seems like extra space

2021-04-29 07:22 UTC, shashankawasthi88 commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +1. On your Home page, navigate to [Integrations](https://postman.postman.co/integrations/browse?category=all), click **Browse All Integrations**, and click **New Relic** in the list of third-party in
The numbering seems to be incorrect

2021-04-29 07:22 UTC, shashankawasthi88 commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +1. On your Home page, navigate to [Integrations](https://postman.postman.co/integrations/browse?category=all), click **Browse All Integrations**, and click **New Relic** in the list of third-party in
This URL is specific to Postman team. We should rather use getpostman.com instead

2021-04-29 07:22 UTC, shashankawasthi88 commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +| Metric | Level | Individual Attributes |
A metric description might be helpful here

2021-04-29 13:56 UTC, jkonrath-postman commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +> There are multiple API key types in New Relic. The account level API Keys cannot be used for inserting  data into New Relic. Insights Insert Keys must be used.
removed

2021-04-29 13:58 UTC, jkonrath-postman commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +1. On your Home page, navigate to [Integrations](https://postman.postman.co/integrations/browse?category=all), click **Browse All Integrations**, and click **New Relic** in the list of third-party in
That's correct - in MD, if you number every step as 1. it will automatically number them at render. It eliminates mistakes when you add/remove steps in the middle later.

2021-04-29 14:41 UTC, jkonrath-postman commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +1. On your Home page, navigate to [Integrations](https://postman.postman.co/integrations/browse?category=all), click **Browse All Integrations**, and click **New Relic** in the list of third-party in
I took this URL out and reworded slightly.

2021-04-30 14:53 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +## Common attributes
I don't think we should use terms like common attributes and individual attributes (little below). These are internal terms.

2021-04-30 14:53 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +| Metric | Level | Individual Attributes |
Yes agree. We can replace the 2nd and 3rd columns. And replace them with the explanation.

2021-04-30 14:53 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +## Metrics pushed to New Relic
We can show the image of how the metrics would show up on the New Relic dashboard. The image is there in the blog post. 

Also an image with attributes for the metrics will be nice. It should also be there in the blog post. Else I will send you one.

2021-05-03 14:13 UTC, jkonrath-postman commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +## Metrics pushed to New Relic
I've added these images from the blog post - they are now in the "Viewing data in New Relic" section.

2021-05-03 15:00 UTC, jkonrath-postman commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +## Common attributes
I renamed this "Dimension attributes"

2021-05-03 15:02 UTC, jkonrath-postman commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +| Metric | Level | Individual Attributes |
I changed this table to be two columns: metric and description, and added a description for each. Some of the metrics listed here were old/off, so I verified the list with what's shown in New Relic.

2021-05-03 15:34 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +## Metrics pushed to New Relic
Can you move this section to "Viewing data in New Relic". They are conveying the same information.

2021-05-03 15:34 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +[![New Relic filters](https://assets.postman.com/postman-docs/new-relic-query.jpg)](/new-relic-query.jpg)
Please move this image to the Dimension attributes section. This images shows that.

2021-05-03 15:34 UTC, jotsarup commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +- environment.id
There are 2 more dimensions available - request.name, request.id. Its shown in the second image in the blog article.

2021-05-03 15:39 UTC, jkonrath-postman commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +- environment.id
added

2021-05-03 16:03 UTC, jotsarup approved these changes

2021-05-03 16:05 UTC, merged