New Run in Postman button
postmanlabs/postman-docs pull request #3047
Opened 2021-05-05 13:26 UTC by sowmyaraj92

2021-05-07 14:50 UTC, jkonrath-postman requested changes
Some minor comments, but make sure to search/replace everything to make sure it's Run in Postman and maybe always make the button name bold?

2021-05-07 14:50 UTC, jkonrath-postman commented on src/pages/docs/publishing-your-api/run-in-postman/creating-run-button.md
> +One way to [share your Postman Collections](/docs/collaborating-in-postman/sharing/) is to create a stand-alone Run in Postman button. You can embed the button in your website or a README to let deve
General question: should be we bolding the **Run in Postman** button like this?

2021-05-07 14:50 UTC, jkonrath-postman commented on src/pages/docs/publishing-your-api/run-in-postman/creating-run-button.md
> +> Note: If the collection is present in a public workpspace, you can directly embed the copied code where you would like the button to be displayed. If the collection is present in a team or a person
* Change "share collection to a public workplace" to "share the collection to a public workspace"
* Change "run in postman button" to "Run in Postman button" (and maybe bold, see the previous comment)

2021-05-12 07:42 UTC, gitThingsDone requested changes
Added one comment, looks good to go otherwise :D

2021-05-12 07:42 UTC, gitThingsDone commented on src/pages/docs/publishing-your-api/run-in-postman/creating-run-button.md
> +> Previously, the Run in Postman button worked with API specification formats like OpenAPI and RAML. To create a button for the standard you use, first convert the file to a collection by [importing
users can still create these run in postman buttons from API specification formats

2021-05-12 10:33 UTC, gitThingsDone approved these changes

2021-05-12 13:37 UTC, jkonrath-postman approved these changes
Approved, but there are two super-minor changes for you to pick up if you can.

2021-05-12 13:37 UTC, jkonrath-postman commented on src/pages/docs/publishing-your-api/run-in-postman/creating-run-button.md
> +> Being a user, you can still create **Run in Postman** button from API specification formats like OpenAPI and RAML. To create a button for the standard you use, first convert the file to a collectio
"can still create a" or "can still create the" ?

2021-05-12 13:37 UTC, jkonrath-postman commented on src/pages/docs/publishing-your-api/run-in-postman/creating-run-button.md
> +Clicking **Run in postman** button navigates to the page where you can fork the collection to your workspace. [Forking the collection](/docs/collaborating-in-postman/version-control-for-collections/)
Should be "Run in Postman"

2021-05-12 14:17 UTC, merged