Specify that the sandbox has an inbuilt _ object from lodash v3:10.1
postmanlabs/postman-docs pull request #3050
Opened 2021-05-06 09:05 UTC by meenakshi-dhanani

2021-05-06 09:11 UTC, DannyDainton commented on src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
> +* [lodash](https://lodash.com/) (inbuilt `_` object v3.10.1 exists in the sandbox by default, use require to load the latest version)
I would go with `built-in`,  as that would be consistent with the sentence above the list of modules.

Apart from that, it's cool. :D

2021-05-06 13:51 UTC, jkonrath-postman requested changes
Hi @meenakshi-dhanani, thanks for the changes!

How about this wording?
(The built-in `_` object v3.10.1 exists in the sandbox by default. Use `require` to load the latest version.)

2021-05-13 07:23 UTC, meenakshi-dhanani commented on src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
> +* [lodash](https://lodash.com/) (inbuilt `_` object v3.10.1 exists in the sandbox by default, use require to load the latest version)
Done

2021-05-13 07:28 UTC, sowmyaraj92 approved these changes
Looks good! 🎉

2021-05-13 07:30 UTC, DannyDainton approved these changes

2021-05-13 14:00 UTC, jkonrath-postman approved these changes
Looks good!

2021-05-13 14:00 UTC, merged