WEBSOCKET-51 WebSocket doc
postmanlabs/postman-docs pull request #3052
Opened 2021-05-07 21:46 UTC by jkonrath-postman

2021-05-10 09:59 UTC, sowmyaraj92 requested changes
@jkonrath-postman Hey Jon, Overall the WebSocket doc looks good. I have suggested few minor changes.

2021-05-10 09:59 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +At the top of the message pane is a connection details badge. It shows if the connection is connecting, connected, disconnecting, or disconnected. Hover over the badge to show details on the connecti
I would suggest rephrasing this - "Next to this is a **^** which you can click to hide messages. Click the **v** to show messages if hidden. " >
You can click **^** next to the badge to hide messages. If messages are hidden, click **^**" to display them.

2021-05-10 09:59 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +The following controls are above the message display:
"Above the message display, you will be able to see the following controls:" maybe this?

2021-05-10 09:59 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +[![WebSocket messages](https://assets.postman.com/postman-docs/websocket-messages.jpg)](https://assets.postman.com/postman-docs/websocket-messages.jpg)
Can we move the screenshot just above the `The following controls are above the message display...` line?

2021-05-10 09:59 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +* A search control. Enter a search term to display only messages containing the term. Click **X** to end the search.
* Search control — You can enter a search keyword in the search control to display only the messages containing the keyword. Click **X** to end the search.

2021-05-10 09:59 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +* The message type list. Select if you want to view all messages, or only incoming or outgoing messages.
* Message type list — Select if you want to view all messages or only incoming or outgoing messages.

2021-05-10 09:59 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +* A trash can icon. Click this to clear all messages.
* Trash — Click the trash can icon to clear all messages.

2021-05-10 09:59 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +1. Click **Disconnect** to disconnect your WebSocket request's connection.
Maybe this — "To disconnect your WebSocket request's connection, click **Disconnect**." ?

2021-05-10 09:59 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +* If you hover over the time, a copy icon is also shown. Click this to copy the message to your clipboard.
Can we add a small screenshot/gif of how it's displayed for each message? (Since there are a lot of bullet points, a bit tricky to look out for information)

2021-05-10 09:59 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +* Click Wrap Line to add or remove line wraps
remove line wraps > "remove line wraps."

2021-05-10 15:12 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +| Handshake request timeout in ms | The length the handshake request should wait before timing out, in milliseconds. This is reset after every redirection. |
Changed this to "How long the handshake request will wait before timing out, in milliseconds."
Also removed that other "should" above.

2021-05-10 15:15 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +You can use the console to debug issues with a WebSocket connection. Click **Console** in the bottom status bar to open the console and view log messages.
Got it, but dropped the word "present." 

(UX uses "Status Bar" (I think) but I didn't change it here. Later I need to look into this globally.)

2021-05-10 15:19 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +You can add details to your request, for example to send additional parameters and headers. You can also configure the connection.
The details are the parameters and headers. Configuring is settings like timeouts and number of attempts.

2021-05-10 15:23 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +> You can't change settings while you are connected. You must make changes before you connect, or click **Disconnect** to stop the current connection.
* We should be using contractions according to UX (we'll talk about that later)
* Changed that to "request details"
* Changed that to "make any changes"

2021-05-10 15:25 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +In the bottom left corner of the editor, you can select the format of your message: **Text**, **JSON**, **XML**, **HTML**, or **Array Buffer**. The editor has syntax highlighting according to the sel
My editor's auto-complete really hates me sometimes.

2021-05-10 15:44 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +* If you hover over the time, a copy icon is also shown. Click this to copy the message to your clipboard.
These are the same as the above screenshot. I want to do an animated gif of the first one though, because it's a bit tricky.

2021-05-14 16:51 UTC, codenirvana requested changes
Overall looks good to me, we just need to:
1. Update a few screenshots
2. Remove/Update a few things (left comments)

2021-05-14 16:51 UTC, codenirvana commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +You can create a WebSocket request from the left sidebar in Postman.
We can also mention the ⌘+N (or Ctrl + N) shortcut.

2021-05-14 16:51 UTC, codenirvana commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +  [![New Screen](https://assets.postman.com/postman-docs/new-request-websocket.jpg)](https://assets.postman.com/postman-docs/new-request-websocket.jpg)
We need to update both the assets.
Changes:
1. New WebSocket Logo
2. Beta label in the context menu
3. Config button (next to connect) is removed

2021-05-14 16:51 UTC, codenirvana commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +When you have finished composing your message, click **Send**. The sent message will remain in the window, in case you want to change it and re-send.
Another feature (only for JSON messages) is, you can comment out the part of the payload which you don't want to send it across. Useful for debugging purposes.

<img width="553" alt="Screenshot 2021-05-14 at 10 13 57 PM" src="https://user-images.githubusercontent.com/4865836/118302315-af905a80-b501-11eb-884b-ca53be747dcb.png">

2021-05-14 16:51 UTC, codenirvana commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +* Click the copy icon to copy the message body to the clipboard.
This (copy action inside editor) is removed.

2021-05-14 16:51 UTC, codenirvana commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +Click the settings button <img alt="WebSocket configure button" src="https://assets.postman.com/postman-docs/websocket-setting-mini-button.jpg" width="27px"/> next to **Connect** to make changes to t
This button is replaced with always visible tabs:
<img width="535" alt="Screenshot 2021-05-14 at 10 18 28 PM" src="https://user-images.githubusercontent.com/4865836/118302819-507f1580-b502-11eb-807c-1a26dde761d5.png">

2021-05-14 16:51 UTC, codenirvana commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +| Maximum number of redirects | The maximum number of redirects to follow. |
Redirect settings are removed.

2021-05-14 16:51 UTC, codenirvana commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +| Maximum message size in bytes | The maximum allowed message size in bytes. |
Now accepts size in MB.

2021-05-17 08:14 UTC, shamasis commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +When you have finished composing your message, click **Send**. The sent message will remain in the window, in case you want to change it and re-send.
Hold on from documenting this comment stripping feature yet.

2021-05-17 15:32 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +When you have finished composing your message, click **Send**. The sent message will remain in the window, in case you want to change it and re-send.
No changes made here.

2021-05-18 15:34 UTC, codenirvana approved these changes

2021-05-18 16:07 UTC, sowmyaraj92 reviewed
@jkonrath-postman Just minor changes and we are good to go!

2021-05-18 16:07 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +At the top of the message pane is a connection details badge. It shows if the connection is connecting, connected, disconnecting, or disconnected. Hover over the badge to show details on the connecti
Since ^ is a clickable action, can we remove "the" in front of it? 
"Click **^** next to the badge to hide messages. If the messages are hidden, click **v** to show them", maybe?

2021-05-18 16:07 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +* If you hover over a message, a check box is displayed. Select the check boxes for two messages, and the time difference between the messages will be displayed. Click **deselect** to remove the time
**deselect** > **Deselect**

2021-05-18 16:07 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +[![WebSocket message body](https://assets.postman.com/postman-docs/websocket-message-body.jpg)](https://assets.postman.com/postman-docs/websocket-message-body.jpg)
Just a suggestion to add an image border here.

2021-05-18 16:07 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +  [![New Screen](https://assets.postman.com/postman-docs/new-request-websocket.jpg)](https://assets.postman.com/postman-docs/new-request-websocket.jpg)
Also, if we can blur out Beta in the screenshot, would be great!

2021-05-18 16:11 UTC, codenirvana commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +  [![New Screen](https://assets.postman.com/postman-docs/new-request-websocket.jpg)](https://assets.postman.com/postman-docs/new-request-websocket.jpg)
`Beta` here doesn’t mean Postman Beta 😅

2021-05-18 16:15 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +  [![New Screen](https://assets.postman.com/postman-docs/new-request-websocket.jpg)](https://assets.postman.com/postman-docs/new-request-websocket.jpg)
Oops! My bad. 🤦‍♀️ 😅 Thank you, Udit!
(Smiling goofily at the moment :D)

2021-05-18 16:29 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +  [![New Screen](https://assets.postman.com/postman-docs/new-request-websocket.jpg)](https://assets.postman.com/postman-docs/new-request-websocket.jpg)
Resolved the border; didn't touch the beta mark.

2021-05-19 02:56 UTC, sowmyaraj92 approved these changes
Looks good to me! 🎉

2021-05-19 21:42 UTC, merged