Private API Network
postmanlabs/postman-docs pull request #3063
Opened 2021-05-13 10:52 UTC by sowmyaraj92

* To update the docs for Private API Network

2021-05-25 07:26 UTC, gitThingsDone commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +You can also add an API to your team's Private API Network from Postman. Go to the [API Builder](/docs/designing-and-developing-your-api/the-api-workflow/) via **APIs** in the left sidebar. Select an
Do we still call this the API Builder externally?

2021-05-27 05:26 UTC, sowmyaraj92 commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +You can also add an API to your team's Private API Network from Postman. Go to the [API Builder](/docs/designing-and-developing-your-api/the-api-workflow/) via **APIs** in the left sidebar. Select an
@gitThingsDone We have a page titled "Using the API Builder", we would need a renaming there as well if we are no longer using this terminology. 
Need more inputs here @jkonrath-postman @DannyDainton : )

2021-05-27 14:21 UTC, jkonrath-postman requested changes
Some minor changes.

2021-05-27 14:21 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
>  Share the APIs that your team uses internally to the Private API Network. Your team can learn about and access these APIs and start using them right away.
Should that start with "You can share the APIs that your team uses internally..." ?

2021-05-27 14:21 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +If you're logged in, go to **Home** in the upper-left of Postman > click **Private API Network** in the left navigation bar. This will take you directly to your team's [Private API Network](https://w
Instead of "if you're logged in" say "log in and.."

2021-05-27 14:21 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +In the modal, choose the workspace containing the API you want to add to the network. You can select as many APIs to add to the network at one time. For each API selected, specify the version(s) to a
change "version(s)" to "versions"

2021-05-27 14:21 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
>  Once you've created the folder, click __Add New__ and select __APIs__ to add APIs to your Team's API Network. You can choose the workspace and then select as many APIs you want to add to the network
Change "version(s)" to "versions"

2021-05-27 14:21 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
>  You can change the versions, update the API summary and even modify the folder to which the API should be added.
change to 
You can change the versions, update the API summary, and modify the folder to which the API should be added.

(Serial comma, drop the "even")

2021-05-27 14:21 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +You can also review version-level details on the right. All available versions are listed below, with an indicator of the active version as well as the version(s) listed to the network.
Change "version(s)" to "versions"

2021-05-27 14:21 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
>  > In order to add your API to the network, it must be in the [API Builder](/docs/designing-and-developing-your-api/the-api-workflow/). You can only add APIs, not collections, to the Private API Netwo
Change "In order to" to "To"

2021-05-28 15:07 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +If you're logged in, go to **Home** in the upper-left of Postman > click **Private API Network** in the left navigation bar. This will take you directly to your team's [Private API Network](https://w
The first sentence is still a big weird. Maybe "If you're logged in, go to **Home** in the upper-left of Postman, and click **Private API Network** in the left navigation bar."

2021-05-28 15:08 UTC, jkonrath-postman approved these changes
Approved, but take a look at that thing on like 34 real quick.

2021-05-28 15:30 UTC, merged