SAST Scanner Rules
postmanlabs/postman-docs pull request #3086
Opened 2021-05-24 05:33 UTC by sowmyaraj92

2021-05-24 12:38 UTC, jaceppo approved these changes

2021-05-24 12:39 UTC, jaceppo approved these changes

2021-05-27 12:43 UTC, tirth055 commented on src/pages/docs/api-security/api-schema.md
> +| Severity | Issue description | Possible fix |
Instead of possible fix, can we use something like "Recommendation" or "Potential fix".
Since there may be cases where users might be okay with accepting this warning and might not really need a "Fix" for this.

2021-05-27 12:49 UTC, tirth055 commented on src/pages/docs/api-security/api-schema.md
> +security: []
The resolution should not contain a blank security array

2021-05-27 14:49 UTC, tirth055 commented on src/pages/docs/api-security/api-schema.md
> +    search_keyword: "api schema, schema validation, security ruleset, security validation"
Can we also add "api security" here.  Also a side note - we shouldn't use security ruleset as a product abstraction yet - this would unnecessarily confuse users about what is a security ruleset v/s security rule v/s validation rule v/s errors/warnings

2021-05-27 15:23 UTC, tirth055 commented on src/pages/docs/api-security/api-schema.md
> +With API Schemas, you will be able to catch security blindspots and misses at the API definition stage of API development. In Postman, you can [validate your API schemas](/docs/designing-and-developi
Let's reword this to something simple like " Postman shows up validation errors in an API schema as you edit it in the define tab. With the help of Warnings in Postman, you will be able to catch security blindspots through the same workflow. Postman will show warnings with the messages mentioned below as soon as it identifies a potential security misconfiguration in your API schema"

2021-05-27 15:27 UTC, tirth055 commented on src/pages/docs/api-security/api-schema.md
> +Also, for every security issue, you can deep-dive into the implications and consequences of leaving the security issue unpatched and the steps that needs to be taken in order to patch this issue.
Can we consider rewording this section to - "The list of Security Warnings that Postman supports at the moment are shown below. You can use this page to deep-dive into each such warning, understand its implication and find out ways to apply patches in order to solve the grass root issue highlighted by the warning"

2021-05-27 15:28 UTC, tirth055 commented on src/pages/docs/api-security/api-schema.md
> +* [Token URL uses HTTP protocol and not a valid uri-reference](#token-url-uses-http-protocol-and-not-a-valid-uri-reference)
We should do a review of whether the terminology here is an exact match to that mentioned on https://apisecurity.io/encyclopedia/content/oasv3/security/authentication/authentication and similar sections on this page.

2021-05-27 15:32 UTC, tirth055 commented on src/pages/docs/api-security/api-schema.md
> +* [Token URL uses HTTP protocol and not a valid uri-reference](#token-url-uses-http-protocol-and-not-a-valid-uri-reference)
Also it would be better if we could group them in a way similar to the one mentioned in the last commit(s) instead of showing 18 different copies.
Structure could be something like:
1) Group 1 (generic description)
- This is applicable if you see the following message text in the warning
   Message : <message A> Severity : High/Med/Low
   Message : <message B> Severity : High/Med/Low
 - Implications/Description
 - Potential fix/ Recommendation
   <GIF explaining how to resolve this warning>

2021-06-03 15:35 UTC, jkonrath-postman requested changes
A bunch of minor edits...

2021-06-03 15:35 UTC, jkonrath-postman commented on src/pages/docs/api-security/api-schema.md
> +Also, for every security warning that Postman supports, you can deep-dive into each warning, understand its implication and find out ways to apply patches in order to solve the grass root issue highl
I'm not into using deep-dive; "inspect each warning" maybe?
Also don't use "grass root issue" - maybe "the underlying issue"?

2021-06-03 15:35 UTC, jkonrath-postman commented on src/pages/docs/api-security/api-schema.md
> +| High | If the global security field is not defined, the API does not require any authentication by default. Anyone can access the API operations that do not have a security field defined. | Securit
"The security property..."

2021-06-03 15:35 UTC, jkonrath-postman commented on src/pages/docs/api-security/api-schema.md
> +| High | An empty object in the security field disables the authentication completely. Anyone can access the operations that do not have a security field defined, without any authentication. | Securi
* "The security property"
* Put backticks around `array`

2021-06-03 15:35 UTC, jkonrath-postman commented on src/pages/docs/api-security/api-schema.md
> +| High | If the security field contains an empty array then it means that no security scheme is applied to the operations by default. | Security property should contain at least one item in the array
Change "Security property" to "The security property" in all of these.

2021-06-03 15:35 UTC, jkonrath-postman commented on src/pages/docs/api-security/api-schema.md
> +| Medium |  If both the global security field and operation’s security field are not defined then anyone can access the API without any authentication. | Define security property in the operation. |
* Change "then" to a comma.
* "Define a security property"

2021-06-03 15:35 UTC, jkonrath-postman commented on src/pages/docs/api-security/api-schema.md
> +| High | The credentials are sent as plain text over an unencrypted network. Attackers can intercept the credentials simply by listening to the network traffic in a public WiFi network. |Make sure th
Wi-Fi

2021-06-03 15:35 UTC, jkonrath-postman commented on src/pages/docs/api-security/api-schema.md
> +| Medium | The credentials are sent as plain text over an unencrypted network. Attackers can intercept the access tokens simply by listening to the network traffic in a public WiFi network. | Make su
Search/replace WiFi with Wi-Fi globally

2021-06-03 15:35 UTC, jkonrath-postman commented on src/pages/docs/api-security/api-schema.md
> +
delete this blank line

2021-06-03 15:35 UTC, jkonrath-postman commented on src/pages/docs/api-security/api-schema.md
> +  - url: https://my.api.server.com/
Global: we need to change any URLs so they are a domain or subdomain of example.com.
Like for this, change it to https://my.api.example.com

2021-06-03 17:07 UTC, tirth055 commented on src/pages/docs/api-security/api-schema.md
> +title: "API Schema"
Let's change this to "Security Warnings" maybe?

2021-06-03 17:08 UTC, tirth055 commented on src/pages/docs/api-security/api-schema.md
> +    url: "/docs/api-security/token-scanner/"
"Token Scanner" and "Security Warnings" do not have any overlaps. I don't think we should mention "Token Scanner" as a prerequisite here.

2021-06-04 05:36 UTC, sowmyaraj92 commented on src/pages/docs/api-security/api-schema.md
> +| Severity | Issue description | Possible fix |
We already discussed this - keeping "Possible fix" for now.

2021-06-04 12:17 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings.md
> +    * [Security field for the operation does not contain any item](#security-field-for-the-operation-does-not-contain-any-item)
@rishab-postman  please review rules till here.

2021-06-04 12:19 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings.md
> +    * [API accepts credentials from OpenID Connect authentication in plain text](#api-accepts-credentials-from-openid-connect-authentication-in-plain-text)
Ronak please start reviewing individual rules from here.

2021-06-04 12:28 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +* [Operations server configuration allows insecure enforcement of security schemes](#operations-server-configuration-allows-insecure-enforcement-of-security-schemes)
Shouldn't this be, operations' server configuration allows insecure enforcement of security schemes.

2021-06-04 12:30 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +    * [Server URL is using HTTP protocol](#server-url-is-using-http-protocol)
This should be 

The Operation's Server URL is using HTTP protocol

2021-06-04 12:31 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +    * [Authorization URL uses http protocol. Credentials will be transferred as plain text](#authorization-url-uses-http-protocol-credentials-will-be-transferred-as-plain-text)
This should be 

Authorization URL uses HTTP protocol. Credentials will be transferred as plain text

2021-06-04 12:32 UTC, rishab-postman commented on src/pages/docs/api-security/security-warnings.md
> +| High | If the global security field is not defined, the API does not require any authentication by default. Anyone can access the API operations that do not have a security field defined. | The sec
For Possible fix text, we can use "security field" instead of "security property"

2021-06-04 12:42 UTC, rishab-postman commented on src/pages/docs/api-security/security-warnings.md
> +| High | Without any reusable security schemes, your API does not globally specify any authentication method for consuming the API operations. This means that anyone can use API operations as long as
The description is the same as the **Possible exploit scenario** section content [here](https://apisecurity.io/encyclopedia/content/oasv3/security/authentication/v3-global-securitydefinitions-undefined). Can we please reword this?

2021-06-04 12:44 UTC, rishab-postman commented on src/pages/docs/api-security/security-warnings.md
> +| High | Without any reusable security schemes, your API does not globally specify any authentication method for consuming the API operations. This means that anyone can use API operations as long as
Resolution here should be
```
components:
  securitySchemes:
    DummyBasicAuth:
      type: http
      scheme: basic
```

2021-06-04 12:47 UTC, rishab-postman commented on src/pages/docs/api-security/security-warnings.md
> +| Medium | This means that no security scheme is applied to the API operation by default. | The security property in any operation should contain at least one item in the array. |
Remove `This means that` from the description
In Possible fix use `security field` instead of `security property`

2021-06-04 13:00 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +    * [Token URL uses HTTP protocol](#token-url-uses-http-protocol)
This can be

OAuth token URL is using HTTP protocol

2021-06-04 13:01 UTC, rishab-postman commented on src/pages/docs/api-security/security-warnings.md
> +    * [Security field is not an array](#security-field-is-not-an-array)
@tirth055 This is more of a validation error than a security warning. Can we please remove this?

2021-06-04 13:03 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +| Medium | The credentials are sent as plain text over an unencrypted network. Attackers can intercept the access tokens simply by listening to the network traffic in a public Wi-Fi network. | Make s
| Make sure the server URL follows HTTPS protocol. |

should be

| Make sure the server URL uses HTTPS protocol. |

2021-06-04 13:04 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +## Operations server configuration allows insecure enforcement of security schemes
Shouldn't this be, operations' server configuration allows insecure enforcement of security schemes.

2021-06-04 13:06 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +| Medium | The API operation accepts the access tokens from a flow that are transported in plain text over an unencrypted channel. Attackers can easily intercept API calls and retrieve the unencrypte
| Make sure that the server URL is a valid URL and follows HTTPS protocol. |

should be

| Make sure that the server URL is a valid URL and uses HTTPS protocol. |

2021-06-04 13:06 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +| Medium | The API operation accepts the credentials that are transported in plain text over an unencrypted channel. Attackers can easily intercept API calls and retrieve the unencrypted tokens. They
| Make sure that the server URL is a valid URL and follows HTTPS protocol. |

should be

| Make sure that the server URL is a valid URL and uses HTTPS protocol. |

2021-06-04 13:27 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +### Server URL is using HTTP protocol
Same as above

2021-06-04 13:29 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +| Medium | The credentials for an operation are sent as plain text over an unencrypted network. Attackers can intercept the access tokens simply by listening to the network traffic in a public Wi-Fi
| Make sure server field of the operation follows HTTPS protocol. |

should be

| Make sure server field of the operation uses HTTPS protocol. |

2021-06-04 13:29 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +### Authorization URL uses http protocol. Credentials will be transferred as plain text
same as above

2021-06-04 13:31 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +```yaml
Resolution schema does not include the global `server` field.

2021-06-04 13:32 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +    authorizationUrl: https://test.com
May be use a different auth URL like this,

authorizationUrl: https://my.auth.server.com/

2021-06-04 13:32 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +### Token URL uses HTTP protocol
Same as above

2021-06-04 13:33 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +| Medium | Tokens are transported over an unencrypted channel. Anyone listening to the network traffic while the token is being sent can intercept it. | Make sure that the token URL is a valid URL an
Tokens are transported over an unencrypted channel. 

should be

OAuth authentication tokens are transported over an unencrypted channel.

2021-06-04 13:34 UTC, ronakodhaviya commented on src/pages/docs/api-security/security-warnings.md
> +```yaml
Lets add a few more lines to the the resolution schema example

2021-06-04 13:37 UTC, rishab-postman commented on src/pages/docs/api-security/security-warnings.md
> +```yaml
we can use this schema
```
components:
  securitySchemes:
     OauthScheme:
        type: oauth2
        flows: 
          authorizationCode:
            tokenUrl: https://test.com
```

2021-06-04 13:44 UTC, rishab-postman commented on src/pages/docs/api-security/security-warnings.md
> +| Medium | This means that no security scheme is applied to the API operation by default. | The security property in any operation should contain at least one item in the array. |
Resolution schema
```
paths:
  /user:
    get:
      security:
      - testAuth : []
```

2021-06-04 19:46 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +    * [Authorization URL uses http protocol. Credentials will be transferred as plain text](#authorization-url-uses-http-protocol-credentials-will-be-transferred-as-plain-text)
Fixed.

2021-06-04 19:47 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +    * [Server URL is using HTTP protocol](#server-url-is-using-http-protocol)
Fixed - Server URL of the operation is using HTTP protocol

2021-06-04 19:48 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +* [Operations server configuration allows insecure enforcement of security schemes](#operations-server-configuration-allows-insecure-enforcement-of-security-schemes)
Fixed - Server configuration of the operation allows insecure enforcement of security schemes

2021-06-04 19:49 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +| High | If the global security field is not defined, the API does not require any authentication by default. Anyone can access the API operations that do not have a security field defined. | The sec
Fixed.

2021-06-04 19:53 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +| High | Without any reusable security schemes, your API does not globally specify any authentication method for consuming the API operations. This means that anyone can use API operations as long as
Fixed - | High | The components object of the API does not declare any security schemes which can be used in the security field of the API or individual operations. | Security schemes should be defined in the schema of the component. |

Plus, the resolution code snippet updated.

2021-06-04 19:56 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +| Medium | This means that no security scheme is applied to the API operation by default. | The security property in any operation should contain at least one item in the array. |
Fixed - | Medium | No security scheme is applied to the API operation by default. | The security field in any operation should contain at least one item in the array. |

Resolution code snippet updated.

2021-06-04 19:58 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +| Medium | The credentials are sent as plain text over an unencrypted network. Attackers can intercept the access tokens simply by listening to the network traffic in a public Wi-Fi network. | Make s
Fixed - Make sure that the server URL is a valid URL and uses HTTPS protocol.

2021-06-04 19:58 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +## Operations server configuration allows insecure enforcement of security schemes
Fixed - Server configuration of the operation allows insecure enforcement of security schemes

2021-06-04 19:59 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +| Medium | The API operation accepts the access tokens from a flow that are transported in plain text over an unencrypted channel. Attackers can easily intercept API calls and retrieve the unencrypte
Fixed - Make sure that the server URL of the operation is a valid URL and uses HTTPS protocol.

2021-06-04 20:00 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +| Medium | The API operation accepts the credentials that are transported in plain text over an unencrypted channel. Attackers can easily intercept API calls and retrieve the unencrypted tokens. They
Fixed - Make sure that the server URL of the operation is a valid URL and uses HTTPS protocol.

2021-06-04 20:00 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +### Server URL is using HTTP protocol
Fixed - Server URL of the operation is using HTTP protocol

2021-06-04 20:01 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +| Medium | The credentials for an operation are sent as plain text over an unencrypted network. Attackers can intercept the access tokens simply by listening to the network traffic in a public Wi-Fi
Fixed - Make sure that the server URL of the operation is a valid URL and uses HTTPS protocol.

2021-06-04 20:02 UTC, jkonrath-postman approved these changes

2021-06-04 20:07 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +    authorizationUrl: https://test.com
Fixed - authorizationUrl: https://my.auth.example.com/

2021-06-04 20:08 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +| Medium | Tokens are transported over an unencrypted channel. Anyone listening to the network traffic while the token is being sent can intercept it. | Make sure that the token URL is a valid URL an
Fixed - OAuth authentication tokens are transported over an unencrypted channel. Anyone listening to the network traffic while the token is being sent can intercept it.

2021-06-04 20:09 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +```yaml
Fixed - 

components:
  securitySchemes:
     OauthScheme:
        type: oauth2
        flows:
          authorizationCode:
            tokenUrl: https://my.token.example.com/

2021-06-04 20:14 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +    * [Security field is not an array](#security-field-is-not-an-array)
Removed.

2021-06-05 08:23 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings.md
> +    * [Token URL uses HTTP protocol](#token-url-uses-http-protocol)
This message will be shown in the product at the exact location of the token url mention. And this is specific to OAuth - so in my opinion, we can go ahead with the existing wording

2021-06-05 08:25 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings.md
> +### Authorization URL uses http protocol. Credentials will be transferred as plain text
This should be resolved in the latest commit.

2021-06-05 08:26 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings.md
> +```yaml
Should be resolved in the latest commit. Have added the exact resolution schema as proposed by @rishab-postman

2021-06-05 08:26 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings.md
> +### Token URL uses HTTP protocol
Should be resolved in the latest commit.

2021-06-07 06:18 UTC, rishabjain22 commented on src/pages/docs/api-security/security-warnings.md
> +    * [Scope for OAuth scheme used in security field not defined in the securityScheme declaration](#scope-for-oauth-scheme-used-in-security-field-not-defined-in-the-securityscheme-declaration)
AFAIR we have decided to use `Security field is missing a scope for OAuth scheme defined in securityScheme object` message for this Rule as mentioned [here in Rule 18](https://postmanlabs.atlassian.net/wiki/spaces/CD/pages/3278733868/SAST+security+warning+messages). @iprithvitharun Can you please check this once.

2021-06-07 06:22 UTC, rishabjain22 commented on src/pages/docs/api-security/security-warnings.md
> +| Low | The OAuth2 scopes used in the global security field should be defined in the security schemes field. Otherwise, an attacker can introduce their scopes to fill the gap and exploit the system.
@iprithvitharun If we are updating the message as per [this comment](https://github.com/postmanlabs/postman-docs/pull/3086/files#r646298886) then please update the heading and description here as well.

2021-06-07 06:51 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +    * [Scope for OAuth scheme used in security field not defined in the securityScheme declaration](#scope-for-oauth-scheme-used-in-security-field-not-defined-in-the-securityscheme-declaration)
@rishabjain22 The change was suggested by @tirth055

2021-06-07 06:53 UTC, iprithvitharun commented on src/pages/docs/api-security/security-warnings.md
> +| Low | The OAuth2 scopes used in the global security field should be defined in the security schemes field. Otherwise, an attacker can introduce their scopes to fill the gap and exploit the system.
@rishabjain22 Heading is updated - Scope for OAuth scheme used in security field not defined in the securityScheme declaration

If the description doesn't match the new heading please mention please suggest the changes and I'll update it. TIA

2021-06-07 07:02 UTC, rishabjain22 commented on src/pages/docs/api-security/security-warnings.md
> +    * [Scope for OAuth scheme used in security field not defined in the securityScheme declaration](#scope-for-oauth-scheme-used-in-security-field-not-defined-in-the-securityscheme-declaration)
@tirth055 @iprithvitharun this rule checks, if all the Oauth scopes defined in securityScheme are used in the global security field or not, but the current message implies otherwise. So I think the current message is wrong.

2021-06-07 07:04 UTC, rishabjain22 commented on src/pages/docs/api-security/security-warnings.md
> +    * [Scope for OAuth scheme used not defined in the securityScheme declaration](#scope-for-oauth-scheme-used-not-defined-in-the-securityscheme-declaration)
For this rule as well message should be this `Operation’s security field is missing a scope for OAuth scheme defined in securityScheme object`.[ Reference comment](https://postmanlabs.atlassian.net/wiki/spaces/CD/pages/3278733868/SAST+security+warning+messages?focusedCommentId=3329393196#comment-3329393196)

2021-06-07 07:06 UTC, rishabjain22 commented on src/pages/docs/api-security/security-warnings.md
> +| Low | The OAuth2 scopes used in the global security field should be defined in the security schemes field. Otherwise, an attacker can introduce their scopes to fill the gap and exploit the system.
@iprithvitharun Let's decide on the heading then we can update the description

2021-06-07 11:23 UTC, merged