Proxy and auto-select region updates
postmanlabs/postman-docs pull request #3121
Opened 2021-06-10 14:01 UTC by sowmyaraj92

2021-06-10 15:02 UTC, jkonrath-postman requested changes
A few little things...

2021-06-10 15:02 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/proxy.md
> +The **Use the system proxy** option allows Postman to use the system's default proxy configuration. It contains an option to use `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` environment variables of t
Instead of ending with "the said system", maybe "It contains an option to use the systems x,y,z environment variables.

2021-06-10 15:02 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/proxy.md
> +The field below **Proxy Server** is **Proxy Auth**, turning this on makes the requests use Basic Authentication method, which requires a username and a password.
Break into two sentences, second one starting with Turning

2021-06-10 15:02 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/proxy.md
> +The **Proxy Bypass** setting lies below the **Proxy Server** option. A number of comma separated hosts can be provided here for which the requests do not use the proxy settings.
Change lies to is. comma-separated is hyphenated.

2021-06-18 03:48 UTC, sowmyaraj92 commented
Raising separate PRs for 2 issues - also `package-lock.json` got modified :( Hence closing this PR.

2021-06-18 03:48 UTC, closed without merging