Update dropbox.md
postmanlabs/postman-docs pull request #3133
Opened 2021-06-15 10:07 UTC by jerry-li-dev

2021-06-15 13:53 UTC, jkonrath-postman requested changes
A couple of little changes, but otherwise good

2021-06-15 13:53 UTC, jkonrath-postman commented on src/pages/docs/integrations/available-integrations/dropbox.md
>  From now on, every change saved to your Postman Collection will automatically upload changes to Dropbox in real time. Complement your team's existing workflows and backup your Postman Collections to
backup/back up

2021-06-15 13:53 UTC, jkonrath-postman commented on src/pages/docs/integrations/available-integrations/dropbox.md
> +    ![dropbox login](https://assets.postman.com/postman-docs/dropbox-login.jpg)
Old screenshot - still mentions Postman Pro

2021-06-15 13:53 UTC, jkonrath-postman commented on src/pages/docs/integrations/available-integrations/dropbox.md
> +    ![allow postman access](https://assets.postman.com/postman-docs/dropbox-allow.jpg)
Also old screenshot

2021-06-15 13:53 UTC, jkonrath-postman commented on src/pages/docs/integrations/available-integrations/dropbox.md
> +  ![view in dropbox](https://assets.postman.com/postman-docs/dropbox_view.jpg)
Old screenshot. (You might be able to just edit that by hand to remove the "Pro" from the Postman Pro folder.)

2021-06-16 22:34 UTC, jerry-li-dev commented on src/pages/docs/integrations/available-integrations/dropbox.md
> +    ![dropbox login](https://assets.postman.com/postman-docs/dropbox-login.jpg)
This is a new screenshot I created. Dropbox still calls it Postman Pro.

2021-06-16 22:35 UTC, jerry-li-dev commented on src/pages/docs/integrations/available-integrations/dropbox.md
> +    ![allow postman access](https://assets.postman.com/postman-docs/dropbox-allow.jpg)
Same thing here. Dropbox still calls it Postman Pro.

2021-06-16 22:36 UTC, jerry-li-dev commented on src/pages/docs/integrations/available-integrations/dropbox.md
> +  ![view in dropbox](https://assets.postman.com/postman-docs/dropbox_view.jpg)
Same thing here. Dropbox still calls it Postman Pro.

2021-06-17 14:52 UTC, jkonrath-postman approved these changes
Looks good to me

2021-06-17 14:54 UTC, merged