TW-76 Scratch Pad docs
postmanlabs/postman-docs pull request #3159
Opened 2021-06-23 17:35 UTC by jkonrath-postman

* New page
* Modifications to the syncing and managing account pages

2021-06-24 06:05 UTC, sowmyaraj92 requested changes
@jkonrath-postman Looks great overall, just minor edits! 🎉

2021-06-24 06:05 UTC, sowmyaraj92 commented on src/pages/docs/getting-started/using-scratch-pad.md
> +
All work in the Scratch Pad > "All the/your work in the Scratch Pad"
after you log in > "once you log in"

2021-06-24 15:25 UTC, jkonrath-postman commented on src/pages/docs/getting-started/using-scratch-pad.md
> +## What you can do in the Scratch Pad
Good idea, I'll use that.

2021-06-24 15:25 UTC, jkonrath-postman commented on src/pages/docs/getting-started/using-scratch-pad.md
> +* Edit documentation for a collection or request.
If a list is a mix of complete and incomplete sentences, you use a period for all of them. https://docs.microsoft.com/en-us/style-guide/scannable-content/lists#punctuation

2021-06-24 15:31 UTC, jkonrath-postman commented on src/pages/docs/getting-started/using-scratch-pad.md
> +If you're logged out or your connection to Postman is broken, you'll see a notice at the top of the screen indicating that you're already in the Scratch Pad.
Confirming this, but if there's no consensus from UX, I might stick with notice.

2021-06-24 16:48 UTC, jkonrath-postman commented on src/pages/docs/getting-started/using-scratch-pad.md
> +If you're logged out or your connection to Postman is broken, you'll see a notice at the top of the screen indicating that you're already in the Scratch Pad.
It's "global banner"...

2021-06-25 08:27 UTC, sowmyaraj92 approved these changes
Looks great! 😊 Ready to merge 🚀 🎉

2021-06-25 08:28 UTC, sowmyaraj92 commented on src/pages/docs/getting-started/using-scratch-pad.md
> +* Edit documentation for a collection or request.
Thank you for this information. Much needed :)

2021-06-25 13:06 UTC, merged