Working directory for Postman web - new branch
postmanlabs/postman-docs pull request #3180
Opened 2021-07-01 07:25 UTC by sowmyaraj92

2021-07-01 12:55 UTC, Raj-postman approved these changes
Rest of it looks all good to me. Thank you!

2021-07-01 12:55 UTC, Raj-postman commented on src/pages/docs/getting-started/settings.md
> +For Postman web, the working directory cannot be modified. When you upload a file on the web, it creates a folder with a random alphanumeric name (e.g. 6OPkYiXVr) in the `~/Postman/files` directory w
> the new folder created would prevent you from sharing the requests with other members seamlessly.

The new folder created would enable you to continue testing with files selected anywhere from your Desktop but for team members to have a seamless experience - it is always suggested that the files remain within ~/Postman/files.

2021-07-01 14:21 UTC, jkonrath-postman requested changes
Couple of minor things...

2021-07-01 14:21 UTC, jkonrath-postman commented on src/pages/docs/getting-started/settings.md
>  * **Location:** Path to local directory containing postman files. The default path populated as a placeholder is `~/Postman/files`.
postman should be Postman

2021-07-01 14:21 UTC, jkonrath-postman commented on src/pages/docs/getting-started/settings.md
> +For Postman app, you can modify the working directory. While uploading a file to the app during a POST request, you will be able to view the file only when it is present in the working directory.
"For Postman app" should be "For the Postman app"

2021-07-01 14:21 UTC, jkonrath-postman commented on src/pages/docs/getting-started/settings.md
> +For Postman web, the working directory cannot be modified. When you upload a file on the web, it creates a folder with a random alphanumeric name (e.g. 6OPkYiXVr) in the `~/Postman/files` directory w
* Change "(e.g. 6OPkYiXVr)" to "(such as 6OPkYiXVr)" and put backticks around the name.
* MSG says not to use "whether or not" - can you reword that?

2021-07-01 14:21 UTC, jkonrath-postman commented on src/pages/docs/getting-started/settings.md
> +the new folder created would enable you to continue testing with files selected anywhere from your Desktop. To ensure a seamless experience for your team members, it is recommended that the files are
* would enable you to / enables you to
* "recommended that the files are located in" - should that be "it's recommended that you keep files in the" or similar?

2021-07-02 04:32 UTC, saswatds commented on src/pages/docs/getting-started/settings.md
> +* **Location:** Path to local directory containing Postman files. The default path populated as a placeholder is `~/Postman/files`.
Is `Postman Files` a noun that people understand? 
To me, Location is the path in my local filesystem which Postman considers as the working directory. Users can put any files in there and Postman will consider them safe and persist the path relative to the working directory. Things outside the working directory are not considered safe.

2021-07-02 04:32 UTC, saswatds commented on src/pages/docs/getting-started/settings.md
> +For the Postman app, you can modify the working directory. While uploading a file to the app during a POST request, you will be able to view the file only when it is present in the working directory.
Should we say postman desktop app? postman app could mean web app as well. Not sure what 
> you will be able to view the file only when it is present in the working directory
means. 

The users will be able to view all files, it is just that files outside the working directory, we do not persist the file path in the collection for security reasons. If you put your files in the working directory they will be persisted relative to the working directory.

2021-07-02 04:32 UTC, saswatds commented on src/pages/docs/getting-started/settings.md
> +For Postman web, the working directory cannot be modified. When you upload a file on the web, it creates a folder with a random alphanumeric name (such as `6OPkYiXVr`) in the `~/Postman/files` direct
The seamless experience for team members only applies to the postman desktop app and has a small caveat that the team members also maintain the same working directory structure.

2021-07-02 07:07 UTC, saswatds approved these changes

2021-07-07 14:05 UTC, jkonrath-postman approved these changes
LGTM!

2021-07-07 17:04 UTC, merged