[TW-90] Rename VictorOps to Splunk On-Call
postmanlabs/postman-docs pull request #3183
Opened 2021-07-05 21:07 UTC by jkonrath-postman

* Rename page
* Add redirect
* Change names
* Cleaned up to make numbered procedures
* Image changes

TODO:
* Image Changes of Splunk On-Call interface
* Steps may be different on their end to get keys etc.

2021-07-07 06:42 UTC, sowmyaraj92 requested changes

2021-07-07 06:42 UTC, sowmyaraj92 commented on src/pages/docs/integrations/available-integrations/splunk-on-call.md
> +    url: "/docs/designing-and-developing-your-api/monitoring-your-api/intro-monitors/"
Can we add "search_keyword" too here?

2021-07-07 06:42 UTC, sowmyaraj92 commented on src/pages/docs/integrations/available-integrations/splunk-on-call.md
> +1. Click the **Add Integration** button.
Click **Add Integration**.

2021-07-07 06:42 UTC, sowmyaraj92 commented on src/pages/docs/integrations/available-integrations/splunk-on-call.md
> +1. If the integration is not already enabled, click the *Enable Integration* button.
click the *Enable Integration* button. > "click **Enable Integration**."

2021-07-07 06:42 UTC, sowmyaraj92 commented on src/pages/docs/integrations/available-integrations/splunk-on-call.md
> +1. On the **Settings** page, go to the the **Alert Behavior** menu and select **Integrations**.
**Alert Behavior** tab maybe?

2021-07-07 06:42 UTC, sowmyaraj92 commented on src/pages/docs/integrations/available-integrations/splunk-on-call.md
> +An incident on Splunk On-Call consists of the basic information of which monitor failed, with the number of errors and failed tests. It also provides a direct link to the failing monitor. This integr
Just a suggestion - Can we reword the first line, this part to be specific "consists of the basic information of which monitor failed" to something like - 
"consists of the basic information about the specific/particular monitor which failed"

2021-07-07 06:42 UTC, sowmyaraj92 commented on src/pages/docs/integrations/available-integrations/splunk-on-call.md
> +   [![enter key](https://assets.postman.com/postman-docs/58842547.png)](https://assets.postman.com/postman-docs/58842547.png)
Also, are we using `.png`formats for the images?

2021-07-07 06:42 UTC, sowmyaraj92 commented on redirects.json
> +}
Can we check if the redirects.json file is working fine?
 I got this error when I tried to run the branch locally - `Unexpected token { in JSON at position 60734`

2021-07-09 19:43 UTC, merged

2021-07-09 19:44 UTC, jkonrath-postman commented
Doing this without the screenshots, just to get the rename and text changes in there.

I'll pick up screenshot changes in tw-107.