[WEBSOCKET-120] WebSocket 1.1 docs
postmanlabs/postman-docs pull request #3233
Opened 2021-07-27 17:49 UTC by jkonrath-postman

2021-07-28 17:13 UTC, codenirvana requested changes

2021-07-30 08:44 UTC, sowmyaraj92 reviewed
Looks great overall, suggested minor edits.

2021-07-30 08:44 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +In Socket.IO, you have the ability to listen to specific events. The **Messages** pane will only display the events for which you've added listeners. Events will be color-coded according to event, to
"according to the event", maybe?

2021-07-30 08:44 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +* If you hover over the time of a raw SocketIO message, an information icon is displayed. Hover over it to see the time, MIME type, and size of the message.
Is it "SocketIO message" or "Socket.IO message"?

2021-07-30 08:44 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +1. In the tab header, select either **Raw** for a raw WebSocket request, or **Socket.IO** for a Socket.IO request.
Can we confirm the terminology for "tab header" here?

2021-07-30 08:44 UTC, sowmyaraj92 commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
>      url: "/docs/getting-started/installation-and-updates/"
Can we add a blog link for Websockets - https://blog.postman.com/postman-supports-websocket-apis/

2021-07-30 14:00 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
> +1. In the tab header, select either **Raw** for a raw WebSocket request, or **Socket.IO** for a Socket.IO request.
Content doesn't have a term for it in their word list, so I'm changing it to "upper left of the tab."

2021-07-30 14:00 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
>      url: "/docs/getting-started/installation-and-updates/"
We're adding all of these as part of Claire's thing. There's already a GH issue for this, so we'll do it there.

2021-07-30 16:28 UTC, merged