[MARKENG-430] Fix 3xx external links
postmanlabs/postman-docs pull request #3298
Opened 2021-07-29 20:59 UTC by pamelagilmour

##Tickets/Issues

[MARKENG-430]

##Root Cause

Urls throwing 300 status codes

##Solution Description

Updated urls from the spreadsheet with resolved urls

2021-07-29 21:24 UTC, jkonrath-postman reviewed
The legacy-documentation ones aren't a worry, since they're not built.

@tristandenyer These look ok to me but I wasn't sure about the long-term maintenance that might result.

Example: If you change https://docs.postman-echo.com/ to the redirect (https://www.postman.com/postman/workspace/published-postman-templates/documentation/631643-f695cab7-6878-eb55-7943-ad88e1ccfd65?ctx=documentation) won't that break if they ever move the target? Seems like it would make more sense to link to the first one, but I'm not an SEO person, so I'm not sure...

2021-07-29 22:00 UTC, tristandenyer commented
> If you change https://docs.postman-echo.com/ to the redirect (https://www.postman.com/postman/workspace/published-postman-templates/documentation/631643-f695cab7-6878-eb55-7943-ad88e1ccfd65?ctx=documentation) won't that break if they ever move the target? Seems like it would make more sense to link to the first one, but I'm not an SEO person, so I'm not sure...

I see your point @jkonrath-postman . I am just not sure how long the redirect for https://docs.postman-echo.com/ will live. To depend on a redirect is a bit brittle, even thought the URL for the new page appears brittle. We have an external link check step in the process (Frog), so if the new one breaks / moves, we will catch it then.

I'd like to stick to the Rule of always point to the resolved link, lest there be a reason (temporary, or otherwise.) This is in part SEO, but also UX, and moreover less reliance on middleware.

2021-07-29 22:02 UTC, tristandenyer approved these changes
LGTM, will also run Frog when in Beta.

2021-07-29 22:08 UTC, tristandenyer requested changes
@pamelagilmour Let's change these 6 links

2021-07-29 22:08 UTC, tristandenyer commented on legacy-documentation/v5/postman/team_library/activity_feed_and_restoring_collections.md
> +Log in to the [Postman Website](https://postman.postman.co/workspaces) and click the **Dashboard** button.
@pamelagilmour Let's change this one to be `https://go.postman.co. The new link is pointing to our Team's workspace (you were likely logged in when resolving the link.)

FYI @jkonrath-postman

2021-07-29 22:08 UTC, tristandenyer commented on src/components/Header/Header.data.json
> +      "url": "https://postman.postman.co/workspaces",
@pamelagilmour Let's change this one to be `https://go.postman.co. The new link is pointing to our Team's workspace (you were likely logged in when resolving the link.)

2021-07-29 22:08 UTC, tristandenyer commented on src/pages/docs/collaborating-in-postman/commenting-on-collections.md
> +1. Sign in to [Postman](https://postman.postman.co/workspaces).
@pamelagilmour Let's change this one to be `https://go.postman.co. The new link is pointing to our Team's workspace (you were likely logged in when resolving the link.)

2021-07-29 22:08 UTC, tristandenyer commented on src/pages/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections.md
> +You can review the activity for a team with a Postman Team, Business, or Enterprise account. In [Postman](https://postman.postman.co/workspaces), use the __Workspaces__ dropdown to select your team,
@pamelagilmour Let's change this one to be `https://go.postman.co. The new link is pointing to our Team's workspace (you were likely logged in when resolving the link.)

2021-07-29 22:08 UTC, tristandenyer commented on src/pages/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections.md
> +You can review the activity for your own account in [Postman](https://postman.postman.co/workspaces). Click your avatar in the top right, and select __Profile__ — the __Activity__ tab will list your
@pamelagilmour Let's change this one to be `https://go.postman.co. The new link is pointing to our Team's workspace (you were likely logged in when resolving the link.)

2021-07-29 22:08 UTC, tristandenyer commented on src/pages/docs/getting-started/installation-and-updates.md
> +To switch from the Chrome app to native, [download](https://www.postman.com/downloads/) Postman and [sign in to your account](https://postman.postman.co/workspaces). Start the native app, and your hi
@pamelagilmour Let's change this one to be `https://go.postman.co. The new link is pointing to our Team's workspace (you were likely logged in when resolving the link.)

2021-08-02 23:36 UTC, pamelagilmour commented
[MARKENG-430] Updated urls accordingly

2021-08-02 23:47 UTC, tristandenyer approved these changes
LGTM

2021-08-02 23:48 UTC, merged