[issue 3197] Explain Request ID that is passed to setNextRequest()
postmanlabs/postman-docs pull request #3307
Opened 2021-08-02 21:38 UTC by jkonrath-postman

* Short note and a screenshot for this
* Numbered list isn't a procedure, so change to bullets

2021-08-02 22:50 UTC, mark-anthony-postman requested changes

2021-08-02 22:50 UTC, mark-anthony-postman commented on src/pages/docs/running-collections/building-workflows.md
> +  <img src="https://assets.postman.com/postman-docs/setnextrequest-request-id.jpg" alt="request ID" width="350px">
Add a blank line above the img tag so that the image renders below the bullet item (rather than on the same line).

2021-08-03 02:12 UTC, taehoshino approved these changes

2021-08-03 02:28 UTC, mark-anthony-postman approved these changes

2021-08-03 02:55 UTC, merged