Update adding-private-network.md
postmanlabs/postman-docs pull request #3351
Opened 2021-08-06 12:47 UTC by jerry-li-dev

2021-08-06 14:47 UTC, jkonrath-postman requested changes

2021-08-06 14:47 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +<img alt="Add API Modal" src="https://assets.postman.com/postman-docs/add-to-team-private-api-network.jpg" width="500px"/>
Throw a border on this one. (It looks like it has one, but not on the bottom side?)

2021-08-06 14:47 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +<img alt="Add APIs Workspace" src="https://assets.postman.com/postman-docs/add-to-team-private-api-network.jpg" width="400px"/>
Same border thing. (Same image for both, though.)

2021-08-16 14:11 UTC, jkonrath-postman requested changes
Look into the image problems here - is it an S3 issue?

2021-08-16 14:11 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +<img alt="Add API Modal" src="https://assets.postman.com/postman-docs/add-to-team-private-api-network-2.jpg" width="500px"/>
Is something up with the S3 hosting on these? I'm getting an access denied message when I try to open the URL.

2021-08-17 00:11 UTC, jerry-li-dev commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +<img alt="Add API Modal" src="https://assets.postman.com/postman-docs/add-to-team-private-api-network-2.jpg" width="500px"/>
Ok, I just fixed the issue. I think the AWS upload errored out and it didn't show an error.

2021-08-17 00:15 UTC, jkonrath-postman approved these changes
LGTM

2021-08-17 02:41 UTC, merged