Language detection format fix
postmanlabs/postman-docs pull request #3358
Opened 2021-08-11 08:33 UTC by sowmyaraj92

2021-08-16 13:07 UTC, jkonrath-postman requested changes

2021-08-16 13:07 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/responses.md
> +For Postman to automatically format the body, make sure the appropriate Content-Type header is returned. If not, you can force formatting through JSON. You can force JSON formatting under the **Gener
* Change "JSON" to **JSON**.
* Change dropdown to dropdown list.

2021-08-17 03:44 UTC, Swapnil-getpostman approved these changes

2021-08-17 13:32 UTC, jkonrath-postman approved these changes
LGTM!

2021-08-18 04:07 UTC, merged