Security warnings - OpenAPI 2.0
postmanlabs/postman-docs pull request #3374
Opened 2021-08-19 11:27 UTC by sowmyaraj92

2021-08-20 15:53 UTC, jkonrath-postman requested changes
A few minor changes.

2021-08-20 15:53 UTC, jkonrath-postman commented on src/pages/docs/api-security/security-warnings-openapi2.md
> +title: "Security Warnings - OpenAPI 2.0"
I can't figure this out, but for some reason 2.0 is shown with a dash and 3.0 is shown with a longer em-dash in the title. It doesn't look right when you see them next to each other in the TOC. Any idea why? I looked at the source, and it's "space-dash-space" in both of them.

<img width="322" alt="image" src="https://user-images.githubusercontent.com/80709817/130258696-463a714e-18cb-499d-a941-4a145dd62141.png">

2021-08-20 15:53 UTC, jkonrath-postman commented on src/pages/docs/api-security/security-warnings-openapi2.md
> +In Postman, we highly recommend you to follow Security warnings at the API definition stage of API development. This set of warnings can be used to govern the security posture of any API definition i
This is subjective, but I don't really like the term "security misses" - can we call it "security issues" or "security warnings"? (This applies to both pages)

2021-08-20 15:53 UTC, jkonrath-postman commented on src/pages/docs/api-security/security-warnings.md
> +> Security warnings are available for OpenAPI 3.0 and [OpenAPI 2.0](/docs/api-security/security-warnings-openapi2/) schemas.
For the image below, can you crop this so it's just the API pane, like this?
<img width="403" alt="image" src="https://user-images.githubusercontent.com/80709817/130259658-7250c3c6-96ed-474f-9dcf-71432790deac.png">

2021-08-20 15:53 UTC, jkonrath-postman commented on src/pages/docs/api-security/security-warnings-openapi2.md
> +<img alt="Possible fix security warnings OpenAPI 2.0" src=""/>
This needs to be cropped in when you shoot it so it doesn't show the left and right sidebars.

(These will have to be reshot for 9/15 too, I just created a Jira for that.)

2021-08-20 16:48 UTC, sowmyaraj92 commented on src/pages/docs/api-security/security-warnings-openapi2.md
> +title: "Security Warnings - OpenAPI 2.0"
Still haven't decided on the final naming convention. Trying to stick to a standard naming across different formats.

2021-08-23 12:09 UTC, sowmyaraj92 commented on src/pages/docs/api-security/security-warnings-openapi2.md
> +title: "Security Warnings - OpenAPI 2.0"
Just looked at the "space-dash-space" and it looks fine, not really sure why it looked different. :/

2021-08-24 03:19 UTC, jkonrath-postman requested changes

2021-08-24 03:19 UTC, jkonrath-postman commented on src/pages/docs/api-security/security-warnings/openapi2.md
> +title: "OpenAPI 2.0"
How about "OpenAPI 2.0 security warnings" or "OpenAPI 2.0 warnings" if that's too long.

2021-08-24 06:23 UTC, rishabjain22 requested changes

2021-08-24 06:23 UTC, rishabjain22 commented on src/pages/docs/api-security/security-warnings/openapi2.md
> +    * [Scope for OAuth scheme used in security field is not defined in the securityDefinitions declaration](#scope-for-oauth-scheme-used-in-security-field-is-not-defined-in-the-securitydefinitions-de
it will be `securityDefinition`

2021-08-24 06:23 UTC, rishabjain22 commented on src/pages/docs/api-security/security-warnings/openapi2.md
> +### Scope for OAuth scheme used in security field is not defined in the securityDefinitions declaration
it will be `securityDefinition`

2021-08-24 06:23 UTC, rishabjain22 commented on src/pages/docs/api-security/security-warnings/openapi2.md
> +```json
Please change the resolution to 
```
swagger: '2.0'
#...
host: 'example.com'
schemes:
  - https
securityDefinitions:
  apiKeyAuth:
    type: apiKey
    name: api_key
    in: header
security:
  - apiKeyAuth: []
  ```

2021-08-24 15:34 UTC, jkonrath-postman approved these changes
LGTM (but I don't know the details on the exact content, so make sure that's OK with the SMEs)

2021-08-25 05:14 UTC, rishabjain22 approved these changes

2021-08-25 06:26 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings/openapi2.md
> +The following list describes possible warning messages and potential ways to resolve them.
Let's reword the sentence to clarify that the below list is applicable only if the API is defined in OpenAPI 2.0
@sowmyaraj92 feel free to ignore this if you feel that this is anyways being conveyed implicitly.

2021-08-25 06:27 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings/openapi2.md
> +<img alt="Security warnings for OpenAPI 2.0" src="https://assets.postman.com/postman-docs/security-warnings-openapi-2.jpg"/>
The gifs and images can be added to the parent page itself - instead of showing how the "Possible fix" link works on both the openapi2 and openapi3 pages.
@sowmyaraj92 what do you think?

2021-08-25 06:29 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings/openapi2.md
> +### Authorization URL uses HTTP protocol. Credentials will be transferred as plain text
@iprithvitharun can we please create a task to ensure that the wording for such messages (where HTTP protocol is mentioned) is conveyed in a better manner? This is not a blocker, but I remember bringing this up earlier as well.
Let's ensure that we don't miss out on this problem.
Currently the messaging is vague, and users end up feeling lost around what they're expected to do.

2021-08-25 06:31 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings/security-warnings-overview.md
> +For more information on types of security warnings, see [Security warnings for OpenAPI 3.0](/docs/api-security/security-warnings/openapi3) and [Security warning for OpenAPI 2.0](/docs/api-security/se
We might consider something like "For the list of all warnings supported, please see Security Warnings for Open API 3.0 and Security Warnings for Open API 2.0".
@sowmyaraj92 thoughts?

2021-08-25 06:37 UTC, sowmyaraj92 commented on src/pages/docs/api-security/security-warnings/openapi2.md
> +<img alt="Security warnings for OpenAPI 2.0" src="https://assets.postman.com/postman-docs/security-warnings-openapi-2.jpg"/>
If we are putting it up on the intro page, we can as well remove them from the openapi2 and open3 pages. The intention was to highlight this flow according to the API schema for both pages.

2021-08-25 06:39 UTC, sowmyaraj92 commented on src/pages/docs/api-security/security-warnings/security-warnings-overview.md
> +For more information on types of security warnings, see [Security warnings for OpenAPI 3.0](/docs/api-security/security-warnings/openapi3) and [Security warning for OpenAPI 2.0](/docs/api-security/se
How does this sound — "For more information on the list of all warnings supported, see [Security Warnings for Open API 3.0](/docs/api-security/security-warnings/openapi3/) and [Security Warnings for Open API 2.0](/docs/api-security/security-warnings/openapi2/)." ?

2021-08-25 07:16 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings/openapi3.md
>  The following list describes possible warning messages and potential ways to resolve them.
Same comment as the one on the openapi2 page.

2021-08-25 07:19 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings/openapi2.md
> +<img alt="Security warnings for OpenAPI 2.0" src="https://assets.postman.com/postman-docs/security-warnings-openapi-2.jpg"/>
In my opinion, the list of supported warnings that we're showing provides a good amount of cognitive load for the user (in the absence of collapsible sections). I don't see the need to have the gifs on both pages, and adding to it - if we can explain this on the parent page itself.
If need be we can add a message at the top, or in the related sections bit that to know how to find "Possible fix" link in the product see <parent page>

2021-08-25 07:20 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings/security-warnings-overview.md
> +For more information on types of security warnings, see [Security warnings for OpenAPI 3.0](/docs/api-security/security-warnings/openapi3) and [Security warning for OpenAPI 2.0](/docs/api-security/se
This looks fine in my opinion.

2021-08-25 08:54 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings/openapi3.md
> +If the API is defined in OpenAPI 3.0, the following list describes possible warning messages and potential ways to resolve them.
"For all APIs defined in OpenAPI 3.0, the following...." is a better fit in my opinion.

2021-08-25 08:54 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings/openapi2.md
> +If the API is defined in OpenAPI 2.0, the following list describes possible warning messages and potential ways to resolve them.
"For all APIs defined in OpenAPI 2.0, the following...." is a better fit in my opinion.

2021-08-25 08:57 UTC, tirth055 commented on src/pages/docs/api-security/security-warnings/openapi3.md
>  Also, for every security warning that Postman supports, you can inspect each warning, understand its implication and find out ways to apply patches in order to solve the underlying issue highlighted
In my opinion, this section is not needed (since something simliar is not present in the openapi2 page as well.
@sowmyaraj92 please confirm regarding this - afaik, this information is given on the parent page as well, and linked in the pre-requisites for this page

2021-08-25 09:01 UTC, tirth055 approved these changes

2021-08-25 09:12 UTC, merged