Manage public elements
postmanlabs/postman-docs pull request #3381
Opened 2021-08-20 12:50 UTC by sowmyaraj92

2021-08-20 16:08 UTC, jkonrath-postman requested changes
A few minor changes - I know this is a work-in-progress, so feel free to tag me for a re-review.

2021-08-20 16:08 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/manage-public-elements.md
> +The Documentation tab displays all the collections with published documentation. The search box below the header enables you to filter by the publisher. Along with the collection name and environment
**Documentation** tab

2021-08-20 16:08 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/manage-public-elements.md
> +Being the Community Manager, you will be able to view, access, or delete the collections with JSON links. In addition to the collection name, the dashboard displays more information about the date th
Change "Being" to "As"

2021-08-20 16:08 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/manage-public-elements.md
> +If you disable the toggle option, no new links can be generated and existing links cannot be modified/edited. The previously created JSON links will still remain accessible.
"modified/edited" to "modified or edited"

2021-08-20 16:08 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/manage-public-elements.md
> +Hover over the **JSON link** corressponding to the collection and click **Copy link to JSON**. Paste the link in a browser of your choice and you will have access to the collection JSON.
corressponding/corresponding

2021-08-20 20:01 UTC, mark-anthony-postman approved these changes
Great work putting together a shiny new page! I made some suggestions--they are all minor but might help readability a bit. Consider using them if you wish 😃

2021-08-21 06:31 UTC, sowmyaraj92 commented on src/pages/docs/collaborating-in-postman/manage-public-elements.md
> +contextual_links:
Yes yes, I need to add them. That was the whole point of keeping contextual links so I remember to add the blogpost and page details on Monday. Thank you for the heads up! :)

2021-08-23 07:51 UTC, gitThingsDone approved these changes
LGTM

2021-08-23 13:30 UTC, mark-anthony-postman requested changes

2021-08-23 13:30 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/manage-public-elements.md
> +To learn more about workspaces, see [Creating workspaces](/docs/collaborating-in-postman/using-workspaces/creating-workspaces/) and [Managing workspaces](docs/collaborating-in-postman/using-workspace
Add leading "/" before "docs" in the Managing workspaces link

2021-08-23 13:30 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/manage-public-elements.md
> +    url: " https://blog.postman.com/how-to-set-up-public-workspaces/"
Remove extra space between quotation mark and **https**

2021-08-23 13:30 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/manage-public-elements.md
> +    url: "docs/collaborating-in-postman/using-workspaces/creating-workspaces"
Add leading "/" before "docs" in Creating workspaces link

2021-08-23 13:57 UTC, mark-anthony-postman approved these changes

2021-08-23 16:01 UTC, jkonrath-postman approved these changes
LGTM

2021-08-23 16:09 UTC, merged