Private API network features
postmanlabs/postman-docs pull request #3414
Opened 2021-09-02 13:25 UTC by sowmyaraj92

2021-09-07 14:56 UTC, mark-anthony-postman requested changes
All the new content looks great! Just some minor typos here and there, and some of the screenshots aren't working for me, as noted.

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +In the modal, you can select one or more APIs you want to add to the network at one time. Create a folder to add the APIs to, if required. Select **Add API**.
We discussed avoiding use of "modal". I think you could simply say: "Select one ore more APIs..."

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +The following lists the six key features of the Private API network that helps discovering Private APIs easier:
"Helps" not in agreement with "features"? How about "...that help make discovering..." instead?

Also, capitalize "Private API Network"

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +You can create new folders from the Private API Network view. Click __Create Folder__ from the left navigation bar to create a new folder. Give it a name and summary (supports markdown). Your new fol
Capitalize "Markdown"

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +To edit the API setting, click __Edit API listing__ icon. You can change the versions, update the API summary, and modify the folder to which the API should be added.
Add "the" before "Edit API Listing icon"? Also, could include an image of the icon? I don't think I see it in the surrounding screenshots.

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +You can also remove the added APIs from Postman's API Network. Click **...** next to the API you would like to remove from network. Once you click __Remove__, your team members will also lose access
If you want, you can use the following to add a three dots icon:
`<img alt="Three dots icon" src="https://assets.postman.com/postman-docs/icon-three-dots-v9.jpg" width="18px" style="vertical-align:middle;margin-bottom:5px">`

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +The sidebar navigation displays the folder structure for your Private API Network. You can also drag and drop the APIs and subfolders to different folders. Furthermore, you can add markdown-supported
Capitalize "Markdown"

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +Clicking on an API takes you to the API details where you will find more information about the API — API description, markdown summary, API versions, the workspace where the API currently exists, API
Capitalize "Markdown"

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +You can filter the APIs in your Private API Network based on name using the search box. Use the **Added by** menu to filter based on the person who added the API. Use **Sort by** option to sort the A
Change "Use Sort by option..." to "Use the Sort by option..."

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +The report feature makes it easier to govern your internal API landscape through deeper insights into APIs in your Private API network.
Capitalize "Private API Network"

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +<img alt="API landscape governance" src="https://assets.postman.com/postman-docs/api-landscape-governance-v9.jpg"/>
Screenshot not working--I don't see the file on the S3 bucket

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +You can always decide the visibility of API versions visible to the consumers. To edit your API versions, click **...** and select **Edit**. You can select the checkbox to make the particular version
If you want, you can use the following to add a three dots icon:
`<img alt="Three dots icon" src="https://assets.postman.com/postman-docs/icon-three-dots-v9.jpg" width="18px" style="vertical-align:middle;margin-bottom:5px">`

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +When you publish the versions of yout APIs to your Private API Network, only the versions visible to the consumers will get published and you can get resume back to your work-in-progress API versions
Change to "...will get published, and you can resume your work-in-progress API versions anytime."

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +<img alt="Publish specific API versions" src="https://assets.postman.com/postman-docs/publish-specific-api-versions-v9.jpg"/>
Screenshot not working--I don't see the file on the S3 bucket

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +You can make all your existing APIs discoverable on the Private API network when you import from GitHub. When you create an API, switch over to **Import** tab to view the options to import from a cod
Capitalize "Private API Network"

Add "the" before "Import tab"

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +Private API Network allows you to share APIs securely within your team using [Postman RBAC](/docs/collaborating-in-postman/roles-and-permissions/#api-roles), users will only see the APIs they have a
I think this would be better as two sentences. So replace the comma with a period and capitalize "Users will only see..."

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +<img alt="Built in access control" src="https://assets.postman.com/postman-docs/built-in-access-control-v9.jpg"/>
Screenshot not working--I don't see the file on the S3 bucket

2021-09-07 14:56 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +The Private API Network is a good place to learn about APIs shared within your team. You can browse private APIs in [the Private API Network](https://go.postman.co/network/private) under your team na
Delete stray "ß" at end of sentence

2021-09-09 11:17 UTC, sowmyaraj92 commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +<img alt="Publish specific API versions" src="https://assets.postman.com/postman-docs/publish-specific-api-versions-v9.jpg"/>
Yet to add this image. Will update it as and when I get a good screenshot.

2021-09-13 14:07 UTC, jkonrath-postman requested changes
A few changes noted.

2021-09-14 03:14 UTC, sowmyaraj92 commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
>  <img alt="Add to Private API Network" src="https://assets.postman.com/postman-docs/add-to-private-api-network-v8.jpg"/>
Added this line in the top section, so taking it down from here.

2021-09-14 08:17 UTC, sowmyaraj92 commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +#### Built in Access Control
Removing this feature down for the release.

2021-09-14 09:05 UTC, gitThingsDone commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +> For each API selected, you can specify the versions. Read more about [API versioning](/docs/designing-and-developing-your-api/versioning-an-api/).
you can not select versions on the publish flow now, all versions that are visible to consumers will be visible on the private API network

2021-09-14 15:26 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +<img alt="API landscape governance" src="https://assets.postman.com/postman-docs/api-landscape-governance-v9.jpg"/>
Works now...

2021-09-14 15:28 UTC, jkonrath-postman approved these changes
Looks great! One little change, but otherwise approved.

2021-09-14 15:28 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/adding-private-network.md
> +<!--#### Built-in Access Control
Remove this section entirely (maybe paste it somewhere else) - comments show up in rendered pages.

2021-09-15 04:51 UTC, mark-anthony-postman approved these changes
LGTM :)

2021-09-15 20:20 UTC, merged