TW-89 CI Integrations
postmanlabs/postman-docs pull request #3415
Opened 2021-09-02 16:00 UTC by mark-anthony-postman

Added the following pages:
- Integrations > CI Integrations
- Integrations > Available Integrations > CI Integrations > CircleCI
- Integrations > Available Integrations > CI Integrations > Travis CI

Added references to CI Integrations on the following pages:
- Integrations > Integrating with Postman
- Designing And Developing Your API > Testing an API
- Running Collections > Using Newman CLI > CI with Postman API
- Running Collections > Using Newman CLI > Integrating with Travis CI

Updated replacements.json so "CI Integrations" displays correctly in Left Nav

Updated note about integration limits on "Integration with Postman" page, and removed note about integration limits on all other pages

2021-09-07 14:27 UTC, jkonrath-postman requested changes
Mostly screenshot drift - let me know when that is stable

2021-09-07 14:27 UTC, jkonrath-postman commented on src/pages/docs/integrations/ci-integrations.md
> +<img alt="View CI recent runs" src="https://assets.postman.com/postman-docs/ci-recent-runs-v9.jpg" width="788">
Might change because of Circle CI/CircleCI. (You might be able to edit that instead of reshooting...)

2021-09-07 14:27 UTC, jkonrath-postman commented on src/pages/docs/integrations/intro-integrations.md
> +For example, if you use GitHub or GitLab for your repository management and use Postman to develop and test your APIs, you can save your Postman collections to your repositories with the [Postman to
Maybe later, but this is probably not the best example anymore because of other changes. @shashankawasthi88 any thoughts on this?

2021-09-07 15:13 UTC, mark-anthony-postman commented on src/pages/docs/integrations/intro-integrations.md
> +For example, if you use GitHub or GitLab for your repository management and use Postman to develop and test your APIs, you can save your Postman collections to your repositories with the [Postman to
I think we can just delete this

2021-09-10 20:02 UTC, jerry-li-dev requested changes

2021-09-10 20:12 UTC, mark-anthony-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/circleci.md
> +    ![CI Integration](https://assets.postman.com/postman-docs/ci-add-integration-v9.jpg)
So far the text in these buttons hasn't been updated

2021-09-10 20:12 UTC, mark-anthony-postman commented on src/pages/docs/integrations/ci-integrations.md
> +<img alt="View CI recent runs" src="https://assets.postman.com/postman-docs/ci-recent-runs-v9.jpg" width="788">
Updated screenshot

2021-09-10 20:17 UTC, jerry-li-dev approved these changes

2021-09-14 05:30 UTC, ankitjaggi approved these changes

2021-09-14 05:34 UTC, shashankawasthi88 approved these changes
Looks good.

2021-09-14 20:32 UTC, jkonrath-postman approved these changes
LGTM

2021-09-15 21:18 UTC, merged