TW-94
postmanlabs/postman-docs pull request #3423
Opened 2021-09-08 20:57 UTC by jkonrath-postman

2021-09-09 15:08 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/developing-an-api.md
> +In the API version **Overview** tab, hover over the element and click **X** to the right of it.
It's now a circle with a minus in it - add a screenshot of it.

2021-09-09 17:45 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/creating-an-api.md
> +## Creating an API
There is a title and H2 with the same name, can we take down the header?

2021-09-09 17:45 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/creating-an-api.md
> +   ![New API](https://assets.postman.com/postman-docs/create-api-v9.jpg)
Can we add the screenshot after the "action to be performed"? (after 3rd point)

2021-09-09 17:45 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/creating-an-api.md
> +1. Select **Create API**.
Since it's a button, maybe "click" instead of select?

2021-09-09 17:45 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/creating-an-api.md
> +   > When you delete an API or remove it from a workspace, the collections, monitors, mocks, and environments linked to it will not be deleted or removed.
If needed, you can use the following to add a three dots icon:
`<img alt="Three dots icon" src="https://assets.postman.com/postman-docs/icon-three-dots-v9.jpg" width="18px" style="vertical-align:middle;margin-bottom:5px">`
Courtesy: @mark-anthony-postman  🥳

2021-09-09 17:45 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/defining-an-api.md
> +The __Definition__ tab in each API version page contains an editor for your API specification (either one you imported or a sample Postman added when you created the API).
Just checking, do we need a screenshot here to show the *Definition* tab?

2021-09-09 17:45 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/developing-an-api.md
> +1. Select the collection with the documentation you want to link and click **Add Documentation**. You will only see available collections in the list.
"You will only see the available collections in the list."

2021-09-09 17:45 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/developing-an-api.md
"You will only see the available environments in the list."

2021-09-09 17:45 UTC, sowmyaraj92 commented on src/pages/docs/designing-and-developing-your-api/developing-an-api.md
> +1. In the API version **Overview** tab, next to **Environments**, select **+**.
Also, do have <img> tags that are to be added?

2021-09-09 21:52 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/developing-an-api.md
> +In the API version **Overview** tab, hover over the element and click **X** to the right of it.
I created an icon you can use. Here's the code:
`<img alt="Edit icon" src="https://assets.postman.com/postman-docs/icon-remove-api-element-v9.jpg" width="18px" style="vertical-align:middle;margin-bottom:5px">`

2021-09-10 22:41 UTC, mark-anthony-postman requested changes
Most my comments are optional. Just a few very minor things that need to be fixed 🙂

2021-09-10 22:41 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
>  * [Creating API versions](#creating-api-versions)
change link to #working-with-api-versions

2021-09-10 22:41 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +## Using an external git repository
Capitalize "Git" in all instances on this page.

2021-09-10 22:41 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +Multiple versions of an API can link to the same repo/branch combination, as long as development only happens on one branch. If you link repo/branch to a new version, then all older integrations on t
"If you link a repo/branch..."

2021-09-10 22:41 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +1. Go to the API **Overview** page. Select **...** in the upper right corner and select **Create version**.
If needed, you can use the following to add a three dots icon:
`<img alt="Three dots icon" src="https://assets.postman.com/postman-docs/icon-three-dots-v9.jpg" width="18px" style="vertical-align:middle;margin-bottom:5px">`

2021-09-10 22:41 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +You can rename, edit, or delete an API version using the __View more actions__ (__...__) menu in the left sidebar. Editing an API enables you to change the name, status, and visibility at once.
If needed, you can use the following to add a three dots icon:
`<img alt="Three dots icon" src="https://assets.postman.com/postman-docs/icon-three-dots-v9.jpg" width="18px" style="vertical-align:middle;margin-bottom:5px">`

2021-09-10 22:41 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +1. Select the Changelog icon in the sidebar. <!-- TODO: icon --> The Changelog will show changes to the API version's schema and associated elements. 1. Select **+ Release changes**.
Add a link break to separate these two steps

2021-09-10 22:41 UTC, mark-anthony-postman commented on src/pages/docs/sending-requests/supported-api-frameworks/graphql.md
> +   <img src="https://assets.postman.com/postman-docs/create-api-v9.jpg" alt="New API" width="350px" />
Add a hard return before screenshot. To indent the screenshot under the step, add 4 spaces before the image.

2021-09-13 10:40 UTC, abhijitkane commented on src/pages/docs/designing-and-developing-your-api/developing-an-api.md
> +In the Postman API Builder, you can develop your API version by linking it to documentation, environments, and mock servers.
We can be specific about the diff b/w API / API Version when introducing the terms. After that, saying "develop your API version" might seem too pedantic. "develop your API" works too.

2021-09-13 10:51 UTC, abhijitkane commented on src/pages/docs/designing-and-developing-your-api/managing-apis.md
> +You can view a changelog of your API schemas in the context bar. You can also create releases of an API from the changelog.
This changelog is now for the API version. It'll include changes from the schema and all linked collections.

2021-09-13 10:58 UTC, abhijitkane commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +* Create releases for minor API changes, and new versions for major changes
We should explain what versions and releases are, and then provide examples of recommended usage.

Versions are meant to simulate parallel lines of development/deployment for an API, and consumers can choose which version they want to use.

Releases represent the evolution of a version, which each release pointing to a fixed snapshot of a version during its evolution.

2021-09-13 10:59 UTC, abhijitkane commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +* Create releases for minor API changes, and new versions for major changes
The internal blog post (mentioned on Slack) has more on this cc @jkonrath-postman

2021-09-13 11:00 UTC, abhijitkane commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +* A _status_ is an arbitrary text tag which you can change to indicate the current development stage of the API.
... of the API version

2021-09-13 11:02 UTC, abhijitkane commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +* A _version_ defines a discrete set of resources shipped to customers defining a feature set.
This could be reworded a bit - didn't get what `discrete set of resources shipped to customers defining a feature set` means.

2021-09-13 11:03 UTC, abhijitkane commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +* A _release_ is a periodic incremental change to a version of an API. Releases can be mapped to git release tags when you are connected to an external git repo.
We should relate releases to the changelog that producers and consumers see.

2021-09-13 14:20 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/creating-an-api.md
> +1. Select **Create API**.
MS style says even buttons are select now.

2021-09-13 14:20 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/creating-an-api.md
> +## Creating an API
I added a single intro sentence, which isn't great, but it works.

2021-09-13 14:22 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/defining-an-api.md
> +The __Definition__ tab in each API version page contains an editor for your API specification (either one you imported or a sample Postman added when you created the API).
No, we're cutting down the number of shots here.

2021-09-13 14:50 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/developing-an-api.md
> +1. In the API version **Overview** tab, next to **Environments**, select **+**.
No tags for environments.

2021-09-13 17:24 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +* Create releases for minor API changes, and new versions for major changes
I'm going to snip out this section (lines 42-45) and go straight into versioning concepts, after the TOC, where I can explain it in more detail.

I'll go through the internal blog post and add that info there, also.

2021-09-13 20:24 UTC, jerry-li-dev approved these changes

2021-09-14 15:59 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/validating-elements-against-schema.md
> +You can access the summary of validation issues from the [web dashboard](https://app.getpostman.com/dashboard) by navigating to your API, then selecting the tab containing the element you want to see
I'm going to have to punt on this. I can't get this to work, and it needs to be completely rewritten, but it's lower priority.

2021-09-14 17:41 UTC, shashankawasthi88 reviewed
Looks good. Added a few comments

2021-09-14 17:41 UTC, shashankawasthi88 commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +1. If you want want to base this version on existing elements, click **Show more options** to expand the dialog. In **Copy elements from a previous version**, choose a previous version of the API. Th
We may want to specify that this will create a new copy of those elements in the Workspace

2021-09-14 17:41 UTC, shashankawasthi88 commented on src/pages/docs/integrations/available-integrations/github.md
> +Postman 9.0 introduced the ability to connect a git repository to an API. Previously, a GitHub integration would only sync API schemas. Now, you can connect your repo to an API directly in the API Bu
We should have a link to API development flow here for people to know what is syncing API and how to go about it.

2021-09-14 17:41 UTC, shashankawasthi88 commented on src/pages/docs/integrations/available-integrations/bitbucket.md
> +Postman 9.0 introduced the ability to connect a git repository to an API. Instead of using an integration, you can directly connect a Bitbucket repo to an API in the API Builder. This provides two-wa
I think we should move this above the Backup Integration. Its very easy to miss this one out

2021-09-14 19:34 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +1. If you want want to base this version on existing elements, click **Show more options** to expand the dialog. In **Copy elements from a previous version**, choose a previous version of the API. Th
Added this, plus the naming convention of the version number at the end.

2021-09-14 21:29 UTC, mark-anthony-postman approved these changes
LGTM

2021-09-15 04:35 UTC, abhijitkane commented on src/pages/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md
> +1. On the API version **Overview** tab, next to **Mock Servers**, select **+** and choose **Create new mock server** or **Add existing mock server**.
@jkonrath-postman At this point, users can also select a tag to create the mock server at. This locks the mock server to a known state of the collection

2021-09-15 04:41 UTC, abhijitkane commented on src/pages/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md
> +1. On the API version **Overview** tab, next to **Mock Servers**, select **+** and choose **Create new mock server** or **Add existing mock server**.
This is valid for mocks, monitors, and documentation

2021-09-15 04:43 UTC, shashankawasthi88 approved these changes
Looks good.

2021-09-15 05:19 UTC, abhijitkane commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +* A _version_ defines a major variant of an API its associated elements, such as documentation, tests, mock servers, and monitors.
of an API *and* its

2021-09-15 05:20 UTC, abhijitkane commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +* A _status_ is an arbitrary text tag which you can change to indicate the current development stage of the API.
It's not arbitrary - we have a fixed list of statuses

2021-09-15 05:24 UTC, abhijitkane commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +* One team can't have two active versions of an API linked to the same branch.
We don't need to explicitly mention 2, 3, 4 - there are error messages in the app that explain this

For #1 - we could explain this in a different way, perhaps saying that when a new version is integrated with a particular branch, older versions linked to the same branch move to a locked state.

2021-09-15 05:30 UTC, abhijitkane commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +When you are connected to an external Git repo, the repo dropdown list displays your current develop branch and indicates if your API changes in Postman are ahead of or behind the files in your exter
The 'switch branch' list will show all branches in your repository, including the configured development branch.

2021-09-15 05:32 UTC, abhijitkane commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +An API status is an arbitrary text tag which you can change to indicate the current stage of the API within your development cycle. For example, you can select a status such as "In Design," "Security
This is technically on the API version. We can call it the API status for readability, but qualify that it's set at the version level.

2021-09-15 13:51 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +1. Go to the API **Overview** page. Select **...** in the upper right corner and select **Create version**.
@abhijitkane I'm not seeing a switch command or a list of other branches. This is in the repo dropdown, right? 

I just created a fresh repo on GitHub cloud, added a main, develop, and feature1 branches, set up a new integration, set develop as the development branch. Pulled (no changes) then pushed (initial changes.) but I only see the develop branch link.

2021-09-15 17:00 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
> +1. Go to the API **Overview** page. Select **...** in the upper right corner and select **Create version**.
Added a new section below on switching branches.

2021-09-15 22:40 UTC, merged