TW 144 upgrade changes
postmanlabs/postman-docs pull request #3424
Opened 2021-09-10 13:12 UTC by jkonrath-postman

See TW-144

2021-09-10 16:35 UTC, claireriley approved these changes
LGTM! Noted one question

2021-09-10 16:35 UTC, claireriley commented on src/pages/docs/administration/upgrading.md
> +## Upgrading to Postman v8
One question—once v9 is out will Postman automatically bump users trying to upgrade from v7 to v9 or will they go to some version of v8 first?

2021-09-10 20:37 UTC, jkonrath-postman commented on src/pages/docs/administration/upgrading.md
> +## Upgrading to Postman v8
That's a good question. @numaanashraf ?

2021-09-12 16:24 UTC, numaanashraf commented on src/pages/docs/administration/upgrading.md
> +## Upgrading to Postman v8
Users can go from v7 to v9 directly. The experience for them will be similar to v7 to v8 upgrade.

2021-09-13 06:25 UTC, claireriley commented
@jkonrath-postman I accidentally made a few commits to this branch instead of my own, reset this one back to your last commit. Apologies for the notifications 😅

2021-09-13 12:43 UTC, numaanashraf requested changes

2021-09-13 12:43 UTC, numaanashraf commented on src/pages/docs/administration/upgrading.md
> +### Upgrading to v9 as an individual
@jkonrath-postman Do we need these two sections? The steps are the same for an individual as well as a team.

2021-09-14 14:12 UTC, jkonrath-postman commented on src/pages/docs/administration/upgrading.md
> +### Upgrading to v9 as an individual
Removed that, and made just one section.

2021-09-14 14:13 UTC, jkonrath-postman commented on src/pages/docs/administration/upgrading.md
> +## Upgrading to Postman v8
I changed the above in V9 section from "You can move from Postman v8 to v9" to "You can move from Postman v7 or v8 to Postman v9"

2021-09-14 14:15 UTC, jkonrath-postman commented on src/pages/docs/administration/upgrading.md
> +Postman v9 provides a consistent, improved API development experience. The Postman desktop app and [Postman on the web](https://community.postman.com/t/whats-new-in-postman-for-the-web/18203) are equ
I think I can, because blog goes live before LC - trying to find the URL for it. (@numaanashraf If you have it, slack me.)

2021-09-15 19:40 UTC, merged