TW-95 APM integration
postmanlabs/postman-docs pull request #3426
Opened 2021-09-10 21:34 UTC by jkonrath-postman

See TW-95

2021-09-13 05:17 UTC, ankitjaggi commented on src/pages/docs/designing-and-developing-your-api/observing-an-api.md
> +* [Using monitors](#using_monitors)
Shouldn't this be `Using Monitors` with `m` being in uppercase?

2021-09-13 05:17 UTC, ankitjaggi commented on src/pages/docs/designing-and-developing-your-api/observing-an-api.md
> +## Using monitors
Same as above

2021-09-13 21:49 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/observing-an-api.md
> +* [Using monitors](#using_monitors)
Headers are sentence case, so only Using is capitalized.

2021-09-13 21:50 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/observing-an-api.md
> +## Using monitors
Headers are sentence case

2021-09-13 21:58 UTC, mark-anthony-postman requested changes

2021-09-13 21:58 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/observing-an-api.md
> +* [Using monitors](#using_monitors)
Change underscores in links to hyphens (for both anchor links in the mini TOC)

2021-09-13 21:58 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/observing-an-api.md
> +You can link monitors in your current workspace to an API version. This enables you to check an API's performance and response times at scheduled intervals. From an API version's **Monitoring** tab,
Delete comma before "or add an existing monitor"

2021-09-13 21:58 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/observing-an-api.md
> +1. In the API version **Monitoring** tab, next to **Monitors**, select __Add Monitor__ choose **Add existing monitor**.
Missing "and" before "choose Add existing monitor"

2021-09-13 21:58 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/observing-an-api.md
> +To add a monitor to a specific version of your collection, see how to [set up monitors](/docs/designing-and-developing-your-api/monitoring-your-api/setting-up-monitor/).
Change the cross reference to "...see Setting up a monitor"

2021-09-13 21:58 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/observing-an-api.md
> +    1. Enter a nickname.
Should indented numbered lists be alphabetical ordering? (a., b., c., etc)

2021-09-13 21:58 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/observing-an-api.md
> +To reconfigure the connection to New Relic, select **...** and choose **Edit integration**. You can then change the nickname, API key, services, dashboads or region. You can also choose **Delete inte
Here's a three dots icon you can use instead of "...":
`img alt="Three dots icon" src="https://assets.postman.com/postman-docs/icon-three-dots-v9.jpg" width="18px" style="vertical-align:middle;margin-bottom:5px">`

2021-09-13 21:58 UTC, mark-anthony-postman commented on src/pages/docs/integrations/available-integrations/new-relic.md
> +Postman also has another integration that enables you to continuously import New Relic application performance management (APM) metrics into the Postman API Builder. For more information, see [Viewin
Change underscores in link to hyphens

2021-09-14 13:52 UTC, shashankawasthi88 reviewed
Looks good.

2021-09-14 14:51 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/observing-an-api.md
> +    1. Enter a nickname.
If I used `a.` for each step (i.e. replacing `1.` with `a.`, the entire indented list won't render and shows up as a single line. Need to look into this later - made a note of it on my list.

2021-09-15 21:06 UTC, merged