Add page on Deployment Control - Enterprise app
postmanlabs/postman-docs pull request #3434
Opened 2021-09-14 08:27 UTC by claireriley

[Spec](https://postmanlabs.atlassian.net/l/c/nVvLJA7J)

Waiting on Postman screenshot (see comment)

2021-09-14 12:12 UTC, numaanashraf requested changes

2021-09-14 12:12 UTC, numaanashraf commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +
@jviotti Are there any instructions or steps we can share to inform users how to update the Enterprise App? Updating is done by installing a newer version of the application right? cc @claireriley

2021-09-14 13:33 UTC, jkonrath-postman approved these changes
Approved, once you get the screenshots and everything Numaan mentioned.

2021-09-14 13:33 UTC, jkonrath-postman commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +To download, navigate to Postman and select **Team** in the upper right > **Team Settings**
missing period at end

2021-09-14 13:44 UTC, jviotti commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +The `INSTALLDIR` public property is used to select a custom installation. If this public property is not manually overwritten, it defaults to `%PROGRAMFILES%\[company]\[name]` for system-wide install
In this case, `[company]` is always "Postman", so we can be clear there

2021-09-14 13:44 UTC, jviotti commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +The `INSTALLDIR` public property is used to select a custom installation. If this public property is not manually overwritten, it defaults to `%PROGRAMFILES%\[company]\[name]` for system-wide install
This is also always about the Postman Enterprise app, so we can also inline the name. @numaanashraf was is the final name we are going for?

2021-09-14 13:48 UTC, jviotti commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +
@numaanashraf I'll extend the Starship docs accordingly, but the summary is the following:

- Upgrading the app is done by simply installing the new version of the MSI (the Windows Installer system will realize it is an upgrade out of the box)
- It is crucial that users upgrade by passing the exact same public properties they used at installation time. For example, if the user first installed by passing `INSTALLDIR=C:\custom` and `MSIINSTALLPERUSER=1`, then the new MSI has to be installed with the exact same properties
- We must clarify that downgrading the version of the app is not supported. If the user attempts to downgrade, an error message will be shown. The user can force-downgrade by manually removing the current version and then installing the older version

2021-09-14 14:53 UTC, mark-anthony-postman approved these changes
Made one minor suggestion, otherwise LGTM 🙂

2021-09-14 14:53 UTC, mark-anthony-postman commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +To download, navigate to Postman and select **Team** in the upper right > **Team Settings**
Maybe better to bring the navigation path together?
"To download, navigate to Postman and select **Team > Team Settings** in the upper right."

2021-09-14 15:23 UTC, numaanashraf commented
@claireriley Here's the download UI screenshot

<img width="1440" alt="download-enterprise-app" src="https://user-images.githubusercontent.com/3295568/133286319-a44d0c1d-f641-4e6b-851f-9dab5045c2ee.png">

2021-09-14 15:31 UTC, numaanashraf commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +The `INSTALLDIR` public property is used to select a custom installation. If this public property is not manually overwritten, it defaults to `%PROGRAMFILES%\[company]\[name]` for system-wide install
@claireriley @jviotti Yep. Company will be "Postman" and name will be "Postman Enterprise"

2021-09-14 17:45 UTC, claireriley commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +The `INSTALLDIR` public property is used to select a custom installation. If this public property is not manually overwritten, it defaults to `%PROGRAMFILES%\[company]\[name]` for system-wide install
@jviotti @numaanashraf will the name "Postman Enterprise" have a hyphen or space?

2021-09-14 18:27 UTC, numaanashraf commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +The `INSTALLDIR` public property is used to select a custom installation. If this public property is not manually overwritten, it defaults to `%PROGRAMFILES%\[company]\[name]` for system-wide install
@claireriley No hyphen. It has a space.

2021-09-15 09:58 UTC, numaanashraf approved these changes

2021-09-15 20:39 UTC, merged