Update for plan changes dec 1
postmanlabs/postman-docs pull request #3710
Opened 2021-11-29 05:24 UTC by claireriley

This PR updates plan names and screenshots in the docs for the dec 1st plan/pricing change.

Summary of changes:
```
Free -> Free, no changes
Team -> Basic, no pricing or feature changes
Business -> Professional, price change but no feature change
Enterprise -> Enterprise, price change and optional control over app version (must be requested, not an external feature)
```

2021-11-29 18:56 UTC, jkonrath-postman requested changes
A few minor changes here, plus the versioning thing we talked about earlier.

2021-11-29 18:56 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/collaboration-intro.md
> +> Postman Free allows teams of up to three to collaborate at no cost. To collaborate with additional team members, features, and increased usage limits, see [Plans and Pricing](https://www.postman.co
"Postman Free" - "Postman basic plan"?

2021-11-29 18:56 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/collaboration-intro.md
> +> Postman Free allows teams of up to three to collaborate at no cost. To collaborate with additional team members, features, and increased usage limits, see [Plans and Pricing](https://www.postman.co
(Or is it Postman free plan?)

2021-11-29 18:56 UTC, jkonrath-postman commented on src/pages/docs/monitoring-your-api/using-static-IPs-to-monitor.md
> +Postman's static IP feature allows you to monitor your APIs that are behind a restricted firewall. This feature is available to all Postman Professional and Enterprise customers, provided your IT tea
Change "whitelist" to "allowlist" (this page only) - you'll have to change this in a couple of places, and one is a heading that breaks a link. (There's another Jira for this globally, but might as well fix it now here. It can't be fixed yet in other places because UX has to change first.)

2021-11-29 19:52 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/collaboration-intro.md
> +> Postman Free allows teams of up to three to collaborate at no cost. To collaborate with additional team members, features, and increased usage limits, see [Plans and Pricing](https://www.postman.co
It's "Postman Free" — I took some of the wording from the blog announcement: https://blog.postman.com/announcing-postman-plans-and-pricing-2021/

("Postman Basic" is the lowest paid plan)

2021-11-29 21:07 UTC, mark-anthony-postman approved these changes
LGTM 🙂

2021-11-30 21:41 UTC, jkonrath-postman approved these changes

2021-11-30 21:43 UTC, jkonrath-postman approved these changes
LGTM

2021-11-30 21:48 UTC, merged