[TW-234] Doc enterprise app for macOS
postmanlabs/postman-docs pull request #3752
Opened 2021-12-13 16:15 UTC by jkonrath-postman

(Needs screenshot at top)

2021-12-13 16:36 UTC, mark-anthony-postman commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +Postman's Enterprise Application is a variant of Postman’s Desktop Application that offers greater control to administrators looking to deploy Postman at an enterprise level. It is available as an MS
Change "Application" to lower case? Elsewhere on the page "app" is lower case

2021-12-13 16:41 UTC, mark-anthony-postman commented on src/pages/docs/administration/managing-enterprise-deployment.md
>  ## Deploying the Postman Enterprise app
I think nesting all subsequent headings under "Deploying the Postman Enterprise app" makes the page harder to scan, especially with the way the H4's render. I would move all headings after this one up a level

2021-12-13 16:49 UTC, mark-anthony-postman commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +A PKG installer can be installed by double-clicking on the file and following the interactive configurable wizard. PKGs can also be installed from a command-line interface using the macOS `installer(
Are the numbers in parentheses needed for `installer(8)`, `defaults(1)`, and `pkgutil(1)`? Doing some searches, I see those on some `man` pages but I don't think they're part of the actual command

2021-12-13 21:43 UTC, jkonrath-postman commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +Postman's Enterprise Application is a variant of Postman’s Desktop Application that offers greater control to administrators looking to deploy Postman at an enterprise level. It is available as an MS
It should be app, but if you take a look at the screenshot, both are used on the download page. I'm sticking to app to be consistent.

2021-12-13 21:48 UTC, jkonrath-postman commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +A PKG installer can be installed by double-clicking on the file and following the interactive configurable wizard. PKGs can also be installed from a command-line interface using the macOS `installer(
None of these are commands with man pages in multiple sections, so I'm striking those from each occurrence.

2021-12-14 00:29 UTC, HeatherStenson approved these changes
Looks good! 🍊

2021-12-14 00:29 UTC, HeatherStenson commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +* Apple Silicon is supported
It looks like these should end in periods, per the LC style guide ("If a bulleted list has a mix of complete and incomplete sentences, all sentences end in a period."):

```suggestion
* You can select between system-wide, per-user installation, or custom installation disks.
* They do not require reboots after installation.
* They are fully configurable for silent installation.
* Apple Silicon is supported.
```

2021-12-14 00:29 UTC, HeatherStenson commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +You can also perform a per-user installation by specifying the `CurrentUserHomeDirectory` target. Given this target, the PKG installs app bundles to `$HOME/Applications` and store installation settin
```suggestion
You can also perform a per-user installation by specifying the `CurrentUserHomeDirectory` target. Given this target, the PKG installs app bundles to `$HOME/Applications` and stores installation settings at `$HOME/Library/Preferences`:
```

2021-12-14 09:37 UTC, RaisinTen requested changes

2021-12-14 14:38 UTC, jkonrath-postman commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +You can define custom properties with the `installationOptions` profile setting. These settings can be changed at installation time using the macOS `defaults` tool either before or after installing t
OK, I'm removing this section then.

2021-12-14 14:52 UTC, RaisinTen commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +You can define custom properties with the `installationOptions` profile setting. These settings can be changed at installation time using the macOS `defaults` tool either before or after installing t
@jkonrath-postman the rest of the section is still useful. The PKG users are still supposed to use `defaults` to set the custom values in the system-wide/user-specific plist. Could you please add back that section and apply the suggested change?

2021-12-14 15:33 UTC, jkonrath-postman commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +You can define custom properties with the `installationOptions` profile setting. These settings can be changed at installation time using the macOS `defaults` tool either before or after installing t
@RaisinTen I've added back the section, and just removed the first sentence. Is that correct?

2022-01-05 14:54 UTC, merged