Add docs for secret variable type
postmanlabs/postman-docs pull request #3755
Opened 2021-12-15 04:20 UTC by claireriley

2021-12-16 13:53 UTC, malvikach requested changes
- Screenshots can be updated since there have been some fixes in beta
- We need a section to talk about backward compatibility so that users using the older app versions understand how they can deal with types
- we need to mention a section on backward compatibility and use of type in postman public API and import flows too

2021-12-16 13:55 UTC, malvikach commented on src/pages/docs/sending-requests/variables.md
> +The two variable types are displayed differently in Postman:
Lets reword this and say the two variable types that you can see on postman environment and globals are:

2021-12-16 13:56 UTC, malvikach commented on src/pages/docs/sending-requests/variables.md
> +* **Default type** is shown as plain text and has no special properties.
lets say no additional properties instead of no special properties

2021-12-16 14:07 UTC, malvikach commented on src/pages/docs/sending-requests/variables.md
> +* **Default type** is shown as plain text and has no special properties.
or extra-ordinary properties

2021-12-16 14:07 UTC, malvikach commented on src/pages/docs/sending-requests/variables.md
> +<img alt="Confirm unmark variable as sensitive" src="https://assets.postman.com/postman-docs/environment-unmask-var-confirmation-9.5.jpg" width="400px"/>
lets update this screenshot from latest beta

2021-12-20 14:33 UTC, jkonrath-postman approved these changes
LGTM - one quick thing, on variables.md, change the `updated` date to 2021-12-20

2021-12-20 16:14 UTC, mark-anthony-postman approved these changes
LGTM 🙂

2021-12-20 18:16 UTC, HeatherStenson approved these changes
Looks great! 🍊

2021-12-20 18:16 UTC, HeatherStenson commented on src/pages/docs/sending-requests/variables.md
> +<!-- -->
Not sure if this a leftover comment or if it's holding space open between the two notes? Calling it out just in case!

2021-12-20 18:16 UTC, HeatherStenson commented on src/pages/docs/sending-requests/variables.md
> +* **Secret type** masks the [initial and current values](#specifying-variable-detail) for all workspace members and can be used to prevent unintentional disclosure of sensitive data, including API se
Totally up to you, but could potentially rework this intro to consolidate a little bit:

```suggestion
Beyond scope, global and environment variables can be defined by type. The two variable types that you can configure for environment and global variables are:

* **Default type** is the base type that is automatically assigned to variables. This type is shown as plain text and has no additional properties.
* **Secret type** masks the [initial and current values](#specifying-variable-detail) for all workspace members and can be used to prevent unintentional disclosure of sensitive data, including API secrets, passwords, tokens, and keys.

Users with [editor](/docs/collaborating-in-postman/roles-and-permissions/) access on a workspace (for global variables) or environment (for environment variables) can opt to change these variables from default to *secret* type.
```

2021-12-21 03:07 UTC, claireriley commented on src/pages/docs/sending-requests/variables.md
> +<!-- -->
No worries! It's my workaround for linting and formatting to allow two notes back-to-back.

2021-12-21 03:11 UTC, claireriley commented on src/pages/docs/sending-requests/variables.md
> +* **Secret type** masks the [initial and current values](#specifying-variable-detail) for all workspace members and can be used to prevent unintentional disclosure of sensitive data, including API se
Thanks Heather! I definitely was looking at this doc too long 😅 appreciate you reworking it a bit, looks much cleaner

2021-12-28 05:34 UTC, malvikach approved these changes

2021-12-28 05:35 UTC, malvikach commented
Approved the PR. There is one addition to inform users about backward compatibility. 2-3 lines on the same will do. This can  be added with next release.
cc: @claireriley @jkonrath-postman

2021-12-28 17:37 UTC, merged

2021-12-29 18:47 UTC, malvikach commented on src/pages/docs/sending-requests/variables.md
> +* **String type** is the default type that is automatically assigned to variables. This type is shown as plain text and has no additional properties.
@tristandenyer We need to change string to default here

2021-12-29 18:47 UTC, malvikach commented on src/pages/docs/sending-requests/variables.md
> +Users with [editor](/docs/collaborating-in-postman/roles-and-permissions/) access on a workspace (for global variables) or environment (for environment variables) can opt to change these variables fr
@tristandenyer  replace string to secret here

2021-12-29 18:49 UTC, malvikach commented on src/pages/docs/sending-requests/variables.md
> +<img alt="Environment editor with string auth key" src="https://assets.postman.com/postman-docs/env-string-auth-key-9.5.jpg"/>
this screenshot will need to be updated @tristandenyer

2021-12-29 18:50 UTC, malvikach commented on src/pages/docs/sending-requests/variables.md
> +Select **string** next to the variable you'd like to change to open the dropdown menu, then select **secret** to update the variable type and save your changes to confirm.
change string to default

2021-12-29 18:50 UTC, malvikach commented on src/pages/docs/sending-requests/variables.md
> +<img alt="Environment editor with secret auth key" src="https://assets.postman.com/postman-docs/env-secret-auth-key-9.5.jpg"/>
image would have to be updated @tristandenyer

2021-12-29 18:52 UTC, malvikach commented on src/pages/docs/sending-requests/variables.md
> +Editors can change the variable type from secret to string at any time, and vice versa. When you change a variable's type from secret back to string, you must confirm by selecting **Change type**.
change string to deault @tristandenyer

2021-12-29 18:52 UTC, malvikach commented on src/pages/docs/sending-requests/variables.md
> +<img alt="Confirm unmark variable as secret" src="https://assets.postman.com/postman-docs/change-var-type-confirmation-9.5.jpg" width="400px"/>
update image @tristandenyer

2021-12-29 19:21 UTC, malvikach commented on src/pages/docs/sending-requests/variables.md
> +> Postman will store environment and global variables as strings regardless of type.
change strings ti default here @tristandenyer