TW-295 Add Find and replace to /getting-started/installation-and-updates/#web-limitations
postmanlabs/postman-docs pull request #3798
Opened 2022-01-05 22:42 UTC by HeatherStenson

- Adds "Find and replace" to the list of limitations for the Postman web client
- Removes "Live preview" and "Saving responses to file" from the list of limitations for the Postman web client (both options are available on web now)
- General copyedits

2022-01-05 23:06 UTC, jkonrath-postman requested changes
Some minor naming things, the agent one in particular. I think that needs some more research.

2022-01-05 23:06 UTC, jkonrath-postman commented on src/pages/docs/getting-started/installation-and-updates.md
> +Postman’s web client is optimized for the following browsers:
Take a look at TW-188 - can we change these to Postman for Web?

2022-01-05 23:06 UTC, jkonrath-postman commented on src/pages/docs/getting-started/installation-and-updates.md
>  ### Installing the Postman desktop agent
Let's talk about the naming of this offline...

2022-01-06 00:13 UTC, HeatherStenson commented on src/pages/docs/getting-started/installation-and-updates.md
> +1. In the **Downloads** folder, install the unzipped `Postman` file.
Yeah, this ended up funkier than I intended. I think it's best to return to the original wording here - changed in 3d8f2c1

2022-01-06 00:14 UTC, HeatherStenson commented on src/pages/docs/getting-started/installation-and-updates.md
> +Postman’s web client is optimized for the following browsers:
Updated in c423aa3

2022-01-06 16:47 UTC, mark-anthony-postman approved these changes
LGTM 🙂

2022-01-07 16:01 UTC, jkonrath-postman approved these changes
LGTM, ignore my comments on naming

2022-01-07 17:00 UTC, merged