CLNTINT-450 Capture requests and cookies
postmanlabs/postman-docs pull request #3828
Opened 2022-01-19 01:13 UTC by HeatherStenson

- Updates `Capture Requests` to `Capture requests and cookies`

2022-01-19 05:13 UTC, shashankawasthi88 reviewed
On the interceptor page in the Sync cookie section, we should add the new Sync cookie snapshot and explain the flow as well.

2022-01-19 05:13 UTC, shashankawasthi88 commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +If you are using APIs to build client-side applications like mobile apps, websites, or desktop applications, you may want to see the actual HTTP and HTTPS request traffic that's being sent and receiv
request, response and cookies are all part of network traffic. Would we want to rephrase this?

2022-01-19 05:13 UTC, shashankawasthi88 commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +> You can only have a single proxy or Interceptor debug session running at the same time.
Why is proxy with a 'p' vs Interceptor with 'I' ?

2022-01-19 14:39 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +> You can only have a single proxy or Interceptor debug session running at the same time.
Interceptor is a branded term (there's an internal list that's shared between UX content, us, and marketing). I'm not sure if we should make proxy a branded term too - let's talk about it offline later.

2022-01-19 15:44 UTC, jkonrath-postman requested changes
A few changes on here.
 @shashankawasthi88  - on the comment about the added flow, if that can't be done quick, we'll open a second ticket on this, because I want to get these changes in ASAP.

2022-01-19 15:44 UTC, jkonrath-postman commented on src/pages/docs/getting-started/introduction.md
> +![![Postman full view](https://assets.postman.com/postman-docs/intro-postman-request-selected-v9.8.jpg)](https://assets.postman.com/postman-docs/intro-postman-request-selected-v9.8.jpg)
I think this is the one place where we need a full-width screenshot. Can you do this showing the left sidebar with collections visible?

2022-01-19 15:44 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +If you are using APIs to build client-side applications like mobile apps, websites, or desktop applications, you may want to see the actual HTTP and HTTPS request traffic that's being sent and receiv
They're the same, but I think we should leave this for search SEO, so this page comes up if you search on cookies.

2022-01-19 15:44 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/interceptor.md
> +* [Using Interceptor with Postman's Chrome app (deprecated)](#using-the-interceptor-with-postmans-chrome-app-deprecated)
Change that back (and the related heading) - I think we might have a link going to that heading, based on the traffic that gets in analytics.

2022-01-19 15:44 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/interceptor.md
> +    <img src="https://assets.postman.com/postman-docs/proxy-capture-requests-button-v9.8.jpg" alt="Capture requests button" width="450px"/>
This and the next image look a bit fuzzy. This one is 334px wide, but the width is set at 450px, which might be the culprit. But the original was 500-some wide, and scaled down to 300, which might be it.

Also, can you show the cursor in the image to show what they should be selecting?

2022-01-19 15:44 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +    <img src="https://assets.postman.com/postman-docs/proxy-capture-requests-button-v9.8.jpg" alt="Capture requests button" width="450px"/>
See my comments in Interceptor - these look a bit fuzzy.

2022-01-19 15:44 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/interceptor.md
> +1. Go to the **Via Incerceptor** tab of the **Capture requests and cookies** window.
```suggestion
1. Go to the **Via Interceptor** tab of the **Capture requests and cookies** window.
```

2022-01-19 16:52 UTC, mark-anthony-postman approved these changes
Let me know if you need help on screenshots 📸  
Otherwise LGTM 🌈

2022-01-19 16:52 UTC, mark-anthony-postman commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +    <img src="https://assets.postman.com/postman-docs/proxy-capture-requests-button-v9.8.jpg" alt="Capture requests button" width="450px"/>
Did you take the images in retina mode (on your macbook screen)? That might help. Part of the problem is that there are small graphics being magnified.

2022-01-19 16:52 UTC, mark-anthony-postman commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +    <img src="https://assets.postman.com/postman-docs/capture-via-proxy-tab-v9.8.jpg" alt="Capture via proxy tab" width="300px"/>
Add a blank  line above and below images to ensure correct spacing between numbered steps.

2022-01-19 17:45 UTC, HeatherStenson commented on src/pages/docs/sending-requests/capturing-request-data/interceptor.md
> +1. Go to the **Via Incerceptor** tab of the **Capture requests and cookies** window.
Omg 🙈

2022-01-19 17:47 UTC, HeatherStenson commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +    <img src="https://assets.postman.com/postman-docs/proxy-capture-requests-button-v9.8.jpg" alt="Capture requests button" width="450px"/>
> Did you take the images in retina mode (on your macbook screen)

Oh! I'm not so that might help. Also realized that I'm stretching the images out larger than it's original size (per @jkonrath-postman's [comment](https://github.com/postmanlabs/postman-docs/pull/3828#discussion_r787879673)), which no doubt adds to the problem. I'll get these fixed!

2022-01-19 18:12 UTC, HeatherStenson commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +> You can only have a single proxy or Interceptor debug session running at the same time.
Per team conversation, I'll revert this to `interceptor` since it's not specifically referring to a named feature in Postman in this case.

2022-01-19 18:16 UTC, HeatherStenson commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +If you are using APIs to build client-side applications like mobile apps, websites, or desktop applications, you may want to see the actual HTTP and HTTPS request traffic that's being sent and receiv
I'll rephrase this to be:

> You can capture network traffic, including requests, responses, and cookies, using the proxy that's built into the Postman app.

2022-01-19 20:29 UTC, HeatherStenson commented
> On the interceptor page in the Sync cookie section, we should add the new Sync cookie snapshot and explain the flow as well.

@shashankawasthi88 After looking over the changes needed to add the new info about syncing cookies to the Interceptor page, I think that's sufficient work to warrant a separate issue as suggested by @jkonrath-postman. I will create a new ticket and tag you in it, and will ask you to review the new PR once it's ready.

2022-01-20 22:11 UTC, claireriley approved these changes
LGTM!

2022-01-20 22:14 UTC, merged