TW 385 SCIM support for Azure AD
postmanlabs/postman-docs pull request #3909
Opened 2022-03-03 21:34 UTC by HeatherStenson

* Reorganizes SCIM docs (TY @claireriley! 🎉)
* Adds information about configuring SCIM provisioning with Azure AD

2022-03-04 09:48 UTC, ArjunSingh-PM reviewed
Heather, thanks a lot for sharing this document. The document looks great. I have added a few comments to the same.

2022-03-04 09:48 UTC, ArjunSingh-PM commented on src/pages/docs/administration/SCIM-provisioning/configuring-scim-with-azure-ad.md
> +1. In the Azure AD **Mappings** section, there are two sets of attribute mappings, one for user objects and one for group objects. Select each one to review the attributes that are synchronized from
Currently, we only support user objects and not group objects. The user should set disable **Provision Azure Active Directory Groups** and only have **Provision Azure Active Directory Users** enabled.

2022-03-04 17:00 UTC, jkonrath-postman requested changes
A few little things, plus Arjun's comments.

2022-03-04 17:00 UTC, jkonrath-postman commented on src/pages/docs/administration/SCIM-provisioning/configuring-scim-with-azure-ad.md
> +Postman can be connected to Azure Active Directory using the "non-gallery application" feature in the Azure AD application gallery. Once they're connected, Azure AD queries the Postman SCIM endpoint
I'd probably just say "Once connected, Azure AD queries..."

2022-03-04 17:00 UTC, jkonrath-postman commented on src/pages/docs/administration/SCIM-provisioning/configuring-scim-with-azure-ad.md
> +1. In the Azure AD **Mappings** section, there are two sets of attribute mappings, one for user objects and one for group objects. Select each one to review the attributes that are synchronized from
"two sets of attribute mappings: one for... "

2022-03-04 17:00 UTC, jkonrath-postman commented on src/pages/docs/administration/SCIM-provisioning/configuring-scim-with-azure-ad.md
> +1. Enter a _name_, then select _Integrate any other application you don't find in the gallery_.
Don't italicize field names. We probably need to add this to the list; MS is saying to bold them: https://docs.microsoft.com/en-us/style-guide/procedures-instructions/formatting-text-in-instructions

2022-03-04 17:00 UTC, jkonrath-postman commented on src/pages/docs/administration/SCIM-provisioning/configuring-scim-with-okta.md
> +To set up provisioning with the Postman Okta app, take the following steps:
```suggestion
To set up provisioning with the Postman Okta app:
```

2022-03-04 17:00 UTC, jkonrath-postman commented on src/pages/docs/administration/SCIM-provisioning/scim-provisioning-overview.md
> +To enable SCIM, navigate to [Postman](https://go.postman.co/home) and select **Team** > **Team Settings** in the upper-right. Select **Authentication** in the left sidebar.
make this procedure a numbered list

2022-03-04 17:00 UTC, jkonrath-postman commented on src/pages/docs/administration/SCIM-provisioning/scim-provisioning-overview.md
> +Under **SCIM provisioning**, select **Generate SCIM API Key**.
Also make this a numbered list

2022-03-04 17:52 UTC, HeatherStenson commented on src/pages/docs/administration/SCIM-provisioning/configuring-scim-with-azure-ad.md
> +1. In the Azure AD **Mappings** section, there are two sets of attribute mappings, one for user objects and one for group objects. Select each one to review the attributes that are synchronized from
Thanks @ArjunSingh-PM - I updated this in [05b6ddd](https://github.com/postmanlabs/postman-docs/pull/3909/commits/05b6dddefe668a69b6a640708131a267d75f94f2).

2022-03-04 17:55 UTC, HeatherStenson commented on src/pages/docs/administration/SCIM-provisioning/configuring-scim-with-azure-ad.md
> +1. In the Azure AD **Mappings** section, there are two sets of attribute mappings, one for user objects and one for group objects. Select each one to review the attributes that are synchronized from
@jkonrath-postman thanks! I reworded to avoid this since per Arjun's comment only one of the links is relevant in this case.

2022-03-04 17:56 UTC, HeatherStenson commented on src/pages/docs/administration/SCIM-provisioning/configuring-scim-with-azure-ad.md
> +1. Enter a _name_, then select _Integrate any other application you don't find in the gallery_.
Thanks! 🙈 I was having flashbacks to my old style guide 😝

2022-03-04 18:20 UTC, HeatherStenson commented
Thanks for your notes and suggestions @ArjunSingh-PM and @jkonrath-postman! Changes have been made.

2022-03-07 17:45 UTC, ArjunSingh-PM approved these changes
That changes look good. Thanks, @HeatherStenson!

2022-03-07 17:47 UTC, ArjunSingh-PM approved these changes

2022-03-07 18:30 UTC, jkonrath-postman approved these changes
LGTM!

2022-03-07 18:50 UTC, merged