Added installationOptions information for enterprise app for windows platform
postmanlabs/postman-docs pull request #3920
Opened 2022-03-10 12:09 UTC by twitharshil

2022-03-10 12:21 UTC, RaisinTen requested changes

2022-03-10 12:21 UTC, RaisinTen commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +### MSI InstallationOptions
```suggestion
### MSI installation Options
```

2022-03-10 12:21 UTC, RaisinTen commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +msiexec /i path/to/package.msi MY_OPTION='hello'
```suggestion
msiexec /i path\to\package.msi MY_OPTION='hello'
```

2022-03-10 12:21 UTC, RaisinTen commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +msiexec /i path/to/package.msi MY_OPTION=7
```suggestion
msiexec /i path\to\package.msi MY_STRING_OPTION=hello MY_INTEGER_OPTION=7
```
I think `msiexec` treats booleans the same way as integers.

2022-03-10 12:49 UTC, twitharshil commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +msiexec /i path/to/package.msi MY_OPTION='hello'
@RaisinTen Are you sure we don't need quotes around string values ?

2022-03-10 13:03 UTC, RaisinTen commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +msiexec /i path/to/package.msi MY_OPTION='hello'
Yea, see how we pass the `INSTALLDIR` property in https://bitbucket.org/postmanlabs/starship/src/master/docs/windows/using-msi.markdown. You may double-check it locally though. ;)

I _think_ we need the quotes (maybe both `'`/`"` will do) for strings with spaces.

2022-03-11 05:53 UTC, twitharshil commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +msiexec /i path/to/package.msi MY_OPTION='hello'
Yup, so it works fine if we add quotes I've tested that

2022-03-11 06:25 UTC, RaisinTen commented on src/pages/docs/administration/managing-enterprise-deployment.md
> +msiexec /i path/to/package.msi MY_OPTION='hello'
```suggestion
msiexec /i path\to\package.msi MY_OPTION='hello'
```
we still need the `\`s on windows

2022-03-11 08:05 UTC, RaisinTen approved these changes
LGTM

2022-03-14 14:09 UTC, jkonrath-postman approved these changes
This branch was stale, so I pulled the latest develop into it. Sorry for the noise there.

I made two small changes in managing-enterprise-deployment.md - otherwise, looks good. @twitharshil let me know if you want to merge or have more changes.

2022-03-15 13:08 UTC, merged