TW 418 Updates to the reporting section
postmanlabs/postman-docs pull request #4005
Opened 2022-04-15 21:23 UTC by HeatherStenson

Builds on work done by @jkonrath-postman in https://github.com/postmanlabs/postman-docs/pull/3944

Addresses team comments in REPORTPROD-640

2022-04-20 21:33 UTC, jkonrath-postman approved these changes
LGTM!

2022-04-22 16:40 UTC, mark-anthony-postman approved these changes
Looks like a great refresh to me!  🌈
Found just one typo and that was it! 😄

2022-04-22 16:40 UTC, mark-anthony-postman commented on src/pages/docs/reports/team-details-reports.md
> +* * **Integrations by type** - The number of integrations, broken down by integration type.
```suggestion
* **Integrations by type** - The number of integrations, broken down by integration type.
```

2022-05-11 21:44 UTC, HeatherStenson commented
Hi @rishabh-nayar-github and @Hon3yNa1r! 👋  This PR is in response to your team notes in REPORTPROD-640. If possible we'd love to get your review on this soon, since the it's almost a month old and we're trying to clear out a backlog of PRs. 😅

2022-05-12 06:03 UTC, Hon3yNa1r commented
> Hi @rishabh-nayar-github and @Hon3yNa1r! 👋 This PR is in response to your team notes in REPORTPROD-640. If possible we'd love to get your review on this soon, since the it's almost a month old and we're trying to clear out a backlog of PRs. 😅

Will be closing review by EOD, apologies for the delay

2022-05-13 07:16 UTC, Hon3yNa1r commented on src/pages/docs/reports/all-apis-reports.md
> +* **Comments over time** - The number times someone has commented on an API in the last six months.
I think we are missing "of" here it should be the number OF times, that is what I see in all other sections.

2022-05-13 07:33 UTC, Hon3yNa1r requested changes
Finished review for all APIs page, added 3 comments, rest all looks great!

2022-05-13 07:33 UTC, Hon3yNa1r commented on src/pages/docs/reports/all-apis-reports.md
> +* **Total public APIs** - The number of APIs that are published to the Public API Network.
I think you don't have to necessarily publish on the network here, correct @rishabh-nayar-github ?

2022-05-13 07:33 UTC, Hon3yNa1r commented on src/pages/docs/reports/all-apis-reports.md
> +* **Public API views** - A graph of the number of views of your team's public APIs over the last three months.
Is there a reason for us to use the term graph here, w.r.t. to all other lines?

2022-05-13 07:33 UTC, Hon3yNa1r commented on src/pages/docs/reports/all-apis-reports.md
> +* **Comments over time** - The number times someone has commented on an API in the last six months.
I think we are missing "of" here it should be the number OF times, that is what I see in all other sections. @HeatherStenson

2022-05-13 07:34 UTC, Hon3yNa1r commented on src/pages/docs/reports/all-apis-reports.md
> +* **Total public APIs** - The number of APIs that are published to the Public API Network.
@HeatherStenson I and @rishabh-nayar-github were wondering if we need to simply comment instead of adding it as a review comment here? Or does either way work?

2022-05-13 07:41 UTC, Hon3yNa1r reviewed
All workspaces page looks good to me. Don't have any new feedback items.

2022-05-13 07:47 UTC, Hon3yNa1r requested changes
Added one comment, for the report's overview. Do not have any additional comments.

2022-05-13 07:47 UTC, Hon3yNa1r commented on src/pages/docs/reports/reports-overview.md
> +* You might not have enabled __Save Responses__ in the __History__ tab in Postman.
@rishabh-nayar-github this should not affect us, right? 
cc: @HeatherStenson

2022-05-13 08:02 UTC, rishabh-nayar-github commented on src/pages/docs/reports/reports-overview.md
> +* You might not have enabled __Save Responses__ in the __History__ tab in Postman.
No. It shouldn't. Because we store this data irrespective. Though if the response doesn't resolve then there won't be any response data.

2022-05-13 08:09 UTC, Hon3yNa1r requested changes
Left one comment, rest all looks good.

2022-05-13 08:09 UTC, Hon3yNa1r commented on src/pages/docs/reports/summary-reports.md
> +* **Public profile views** - The total number of views of your team's public profile in the reporting period.
What would be the reporting period here is confusing? @rishabh-nayar-github isn't this updated to the latest view count, based on the last reporting refresh?
cc: @HeatherStenson

2022-05-16 18:25 UTC, HeatherStenson commented on src/pages/docs/reports/all-apis-reports.md
> +* **Comments over time** - The number times someone has commented on an API in the last six months.
Good catch, thank you! Fixed in [ce58095](https://github.com/postmanlabs/postman-docs/pull/4005/commits/ce580953842f102723df2015300ac9e530a5b2dd)

2022-05-16 19:24 UTC, HeatherStenson commented on src/pages/docs/reports/all-apis-reports.md
> +* **Total public APIs** - The number of APIs that are published to the Public API Network.
Either adding single comments or adding comments as part of a review works, so whichever you prefer!

2022-05-16 19:26 UTC, HeatherStenson commented on src/pages/docs/reports/all-apis-reports.md
> +* **Total public APIs** - The number of APIs that are published to the Public API Network.
> I think you don't have to necessarily publish on the network here, correct

Would it be correct to say "The number of APIs in your public workspaces" instead?

2022-05-16 20:25 UTC, HeatherStenson commented on src/pages/docs/reports/summary-reports.md
> +* **Public profile views** - The total number of views of your team's public profile in the reporting period.
Ah, thanks for catching this @Hon3yNa1r - I was using "in the reporting period" as a placeholder when I wasn't sure how long the reporting period was (for this report, either 3 or 6 months) and didn't catch this to update. Is this the total number of public profile views during one of those time spans? Or is it the total number of public profile views since the profile was created? Or something else?

2022-05-16 20:28 UTC, HeatherStenson commented on src/pages/docs/reports/team-details-reports.md
> +* **Integrations by type** - The number of integrations, broken down by integration type.
> integrations of type api_github & apiversion_github don't count in the resource usage though

Are those the integrations documented in https://learning.postman.com/docs/integrations/available-integrations/github/ and https://learning.postman.com/docs/designing-and-developing-your-api/versioning-an-api/#using-an-external-git-repository ?

2022-05-17 00:30 UTC, HeatherStenson commented on src/pages/docs/reports/reports-overview.md
> +* You might not have enabled __Save Responses__ in the __History__ tab in Postman.
Removed in [0d2aabe](https://github.com/postmanlabs/postman-docs/pull/4005/commits/0d2aabe0ac2fed41e16d375dfd9eceedd90c80a3)

2022-05-17 00:30 UTC, HeatherStenson commented on src/pages/docs/reports/all-apis-reports.md
> +* **Public API views** - A graph of the number of views of your team's public APIs over the last three months.
Good catch, updated the wording in [b8fd984](https://github.com/postmanlabs/postman-docs/pull/4005/commits/b8fd984bf197f6956a87f79d0d4ea6dff684bba3)!

2022-05-17 00:31 UTC, HeatherStenson commented on src/pages/docs/reports/team-details-reports.md
> +* **Used slots over time** - The number of billed seats and unbilled seats used by your team in the last six months.
Thanks! Updated in [c608fac](https://github.com/postmanlabs/postman-docs/pull/4005/commits/c608faca6e8a24eb892e041ef1e5f0482b226678)

2022-05-17 00:32 UTC, HeatherStenson commented on src/pages/docs/reports/reports-overview.md
> +You can only see report data that's available to you based on your [role](/docs/collaborating-in-postman/roles-and-permissions/). If you don't have role-based permission to access an entity, you won'
Thanks @rishabh-nayar-github! I updated the wording in [2fa50b2](https://github.com/postmanlabs/postman-docs/pull/4005/commits/2fa50b2e5b627f3126db798b03dc66d5645c32c9) - can you please take a look to confirm that I got it right?

2022-05-17 00:33 UTC, HeatherStenson commented on src/pages/docs/reports/all-apis-reports.md
>  The **Team APIs** report provides information on APIs created by your team, including:
Thanks! Updated this wording in [b0aa83d](https://github.com/postmanlabs/postman-docs/pull/4005/commits/b0aa83d47a56ff2fb99131a9a77c9dcf062e895c)

2022-05-17 00:34 UTC, HeatherStenson commented on src/pages/docs/reports/all-apis-reports.md
> -* **Response time** - The average response time of all APIs over time.
Thanks! Updated in [b0aa83d](https://github.com/postmanlabs/postman-docs/pull/4005/commits/b0aa83d47a56ff2fb99131a9a77c9dcf062e895c). I also updated the wording for Response time to include that caveat.

2022-05-17 00:35 UTC, HeatherStenson commented on src/pages/docs/reports/all-apis-reports.md
> +* **Schemas by type** - The number of APIs by schema type (like OpenAPI, GraphQL, and Swagger). If an API has more than one version with different schemas, the API will have entries in each of those
Thanks! Updated this wording in [b0aa83d](https://github.com/postmanlabs/postman-docs/pull/4005/commits/b0aa83d47a56ff2fb99131a9a77c9dcf062e895c)

2022-05-17 00:36 UTC, HeatherStenson commented on src/pages/docs/reports/all-workspaces-reports.md
> +* **Workspaces by type** - The total number of personal, private, public, and team workspaces, and the number of empty workspaces of each type. Empty workspaces are workspaces that don't contain any
Good call, updated in [21ee042](https://github.com/postmanlabs/postman-docs/pull/4005/commits/21ee0424cd4d5475e8de3a2c14e3b7e02b9a6a38)

2022-05-17 00:37 UTC, HeatherStenson commented on src/pages/docs/reports/all-workspaces-reports.md
> +* **Views on public entities** - The number of workspace and collection views within your public workspaces in the last three months.
Yes, that sounds much better! Updated in [606e754](https://github.com/postmanlabs/postman-docs/pull/4005/commits/606e754dd8fea7258ce3363b9c537706a66788a8)

2022-05-17 00:37 UTC, HeatherStenson commented on src/pages/docs/reports/all-workspaces-reports.md
> +    * Creating, editing, deleting, and sending requests.
I separated "sending requests" into its own item in [ee006d0](https://github.com/postmanlabs/postman-docs/pull/4005/commits/ee006d068854b3ae997c7206b7e1315e519a3dda)

2022-05-17 00:39 UTC, HeatherStenson commented on src/pages/docs/reports/all-apis-reports.md
>  The __Public APIs__ report provides metrics including an overview of your total published APIs, API updates and views, and a separate view of your APIs with and without mocks, monitors, tests, and do
Thanks! Updated in [fe93a54](https://github.com/postmanlabs/postman-docs/pull/4005/commits/fe93a541a1f793ea74668135496421daae9b7719)

2022-05-18 09:49 UTC, rishabh-nayar-github commented on src/pages/docs/reports/all-apis-reports.md
> +* **Total public APIs** - The number of APIs that are published to the Public API Network.
Yes @HeatherStenson That would be better. As there is no explicit option of publishing to Public Network as of now.

2022-05-18 09:54 UTC, rishabh-nayar-github commented on src/pages/docs/reports/team-details-reports.md
> +* **Integrations by type** - The number of integrations, broken down by integration type.
I am not sure about this @HeatherStenson . Let me check with someone from integration squad for this once.

2022-05-18 09:58 UTC, rishabh-nayar-github commented on src/pages/docs/reports/all-apis-reports.md
> -* **Response time** - The average response time of all APIs over time.
Oh. Also - Doesn't this PR get updated with that commit (as in bitbucket)?

2022-05-19 05:14 UTC, Hon3yNa1r approved these changes
LGTM, thanks a lot @HeatherStenson.

2022-05-19 17:27 UTC, merged