[TW-340] Update changelog docs
postmanlabs/postman-docs pull request #4032
Opened 2022-05-05 06:38 UTC by claireriley

2022-05-05 07:26 UTC, kartikjain26 requested changes

2022-05-05 07:26 UTC, kartikjain26 commented on src/pages/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections.md
> +Each Postman Collection has a changelog that covers create, update, and delete events. You can use the changelog to keep track of updates you and your collaborators make to your private and team coll
We can include transfer also here.

2022-05-05 07:26 UTC, kartikjain26 commented on src/pages/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections.md
> +Each Postman Collection has a changelog that covers create, update, and delete events. You can use the changelog to keep track of updates you and your collaborators make to your private and team coll
Can change this `you and your collaborators` to `you and other collaborators`

2022-05-05 07:26 UTC, kartikjain26 commented on src/pages/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections.md
> +You can review the activity for your own account in [Postman](https://go.postman.co/). Select your avatar in the top right, then select __Profile__. The __Activity__ tab will list your events.
do we need this in changelog ?

2022-05-05 17:02 UTC, HeatherStenson approved these changes
Looks good! 🍊

2022-05-05 17:14 UTC, jkonrath-postman approved these changes
Looks good to me!

2022-05-05 19:35 UTC, mark-anthony-postman approved these changes
LGTM! 🌟  Just a couple small comments

2022-05-05 19:35 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections.md
>  * Viewing changes to a [collection](#viewing-the-collection-changelog), [workspace](#viewing-workspace-activity), [team](#viewing-team-activity), or [user account](#viewing-user-activity).
```suggestion
* Viewing changes to a [collection](#viewing-the-collection-changelog), [workspace](#viewing-workspace-activity), [team](#viewing-team-activity), or [user account](#viewing-user-activity)
```

2022-05-05 19:35 UTC, mark-anthony-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections.md
> +    <img alt="Restore from changelog" src="https://assets.postman.com/postman-docs/changelog-restore-v9.16.jpg" width="350px"/>
Add a blank line before the image

2022-05-05 19:35 UTC, mark-anthony-postman commented on src/pages/docs/sending-requests/intro-to-collections.md
> +    <img alt="Restore from changelog" src="https://assets.postman.com/postman-docs/changelog-restore-v9.16.jpg" width="350px"/>
Add a blank line before the image

2022-05-11 04:41 UTC, claireriley commented on src/pages/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections.md
> +You can review the activity for your own account in [Postman](https://go.postman.co/). Select your avatar in the top right, then select __Profile__. The __Activity__ tab will list your events.
Looks like this is outdated, removed it

2022-05-26 06:34 UTC, ankitjaggi approved these changes

2022-05-26 06:34 UTC, ankitjaggi commented
@claireriley We can merge this and release the new docs now.

2022-05-26 15:08 UTC, merged