TW 502 Documentation for API security reports
postmanlabs/postman-docs pull request #4106
Opened 2022-06-16 23:28 UTC by HeatherStenson

Adds documentation for the upcoming API security reports

2022-06-17 15:10 UTC, mark-anthony-postman approved these changes
LGTM! 🦄

2022-07-11 19:38 UTC, jkonrath-postman approved these changes
LGTM

2022-07-11 19:38 UTC, jkonrath-postman commented on src/pages/docs/reports/security-audit-reports.md
>  updated: 2022-05-19
Bump up your date here

2022-09-05 11:53 UTC, savageCoder55 commented on src/pages/docs/reports/api-governance-reports.md
> +* [Private Network APIs](#private-network-apis)
I believe we'll be shipping only 2 reports based on the latest decisions for the v10 launch.
These reports will be `API Governance > Public APIs` and `API Governance > Private Network APIs`

Request you to update the same.
cc : @bhargavkn

2022-09-05 11:53 UTC, savageCoder55 commented on src/pages/docs/reports/api-governance-reports.md
> +* **Top rules violated** - The API Governance rules that are most frequently violated in APIs owned by your team.
Based on the above comment, this section won't be needed immediately

2022-09-05 11:56 UTC, savageCoder55 commented on src/pages/docs/reports/api-governance-reports.md
> +* **Compliance** -
I believe we should rename this to `Conformance` as Compliance has a different legal connotation on the privacy front w.r.t GDPR and HIPPAA
cc : @bhargavkn @Hon3yNa1r 

Also some context here as to what data points are included - e.g showing details of APIs that have no `Governance Rule violations`

PS : please note we have moved towards using `Rule violation` as the product abstraction instead of `API Warnings`

2022-09-05 11:57 UTC, savageCoder55 commented on src/pages/docs/reports/api-governance-reports.md
> +* **Non-compliance** -
Requesting renaming to `Non-conformance `and refer the above comment for similar changes

2022-09-05 11:58 UTC, savageCoder55 commented on src/pages/docs/reports/api-governance-reports.md
> +* **API compliance over time** -
Would suggest renaming to `API conformance over time`

2022-09-05 11:58 UTC, savageCoder55 commented on src/pages/docs/reports/api-governance-reports.md
> +
This section will not be needed as per the latest v10 decisions for reporting.

2022-09-05 11:59 UTC, savageCoder55 commented on src/pages/docs/reports/api-governance-reports.md
> +The **Public APIs** report provides the following information for the past 30 days:
Let's ensure that we mention clearly that the `Public APIs` report will contain data from APIs in public workspaces alone

2022-09-05 12:00 UTC, savageCoder55 commented on src/pages/docs/reports/api-governance-reports.md
> +The **Private Network APIs** report provides the following information for the past 30 days:
Similar comment here - let's convey that this will depict data gathered from APIs that are added to the Private API Network for the respective Postman team.

2022-09-05 12:01 UTC, savageCoder55 commented on src/pages/docs/reports/api-security-reports.md
> +* **Top 3 APIs with most violations** -
Won't be needed

2022-09-05 12:01 UTC, savageCoder55 commented on src/pages/docs/reports/api-security-reports.md
> +* **Top rules violated** -
Won't be needed

2022-09-05 12:02 UTC, savageCoder55 commented on src/pages/docs/reports/api-security-reports.md
> +* [Private Network APIs](#private-network-apis)
Requesting that we reduce this to only `API Security > Public APIs` and `API Security > Private Network APIs`

2022-09-05 12:03 UTC, savageCoder55 commented on src/pages/docs/reports/api-security-reports.md
> +* **Top 3 APIs with most violations** -
Won't be needed

2022-09-05 12:03 UTC, savageCoder55 commented on src/pages/docs/reports/api-security-reports.md
> +* [Private Network APIs](#private-network-apis)
Requesting that we reduce this to only `API Security > Public APIs` and `API Security > Private Network APIs`

2022-09-05 12:04 UTC, savageCoder55 commented on src/pages/docs/reports/api-security-reports.md
> +* **API compliance over time** -
Similar naming changes to the ones mentioned for API Governance page

2022-09-05 12:04 UTC, savageCoder55 commented on src/pages/docs/reports/api-security-reports.md
> +* **API compliance over time** -
SImilar changes to the ones mentioned on the API Governance page

2022-09-05 12:05 UTC, savageCoder55 requested changes
There are a few small changes I've requested. Also request to add @bhargavkn and @Hon3yNa1r as reviewers for this.

2022-09-06 23:37 UTC, HeatherStenson commented
Thanks for your notes @savageCoder55! I've made updates accordingly. If you and/or @bhargavkn and @Hon3yNa1r could please evaluate the descriptions for each visualization, that would be great. I never found any internal documentation for that so I was guessing 😁

2022-09-06 23:37 UTC, HeatherStenson commented
@MatthewPinsker-postman ready for you to take a look at this one!

2022-09-07 17:04 UTC, MatthewPinsker-postman commented on src/pages/docs/reports/api-governance-reports.md
> +title: "API Governance reports"
I think this topic is missing from the left nav.

2022-09-07 17:04 UTC, MatthewPinsker-postman commented on src/pages/docs/reports/api-security-reports.md
> +title: "API Security reports"
I think this topic is missing from the left nav.

2022-09-07 17:05 UTC, MatthewPinsker-postman commented on src/pages/docs/reports/api-governance-reports.md
> +The **API Security** report dashboard provides metrics relevant to your team's [API Governance](/docs/api-governance/api-governance-overview/) rule compliance. This section has two reports:
Should "API Security" be italicized, instead of bold?

2022-09-07 17:06 UTC, MatthewPinsker-postman commented on src/pages/docs/reports/api-governance-reports.md
> +The **Public APIs** report provides the following information for APIs in your team's [public workspaces](/docs/collaborating-in-postman/using-workspaces/public-workspaces/) over the past 30 days:
Same question as above about italic vs bold.

2022-09-07 17:06 UTC, MatthewPinsker-postman commented on src/pages/docs/reports/api-governance-reports.md
> +The **Private Network APIs** report provides the following information for APIs in your team's [Private API Network](/docs/collaborating-in-postman/adding-private-network/) over the past 30 days:
Same question as above about italic vs bold.

2022-09-07 17:09 UTC, MatthewPinsker-postman commented on src/pages/docs/reports/api-governance-reports.md
> +* **Conformance** - The number of APIs in your team's public workspaces that don't have any API Governance rule violations.
On beta, I'm seeing "compliance" instead of "conformance". Although, I might not be looking at the correct track.

2022-09-07 17:10 UTC, MatthewPinsker-postman commented on src/pages/docs/reports/api-security-reports.md
> +The **API Security** report dashboard provides metrics relevant to the [API Security](/docs/api-governance/api-testing/api-testing-warnings/) posture of your Postman APIs. This section has two report
Same question as above about italic vs bold.

2022-09-07 17:14 UTC, MatthewPinsker-postman approved these changes
Looks good to me! I added a few inline comments/questions.

2022-09-07 17:55 UTC, HeatherStenson commented on src/pages/docs/reports/api-governance-reports.md
> +* **Conformance** - The number of APIs in your team's public workspaces that don't have any API Governance rule violations.
Y, this change was based on @savageCoder55's [review](https://github.com/postmanlabs/postman-docs/pull/4106#discussion_r962826505) - I'm assuming this will change in the product as well but will revert back of that's not the case.

2022-09-07 18:10 UTC, HeatherStenson commented on src/pages/docs/reports/api-security-reports.md
> +title: "API Security reports"
Yikes, big thing to overlook! Ty, great catch.

2022-09-07 18:10 UTC, HeatherStenson commented on src/pages/docs/reports/api-governance-reports.md
> +title: "API Governance reports"
Thank you, good catch!

2022-09-07 20:17 UTC, MatthewPinsker-postman commented on src/pages/docs/reports/api-governance-reports.md
> +The **API Security** report dashboard provides metrics relevant to your team's [API Governance](/docs/api-governance/api-governance-overview/) rule compliance. This section has two reports:
Should this be "The **API Governance** report dashboard"?

2022-09-08 17:26 UTC, HeatherStenson commented on src/pages/docs/reports/api-governance-reports.md
> +The **API Security** report dashboard provides metrics relevant to your team's [API Governance](/docs/api-governance/api-governance-overview/) rule compliance. This section has two reports:
```suggestion
The **API Governance** report dashboard provides metrics relevant to your team's [API Governance](/docs/api-governance/api-governance-overview/) rule compliance. This section has two reports:
```

2022-09-08 17:27 UTC, HeatherStenson commented on src/pages/docs/reports/api-governance-reports.md
> +The **API Security** report dashboard provides metrics relevant to your team's [API Governance](/docs/api-governance/api-governance-overview/) rule compliance. This section has two reports:
Wow, I was really on a roll here 🤦‍♀️ Thanks for catching!

2022-09-12 22:07 UTC, HeatherStenson commented
@Hon3yNa1r and @bhargavkn please let me know ASAP if you want any changes to the content here!

2022-09-14 06:35 UTC, savageCoder55 commented
Let's hold off on merging this PR at the moment. We can plan to add this to the LC once we're through with the existing LC changes that need to accompany the v10 launch.

2022-09-15 15:57 UTC, closed without merging