[TW-620] Note uptime monitor creation is disabled
postmanlabs/postman-docs pull request #4205
Opened 2022-08-03 20:37 UTC by mark-anthony-postman

- Added notes stating the uptime monitor open beta is over
- Clarified FAQ about uploading data files

2022-08-03 21:42 UTC, petewitcher approved these changes
LGTM!

2022-08-04 14:54 UTC, MatthewPinsker-postman commented on src/pages/docs/monitoring-your-api/intro-monitors.md
> +> **The uptime monitors open beta period is over.** You can no longer create new uptime monitors. Your existing uptime monitors will keep working, and you can continue to use them to monitor API upti
In lines 51 and 65, we mention "Uptime monitors (open beta)." Should we remove instances of "(open beta)" because the beta period has ended? My thinking is that users might think the open beta is still going if they miss the note.

2022-08-04 14:57 UTC, MatthewPinsker-postman commented on src/pages/docs/monitoring-your-api/uptime-monitors.md
> +> **The uptime monitors open beta period is over.** You can no longer create new uptime monitors. Your existing uptime monitors will keep working, and you can continue to use them to monitor API upti
In line 19, we mention "Uptime monitors (open beta)." Should we remove this instance of "(open beta)" because the beta period has ended? My thinking is that users might think the open beta is still going if they miss the note.

2022-08-09 22:27 UTC, godfrzero requested changes

2022-08-09 22:27 UTC, godfrzero commented on src/pages/docs/monitoring-your-api/faqs-monitors.md
>  search_keyword: "console.log, console.warn"
Are these terms used for SEO?

2022-08-09 22:27 UTC, godfrzero commented on src/pages/docs/monitoring-your-api/intro-monitors.md
> +> **The uptime monitors open beta period is over.** You can no longer create new uptime monitors. Your existing uptime monitors will keep working, and you can continue to use them to monitor API upti
+1 on this.

2022-08-09 22:37 UTC, mark-anthony-postman commented on src/pages/docs/monitoring-your-api/faqs-monitors.md
>  search_keyword: "console.log, console.warn"
These search terms are for the "Search Postman Docs" box in the upper right corner of the Learning Center, not for Google search. Our search tool, Algolia, only indexes the first 6500 characters of a topic, so we use this to add search terms for things toward the bottom of long pages if we're worried Algolia won't index them.

2022-08-10 14:56 UTC, godfrzero approved these changes

2022-08-10 14:57 UTC, merged