TW 639 Update linting wording
postmanlabs/postman-docs pull request #4228
Opened 2022-08-18 23:33 UTC by HeatherStenson

This PR updates wording for selected OpenAPI 2.0 and 3.0 linting rules, based on reviews from the Open Tech team.

2022-08-18 23:35 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +### Your request bodies all need examples
@chinmayjoshi I changed the message wording to be more succinct (I hope) than what was in the spreadsheet ("All request bodies should have example or examples present"). Let me know if this works

2022-08-18 23:37 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +<!-- TODO: confirm that details are right for openapi2 -->
@chinmayjoshi Since this is new for the OpenAPI 2.0 rules, if you can make sure I got the details right that would be great.

2022-08-18 23:38 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +<!-- TODO: confirm that details are right for openapi2 -->
@chinmayjoshi This is also new for the OpenAPI 2.0 rules, so if you can make sure I got the details right I would appreciate it!

2022-08-18 23:40 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +<!-- TODO: confirm message wording is okay -->
@chinmayjoshi I changed the message wording to be more succinct (I hope) than what was in the spreadsheet ("All your responses need to have the example or examples field defined."). Please let me know if that wording is okay!

2022-08-18 23:42 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +### A schema property should reference a reusable schema
@chinmayjoshi Our build system was complaining about `$ref` being included in the heading, so I reworded from the original that was in the spreadsheet ("A schema property should have a $ref property referencing a reusable schema"). Let me know if that works - if not, we'll figure out a workaround.

2022-08-18 23:43 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +<!-- TODO: confirm that details are right for openapi2 -->
@chinmayjoshi Since this is new for the OpenAPI 2.0 rules, if you can make sure I got the details right that would be great.

2022-09-05 12:32 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +    * [Your responses all need examples](#your-responses-all-need-examples)
Similar comment as above

2022-09-05 12:33 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +    * [A 204 No Content response can't have a body](#a-204-no-content-response-cant-have-a-body)
The name here seems a bit off - @chinmayjoshi can you please suggest something that is a bit more clearer

2022-09-05 12:34 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [info object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#infoObject) doesn't contain a [contact object](https://github.com/OAI/OpenAPI-Specification/
We should try and use `API definition` instead of `API schemas` for all places that we reference schemas.
@chinmayjoshi / @rishabjain22 / @arno-di-loreto will be better equipped to review the content of each of the rules.

2022-09-05 12:36 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [info object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#infoObject) doesn't contain a [contact object](https://github.com/OAI/OpenAPI-Specification/
General comment here - we should frame the sentences so that they feel more like suggestions.
Something like - It is recommended for your API definition's info object to contain contact details ..... - something like this

2022-09-05 12:38 UTC, savageCoder55 requested changes
@chinmayjoshi @rishabjain22 @raghavgarg1257 @arno-di-loreto request you to please review this PR for the LC content since you're better equipped to suggest the content for individual rules.

I have added a few high level comments from a messaging perspective for @HeatherStenson

2022-09-05 12:40 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [info object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#infoObject) doesn't contain a [contact object](https://github.com/OAI/OpenAPI-Specification/
@arno-di-loreto request you to review this PR as per your bandwidth

2022-09-06 14:44 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +    * [Your operation summaries shouldn't end with a period](#your-operation-summaries-shouldnt-end-with-a-period)
Agree, the original is better. It seems the new wordings come from the Open Tech [checked/updated Spectral rules](https://github.com/postman-open-technologies/linting-rules-v2/tree/main/specifications/openapi/sources/refining-rules).
I should update them to match the initial text (the one without "Your ...").

2022-09-06 14:51 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +    * [A 204 No Content response can't have a body](#a-204-no-content-response-cant-have-a-body)
Though I wrote it myself, it took me a moment to figure out what I wanted to say 😅. That's an "A '_204 No Content_' response can't have a body". "No Content" is the human-readable reason for 204. The "No Content" reason could be removed, leading to "A 204 response can't have a body".

2022-09-06 15:07 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +    * [Your operation summaries shouldn't end with a period](#your-operation-summaries-shouldnt-end-with-a-period)
That means that all sentences "You xxx all need yyy" should be replaced by "All xxx should have yyy"

2022-09-06 15:15 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [info object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#infoObject) doesn't contain a [contact object](https://github.com/OAI/OpenAPI-Specification/
Agree on "API definition" instead of "API Schema".

2022-09-06 15:18 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +openapi: "3.1.0"
Also, that's 3.1, I'm happy with that but is this the version we want to push forward yet as it not completely supported? (Removing the openapi version number would solve the problem for now as all rules works for 3.x)

2022-09-06 15:19 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +| Your API schema's [info object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#infoObject) doesn't contain a [contact object](https://github.com/OAI/OpenAPI-Specification/
Same comment as below regarding the OpenAPI 3 version targeted by documentation links.

2022-09-09 13:35 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [contact object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#contactObject) doesn't contain an email address. Although an email isn't required, just a
We should remove the "dependency" with the name (I wrote the original description with the whole default ruleset in mind) and rephrase it with something like this:

> Although a contact email isn't required, it gives a way to contact your organization of the API owner.

The same goes for the "contact url" and "contact email or url" rules.

2022-09-09 13:36 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [contact object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#contactObject) doesn't contain a contact URL or email address. Although a contact URL or
See comments on contact email (remove dependency with name)

2022-09-09 13:41 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +    * [Your operation summaries shouldn't end with a period](#your-operation-summaries-shouldnt-end-with-a-period)
General comment for both files I would have expected the following rules to be removed as they are not in the rules I have fixed and redefined, @chinmayjoshi @savageCoder55 can you confirm?

- The info object should have an API ID extension
- The info object should have an audience extension
- There should be no empty paths
- There should be a central tags object
- All tags should have a description
- There should be at least one tag
- All operations should have tags
- All operations should have at least one tag
- DELETE operations shouldn't have a response body
- DELETE operations should have a 500 status code for the response
- Operation should return a 2xx HTTP status code
- Operation should return a 5xx HTTP status code
- All schemas should have properties
- Integer format should be int32 or int64
- Number format should be decimal32, decimal64, float, double, or decimal128

2022-09-09 13:43 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +    * [Your parameters all need examples](#your-parameters-all-need-examples)
Rule to remove, "parameters all need examples" is a v3 only rule (impossible to put examples on non-body parameters in swagger 2).

2022-09-09 13:45 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +    name: A contact name
Remove the name property (it's optional, see also comment on line 857)

2022-09-09 13:46 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +    name: A contact name
Remove the name property (it's optional, see also comment on line 857)

2022-09-09 13:49 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [contact object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#contactObject) doesn't contain a contact URL or email address. Although a contact URL or
Link target wrong version of the spec documentation: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#contact-object

2022-09-09 13:49 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [info object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#infoObject) doesn't contain a [contact object](https://github.com/OAI/OpenAPI-Specification/
Link target wrong version of the spec https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#contact-object

2022-09-09 13:51 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [contact object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#contactObject) doesn't contain an email address. Although an email isn't required, just a
Link target wrong version of the spec documentation: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#contact-object

2022-09-09 13:52 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [contact object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#contactObject) doesn't contain a contact URL. Although a contact URL isn't required, just
Link target wrong version of the spec documentation: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#contact-object

2022-09-09 13:53 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [info object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#infoObject) doesn't contain a description. Although a description isn't required, including
Link target wrong version of the spec: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#info-object

2022-09-09 13:53 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [info object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#infoObject) doesn't contain a [license object](https://github.com/OAI/OpenAPI-Specification/
Link target wrong version of the spec: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#info-object

2022-09-09 13:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [license object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#licenseObject) doesn't contain a license URL, which provides a link to a web page that de
Link target wrong version of the spec https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#license-object

2022-09-09 13:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [info object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#infoObject) doesn't contain a URL for the Terms of Service for the API. A terms of service i
Link target wrong version of the spec: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#info-object

2022-09-09 13:55 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [info object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#infoObject) doesn't contain an API ID extension (`x-api-id`), which is a custom header used
Link target wrong version of the spec: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#info-object

2022-09-09 13:57 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
>    '/health_check':
Replace by /health_check by /resources to be consistent with other snippets (at least the governance ones)

2022-09-09 14:00 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| One or more [operation objects](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#operation-object) in your API schema doesn't have a description. When the resource path, HTT
Link targets wrong version https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#operationObject

2022-09-09 14:00 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| One or more [operation objects](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#operation-object) in your API schema doesn't have a summary. A summary of what the operation
Link targets wrong version https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#operationObject

2022-09-09 14:22 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| One or more [operation objects](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#operation-object) in your API schema contains a summary that ends with a period (`.`). API d
Link targets wrong version https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#operation-object

2022-09-09 14:24 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +### Your parameters all need examples
v3 only rule, to remove

2022-09-09 14:28 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +### Your request bodies all need examples
That works. 
Note that this "Your ..." should be modified like all others in "All ..."

2022-09-09 14:30 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| One or more [parameter objects](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#parameter-object) in an [operations object](https://github.com/OAI/OpenAPI-Specification/blo
@chinmayjoshi I have a doubt will the mock generator take advantage of that example below? (it's a bit different from what happens in OpenAPI3, here we just use the example property of JSON schema, not an OpenAPI property as it is done in v3).

2022-09-09 14:32 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +<!-- TODO: confirm message wording is okay -->
Same as works request bodies examples: That works.
Note that this "Your ..." should be modified like all others in "All ..."

2022-09-09 14:39 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| One or more [parameter objects](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#parameter-object) in an [operations object](https://github.com/OAI/OpenAPI-Specification/blo
Issue description first sentence (link targets schema object definition, only parameters having `in` set to `body` are concerned, no the other ones like the `query` ones for instance): 

> One or more body parameter object [schema](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#schemaObject) in your API definition doesn't contain an example.

Fix: 

> Add an `example` field to the schema to all body parameters

2022-09-09 14:43 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| One or more [parameter objects](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#parameter-object) in an [operations object](https://github.com/OAI/OpenAPI-Specification/blo
Maybe rephrase "It's important to provide the `example` field to help..." to "It's important to provide an example of the request body to help..." (the idea is to talk more about "principles" instead of the spec, as it is done in the rule dealing with contact: first sentence describe the problem from a spec perspective, then the next ones explain the problem from an API/principles perspective

2022-09-09 14:49 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| One or more [response objects](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#responseObject) in your API schema doesn't contain an example. It's important to provide the
Issue description: "It's important to provide an example field to ..."
Fix (examples and not example): Add an `examples` field to all response objects

2022-09-09 15:08 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| One or more [response objects](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#responseObject) in your API schema doesn't contain an example. It's important to provide the
Link targets wrong version https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#response-object

2022-09-09 22:39 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +    * [Your operation summaries shouldn't end with a period](#your-operation-summaries-shouldnt-end-with-a-period)
@arno-di-loreto from the list above, I do see the following rules in the spreadsheet of rules you fixed:

- Operation should return a 2xx HTTP status code
- Operation should return a 5xx HTTP status code

Should those still be removed from these files?

2022-09-12 08:43 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
>  * [API information](#api-information)
Note that besides the swagger/openapi in snippets, text and snippets can be identical for all rules in this "API information" section

2022-09-12 08:49 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| Your API schema's [info object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#infoObject) doesn't contain a [contact object](https://github.com/OAI/OpenAPI-Specification/
There are 3 (all optional) properties in contact: name, email, and url (not just name and email). To keep the rules as open as possible (there are rules covering various scenarios), can we rephrase "which contains contact information including a name and email address" into something that includes url in the list of possibilities "which contains contact information such as a name, email address or url"

2022-09-12 09:16 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
>      url: https://example.com
https://example.com/support to be consistent with other snippets

2022-09-12 09:16 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +    name: A contact name
Remove name

2022-09-12 09:19 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +    url: https://example.com/support
Remove url

2022-09-12 09:19 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +    name: A contact name
Remove name

2022-09-12 14:01 UTC, arno-di-loreto reviewed
All done (I hope so at least 😅)

2022-09-12 14:01 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +| One or more [schema objects](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#schemaObject) in your API definition's [components object](https://github.com/OAI/OpenAPI-Speci
Remove reference to components, this rule target all array either they are defined in reusable schemas or inlines in body parameters or responses.

One or more [schema objects](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#schemaObject) in your API definition has an array type property but doesn't define minItem or maxItem. Consumers and providers can't handle an infinite number of elements. Setting the minimum and maximum boundaries helps in defining limits and enabling pagination.

2022-09-12 14:01 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +| One or more properties in a [schema object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#schemaObject) in your API definition's [components object](https://github.com/OA
Remove reference to components; his rule targets all properties, whether they are defined in reusable schemas or inlines in body parameters or responses.

2022-09-12 21:38 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-definition/openapi2.md
>  * [API information](#api-information)
Hi @arno-di-loreto can you explain more what you mean here? Do you mean that the snippet text can be identical between 2.0 and 3.0, minus the swagger/openapi line? And that the issue description and possible fix can be identical btw 2.0 and 3.0, minus the documentation links?

2022-09-13 16:25 UTC, jkonrath-postman approved these changes
LGTM - check your links (maybe with an `nvm run build`) and do a quick Vale to check for glaring issues, but otherwise looks good!

2022-09-13 16:49 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +| One or more PUT [operation objects](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#operationObject) in your API definition doesn't contain a [request body object](https://gi
Everything I can find on verb agreement for "one or more" and similar constructions seems to 🥁 _disagree_, but [this](https://english.stackexchange.com/a/485150) was fairly compelling:

"**One or more x.** The expression _one or more_ always takes a plural verb."

Based on that, I'll update this and others to "one or more ... don't".

2022-09-14 08:48 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
>  Postman recommends that you follow security and format warnings at the API definition phase of API development. A warning doesn't mean that your API schema is broken! Instead, it indicates that there
Can we please replace warnings with rule violations?

2022-09-14 08:48 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
>  After you [create a new API](/docs/designing-and-developing-your-api/creating-an-api/), select the **Definition** tab on the API version page to inspect the issues found in the API definition, if any
Replace Warnings with rule violations

2022-09-14 08:51 UTC, savageCoder55 reviewed
A couple small comments. Else everything looks good.
@HeatherStenson let's track separation of API Security and API Governance via Jira for a post v10 update to the LC

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +              value: example
I would recommend using the same kind of example as for the request body, some readers may take the "value" name as an OpenAPI property.

```
aProperty: example value
```

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +info:
info and its content can be replaced by `# ...` like in following examples

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +info:
info and its content can be replaced by `# ...` like in following examples

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +info:
info and its content can be replaced by `# ...` like in following examples

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +info:
info and its content can be replaced by `# ...` like in following examples

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +info:
info and its content can be replaced by `# ...` like in following examples

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +info:
info and its content can be replaced by `# ...` like in following examples

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +info:
info and its content can be replaced by `# ...` like in following examples

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
>  Postman recommends that you follow security and format warnings at the API definition phase of API development. A warning doesn't mean that your API schema is broken! Instead, it indicates that there
Question: this text talks about "warning" but there are other severity levels (error, info, and hint). Is this "warning" in a general sense?

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +  version: '1.0'
Same remark as in v2, there's a mix of single/double quote 'value' and "value", we should stick to one type of quote. I'm used to using "double quotes" but I checked the boilerplate in the editor, and it seems 'single quotes' are used.

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
>    description: Project API description
replace by description: An API description to be consistent with other snippets

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +  description: An API description
remove description (it's optional) and that will make this snippet consistent with the following ones

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +  description: An API description
remove description (it's optional) and that will make this snippet consistent with the following ones

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +  description: An API description
remove description (it's optional) to be consistent with following snippets

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +  description: An API description
remove description (it's optional) to be consistent with following snippets

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +    url: https://example.com
`https://example.com/support` to be consistent with other snippets

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +    url: https://example.com
`https://example.com/support` to be consistent with other snippets

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
>      get:
Remove get and its content (that will remove the health_check operationId which does not math the path in the making)

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +info:
Replace info and its content with `# ...`

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +info:
Replace info and its content with `# ...`

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +info:
Replace info and its content with `# ...`

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +info:
Replace info and its content with `# ...`

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +info:
Replace info and its content with `# ...`

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +info:
Replace info and its content with `# ...`

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +info:
Replace info and its content with `# ...`

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +info:
Replace info and its content with `# ...`

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +info:
Replace info and its content with `# ...`

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +info:
Replace info and its content with `# ...`

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +info:
Replace info and its content with `# ...`

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +info:
Replace info and its content with `# ...`

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +info:
Replace info and its content with `# ...`

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +info:
Replace info and its content with `# ...`

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +info:
Replace info and its content with `# ...`

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +      responses:
Remove responses (unnecessary and not present in v2 snippet)

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
We could have a second snippet demonstrating the use of `example` (though I do not recommend to use it, but that's another story).

```
openapi: "3.0.3"
# ...
paths:
  /resources:
    get:
      parameters:
        - name: status
          description: Filters resources on their status
          in: query
          example: done
          schema:
            type: string
```

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +      responses:
responses and its content can be removed

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
Same as for parameter, a second snippet demonstrating `example`

```
openapi: "3.0.3"
# ...
paths:
  /resources:
    post:
      requestBody:
        content:
          'application/json':
            schema:
              # ...
            example:
              aProperty: example value
```

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
Add a snippet demonstrating `examples` (to be consistent will other places where `examples` or `example` are requested.

```
openapi: "3.0.3"
# ...
paths:
  /resources:
    get:
      responses:
        '200':
          description: A success response
          content:
            'application/json':
              schema:
                # ...
              examples:
                anExample:
                  summary: An example
                  description: This is an example description
                  value:
                    aProperty: example value
```

2022-09-14 08:54 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
> +### All schema properties should have descriptions
This rule should be placed before "Arrays must have ..." (as it is in the TOC)

2022-09-14 09:06 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +        - in: formData
@HeatherStenson that's one to fix before launch

2022-09-14 09:06 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +        - in: formData
@HeatherStenson that's one to fix before launch

2022-09-14 09:07 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +              value: example
@HeatherStenson that's one to fix before launch

2022-09-14 09:08 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
@HeatherStenson that's one to fix before launch

2022-09-14 09:08 UTC, arno-di-loreto commented on src/pages/docs/api-governance/api-definition/openapi3.md
@HeatherStenson that's one to fix before launch

2022-09-14 17:51 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
>  Postman recommends that you follow security and format warnings at the API definition phase of API development. A warning doesn't mean that your API schema is broken! Instead, it indicates that there
Yes, good catch. I'll reword as "rule violation"

2022-09-14 18:01 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
>  After you [create a new API](/docs/designing-and-developing-your-api/creating-an-api/), select the **Definition** tab on the API version page to inspect the issues found in the API definition, if any
These updates are happening in https://github.com/postmanlabs/postman-docs/pull/4274

2022-09-14 18:06 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-definition/openapi2.md
> +  version: '1.0'
Will update 👍

2022-09-14 18:44 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-definition/openapi2.md
>  * [API information](#api-information)
Thanks for clarifying! I've confirmed parity btw 2.0 and 3.0 for the API info section.

2022-09-14 18:59 UTC, merged

2022-09-15 07:22 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
>  Postman recommends that you follow security and format warnings at the API definition phase of API development. A warning doesn't mean that your API schema is broken! Instead, it indicates that there
I believe the PR here : https://github.com/postmanlabs/postman-docs/pull/4274/files addresses this

2022-09-15 07:22 UTC, savageCoder55 reviewed
LGTM