[TW-598] Azure DevOps Pipelines integration
postmanlabs/postman-docs pull request #4234
Opened 2022-08-24 16:19 UTC by MatthewPinsker-postman

Azure DevOps Pipelines CI integration topic.

- Created a new page for this CI integration.
- Page is accessible from the left navigation menu and the "CI Integrations" page at `src/pages/docs/integrations/ci-integrations.md`

2022-08-26 21:45 UTC, jkonrath-postman approved these changes
LGTM!

2022-08-31 15:21 UTC, jankratochvilcz requested changes

2022-08-31 15:21 UTC, jankratochvilcz commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +If you haven't already, create a pipeline in the repository you use for your API. To create a pipeline, you add an `azure-pipelines.yml` file to your repository. You define your pipeline in this YAML
The file doesn't need to be named `azure-pipelines.yml`. It could be better to just refer folks to the official docs as they will be always up to date, creating less work for us and more comprehensive info for our users.

2022-08-31 15:21 UTC, jankratochvilcz commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +1. Enter a **Nickname** to help you recognize the integration later.
I believe we should be generating a default nickname, so the users can omit this step. Hopefully, we can hide the nickname completely at some point as it just adds friction to the onboarding

2022-08-31 15:21 UTC, jankratochvilcz commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +1. Select **Connect**.
Nitpick, but is select the right verb for buttons? Press/click could be more clear and enable us between selection and clicking

2022-08-31 15:21 UTC, jankratochvilcz commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +To view build jobs, open an API version and select the **Test** tab. The most recent jobs are listed under **CI/CD Builds**.
This is incorrect vernacular, the Azure UI uses the "pipeline run" colocation in most places we've seen. We should make sure we use the same nouns/verbs as Azure uses throughout to make the docs welcoming for Azure users. I realize we have a dichotomy where our UX uses incorrect terms as is generic, but these docs are a great opportunity to create a mental map for the user to navigate our product :-)

2022-08-31 15:21 UTC, jankratochvilcz commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +### Example azure-pipelines.yml file
Do we want to be including this? If we evolve this in the product, it will become easy for this doc to be outdated

2022-08-31 16:23 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +To set up an Azure DevOps Pipelines integration for your API, first create a pipeline in the version control system of your choice, and then configure your API in Postman. After you set up the integr
How about this?


"To set up an Azure DevOps Pipelines integration for your API, first create a repository in a [version control system supported by Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/). Create a pipeline in the repository, and then configure your API in Postman. After you set up the integration, you can view the status of builds from within Postman."

***

Please let me know if there are any additional details you think we should add here. Please note that this section is meant to be a brief overview. In the following sections, we go into more detail.

2022-08-31 16:26 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +If you haven't already, create a pipeline in the repository you use for your API. To create a pipeline, you add an `azure-pipelines.yml` file to your repository. You define your pipeline in this YAML
In our docs, we want to include a brief, high-level overview of the CI tool's user flow. The external link includes more detailed information.

Please let me know if there is anything you think we should add or omit from this section. Thanks!

***

How about this change?

"If you haven't already, create a repository in a version control system supported by Azure Pipelines. To create a pipeline, add a YAML file in your repository. You define your pipeline in this YAML file. To learn more, see [the Azure Pipelines documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-get-started)."

2022-08-31 16:30 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +1. Enter a **Nickname** to help you recognize the integration later.
We could add a second sentence similar to: "Postman pre-fills a nickname in the format `Azure DevOps Pipelines-{API_NAME}-{API_VERSION_NAME}`, and you can edit it if you want."

2022-08-31 16:34 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +1. Select **Connect**.
Thanks, Jan. Our style guidelines state to use "select" when referring to selecting a button, link, or menu option. We typically don't use "click" in our documentation.

2022-08-31 16:43 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +To view build jobs, open an API version and select the **Test** tab. The most recent jobs are listed under **CI/CD Builds**.
Thanks, Jan. Yes, we can change "build jobs" to "pipeline runs". I'll look for other occurrences on this page and make the change.

2022-08-31 16:47 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +### Example azure-pipelines.yml file
Yes, let's include this to be consistent with our preexisting CI integration docs. It's helpful for users to have a visual of what the config should look like.

2022-08-31 17:43 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +To view build jobs, open an API version and select the **Test** tab. The most recent jobs are listed under **CI/CD Builds**.
Looking at the documentation in more detail, there are more occurrences of "build" than I realized. As you pointed out, there is a discrepancy between the terms used in Postman (build/build job) and Azure DevOps (pipeline/pipeline run).

There are instances where we can easily change build/build job to pipeline/pipeline run. But I think this could become confusing when we start explaining areas of the UI--such as the "build status" option in the dropdown menu.

To help users understand the connection between build/build job and pipeline/pipeline run, I'm thinking that we could clarify this when each term is first used on the page.
For example: `builds (pipelines)` and `build jobs (pipeline runs)`

2022-10-17 14:20 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +### Example azure-pipelines.yml file
I removed this example file in the latest commit to be consistent with existing CI integrations. We removed these example files (from existing CI integrations) in the v10 release.

2022-10-26 13:25 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +1. Enter a **Nickname** to help you recognize the integration later.
The line is now updated to: "Postman pre-fills a nickname in the format `Azure Pipelines-{API_NAME}`, and you can edit it if you want."

2022-10-31 09:35 UTC, jankratochvilcz commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +To set up an Azure DevOps Pipelines integration for your API, first create a pipeline in the version control system of your choice, and then configure your API in Postman. After you set up the integr
This sounds great!

2022-10-31 09:35 UTC, jankratochvilcz commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +If you haven't already, create a pipeline in the repository you use for your API. To create a pipeline, you add an `azure-pipelines.yml` file to your repository. You define your pipeline in this YAML
Sounds good!

2022-10-31 09:36 UTC, jankratochvilcz commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +1. Enter a **Nickname** to help you recognize the integration later.
Sounds good!

2022-10-31 09:37 UTC, jankratochvilcz commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +To view build jobs, open an API version and select the **Test** tab. The most recent jobs are listed under **CI/CD Builds**.
Yeah, I think this would be worthwhile. If we can include verbiage along the lines of `Pipeline runs (sometimes referred to as builds within Postman)` it would make things clearer for the user!

2022-10-31 09:53 UTC, jankratochvilcz reviewed
Looks good! I don't have permission to approve but consider approved from my side, the feedback is only about cosmetics.

I really miss some kind fo a style guide I could review against, is that something we're working on/have? E.g., preferred verbs for certain actions, tone, etc.,

2022-10-31 09:53 UTC, jankratochvilcz commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +* [Configuring an Azure Pipelines integration](#configuring-an-azure-pipelines-integration)
(optional) we could combine these two sections as they are both fundamentally about the setup. The docs has a lot of headings and `Creating a pipeline in Azure DevOps` is a very short section, so combining it could make the doc more breathable

2022-10-31 09:53 UTC, jankratochvilcz commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +1. Enter a **Nickname** to help you recognize the integration later. Postman pre-fills a nickname in the format `Azure Pipelines-{API_NAME}`, and you can edit it if you want.
(optional) Not a native speaker, but curious here. If you capitalize _Nickname_, it feels like it'd become a proper noun, in which case the indefinite article should not be here. What's wrong about my reasoning?

2022-10-31 09:53 UTC, jankratochvilcz commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +* To view a build in Azure DevOps, select the build name.
```suggestion
* To view a build on the Azure DevOps website, select the build name.
```

(optional) It could be explicit we're talking about the web UI here.

2022-10-31 09:53 UTC, jankratochvilcz commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +To view the results of API Governance and API Security checks that ran as part of the build, first [configure the Postman CLI for Azure Pipelines](#configuring-the-postman-cli-for-azure-pipelines) an
```suggestion
To view the results of API Governance and API Security checks that ran as part of the build, first [configure the Postman CLI for Azure Pipelines](#configuring-the-postman-cli-for-azure-pipelines) and then trigger a new build on Azure DevOps. After the build is complete, use the arrows to expand a build and expand an API definition to view any rule violations.
```

(optional) Azure uses the verb _trigger_ [ref](https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops), so it'd feel polished to align. Just a suggestion!

2022-10-31 09:53 UTC, jankratochvilcz commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +With the help of the Postman CLI and the Postman API, you can run API tests created in Postman as part of your Azure DevOps pipeline. First generate the Postman CLI configuration code in Postman. The
(optional) As a developer, I wouldn't know what are "API tests". Tried to rephrase a bit to make it more obvious what we mean

```suggestion
With the help of the Postman CLI and the Postman API, you can run Postman test collections as part of your Azure DevOps pipeline. First, generate the Postman CLI configuration code in Postman. Then add the configuration code to the YAML file in your repository.
```

2022-10-31 09:53 UTC, jankratochvilcz commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +<img alt="Connect to Azure DevOps Pipelines" src="https://assets.postman.com/postman-docs/v10/azure-pipelines-connect-project-v10.jpg" width="518px">
```suggestion
<img alt="Connect to Azure Pipelines" src="https://assets.postman.com/postman-docs/v10/azure-pipelines-connect-project-v10.jpg" width="518px">
```

2022-10-31 14:43 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-devops-pipelines.md
> +To view build jobs, open an API version and select the **Test** tab. The most recent jobs are listed under **CI/CD Builds**.
Thanks, Jan. To be consistent with other CI integration pages and the Postman UI, I think it would be best to use "builds" as the primary/generic term and keep the Azure Pipelines-specific term inside the parentheses. This way the terminology is consistent between the docs and Postman UI.

2022-10-31 15:00 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +* [Configuring an Azure Pipelines integration](#configuring-an-azure-pipelines-integration)
Let's keep these separate for now. Each section covers something different. Separating the sections helps keep each section focused on something specific.

2022-10-31 15:15 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +1. Enter a **Nickname** to help you recognize the integration later. Postman pre-fills a nickname in the format `Azure Pipelines-{API_NAME}`, and you can edit it if you want.
Good question! We are capitalizing "Nickname" and making it bold because it aligns with our [style guide](https://github.com/postmanlabs/postman-docs/blob/develop/DOCS_STYLE_GUIDE.md#formatting-and-structure) of using bold to highlight names for parts of the software that the user interacts with.

This formatting helps clarify what we're asking the user to add, and also makes the content easier to scan.

In terms of the grammar, it's the same as writing "Enter a nickname to help you recognize..."

2022-10-31 15:31 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +To view the results of API Governance and API Security checks that ran as part of the build, first [configure the Postman CLI for Azure Pipelines](#configuring-the-postman-cli-for-azure-pipelines) an
Thanks, Jan. I don't think we need to be consistent in this way with Azure Pipelines. We use "start build" or "run build" in the docs and Postman UI, so I think it's better to be consistent here.

Instead of pointing to [Pipelines run sequence](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/runs?view=azure-devops) on `line 71`, I'm wondering if it would be more helpful to point to [Specify events that trigger pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops). This way we could point users to more specific information about starting/triggering builds. What do you think?

2022-10-31 15:38 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +* To view a build in Azure DevOps, select the build name.
Thanks, Jan. This is a format we follow in all of our CI integrations, so it isn't only an Azure Pipelines change. Let's keep this as is for now. I will bring up your feedback with my manager.

2022-10-31 17:34 UTC, mark-anthony-postman approved these changes
This new content looks awesome! 🌟 Made some comments but they're all super minor stuff 😀

2022-10-31 17:34 UTC, mark-anthony-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +After you set up an Azure Pipelines integration, information for build jobs (pipeline runs) is available in Postman. For each build you can view the branch, start time, duration, and status (`Succeed
```suggestion
After you set up an Azure Pipelines integration, information for build jobs (pipeline runs) is available in Postman. For each build you can view the branch, start time, duration, and status (`Successful` or `Failed`). You can also view the results of collection runs that are [configured in your pipeline using the Postman CLI](#viewing-collection-run-details).
```

2022-10-31 17:34 UTC, mark-anthony-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +After you set up an Azure Pipelines integration, information for build jobs (pipeline runs) is available in Postman. For each build you can view the branch, start time, duration, and status (`Succeed
The screenshot shows `Successful`

2022-10-31 17:34 UTC, mark-anthony-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +To view build jobs, open an API version and select the **Test** tab. The most recent jobs are listed under **CI/CD Builds**.
```suggestion
To view build jobs, open an API version and select **Test and Automation**. The most recent jobs are listed under the repository name.
```

2022-10-31 17:34 UTC, mark-anthony-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +To view build jobs, open an API version and select the **Test** tab. The most recent jobs are listed under **CI/CD Builds**.
There is also an occurrence of "Test tab" on the `bitbucket-pipelines.md` page (line 80). Would you mind fixing that one as well?

2022-10-31 17:34 UTC, mark-anthony-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +* To view more details for a build, use the arrows to expand a build and expand **Build Steps**. For each build step you can view the name, duration, and status.
From the screenshot, it doesn't look like you have a "Build Steps" node to expand. Delete this bullet?

2022-10-31 17:34 UTC, mark-anthony-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +<img alt="View API Governance and API Security results" src="https://assets.postman.com/postman-docs/v10/azure-api-governance-and-security-results-v10.jpg">
Screenshot needs a border

2022-10-31 19:24 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +page_id: "azure-pipelines"
Fixed.

2022-10-31 19:32 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +To view build jobs, open an API version and select the **Test** tab. The most recent jobs are listed under **CI/CD Builds**.
Good catch! This is now fixed in both places.

2022-10-31 19:36 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +* To view more details for a build, use the arrows to expand a build and expand **Build Steps**. For each build step you can view the name, duration, and status.
Good catch. This was already removed from the other CI integrations. This is now fixed.

2022-10-31 21:01 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +<img alt="View API Governance and API Security results" src="https://assets.postman.com/postman-docs/v10/azure-api-governance-and-security-results-v10.jpg">
I confirmed that the screenshot has a border. The team is looking into the disappearing border issue at https://postmanlabs.atlassian.net/browse/MARKENG-1927

2022-11-10 06:50 UTC, anshuljain03 commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +    * Replace all instances of `$(POSTMAN_API_KEY)` with a valid [Postman API Key](/docs/developer/intro-api/#generating-a-postman-api-key).
No, we recommend users to store the key in azure pipelines secret manager. Ref: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-secret-variables?view=azure-devops&tabs=yaml%2Cbash

2022-11-10 16:59 UTC, jankratochvilpostman approved these changes
Looks good!

2022-11-10 16:59 UTC, jankratochvilpostman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +To set up an Azure Pipelines integration for your API, first create a pipeline in Azure DevOps and then configure your API in Postman. <!-- repository in a [version control system supported by Azure
Is this <!-- syntax intentional? Unsure what's the reasoning, the content seems largely the same.

2022-11-10 16:59 UTC, jankratochvilpostman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +With the help of the Postman CLI and the Postman API, you can run API tests created in Postman as part of your Azure DevOps pipeline. First generate the Postman CLI configuration code in Postman. The
I think `Azure Repos repository` would be the correct reference as Git should be implied (Azure Repos doesn't host other kinds of repositories.

2022-11-10 16:59 UTC, jankratochvilpostman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +1. Create a new YAML file in your Azure Repos Git repository, and then edit the file.
Same as above.

2022-11-10 16:59 UTC, jankratochvilpostman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +To view the results of API Governance and API Security checks that ran as part of the build, first [configure the Postman CLI for Azure Pipelines](#configuring-the-postman-cli-for-azure-pipelines) an
Sounds good!

2022-11-10 17:11 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +To set up an Azure Pipelines integration for your API, first create a pipeline in Azure DevOps and then configure your API in Postman. <!-- repository in a [version control system supported by Azure
Thanks for bringing this up! Yes, this is intentional. That syntax is a comment, so anything inside that will not display in the docs. My intention is to preserve this content because it will become relevant when we allow users to use other repositories with the integration.

2022-11-10 17:13 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +With the help of the Postman CLI and the Postman API, you can run API tests created in Postman as part of your Azure DevOps pipeline. First generate the Postman CLI configuration code in Postman. The
I wrote "Azure Repos Git repository" because this is how they refer to it in the Azure Pipelines docs and UI. See https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml

What do you think?

2022-11-10 17:32 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +To view the results of API Governance and API Security checks that ran as part of the build, first [configure the Postman CLI for Azure Pipelines](#configuring-the-postman-cli-for-azure-pipelines) an
This is now updated.

2022-11-10 17:34 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +With the help of the Postman CLI and the Postman API, you can run API tests created in Postman as part of your Azure DevOps pipeline. First generate the Postman CLI configuration code in Postman. The
I left the first occurrence as "Azure Repos Git repository" because of the reason mentioned above. Also, the text is hyperlinked and points to an Azure Pipelines page that uses this same language. In other occurrences in the Postman docs, I changed this to "Azure Repos repository".

2022-11-10 17:35 UTC, MatthewPinsker-postman commented on src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md
> +1. Create a new YAML file in your Azure Repos Git repository, and then edit the file.
This is now updated.

2022-11-11 13:32 UTC, shashankawasthi88 reviewed
The integrations part looks good to me

2023-01-10 15:44 UTC, merged