TW 332 API security admin panel
postmanlabs/postman-docs pull request #4243
Opened 2022-08-26 00:10 UTC by HeatherStenson

This PR _only_ covers the UI for the API security admin panel. This PR will be merged into `tw-603-v10-api-security` once it's approved and ready to go. I'm holding off on screenshots until closer to release date to account for any UI and/or behavior changes.

2022-09-01 16:50 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/api-governance-admin-panel.md
> +Select Import from library. To see more details about a particular rule, select the expand icon > next to the rule name. Select the rules in the library you want to add, then select Import selected.
Should "Import from library", "Import selected", and "Import all" be in bold? I'm asking because it seems like these are buttons. I could not verify this on beta because I believe I don't have the correct permissions.

2022-09-01 16:53 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/api-governance-admin-panel.md
> +All the available governance rules turned on by default. Your team can configure individual governance rules to meet your development needs. If you turn a rule off, you and your team members won't se
```suggestion
All the available governance rules are turned on by default. Your team can configure individual governance rules to meet your development needs. If you turn a rule off, you and your team members won't see warnings for this rule if it's violated in your API's definition.
```

2022-09-01 16:54 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/api-governance-admin-panel.md
> +1. Select **Create new rule**.
In beta, it looks like the button name uses title case. Although, I might not be looking at the correct track.

2022-09-01 16:57 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +**API testing** - Postman applies governance rules to your [API requests](https://learning.postman.com/docs/api-governance/api-testing/api-testing-warnings/) and shows warnings about issues that migh
Is this meant to be a bulleted list? I'm asking because the content is displaying as a paragraph on my local build.

2022-09-01 16:59 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +All the available security rules turned on by default. Your team can configure individual security rules to meet your development needs. If you turn a rule off, you and your team members won't see wa
```suggestion
All the available security rules are turned on by default. Your team can configure individual security rules to meet your development needs. If you turn a rule off, you and your team members won't see warnings for this rule if it's violated in your API's definition or when you send an API request.
```

2022-09-01 17:00 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +* To configure the security rules that Postman runs during the design phase of API development, select **API definitions**.
On beta, it looks like the tab name uses title case. Although, I might not be looking at the correct track.

2022-09-01 17:00 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +1. Select **API definitions**.
On beta, it looks like the tab name uses title case. Although, I might not be looking at the correct track.

2022-09-01 17:01 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +1. Select **Create new rule**.
On beta, it looks like the button name uses title case. Although, I might not be looking at the correct track.

2022-09-01 17:02 UTC, MatthewPinsker-postman approved these changes
Looks good to me! I added a few inline questions/thoughts. Thanks!

2022-09-02 17:35 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +**API testing** - Postman applies governance rules to your [API requests](https://learning.postman.com/docs/api-governance/api-testing/api-testing-warnings/) and shows warnings about issues that migh
```suggestion
* **API design** - Postman applies governance rules to your [API definition](/docs/designing-and-developing-your-api/defining-an-api/) and shows warnings about your definition's format and security posture.
* **API testing** - Postman applies governance rules to your [API requests](https://learning.postman.com/docs/api-governance/api-testing/api-testing-warnings/) and shows warnings about issues that might impact their security posture.
```

2022-09-02 17:36 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +**API testing** - Postman applies governance rules to your [API requests](https://learning.postman.com/docs/api-governance/api-testing/api-testing-warnings/) and shows warnings about issues that migh
Oops! Ty, good catch ⚾

2022-09-02 17:38 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-governance-admin-panel.md
> +Select Import from library. To see more details about a particular rule, select the expand icon > next to the rule name. Select the rules in the library you want to add, then select Import selected.
```suggestion
Select **Import from library**. To see more details about a particular rule, select the expand icon **>** next to the rule name. Select the rules in the library you want to add, then select **Import selected**. If you want to import all the rules, select **Import all**. Once you import new rules from the library, you need to turn them on in the Governance dashboard.
```

2022-09-02 17:39 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-governance-admin-panel.md
> +Select Import from library. To see more details about a particular rule, select the expand icon > next to the rule name. Select the rules in the library you want to add, then select Import selected.
Thanks! Missed those when copying from my note-taking app 🤦

2022-09-02 17:44 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +1. Select **Create new rule**.
Yeah, the casing is wrong on the buttons rn. I'm going to leave the PR as-is now with the assumption that it'll get fixed before going to prod

2022-09-05 13:04 UTC, savageCoder55 commented on src/components/LeftNav/LeftNavItems.jsx
> +        name: 'API governance admin panel',
I would suggest that we refrain from using the words `admin panel` in the official documentation since that is an internal construct.

It would be better to have `API Governance > Configured Rules` as the name since this is similar to the wording we show in the product as well here : https://cooper.postman-beta.co/api-governance

2022-09-05 13:05 UTC, savageCoder55 commented on src/components/LeftNav/LeftNavItems.jsx
> +        name: 'API security admin panel',
Same as the comment above

2022-09-05 13:07 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-governance-admin-panel.md
> +The _API Governance admin panel_ enables you to customize the governance rules that Postman applies to your API at the design phase. Postman applies governance rules to your [API definition](/docs/de
Instead of `API at the design phase`, we can just use `API definitions` - thoughts?

Let's replace all the places where we have mentioned `warnings` to `Rule violations` - when it comes to API definitions.

2022-09-05 13:07 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-governance-admin-panel.md
> +* [Accessing the API Governance admin panel](#accessing-the-api-governance-admin-panel)
Accessing the configured Governance rules - thoughts?

2022-09-05 13:09 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-governance-admin-panel.md
> +> Access to the API Governance admin panel is only available for users who have both an Admin and a Developer role assigned to them. If you don't see the **API Governance** link from the Postman home
This needs to be updated. The links for API Governance and API Security will be visible to all users provided they are part of a team with an active Postman Enterprise plan.

If they are not able to see this, then they are not part of an Enterprise plan.

2022-09-05 13:12 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-governance-admin-panel.md
> +### Turning governance rules off and on
I would suggest that we follow the following IA for this page.
- How to navigate to the configured rules page
- Adding rules to your Governance configuration
- - Import pre-configured rules from the Postman library
- - Add custom rules (where we talk a bit more about Spectral)
- Enable/Disable the configured rules

2022-09-05 13:13 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-governance-admin-panel.md
> +> You must have an [Admin or Developer](/docs/collaborating-in-postman/roles-and-permissions/) role for your team to turn governance rules off and on.
For places where this information is present I would suggest we reword this to `only Admins with a Developer role can do....` - in my opinion this is less ambiguous

2022-09-05 13:14 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-governance-admin-panel.md
> +All the available governance rules are turned on by default. Your team can configure individual governance rules to meet your development needs. If you turn a rule off, you and your team members won'
I believe we're enabling only a subset of the rules present in the Postman library by default. Let's change this part to reflect the same.

cc : @chinmayjoshi

2022-09-05 13:16 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-governance-admin-panel.md
> +To turn a governance rule off, select the toggle next to the rule name. To turn the rule back on, select the toggle again.
This line is better housed in the section that talks about enabling/disabling the rules.

2022-09-05 13:16 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-governance-admin-panel.md
> +> You must have an [Admin or Developer](/docs/collaborating-in-postman/roles-and-permissions/) role for your team to create custom governance rules.
Same comment as before

2022-09-05 15:11 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +title: "API Security admin panel"
Similar comments about renaming as mentioned for API Governance

2022-09-05 15:15 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +* **API testing** - Postman applies governance rules to your [API requests](https://learning.postman.com/docs/api-governance/api-testing/api-testing-warnings/) and shows warnings about issues that mi
Let's rename these to `API Definition` and `Requests` since we use the same terminology in the product here : https://cooper.postman-beta.co/api-security

2022-09-05 15:15 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +* **API design** - Postman applies governance rules to your [API definition](/docs/designing-and-developing-your-api/defining-an-api/) and shows warnings about your definition's format and security p
Let's ensure that for API definitions, we call that Postman highlights `Rule violations`

2022-09-05 15:17 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +* **API testing** - Postman applies governance rules to your [API requests](https://learning.postman.com/docs/api-governance/api-testing/api-testing-warnings/) and shows warnings about issues that mi
Lets say something like - Postman applies security rules configured for Requests whenever requests to any API is sent using Postman either via Postman Web or using the Postman Desktop app.

2022-09-05 15:18 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +The _API Security admin panel_ enables you to customize the rules that Postman applies to your API at both the design phase and the testing phase of API development:
instead of saying at the API design and testing phase, let's stick to using `API definitions` and `Requests` as this is the terminology used in the product.

2022-09-05 15:19 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +
Similar comments as that mentioned in API Governance.
Please note that there will be no import from library flow - so will have to adapt the content here accordingly.

@HeatherStenson please work with @chinmayjoshi and @savageCoder55 in order to get the IA for this finalized - in a similar vein as what I've mentioned before.

2022-09-05 15:20 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +## Creating custom security rules
Similar comments as the custom rules for API Governance part.

2022-09-05 15:21 UTC, savageCoder55 requested changes
Added a few things that I feel we could do with. Please feel free to discuss this over a call synchronously as well.

Additionally requesting @chinmayjoshi and @arno-di-loreto to add their thoughts in the places I've tagged them.

2022-09-06 09:32 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-security-admin-panel.md
> +
I would suggest that we go ahead with the following IA.

- How to navigate to the configured rules page
-- API definition
--- Adding rules to your Security configuration
---- Pre-configured rules that are enabled by default
---- Add custom rules (where we talk a bit more about Spectral)
--- Enable/Disable the configured rules (can enable/disable any rule either pre-configured or custom)
--- Removing rules from your Governance configuration (people can only remove the custom rules that have been added)
-- Requests
--- Pre-configured rules that are enabled by default
--- Enable/Disable the configured rules

2022-09-06 09:33 UTC, savageCoder55 reviewed
Added one more comment

2022-09-08 21:10 UTC, HeatherStenson commented on src/pages/docs/api-governance/configuring-api-governance-rules.md
> +### Adding custom rules
[@chinmayjoshi](https://github.com/chinmayjoshi) and [@arno-di-loreto](https://github.com/arno-di-loreto) can you please help me with this section per @savageCoder55's  comment here: https://github.com/postmanlabs/postman-docs/pull/4243#discussion_r962997229

2022-09-08 21:12 UTC, HeatherStenson commented on src/pages/docs/api-governance/configuring-api-security-rules.md
> +### Adding custom rules
@chinmayjoshi and @arno-di-loreto can you please help me with this section too (ref #4243 (comment))

2022-09-13 18:05 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-governance-overview.md
> +title: "API Governance and API Security at Postman"
```suggestion
title: "API Governance and API Security in Postman"
```

2022-09-14 04:04 UTC, HeatherStenson commented on src/components/LeftNav/LeftNavItems.jsx
> +      },
@savageCoder55 I made some path changes to account for the new Spectral page. The new URLs for the configuration pages will be in a subsection called "Configurable rules":

- https://learning.postman.com/docs/api-governance/configurable-rules/configuring-api-governance-rules/
- https://learning.postman.com/docs/api-governance/configurable-rules/configuring-api-security-rules/

The URL for the Spectral rules page will also be in the "Configurable rules" subsection:

- https://learning.postman.com/docs/api-governance/configurable-rules/spectral/

2022-09-14 04:06 UTC, HeatherStenson commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +title: "Using Spectral in Postman"
@savageCoder55 @arno-di-loreto @chinmayjoshi This is the new Spectral page, based on Arnaud's draft. Please take a look!

@MatthewPinsker-postman and/or @jkonrath-postman if you could also take a look from a TW perspective I'd appreciate it 🙏

2022-09-14 08:31 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> +> Only Team Admins with a [Developer role](/docs/collaborating-in-postman/roles-and-permissions/#team-roles) can create custom API Governance rules.
This is true even for importing from Postman library

2022-09-14 08:32 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> +To remove an API Governance rule, select the delete icon <img alt="Delete icon" src="https://assets.postman.com/postman-docs/icon-delete-v9.jpg#icon" width="12px"> next to its name. You can re-import
Let's add that if you delete a custom rule, you need to re-create the same using "Create New Rule"<link to the prev section>

2022-09-14 08:35 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/configuring-api-security-rules.md
> +Postman applies security rules to your [API definition](/docs/api-governance/api-definition/api-definition-warnings/) and shows warnings about issues that might impact your definition's security post
please replace warnings with violations

2022-09-14 08:40 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +[Team Admins](/docs/collaborating-in-postman/roles-and-permissions/) can define rules according to Spectral guidelines, then import them into Postman as custom rules.
Let's just link back to the create rule pages in API Governance and API Security sections.
This would be cleaner in my opinion.

Just a thought.

2022-09-14 08:41 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +Spectral is a linter that checks whether a JSON or YAML document conforms to a set of defined rules. It's used to check that the APIs defined in OpenAPI documents conform to API design guidelines spe
This first sentence I believe is not needed - we cover this in the intro to this page as well.

2022-09-14 08:44 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +Spectral is a linter that checks whether a JSON or YAML document conforms to a set of defined rules. It's used to check that the APIs defined in OpenAPI documents conform to API design guidelines spe
instead of `API design guidelines specified in the context of API governance policies` I'd suggest replacing with `API design guidelines against a set of rules`

2022-09-14 08:45 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +Whether it's created within Postman or imported from another source, a Spectral document needs to contain the following properties:
at the end, let's say that `a Spectral document needs to contain the properties as shown in the example below`

2022-09-14 08:55 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +`description` | An optional description of the rule. It will be shown in the API governance settings you provide one.
instead of `API Governance settings` let's say the `Configurable rules page for either API Governance or API Security`

2022-09-14 08:57 UTC, savageCoder55 reviewed
Reviewed and added some suggestions

2022-09-14 16:43 UTC, HeatherStenson commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> +> Only Team Admins with a [Developer role](/docs/collaborating-in-postman/roles-and-permissions/#team-roles) can create custom API Governance rules.
Thanks - adding a note to that effect in the library section.

2022-09-14 20:59 UTC, MatthewPinsker-postman commented on src/components/LeftNav/LeftNavItems.jsx
> +        ]
I think you're missing a comma here.

2022-09-14 21:00 UTC, MatthewPinsker-postman commented on src/components/LeftNav/LeftNavItems.jsx
> +            url: '/docs/api-governance/configurable-rules/configurable-rules-overview/'
Looking at other examples in this file, I think were missing ending commas on lines 648, 652, 656, and 660.

2022-09-14 21:07 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +    * [Building and testing JSON Path Plus expressions](building-and-testing-json-path-plus-expressions)
```suggestion
    * [Building and testing JSON Path Plus expressions](#building-and-testing-json-path-plus-expressions)
```

2022-09-14 21:09 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +A Spectral rule targets a given location using a [JSON Path Plus expression](#json-path-and-json-path-plus), then tests the values it finds with a `function`. It returns an error if the values don't
Does function need to be formatted as an inline code block?

2022-09-14 21:12 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +First, the rule targets the `title` property of the `info` object located at the root (`$`) of the document with the [JSON Path Plus expression](#json-path-and-json-path-plus) `$.info.title`. In `the
```suggestion
First, the rule targets the `title` property of the `info` object located at the root (`$`) of the document with the [JSON Path Plus expression](#json-path-and-json-path-plus) `$.info.title`. In `then`, the function named `pattern` checks whether the value of the `title` property doesn't match (`functionOptions.notMatch`) the regular expression looking for the word "api" in any case (`/\b(api)\b/i`).
```

2022-09-14 21:16 UTC, jkonrath-postman approved these changes
LGTM

2022-09-14 21:18 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +> Don't forget to turn on your custom rules after you create or import them!
It's my understanding that we typically avoid exclamation points. Also, instead of "Don't forget", how about "Remember"? To me, this is easier to scan.

**Proposal:**
`Remember to turn on your custom rules after you create or import them.`

2022-09-14 21:21 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +`severity` | The severity of the problem detected by the rule. The possible values are `error`, `warn` (default), `info`, and `hint`. These values can be used as follows: <br><ul><li>`error` - An obv
```suggestion
`severity` | The severity of the problem detected by the rule. The possible values are `error`, `warn` (default), `info`, and `hint`. These values can be used as follows: <br><ul><li>`error` - An obvious error that must be fixed. Something is going against guidelines.</li><li>`warn` - A possible error. If it's an error, it must be fixed. Some deviation on specific rules may be tolerated, like a `POST` without a body.</li><li>`info` - Something that could possibly be improved. An optional pattern defined in the guidelines could be applied.</li><li>`hint` - Something to be discussed during an API design review.</li></ul>
```

2022-09-14 21:23 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +`then` | **Required**. This can be a list with at least one element or a single element. If the given JSON Path Plus expressions return values, the functions will be applied to all of them.
Should "JSON Path Plus expressions" also include an anchor link to the section? I'm asking because it looks like we're doing that in other rows.

2022-09-14 21:30 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +* `$.paths.*[post,patch,put]` - All POST, PATCH, and PUT operations across all `paths`. `[ ]` can be used to filter elements.
```suggestion
* `$.paths.*[post,patch,put]` - All `POST`, `PATCH`, and `PUT` operations across all `paths`. `[ ]` can be used to filter elements.
```

2022-09-14 21:32 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +title: "Using Spectral in Postman"
@HeatherStenson Looks good to me! I added a few proposed changes.

2022-09-14 21:32 UTC, HeatherStenson commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +> Don't forget to turn on your custom rules after you create or import them!
```suggestion
> Remember to turn on your custom rules after you create or import them.
```

2022-09-14 21:33 UTC, HeatherStenson commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +`then` | **Required**. This can be a list with at least one element or a single element. If the given JSON Path Plus expressions return values, the functions will be applied to all of them.
```suggestion
`then` | **Required**. This can be a list with at least one element or a single element. If the given [JSON Path Plus expressions](#json-path-and-json-path-plus) return values, the functions will be applied to all of them.
```

2022-09-14 21:35 UTC, HeatherStenson commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +A Spectral rule targets a given location using a [JSON Path Plus expression](#json-path-and-json-path-plus), then tests the values it finds with a `function`. It returns an error if the values don't
Double-checked and yep, it's supposed to be. Which I missed on line 37!

2022-09-14 21:36 UTC, HeatherStenson commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +First, the rule targets the `title` property of the `info` object located at the root (`$`) of the document with the [JSON Path Plus expression](#json-path-and-json-path-plus) `$.info.title`. In `the
```suggestion
First, the rule targets the `title` property of the `info` object located at the root (`$`) of the document with the [JSON Path Plus expression](#json-path-and-json-path-plus) `$.info.title`. In `then`, the `function` named `pattern` checks whether the value of the `title` property doesn't match (`functionOptions.notMatch`) the regular expression looking for the word "api" in any case (`/\b(api)\b/i`).
```

2022-09-14 21:44 UTC, HeatherStenson commented on src/pages/docs/api-governance/configurable-rules/spectral.md
> +title: "Using Spectral in Postman"
Thank you!!!

2022-09-14 21:45 UTC, HeatherStenson commented on src/components/LeftNav/LeftNavItems.jsx
> +            url: '/docs/api-governance/configurable-rules/configurable-rules-overview/'
Sure was! Thank you for catching this. It doesn't seem to cause any problems with building but just in case 😬

2022-09-14 21:45 UTC, merged

2022-09-15 07:15 UTC, savageCoder55 reviewed
LGTM