TW-227 gRPC
postmanlabs/postman-docs pull request #4244
Opened 2022-08-26 15:34 UTC by jkonrath-postman

2022-08-26 16:00 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/first-grpc-request.md
> +* **Server streaming** - The client needs to make a single request for the server to respond back with a stream of messages.
Same feedback/thought as line 22.

2022-08-26 16:05 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/first-grpc-request.md
> +This example will create and execute a unary request. To learn about invoking the other method types, see [Using the gRPC request interface](/docs/sending-requests/grpc/grpc-request-interface/).
What is the example that will create/execute a unary request?

If this is referring to the following section, what do you think about moving this line to the "Creating and invoking a request" section?

2022-08-26 16:07 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/first-grpc-request.md
> +> If you are using Postman for Web, you must use the Postman Desktop Agent. See [Using the Postman web app](/docs/getting-started/installation-and-updates/#using-the-postman-web-app) for more informa
Instead of "Postman for Web", should this be "the Postman web app"?

2022-08-26 16:08 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/first-grpc-request.md
> +1. In Postman, select  __New__ &gt; __gRPC Request__ to open a request in a new tab. (In the Postman desktop app, you can also select **⌘+N** or **Ctrl+N**, then select __gRPC Request__)
```suggestion
1. In Postman, select  __New__ &gt; __gRPC Request__ to open a request in a new tab. (In the Postman desktop app, you can also select **⌘+N** or **Ctrl+N**, then select __gRPC Request__.)
```

2022-08-26 16:13 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/first-grpc-request.md
> +1. Replace the sample string data with **Your name** and select **Invoke**.
Does "Your name" need to be in bold? I'm asking because it seems like we expect users to enter their actual name.

I'm wondering if we could update this step to something like: `Replace the sample string data with your name and select **Invoke**.`

2022-08-26 16:14 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/first-grpc-request.md
> +Once the method is invoked, the server processes the information passed and gives back a response.
Same feedback/thought as line 22.

2022-08-26 16:19 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-client-overview.md
> +
Should we include a "Contents" section?

2022-08-26 16:24 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-client-overview.md
> +contextual_links:
For lines 13 and 16, should the case we use here match the case used in the resource?

I'm asking because we are using sentence case, but the blog titles are in title case. I recall seeing other examples where we match the case.

2022-08-26 16:27 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +* [The response section](#response)
```suggestion
* [The response section](#the-response-section)
```

2022-08-26 16:33 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +Create a new gRPC request by selecting the **New** button in the left sidebar which brings up the ‘Create new’ modal. Select gRPC request from the list to open a blank **gRPC request** in a new tab.
In other examples in our docs, it looks like modal names should be bold.

2022-08-26 16:40 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +    * **Authorization** - Pass credentials that the server would use to authorize the connection here. You can choose from a list of Auth types including API Key, Basic auth, and Bearer token. Learn
Should "Auth" be capitalized in the context of `You can choose from a list of Auth types...`?

I'm asking because it looks like "auth" is typically written in lowercase in our docs.

2022-08-26 16:42 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +    * **Metadata** - Pass additional metadata along with the request in the form of key-value pairs. Metadata is used by the client to provide more information about the call to the server.
To write the second sentence using active voice, what do you think about the following change?

`The client uses metadata to provide more information about the call to the server.`

2022-08-26 16:49 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +* **TLS Toggle** - Unlike HTTP which defines if the call is going to be executed over a secured or unsecured connection using the URL structure (`http://` for unsecured, `https://` for secured), with
Should the icon name be lowercase? I'm asking because it looks like we are making icon names lowercase in other examples.

2022-08-26 16:54 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +To invoke a unary request, select the method from the **Method selection dropdown**, add the details and select **Invoke**. The server processes the sent information and gives back a response.
```suggestion
To invoke a unary request, select the method from the **Method selection** dropdown, add the details and select **Invoke**. The server processes the sent information and gives back a response.
```

2022-08-26 16:55 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +To invoke a client streaming method, select the method from the **Method selection dropdown**, enter the details and select **Invoke**. This puts gRPC requests in a persistent ‘Streaming' state where
```suggestion
To invoke a client streaming method, select the method from the **Method selection** dropdown, enter the details and select **Invoke**. This puts gRPC requests in a persistent ‘Streaming' state where you can send multiple messages and once you’re done, select **End streaming**. The server then processes all the information passed and gives back a response.
```

2022-08-26 17:01 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +To invoke a client streaming method, select the method from the **Method selection dropdown**, enter the details and select **Invoke**. This puts gRPC requests in a persistent ‘Streaming' state where
It looks like the opening apostrophe before "Streaming" displays different from the ending apostrophe.

Also, should "Streaming" be surrounded by double quotation marks instead of single? I'm asking because on line 62 "beta" is used in a similar way, but the word is surrounded by double quotation marks.

2022-08-26 17:02 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +To invoke a server streaming method, select the method from the **Method selection dropdown**, enter the details, and select **Invoke**. The request goes into a persistent 'Streaming' state and the r
```suggestion
To invoke a server streaming method, select the method from the **Method selection** dropdown, enter the details, and select **Invoke**. The request goes into a persistent 'Streaming' state and the responses from the server start appearing at the bottom in the response area. Depending on the use case, the stream closes automatically after the server has streamed all the messages. You can manually end the stream by selecting **Cancel** next to the **URL bar**.
```

2022-08-26 17:04 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +    * **Metadata(Initial) and Trailing metadata** - Metadata returned by the server typically consists of additional information about the execution.
```suggestion
    * **Metadata (Initial) and Trailing metadata** - Metadata returned by the server typically consists of additional information about the execution.
```

2022-08-26 17:06 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +* **Additional information** - This section provides you with key information regarding performance and if the execution was successful. You can assess the performance of the API using the informatio
```suggestion
* **Additional information** - This section provides you with key information regarding performance and if the execution was successful. You can assess the performance of the API using the information on how long the execution took. The status code gives you information explaining whether the execution was successful. The status code `0 OK` signifies successful execution. In case of an error, a gRPC-based implementation returns different status codes for different error scenarios which help you understand the cause and figure out the next set of actions by hovering on it.
```

2022-08-26 17:08 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +* **Search through response** - Look for specific things within the response using the 'Search' button.
```suggestion
* **Search through response** - Look for specific things within the response using the **Search** button.
```

2022-08-26 17:09 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +* **Multiple responses** - While invoking a streaming method type (client streaming, server streaming or bidirectional streaming), the client-server communication within a single session is recorded
```suggestion
* **Multiple responses** - While invoking a streaming method type (client streaming, server streaming, or bidirectional streaming), the client-server communication within a single session is recorded in the response area as a series of sent and received messages in a timeline instead of a single response.
```

2022-08-26 17:10 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +    * **Message filter** - Adjust the view based on the type of messages using the message filter. Instead of all messages, you can choose to view only the ones Sent from the client or Received from
```suggestion
    * **Message filter** - Adjust the view based on the type of messages using the message filter. Instead of all messages, you can choose to view only the ones sent from the client or received from the server.
```

2022-08-26 17:18 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +    * **Clear messages** - Using the ‘Clear messages' button hides all the messages exchanged from the view to clean up the response area so that you can focus on the new messages. You can restore th
```suggestion
    * **Clear messages** - The **Clear messages** button hides all exchanged messaged from the view, cleaning up the response area so you can focus on new messages. You can restore the messages using the **Restore** button in the hidden view.
```

2022-08-26 17:20 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +* **Test results** - The results for assertions you write in the Scripts section appear here. Based on the test script, the results can be one of three types: Passed, Failed, and Skipped. Learn more
Are the result types similar to status codes? I'm asking because we typically format status codes in inline code blocks.

2022-08-26 17:21 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +The sidebar gives you access to additional tools and information like documentation, commenting and meta information on the request.
```suggestion
The sidebar gives you access to additional tools and information like documentation, commenting, and meta information on the request.
```

2022-08-26 17:23 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +* **Request documentation** - Use the documentation pane to write documentation of your request to make it easier for others to consume it. When you select a method, Postman automatically generates d
```suggestion
* **Request documentation** - Use the documentation pane to write documentation for your request, making it easier for others to consume it. When you select a method, Postman automatically generates documentation for the payload fields and data types using the Protobuf definition. You can add additional descriptions using Markdown to make it better.
```

2022-08-26 17:31 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/scripting-in-grpc-request.md
> +To learn more about writing tests, see [writing tests](/docs/writing-scripts/test-scripts.md).
```suggestion
To learn more about writing tests, see [writing tests](/docs/writing-scripts/test-scripts/).
```

2022-08-26 17:34 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/test-examples.md
> +    url: "/docs/sending-requests/grpc/writing-tests/"
This page does not seem to exist. Is this URL supposed to point to `/docs/writing-scripts/test-scripts/`?

2022-08-26 17:39 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/test-examples.md
> +You can also assert the same using the [pm.expect](/docs/sending-requests/grpc/postman-sandbox-api/#pmexpect) method
```suggestion
You can also assert the same using the [pm.expect](/docs/sending-requests/grpc/postman-sandbox-api/#pmexpect) method.
```

2022-08-26 17:48 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/test-examples.md
> +In case of multiple response messages (request with the server or bidirectional streaming method), the below tests will check all the messages for the given assertion. For a request with unary or cli
What do we mean by an assertion will be "done on" something? I'm wondering if there is a clearer word we can use here like "tested", "executed", or something else. My concern is that folks reading in a second language might find "done on" difficult to understand.

2022-08-26 17:49 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/test-examples.md
> +The below assertions can done on request messages as well using `pm.request` object.
Same feedback/thought as line 117.

Also, we are missing the word "be" before "done on request messages...".

2022-08-26 17:51 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/test-examples.md
> +> By default, pm.response.messages.to.include() has `.deep` applied to it.
```suggestion
> By default, `pm.response.messages.to.include()` has `.deep` applied to it.
```

2022-08-26 17:53 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/understanding-grpc-types.md
> +When sending or receiving a gRPC request or response, the messages being sent back and forth are transmitted in a format called [Protocol Buffers](https://developers.google.com/protocol-buffers) (als
```suggestion
When sending or receiving a gRPC request or response, the messages being sent back and forth are transmitted in a format called [Protocol Buffers](https://developers.google.com/protocol-buffers) (also called "protobuf" or "proto"). Unlike other data formats such as JSON or XML, which are text-based, Protocol Buffers use a _binary format_. Binary formats aren't meant to be read by humans, so Postman provides a **JSON interface** that enables you to read and write data when using gRPC.
```

2022-08-26 17:54 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/understanding-grpc-types.md
> +When sending or receiving a gRPC request or response, the messages being sent back and forth are transmitted in a format called [Protocol Buffers](https://developers.google.com/protocol-buffers) (als
According to the style guide, we should avoid terms like "easy" and "simply".

2022-08-26 17:56 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/understanding-grpc-types.md
> +
Should we add a "Contents" section?

2022-08-26 17:58 UTC, MatthewPinsker-postman commented on src/components/LeftNav/LeftNavItems.jsx
> +        name: 'Using gRPC Requests',
The `/docs/sending-requests/grpc/using-grpc-mock/` topic is missing from the left navigation menu. Is this intentional?

2022-08-26 19:13 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-mock.md
> +1. Create a new gRPC request. See [Creating a new request](s/docs/sending-requests/grpc/grpc-request-interface/#creating-a-new-request) for more information.
```suggestion
1. Create a new gRPC request. See [Creating a new request](/docs/sending-requests/grpc/grpc-request-interface/#creating-a-new-request) for more information.
```

2022-08-26 19:15 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-mock.md
> +    * **Use an API from this workspace** - select an existing protobuf API in the current workspace.
```suggestion
    * **Use an API from this workspace** - Select an existing protobuf API in the current workspace.
```

2022-08-26 19:15 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-mock.md
> +    * **Import a .proto file** - add a new protobuf API from a `.proto` file.
```suggestion
    * **Import a .proto file** - Add a new protobuf API from a `.proto` file.
```

2022-08-26 19:15 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-mock.md
> +    * **Create a new API** - open the Postman API Builder and create a new protobuf API.
```suggestion
    * **Create a new API** - Open the Postman API Builder and create a new protobuf API.
```

2022-08-26 19:18 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-mock.md
> +1. In the **Metadata** pane of the response, find the value of the key-value pair named 'seed'.
According to the style guide, periods and commands should appear in quotation marks. Should we apply that guideline in this instance?

2022-08-26 19:19 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-mock.md
> +The mock servers in gPRC are independent of the mock server feature in Postman. See [setting up mock servers](/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md) for more informa
```suggestion
The mock servers in gPRC are independent of the mock server feature in Postman. See [setting up mock servers](/docs/designing-and-developing-your-api/mocking-data/setting-up-mock/) for more information about using mock servers for your other APIs.
```

2022-08-26 19:26 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/using-service-definition.md
> +gRPC uses [Protocol Buffers (protobuf)](https://developers.google.com/protocol-buffers/docs/overview) as the Interface Definition Language (IDL) to define the service definition. While creating a gRP
```suggestion
gRPC uses [Protocol Buffers (protobuf)](https://developers.google.com/protocol-buffers/docs/overview) as the Interface Definition Language (IDL) to define the service definition. While creating a gRPC request, you will need to add the appropriate service definition to the request in order to choose a method that you want to invoke. You can configure the service definition by heading to the **Service definition** tab in a gRPC request.
```

2022-08-26 19:28 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/using-service-definition.md
> +While creating a new request, if the service definition isn't configured, Postman prompts you to configure it when you select the Method selection dropdown. This interface serves as a quick way to ad
```suggestion
While creating a new request, if the service definition isn't configured, Postman prompts you to configure it when you select the **Method selection** dropdown. This interface serves as a quick way to add your service definition and move on to invoking your request. From this menu, you can select a protobuf API available in your workspace or import a new one by dragging a `.proto` file from your local system and dropping it into Postman.
```

2022-08-26 19:30 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/using-service-definition.md
> +Go to the **Service definition tab** and select **Select a protobuf API from this workspace**. This opens the **API selection dropdown** where you can browse through the available APIs and select the
```suggestion
Go to the **Service definition** tab and select **Select a protobuf API from this workspace**. This opens the **API selection** dropdown where you can browse through the available APIs and select the one you want to use.
```

2022-08-26 19:31 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/using-service-definition.md
> +While testing the services, you can also switch to a different version of the selected API by selecting the Version selector next to the API name.
```suggestion
While testing the services, you can also switch to a different version of the selected API by selecting the **Version** selector next to the API name.
```

2022-08-26 19:31 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/using-service-definition.md
> +1. Go to the **Service definition tab** and select **Import a .proto file**.
```suggestion
1. Go to the **Service definition** tab and select **Import a .proto file**.
```

2022-08-26 19:33 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/using-service-definition.md
> +Go to the **Service definition tab** and select **Create a new API**. This brings up the create new API flow where you will have to name the new API and the version and select the type of API you wan
```suggestion
Go to the **Service definition** tab and select **Create a new API**. This brings up the create new API flow where you will have to name the new API and the version and select the type of API you want to create. Postman supports creating a protobuf API in _protobuf 2_ and _protobuf 3_. Once you’re done, select **Create new API**. This opens the API in the Postman API Builder in a new tab.
```

2022-08-26 19:37 UTC, MatthewPinsker-postman commented on src/pages/docs/writing-scripts/test-scripts.md
> +3. Use [snippets](#using-snippets) from the right panel to add a test or [write customized assertions](#writing-your-assertions).
It looks like "write customized assertions" points to a section that doesn't exist.

2022-08-26 19:38 UTC, MatthewPinsker-postman commented on src/pages/docs/writing-scripts/test-scripts.md
> +Both the execution hooks are available for all gRPC requests irrespective of the method type being unary, client streaming, server streaming, or bidirectional streaming. Your scripts can include howe
```suggestion
Both the execution hooks are available for all gRPC requests regardless of the method type being unary, client streaming, server streaming, or bidirectional streaming. Your scripts can include however many tests you need and will save along with the rest of your request when you select **Save**.
```

2022-08-26 19:39 UTC, MatthewPinsker-postman commented on src/pages/docs/writing-scripts/test-scripts.md
> +Both the execution hooks are available for all gRPC requests irrespective of the method type being unary, client streaming, server streaming, or bidirectional streaming. Your scripts can include howe
I'm proposing this change because I'm concerned that "irrespective" might increase the readability level.

2022-08-26 20:26 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/grpc/postman-sandbox-api.md
> +    * `timestamp`: time at which the message was sent (<a href='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date' target='_blank'>Date</a>) object).
Is " object)" at the end of the sentence an intentional addition?

2022-08-26 20:29 UTC, petewitcher commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +The server URL is used to define the endpoint where the service is hosted. Being a protocol of its own, a gRPC URL often starts with `grpc://` instead of `http://` or `https://`. While creating a new
I'd change `in creating` to `create`. Also `testing out` to `testing`.

2022-08-26 20:33 UTC, MatthewPinsker-postman approved these changes
I added some questions and proposed changes. Otherwise, it looks good to me!

2022-08-26 21:09 UTC, petewitcher commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +* **Server URL** - Defines the endpoint where the service is hosted. A gRPC URL often starts with `grpc://` instead of `http://` or `https://`. While creating a new request, you can also browse throu
I'd change 'in creating' to 'create' and 'testing out' to 'testing'.

2022-08-26 21:11 UTC, petewitcher commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +
I'd change 'along with' to 'with'.

2022-08-26 21:25 UTC, petewitcher commented on src/pages/docs/sending-requests/grpc/postman-sandbox-api.md
> +* The package, service and method name in the format `packageName.serviceName.methodName`:
```suggestion
* The package, service, and method name in the format `packageName.serviceName.methodName`:
```

2022-08-26 21:29 UTC, petewitcher commented on src/pages/docs/sending-requests/grpc/postman-sandbox-api.md
> +  You can also include multiple assertions to group the related ones in a single test.
```suggestion
  You can also include multiple assertions to group the related ones in a single test:
```

2022-08-29 14:52 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/grpc/understanding-grpc-types.md
> +
We can skip because there are only two H2s.

2022-08-29 21:49 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +* **Test results** - The results for assertions you write in the Scripts section appear here. Based on the test script, the results can be one of three types: Passed, Failed, and Skipped. Learn more
No codes, just text.

2022-09-02 14:17 UTC, SterlingChin commented on src/pages/docs/sending-requests/grpc/grpc-client-overview.md
> +- [Working with service definitions](/docs/sending-requests/grpc/using-service-definition/)
To keep it consistent with the left nav bar:
```suggestion
- [Using the gRPC request interface](/docs/sending-requests/grpc/grpc-request-interface/)
- [Invoking your first gRPC request](/docs/sending-requests/grpc/first-grpc-request/)
- [Working with service definitions](/docs/sending-requests/grpc/using-service-definition/)
```
![Screen Shot 2022-09-02 at 9 10 50 AM](https://user-images.githubusercontent.com/8900638/188168797-92f33cd4-5f07-4867-8159-d6fe47d224be.png)

2022-09-02 15:27 UTC, SterlingChin commented on src/pages/docs/sending-requests/grpc/first-grpc-request.md
> +1. Enter the URL as: `grpc://grpcb.in:9000`. This is an echo endpoint that enables you to try out various types of services and methods.
We are working on a postman-echo service for gRPC that will replace this end-point with one that is built in-house. This will be done sometime next week.

2022-09-02 15:27 UTC, SterlingChin commented on src/pages/docs/sending-requests/grpc/first-grpc-request.md
> +
Similar to other comments, can we add a `.gif` or video here to provide additional direction?

2022-09-02 21:36 UTC, SterlingChin requested changes
Amazing work on these docs! Thank you so much!

I've added some comments and suggested changes. Feel free to reach out with any questions you may have.

2022-09-02 21:36 UTC, SterlingChin commented on src/pages/docs/sending-requests/grpc/using-service-definition.md
> +If server reflection isn't enabled by the server, you can use a protobuf API as a service definition for the request. For this, you can either select an existing protobuf API in your workspace or imp
```suggestion
If server reflection isn't enabled by the server, you can use a protobuf API as a service definition for the request. For this, you can either select an existing protobuf API in your workspace or import a `.proto` file as a protobuf API into Postman. You can also create a new protobuf API using the Postman API Builder.
```

2022-09-02 21:36 UTC, SterlingChin commented on src/pages/docs/sending-requests/grpc/using-service-definition.md
> +1. Give your new API a name, add a version name, and select Import as an API.
```suggestion
1. Give your new API a name, add a version name, and select **Import as API**.
```

2022-09-02 21:36 UTC, SterlingChin commented on src/pages/docs/sending-requests/grpc/using-service-definition.md
> +<img src="https://assets.postman.com/postman-labs-docs/grpc-docs/using-service-definition/adding-import-paths.gif" alt="Adding import paths">
This user interaction is likely to change before V10 and will need an updated `.gif` and explanation.

2022-09-02 21:36 UTC, SterlingChin commented on src/pages/docs/sending-requests/grpc/using-service-definition.md
> +Go to the **Service definition** tab and select **Create a new API**. This brings up the create new API flow where you will have to name the new API and the version and select the type of API you wan
```suggestion
Go to the **Service definition** tab and select **Create New API**. This brings up the create new API flow where you will have to name the new API and the version and select the type of API you want to create. Postman supports creating a protobuf API in _protobuf 2_ and _protobuf 3_. Once you’re done, select **Create New API**. This opens the API in the Postman API Builder in a new tab.
```

2022-09-02 21:36 UTC, SterlingChin commented on src/pages/docs/sending-requests/grpc/using-grpc-mock.md
> +1. Create a new gRPC request. See [Creating a new request](/docs/sending-requests/grpc/grpc-request-interface/#creating-a-new-request) for more information.
Thoughts?
```suggestion
1. Create a new gRPC request. (See [Creating a new request](/docs/sending-requests/grpc/grpc-request-interface/#creating-a-new-request) for more information)
```

2022-09-02 21:36 UTC, SterlingChin commented on src/pages/docs/sending-requests/grpc/using-grpc-mock.md
> +1. After you have selected an API, select **Enter server URL** again, and select **Use Mock URL**.
We should add something about mock servers automatically being generated.

2022-09-02 21:36 UTC, SterlingChin commented on src/pages/docs/sending-requests/grpc/using-grpc-mock.md
> +To pass seed data:
This section could use either a `.gif` or images to help describe this. I can see this being very confusing for a first time user.

2022-09-06 14:50 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-mock.md
> +1. Create a new gRPC request. See [Creating a new request](/docs/sending-requests/grpc/grpc-request-interface/#creating-a-new-request) for more information.
I'd avoid parents here to keep it conversational.

2022-09-06 20:44 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +Create a new gRPC request by selecting the **New** button in the left sidebar which brings up the **Create new** dialog. Select gRPC request from the list to open a blank **gRPC request** in a new ta
Added a slightly shorter version for this step to only show the new request creation, but not entering the URL or picking a method.

2022-09-06 20:46 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/grpc/first-grpc-request.md
> +1. Enter the URL as: `grpc://grpcb.in:9000`. This is an echo endpoint that enables you to try out various types of services and methods.
Moving this to a subtask so it won't block us.

2022-09-06 21:51 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/grpc/first-grpc-request.md
> +
Let's defer this until we have the new echo service.

2022-09-14 17:28 UTC, SterlingChin approved these changes

2022-09-14 19:25 UTC, merged