TW 634 API definition linting
postmanlabs/postman-docs pull request #4249
Opened 2022-08-29 23:44 UTC by HeatherStenson

This PR _only_ covers the UI for the governance and security warnings for the API definition. This PR will be merged into `tw-603-v10-api-security` once it's approved and ready to go. I'm holding off on screenshots until closer to release date to account for any UI and/or behavior changes.

2022-08-31 14:03 UTC, jkonrath-postman approved these changes
LGTM (with edits) but talk to me about the merge order, because this is a bit of a moving target.

2022-08-31 14:03 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/defining-an-api.md
> +As you create your API definition in the schema editor, Postman automatically lints it using API Governance and API Security rules. If the linter finds any problems, Postman displays warnings below t
I don't know if you want to add a sentence or a part of a sentence saying what exactly linting is. ("Analyzes your code for issues" or something?) I only say this because someone asked in Slack recently what that meant.

2022-08-31 14:03 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/defining-an-api.md
> +As you create your API definition in the schema editor, Postman automatically lints it using API Governance and API Security rules. If the linter finds any problems, Postman displays warnings below t
```suggestion
As you create your API definition in the editor, Postman automatically lints it using API Governance and API Security rules. If the linter finds any problems, Postman displays warnings below the editor.
```

2022-08-31 14:03 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/defining-an-api.md
> +As you create your API definition in the schema editor, Postman automatically lints it using API Governance and API Security rules. If the linter finds any problems, Postman displays warnings below t
I think we're just calling it "editor" now.

2022-08-31 18:55 UTC, HeatherStenson commented
Thanks Jon! Updated per your notes and our convo. I'll watch TW-493 with an eye to minimizing merge woes.

2022-09-06 13:38 UTC, savageCoder55 commented on src/pages/docs/designing-and-developing-your-api/defining-an-api.md
> +## Linting your API definition
Let's stick to using "Rule violations" here.

2022-09-06 13:43 UTC, savageCoder55 commented on src/pages/docs/designing-and-developing-your-api/defining-an-api.md
> +As you create your API definition in the editor, Postman automatically checks it against API Governance and API Security rules using a built-in linter. If the linter finds any problems, Postman displ
Suggestion:
Replace : "Postman automatically checks it against API Governance and API Security rules using a built-in linter. If the linter finds any problems, Postman displays warnings below the editor"
With : "Postman automatically checks it against API Governance and API Security rules configured for your team. Any Rule violations are displayed below the editor, to help you improve your API definition"

Also let's add links to the API Governance and API Security sections of the LC embedded in the text above for the configured rules texts.

2022-09-06 13:45 UTC, savageCoder55 commented on src/pages/docs/designing-and-developing-your-api/defining-an-api.md
> +To see any linting warnings, select **Rule** next to **Violations found in schema**. Postman displays each warning on its own line, with a brief description of the issue, the type of issue (governanc
Let's revamp this line a bit - we should try to not use the keyword "Warnings" and instead replace it with "Rule violations"

2022-09-06 13:48 UTC, savageCoder55 commented on src/pages/docs/designing-and-developing-your-api/defining-an-api.md
> +**API Security** - Postman lints your API definition using a pre-defined set of [security rules](/docs/api-governance/api-testing/api-testing-warnings/).
Since we're not adding "API Governance" and "API Security" as sections to the LC yet, I would suggest that we just add one line saying 
"To learn more about the supported API description formats, pre-configured rules and creating new rules refer to the <API definition> section of <API Security and Governance>"

2022-09-06 13:50 UTC, savageCoder55 commented on src/pages/docs/designing-and-developing-your-api/defining-an-api.md
> +If you want to use the warning later, select **Unhide**. <!-- TODO: find what this actually is - I think it's a message bar that indicates how many rules are hidden? -->
General comment is to replace "Warning" with "Rule violation"

2022-09-06 13:50 UTC, savageCoder55 requested changes
Requested a few small changes.

2022-09-09 18:39 UTC, HeatherStenson commented on src/pages/docs/designing-and-developing-your-api/defining-an-api.md
> +> [This feature is only available to Postman Enterprise teams.](https://www.postman.com/pricing)
```suggestion
> [This feature is only available for Postman Enterprise teams.](https://www.postman.com/pricing)
```

2022-09-09 18:40 UTC, HeatherStenson commented on src/pages/docs/designing-and-developing-your-api/defining-an-api.md
> +> To hide a rule violation globally, you can use either the [configurable API Governance rules](/docs/api-governance/configuring-api-governance-rules/) or the [configurable API Security rules](/docs/
```suggestion
> To hide a rule violation globally, you can use either [configurable API Governance rules](/docs/api-governance/configuring-api-governance-rules/) or [configurable API Security rules](/docs/api-governance/configuring-api-security-rules/) ([Enterprise teams only](https://www.postman.com/pricing/)), depending on the rule type.
```

2022-09-09 18:42 UTC, HeatherStenson commented on src/pages/docs/designing-and-developing-your-api/defining-an-api.md
> +To see any rule violations, select **Rule** next to **Violations found in schema**. Postman displays each rule violation on its own line, with a brief description of the issue, the rule type (governa
```suggestion
To see any rule violations, select **Rule** next to **Violations found in schema**. Postman displays each rule violation on its own line, with a brief description of the issue, the rule type (**Governance** or **Security**), and the line and file the where the rule violation occurs. When you select a rule violations, Postman highlights the section of the definition that triggered it.
```

2022-09-12 22:14 UTC, merged

2022-09-15 06:45 UTC, savageCoder55 commented on src/pages/docs/designing-and-developing-your-api/defining-an-api.md
> +To learn more about the supported API description formats, the rules preconfigured in Postman, and how to create new rules, see [API definition warnings](/docs/api-governance/api-definition/api-defin
Warnings to rule violations

2022-09-15 06:47 UTC, savageCoder55 reviewed
LGTM