TW 545 API Governance and API Security linting with the Postman CLI
postmanlabs/postman-docs pull request #4257
Opened 2022-09-01 22:45 UTC by HeatherStenson

cc @petewitcher for potential collaboration!

2022-09-06 13:25 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
> +* [Viewing governance and security warnings for the API definition](#viewing-governance-and-security-warnings-for-the-API-definition)
Let's rename "Warnings" to "Rule violations"

2022-09-06 13:26 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
> +* [Governance and security linting with the Postman CLI](#governance-and-security-linting-with-the-postman-cli)
I would suggest that we use "Tracking rule violations in CI/CD"

2022-09-06 13:27 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
>  After you [create a new API](/docs/designing-and-developing-your-api/creating-an-api/), select the **Definition** tab on the API version page to inspect the issues found in the API definition, if any
**Warnings** should be **Rule violations**

2022-09-06 13:33 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-testing/api-testing-warnings.md
>  <img alt="Viewing security warnings in the right sidebar" src="https://assets.postman.com/postman-docs/api-governance-testing-warnings-beta.jpg" width="400px"/>
We need to update this asset with the latest UI changes

2022-09-06 13:35 UTC, savageCoder55 requested changes
Requested a couple changes. Nothing too drastic

2022-09-06 13:53 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
> +* [Governance and security linting with the Postman CLI](#governance-and-security-linting-with-the-postman-cli)
I'm not sure if this section of the LC will be updated to also market the Postman CLI tooling as well: https://learning.postman.com/docs/designing-and-developing-your-api/testing-an-api/#adding-ci-integration

@HeatherStenson can we please check with technical writers working with Runtime about this ⬆️ ?

2022-09-06 15:26 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
>  After you [create a new API](/docs/designing-and-developing-your-api/creating-an-api/), select the **Definition** tab on the API version page to inspect the issues found in the API definition, if any
Also @HeatherStenson wanted your thoughts on keeping this particular content here. We're already adding content to the "creating an API" page in the LC using this PR : https://github.com/postmanlabs/postman-docs/pull/4249/files

So wanted to understand if we're okay with the content duplication.
If yes, then we should add the hide feature over here as well - let's discuss this once as well in a call.

2022-09-09 20:33 UTC, HeatherStenson commented
@MatthewPinsker-postman and/or @jkonrath-postman ready for you to take a look at this one!

2022-09-09 20:39 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
> +* [Viewing governance and security rule violations in the API definition](#viewing-governance-and-security-rule-violations-in-the-API-definition)
```suggestion
* [Viewing governance and security rule violations in the API definition](#viewing-governance-and-security-rule-violations-in-the-api-definition)
```

2022-09-09 20:40 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
> +* [Viewing governance and security rule violations in the API definition](#viewing-governance-and-security-rule-violations-in-the-API-definition)
The all caps seems to prevent the anchor link from working as expected.

2022-09-09 20:52 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
> +After you [create a new API](/docs/designing-and-developing-your-api/creating-an-api/), select the **Definition** tab on the API overview page to inspect any API Governance or API Security rule viola
With the new changes to API Builder, it's my understanding that we removed the **Definition** tab. To open the API definition file, it's my understanding that you:

1. Select **APIs** in the sidebar, and then select an API.
2. Under **Definition**, select **View files** on the API overview page.

2022-09-09 20:55 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
> +> [The Postman CLI is only available to Postman Enterprise teams.](https://www.postman.com/pricing)
@jkonrath-postman Do we mention this in the Postman CLI docs?

2022-09-09 21:16 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
> +To see the results, go to the build page and select the desired build. Next, select the API definition to expand it and see the build’s results and any rule violations, if applicable.
To clarify, when you expand a build, will there be a nested expandable section where users can expand the API definition? I'm wondering if this will be similar to **Collection Runs** at https://learning.postman.com/docs/integrations/available-integrations/ci-integrations/gitlab-ci/#viewing-collection-run-details

2022-09-09 21:17 UTC, MatthewPinsker-postman approved these changes
Looks good to me! I added a few suggestions and questions. Thanks!

2022-09-09 21:55 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
> +* [Viewing governance and security rule violations in the API definition](#viewing-governance-and-security-rule-violations-in-the-API-definition)
Sure does! 🤦  Thanks for catching

2022-09-09 21:57 UTC, jkonrath-postman approved these changes
LGTM pending that CLI enterprise bit

2022-09-09 21:57 UTC, jkonrath-postman commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
> +> [The Postman CLI is only available to Postman Enterprise teams.](https://www.postman.com/pricing)
@HeatherStenson The Postman CLI is available to all plans, but the governance/security feature is not. Change this note to reflect that and look if anything similar's mentioned in your PRs. I'll look in the CLI to add a note there.

2022-09-09 21:57 UTC, jkonrath-postman commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
> +* [Governance and security linting with the Postman CLI](#governance-and-security-linting-with-the-postman-cli)
@savageCoder55 The individual CI integration pages and the overview CI integration page is being changed to show how to use PCLI instead of Newman, and there will be a separate page in the PCLI doc covering generically how to use it for CI.

2022-09-09 21:57 UTC, jkonrath-postman commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
> +After you [create a new API](/docs/designing-and-developing-your-api/creating-an-api/), select the **Definition** tab on the API overview page to inspect any API Governance or API Security rule viola
You can do that, or just open an API and then drill through the hierarchy in the left sidebar and open up a file.

2022-09-09 21:58 UTC, HeatherStenson commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
> +> [The Postman CLI is only available to Postman Enterprise teams.](https://www.postman.com/pricing)
My bad - it's not the CLI that's Enterprise-only, just this feature. Updating the note accordingly.

2022-09-09 22:14 UTC, HeatherStenson commented
Ty @jkonrath-postman and @MatthewPinsker-postman! Updated.

2022-09-12 22:13 UTC, merged

2022-09-15 06:43 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
Need to update this - change warnings to rule violations

2022-09-15 06:44 UTC, savageCoder55 commented on src/pages/docs/api-governance/api-definition/api-definition-warnings.md
>  search_keyword: "api security, api schema, security warnings, schema validation, security validation, api security audit, api security scan, api schema vulnerabilities, security audit,openapi 3.0"
For the headers above this - need to replace warnings with rule violations.

2022-09-15 06:46 UTC, savageCoder55 reviewed
LGTM