[TW-667] Change update instructions for v10
postmanlabs/postman-docs pull request #4269
Opened 2022-09-08 23:31 UTC by MatthewPinsker-postman

**Completed:**
* Added new section for updating to v10; the new sections explains which versions perform automatic updates
* Added download links for Postman v9
* Removed mentions of upgrading from and downloading Postman v7

**In progress:**
* We need to confirm whether we should provide download links for v9.

2022-09-09 12:11 UTC, jkonrath-postman approved these changes
LGTM!

2022-09-14 01:07 UTC, jonycheung approved these changes
LGTM. We'll setup the new v9 links today in https://postmanlabs.atlassian.net/browse/WEBFN-1699

2022-09-15 00:13 UTC, jonycheung requested changes
Looks good. Just 1 comment.

2022-09-15 00:13 UTC, jonycheung commented on src/pages/docs/administration/updating.md
> +Use the following links to download the latest Postman v9 version for your platform.
Because folks will be automatically updated to v10, let's add a line here for folks downloading v9. If their account has v10 enabled, the app will automatically be updated to v10.

2022-09-15 00:15 UTC, jonycheung approved these changes

2022-09-15 12:57 UTC, merged

2022-09-15 15:38 UTC, MatthewPinsker-postman commented on src/pages/docs/administration/updating.md
> +Use the following links to download the latest Postman v9 version for your platform.
Thanks, @jonycheung . This will be addressed in a separate ticket because the documentation is frozen for the v10 release. Here is the ticket for this change:

https://postmanlabs.atlassian.net/browse/TW-686