[TW-785] flows edits continued
postmanlabs/postman-docs pull request #4449
Opened 2022-12-06 17:51 UTC by petewitcher

2022-12-06 21:58 UTC, jkonrath-postman requested changes
A couple of changes - we should probably talk more about a better strategy on the blocks list.

2022-12-06 21:58 UTC, jkonrath-postman commented on src/pages/docs/getting-started/introduction.md
> +* [__Creating API workflows__](#creating-api-workflows)
```suggestion
* [__Using Postman Flows__](#using-postman-flows)
```

2022-12-06 21:58 UTC, jkonrath-postman commented on src/pages/docs/getting-started/introduction.md
> +* [__Creating API workflows__](#creating-api-workflows)
Let's make this jump and the heading use the feature name, just to make sure we lead with it. You also need to change the heading below to match this.

2022-12-06 21:58 UTC, jkonrath-postman commented on src/pages/docs/postman-flows/flows-intro/building-your-first-flow.md
> +1. Select **New** &gt; **Flows**. A **Start** block appears automatically.
I think we need to glue together a few of these single steps so we don't have a ten-step procedure right out of the gate.

Like 1 and 2 could be a two-sentence step. 4-6 could be glued together 7-8 or 9, could be one.

2022-12-06 21:58 UTC, jkonrath-postman commented on src/pages/docs/postman-flows/core-concepts/blocks-list.md
So, I know we've gone back and forth on this, but I think today's decision (sorry) is that instead of an A-Z of all blocks, we'd have 7 H2s for Data, Trigger, Logic, etc, and then in each of those, have an H3 for each block. 

The eventual goal is to break it up into individual pages, but for now, let's do the above.

2022-12-06 22:41 UTC, petewitcher commented on src/pages/docs/postman-flows/core-concepts/blocks-list.md
Done.

2022-12-06 22:52 UTC, petewitcher commented on src/pages/docs/postman-flows/flows-intro/building-your-first-flow.md
> +1. Select **New** &gt; **Flows**. A **Start** block appears automatically.
Done.

2022-12-12 17:06 UTC, mark-anthony-postman approved these changes
Changes are looking good! Made a few suggestions 😀

2022-12-12 20:34 UTC, petewitcher commented on src/pages/docs/postman-flows/flows-intro/the-interface.md
> +![Interface](https://assets.postman.com/postman-docs/v10/updated-interface-main-v10.jpg)
Thanks Mark I'll use flows-interface-main.jpg sans border for now. The images are already inconsistent about borders so I'll create a separate ticket for that.

2022-12-12 20:42 UTC, petewitcher commented on src/pages/docs/postman-flows/flows-intro/chaining-requests-with-data.md
> +> Check out the example flow: [Pass data from requests](https://www.postman.com/postman/workspace/example-flows/flow/62fdd3360a222e16840ce44b)
I actually omitted the periods after the code samples at the ends of two steps because it's easier to select them and copy them to the clipboard. It's technically breaking the rules but I thought the user would appreciate it. In any case, I've put them back in because now I think it looks wrong without them.

2022-12-12 20:43 UTC, petewitcher commented on src/pages/docs/postman-flows/flows-intro/chaining-requests-with-data.md
>  1. **Add two Send Request blocks**
Thanks, that one was a typo.

2022-12-12 22:57 UTC, jkonrath-postman approved these changes

2022-12-12 22:58 UTC, merged