TW 381 OAuth refresh
postmanlabs/postman-docs pull request #4457
Opened 2022-12-08 20:00 UTC by HeatherStenson

2022-12-08 21:28 UTC, mark-anthony-postman approved these changes
LGTM! 💎✨

2022-12-09 15:18 UTC, jkonrath-postman approved these changes
LGTM

2022-12-09 15:18 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/authorization.md
> +With auto-refresh, Postman refreshes the token in the background before you send a request that uses it. The refreshed access token is updated wherever it's used, including in execution environments
```suggestion
With auto-refresh, Postman refreshes the token in the background before you send a request that uses it. The refreshed access token is updated wherever it's used, including in execution environments like [monitors](/docs/monitoring-your-api/intro-monitors/), [Collection Runner](/docs/running-collections/running-collections-overview/), [Flows](/docs/postman-flows/flows-intro/flows-overview/), [Newman](/docs/running-collections/using-newman-cli/command-line-integration-with-newman/), and the [Postman CLI](/docs/postman-cli/postman-cli-overview/).
```

2022-12-12 18:41 UTC, giridharvc7 requested changes

2022-12-14 00:22 UTC, merged