[TW-891] Doc collection run plan changes
postmanlabs/postman-docs pull request #4555
Opened 2023-02-06 23:29 UTC by mark-anthony-postman

2023-02-06 23:42 UTC, MatthewPinsker-postman commented on src/pages/docs/administration/resource-usage.md
> +Your Postman plan gives you a limited number of [collection runs](/docs/running-collections/intro-to-collection-runs/) you can use each month. This limit applies to collections that you run in a work
What do you think about linking to the Plans page? This way users can learn how many collections they can run per plan type. https://www.postman.com/pricing/

2023-02-06 23:45 UTC, MatthewPinsker-postman approved these changes
Looks good! I added one minor suggestion. Thanks!

2023-02-06 23:48 UTC, HeatherStenson approved these changes
Looks good! Just one small thought about wording.

2023-02-06 23:48 UTC, HeatherStenson commented on src/pages/docs/administration/resource-usage.md
> +Your Postman plan gives you a limited number of [collection runs](/docs/running-collections/intro-to-collection-runs/) you can use each month. This limit applies to collections that you run in a work
Maybe separate out "(not scheduled collection runs in the Postman cloud)" as its own sentence? I kind of got lost in that sentence and worry that other readers might too.

```suggestion
Your Postman plan gives you a limited number of [collection runs](/docs/running-collections/intro-to-collection-runs/) you can use each month. This limit applies to collections that you run in a workspace or the Scratch Pad using the **Run manually** option. This limit doesn't apply to [scheduled collection runs](/docs/running-collections/scheduling-collection-runs/) in the Postman cloud. Each iteration counts as a single run. You will get a notification in the Collection Runner when you're approaching your usage limit. (Collection run usage doesn't appear on the Resource Usage dashboard.)
```

2023-02-07 00:22 UTC, postfrzero requested changes

2023-02-07 00:22 UTC, postfrzero commented on src/pages/docs/administration/resource-usage.md
> +Your Postman plan gives you a limited number of [collection runs](/docs/running-collections/intro-to-collection-runs/) you can use each month. This limit applies to collections that you run in a work
> Each iteration counts as a single run.

A single run can have multiple iterations and it'll still count as a single run.

> You will get a notification in the Collection Runner when you're approaching your usage limit.

They won't get a notification in the classical sense, but instead messaging will appear within the collection runner to let them know. I'm not how we can tweak the wording here to communicate that. 😅

2023-02-07 16:39 UTC, mark-anthony-postman commented on src/pages/docs/administration/resource-usage.md
> +Your Postman plan gives you a limited number of [collection runs](/docs/running-collections/intro-to-collection-runs/) you can use each month. This limit applies to collections that you run in a work
Sounds good! There was a link to the pricing page at the top of this page, but I went ahead and added it here as well, and in each of the other sections.

2023-02-07 16:48 UTC, mark-anthony-postman commented on src/pages/docs/administration/resource-usage.md
> +Your Postman plan gives you a limited number of [collection runs](/docs/running-collections/intro-to-collection-runs/) you can use each month. This limit applies to collections that you run in a work
Great, thanks for clarifying both of these points! I updated the text to (hopefully) be more accurate 😀

2023-02-08 16:16 UTC, postfrzero approved these changes

2023-02-08 16:28 UTC, merged