TW 904 Settings - switch security warnings off or on
postmanlabs/postman-docs pull request #4562
Opened 2023-02-08 23:16 UTC by HeatherStenson

2023-02-08 23:45 UTC, mark-anthony-postman approved these changes
Needs one minor fix, otherwise looks great! 🌟

2023-02-08 23:45 UTC, mark-anthony-postman commented on src/pages/docs/sending-requests/responses.md
> +<img alt="Settings icon" src="https://assets.postman.com/postman-docs/icon-settings-v9.jpg#icon" width="16px">, then select **Settings > General** and turn off **Security Warnings count**. While the
The note isn't rendering correctly- removing the line break before the icon should fix it

2023-02-09 00:01 UTC, HeatherStenson commented on src/pages/docs/sending-requests/responses.md
> +<img alt="Settings icon" src="https://assets.postman.com/postman-docs/icon-settings-v9.jpg#icon" width="16px">, then select **Settings > General** and turn off **Security Warnings count**. While the
Oh boy, this was a good one 😅 Thanks Mark!

2023-02-09 12:32 UTC, savageCoder55 requested changes
Small change requested.

2023-02-09 12:39 UTC, rishabjain22 commented on src/pages/docs/sending-requests/responses.md
> +> You can hide the number of security warnings that Postman displays in the **Security** tab if this number is not important to you. In the Postman header, select the settings icon <img alt="Settings
@savageCoder55 @HeatherStenson Yes, this functionality is only rolled out to 5% of non-Enterprise users.

2023-02-09 19:07 UTC, claireriley approved these changes
LGTM! ⭐

2023-07-18 18:09 UTC, jkonrath-postman commented
This got shipped at some point and a different PR changed the settings, so this isn't needed anymore.

2023-07-18 18:09 UTC, closed without merging