[TW-884] gRPC saved examples
postmanlabs/postman-docs pull request #4567
Opened 2023-02-09 23:03 UTC by petewitcher

2023-02-10 21:42 UTC, mark-anthony-postman approved these changes
The new content looks great! 🙌

2023-02-10 21:42 UTC, mark-anthony-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-mock.md
> +> [Saved examples](src/pages/docs/sending-requests/using-grpc-saved-examples/) are also useful for developing endpoint-dependent features before the API is complete and accessible.
```suggestion
> [Saved examples](/docs/sending-requests/using-grpc-saved-examples/) are also useful for developing endpoint-dependent features before the API is complete and accessible.
```

2023-02-10 21:42 UTC, mark-anthony-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +1. Select the **Select a method** dropdown and select **LotsOfGreetings**.
```suggestion
1. Select the **Select a method** dropdown list and select **LotsOfGreetings**.
```

2023-02-10 21:42 UTC, mark-anthony-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +1. Select the **Select a method** dropdown and select **LotsOfGreetings**.
According to the [A-Z word list](https://postmanlabs.atlassian.net/wiki/spaces/TW/pages/3346170709/A-Z+word+list#D), we should use "dropdown list"

2023-02-10 21:44 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +1. Select the **Select a method** dropdown and select **LotsOfGreetings**.
Thanks Mark!

2023-02-10 22:25 UTC, jkonrath-postman approved these changes
A couple of minor things, but otherwise LGTM

2023-02-10 22:25 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +> If you are using the Postman web app, Postman recommends using the Postman Desktop Agent for the best experience. See [About the Postman Agent](/docs/getting-started/about-postman-agent/) for more
Is it recommended, or is it required?

2023-02-10 22:25 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +1. Select **Enter Server URL** and enter `grpcb.in:9001`.
Can we use the Postman echo service for this?

2023-02-10 22:29 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +1. Select **Enter Server URL** and enter `grpcb.in:9001`.
I did originally, but server reflection stopped working for grpc.postman-echo.com and I couldn't load any methods.

2023-02-10 22:52 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +> If you are using the Postman web app, Postman recommends using the Postman Desktop Agent for the best experience. See [About the Postman Agent](/docs/getting-started/about-postman-agent/) for more
I think it's recommended because I see the phrase in three other files. I'll confirm with Shobhit.

2023-02-13 09:55 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +> If you are using the Postman web app, Postman recommends using the Postman Desktop Agent for the best experience. See [About the Postman Agent](/docs/getting-started/about-postman-agent/) for more
Required : (
gRPC, WebSocket and GraphQL request execution cannot be done over cloud agent.

2023-02-13 13:04 UTC, skatikia requested changes

2023-02-14 16:58 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +1. Select **Enter Server URL** and enter `grpcb.in:9001`.
@petewitcher-postman the Postman echo service is up and running again. We can use it to demo things in here.
Here's a collection documenting the echo service: https://www.postman.com/postman/workspace/published-postman-templates/collection/63e9a08f30041c45db919fa0

2023-02-14 17:43 UTC, skatikia requested changes

2023-02-14 17:43 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +* [Creating a gRPC saved example without an API call](#creating-a-grpc-saved-example-without-an-api-call)
We can just call them 'Examples', right? Unless we have specific reason to call them 'Saved examples'

2023-02-14 17:43 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +1. Select the **Select a method** dropdown list and select **LotsOfGreetings**.
Do you think it's important to say, 'Once the list of methods is loaded...'? Server reflection can take some time to load the methods.

2023-02-14 17:43 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +1. Select the **Select a method** dropdown list and select **LotsOfGreetings**.
We can demo this using a Unary method, as that's what 90% of users would be using frequently. Then we can add a short description to include streaming-type methods.

Or demostrate the streaming type methods in the 'Creating an example from scratch' section maybe. That's where the 'Generate example stream' features shines the brightest.

2023-02-14 17:43 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +## Creating a gRPC saved example without an API call
Just say- "Create an example from scratch"?

2023-02-14 17:43 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +    ![Select Add example](https://assets.postman.com/postman-docs/v10/grpc-create-example-1add-v10.jpg)
How about a screenshot with the request interface open in the right. My only concern with this screenshot is that the 'no tab state' is a forced state of the app. Typically I would create my request -> Add to collection -> Add example. In this flow, I would not encounter the 'no tab state'

2023-02-14 17:43 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +1. [Edit the gRPC saved example.](#editing-a-grpc-saved-example)
We have the option to demo the 'Generate example stream' feature here. Which is something users would be doing often if their API is yet to be implemented. It's available in the dropdown next to 'Add a Message'. It creates a dummy message stream automatically using the message structure defined in the protobuf schema.

2023-02-14 17:43 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-mock.md
> +
Not sure what an endpoint-dependent feature means here.

2023-02-14 17:43 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +
Can we also update the screenshot on top of this page with this change?

2023-02-14 17:43 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/grpc-client-overview.md
> +<img src="https://assets.postman.com/postman-docs/v10/grpc-echo-request-1-v10.jpg" alt="gRPC request interface">
❤️

2023-02-14 17:43 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/first-grpc-request.md
> +
This page is meant to get users who doen't know about gRPC support on postman to get started quickly. Maybe we can avoind mentioning examples here which is an advanced usecase?

2023-02-14 17:43 UTC, skatikia commented on src/components/LeftNav/LeftNavItems.jsx
> +            name: 'Using gRPC saved examples',
Not sure about using "saved" examples here. We can just say "Examples"

2023-02-14 17:46 UTC, skatikia commented
@petewitcher-postman We also need to include the 'Use messages from examples' feature. We can take it up in a separate PR but just a heads-up. The feature is already on prod.

2023-02-14 17:48 UTC, skatikia commented
Another heads up for 'examples in request documentation'. Not on prod yet. But you can use this track to get started on the content- https://go.postman-beta.co/?_track=br-feature-APICLIENT-361-documentation-from-saved-examples

2023-02-15 15:23 UTC, petewitcher-postman commented on src/components/LeftNav/LeftNavItems.jsx
> +            name: 'Using gRPC saved examples',
Fixed

2023-02-15 15:29 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +* [Creating a gRPC saved example without an API call](#creating-a-grpc-saved-example-without-an-api-call)
Absolutely, thanks Shobhit.

2023-02-15 15:48 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/examples.md
> +> For gRPC examples with streaming methods, you must stop streaming before saving the example. See [Using the gRPC request interface](/docs/sending-requests/grpc/grpc-request-interface/#the-response-
Thanks Shobhit, I made the changes you suggested and linked to the "Using gRPC examples" doc. I also deleted the "see also" because I think it's not necessary.

2023-02-15 15:55 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/first-grpc-request.md
> +
Good suggestion, done.

2023-02-15 16:11 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-mock.md
> +
I was freestyling a bit. :D Based on your comments about the two primary use cases for gRPC examples, I'm deleting this cross reference. I think it doesn't belong here.

2023-02-15 16:28 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +You can save, edit, and create [examples](/docs/sending-requests/examples/) for gRPC requests. You can also include documentation with each gRPC saved example. gRPC saved examples can help API consum
Thanks Shobhit for the excellent comments! I've rewritten this paragraph using content from your blog post and these comments. I think it now covers the suggestions you made, but let me know if you'd like more edits. 👍

2023-02-15 16:34 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +## Creating a gRPC saved example without an API call
Good call, done.

2023-02-16 15:55 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +This example creates and executes a client streaming request, then saves the response as a gRPC saved example.
Ha yes of course, changed to `procedure`.

2023-02-16 16:28 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +1. Select the **Select a method** dropdown list and select **LotsOfGreetings**.
I added `When the list of methods has loaded,`.

I rewrote this procedure with a unary method.

2023-02-16 16:41 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +1. [Edit the gRPC saved example.](#editing-a-grpc-saved-example)
Done, thanks for the suggestion and useful info!

2023-02-16 16:43 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +1. Select **Generate example message**.
I removed the steps referencing `Generate example message` to simplify the procedure. Thanks for the heads-up.

2023-02-16 17:24 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/grpc-request-interface.md
> +
Done

2023-02-16 18:56 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-saved-examples.md
> +    ![Select Add example](https://assets.postman.com/postman-docs/v10/grpc-create-example-1add-v10.jpg)
Done

2023-02-17 12:18 UTC, skatikia requested changes
@petewitcher-postman Almost there! Added a few more comments. Do check them out. Let me know once done. I can do another round of review early in my morning (your evening).

2023-02-17 12:18 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +## Creating a gRPC example from scratch
Love this section! Touches all the right points.

However, if we're showing a unary method in last two walkthroughs, it'll be better to get a segue here that says- "Well, we've been working with a Unary method so far. Let's see what working with a streaming method looks like."

2023-02-17 12:18 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +    ![New example](https://assets.postman.com/postman-docs/v10/grpc-create-example-2save-1-v10.jpg)
Something wrong with the image. This is not how what it should look like. Can you try again?

2023-02-17 12:18 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +    ![New example](https://assets.postman.com/postman-docs/v10/grpc-create-example-2save-1-v10.jpg)
It's got an error.

2023-02-17 12:18 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +1. Hover over the gRPC request you created and select the more actions icon <img alt="More actions icon" src="https://assets.postman.com/postman-docs/icon-more-actions-v9.jpg#icon" width="16px">.
More actions 'button'?

2023-02-17 12:18 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +1. In the sidebar, select the example you created.
It opens up automatically when you click 'Add example'. You don't have to select in the sidebar.

2023-02-17 12:18 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +1. Select the **Add a Message** dropdown and select **Message stream**. This creates a dummy message stream automatically using the message structure defined in the protobuf schema.
Can we break this sentence into two and add an image that shows the output of 'Generate example stream'? The story feels incomplete without it 😅

2023-02-17 13:13 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +APIs can be complex, and so can the guidelines for using them. Examples help consumers understand APIs by capturing the request sent from the client and the response received from the server in a sin
Done

2023-02-17 13:13 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +This procedure creates and executes a client streaming request, then saves the response as a gRPC example.
Done

2023-02-17 13:14 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +1. Hover over the gRPC request you created and select the more actions icon <img alt="More actions icon" src="https://assets.postman.com/postman-docs/icon-more-actions-v9.jpg#icon" width="16px">.
We use 'icon' throughout the learning center.

2023-02-17 13:22 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +
I've created a jira ticket for this and will make these changes next week. I think this will require some time to create and review and I don't think I have enough time to complete it before we push to prod today.

2023-02-17 13:26 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +## Creating a gRPC example from scratch
I've added this task to TW-946 and will complete it next week.

2023-02-17 13:27 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +1. In the sidebar, select the example you created.
Fixed

2023-02-17 13:33 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +    ![New example](https://assets.postman.com/postman-docs/v10/grpc-create-example-2save-1-v10.jpg)
Fixed

2023-02-17 13:57 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +1. Select the **Add a Message** dropdown and select **Message stream**. This creates a dummy message stream automatically using the message structure defined in the protobuf schema.
Done

2023-02-17 15:34 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +## Creating a gRPC example from scratch
Fixed

2023-02-17 15:36 UTC, jkonrath-postman approved these changes
LGTM

2023-02-17 17:11 UTC, merged