[TW-934] Consuming saved example responses
postmanlabs/postman-docs pull request #4572
Opened 2023-02-13 22:17 UTC by MatthewPinsker-postman

* Explained how users can open saved example responses as requests. Users can then send the request, enabling them to try the example.
* Explained an alternative user flow for editing saved example responses.

2023-02-14 06:33 UTC, giridharvc7 commented on src/pages/docs/sending-requests/examples.md
> +1. You can try the example in the new request. Select **Send**, and then review the response.
Selecting *Try* will automatically send the request

2023-02-14 06:36 UTC, giridharvc7 commented on src/pages/docs/sending-requests/examples.md
> +1. Optionally, you can select **Save** to save the new request to a new or existing collection in your workspace.
We can also mention this workflow
- Updating the original example with the latest response 
<img width="382" alt="image" src="https://user-images.githubusercontent.com/1040583/218658290-27a5ad1a-5dd7-4f54-8a80-1345aa608f57.png">

2023-02-14 06:37 UTC, giridharvc7 requested changes
Have left some comments on what we can add

2023-02-14 06:43 UTC, coditva commented on src/pages/docs/sending-requests/examples.md
> +    The name of the example response you're trying is next to the request's name in the workbench. Select the example response's name to open it in a separate tab.
"example response" seems redundant. Let's just keep "example"
```suggestion
    The name of the example you're trying is next to the request's name in the workbench. Select the example response's name to open it in a separate tab.
```

2023-02-14 06:43 UTC, coditva commented on src/pages/docs/sending-requests/examples.md
> +    The name of the example response you're trying is next to the request's name in the workbench. Select the example response's name to open it in a separate tab.
"workbench" is a technical term that the user is not aware of. Let's use "tab" like we're using everywhere else.
```suggestion
    The name of the example response you're trying is next to the request's name in the tab. Select the example response's name to open it in a separate tab.
```

2023-02-14 15:35 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/examples.md
> +    The name of the example response you're trying is next to the request's name in the workbench. Select the example response's name to open it in a separate tab.
We use "workbench" in the documentation to refer to that section of the UI. I think we can leave this as "workbench" for now. For details, please see [Navigating Postman](https://learning.postman.com/docs/getting-started/navigating-postman/#workbench).

2023-02-14 15:55 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/examples.md
> +1. Optionally, you can select **Save** to save the new request to a new or existing collection in your workspace.
@giridharvc7 I think I already addressed this workflow in the "Editing an example" section. The steps begin with "To edit an example after trying it, do the following:"

Can you please confirm?

2023-02-14 15:57 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/examples.md
> +1. You can try the example in the new request. Select **Send**, and then review the response.
This is now added.

2023-02-14 15:57 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/examples.md
> +    The name of the example response you're trying is next to the request's name in the workbench. Select the example response's name to open it in a separate tab.
This is now updated.

2023-02-14 16:38 UTC, mark-anthony-postman approved these changes
Changes look great! 🌟 Made one suggestion

2023-02-14 16:38 UTC, mark-anthony-postman commented on src/pages/docs/sending-requests/examples.md
> +1. Try the example in the new request, and review the request details.
Since the request is automatically sent in the request above, this step feels a little confusing. I'm not sure what I should "try" here, unless I were to hit "Send" again. Maybe this step should just be:

Review the request and response details.

2023-02-15 16:06 UTC, jkonrath-postman approved these changes
LGTM

2023-02-15 16:28 UTC, merged