TW-937 Doc support for JWT auth
postmanlabs/postman-docs pull request #4573
Opened 2023-02-13 22:47 UTC by jkonrath-postman

2023-02-13 23:30 UTC, MatthewPinsker-postman approved these changes
Looks good!

2023-02-14 01:07 UTC, giridharvc7 commented on src/pages/docs/sending-requests/authorization.md
> +Postman also supports generating JWT bearer tokens to authorize requests. You can enter a payload in an an editor, and JWT tokens are generated and added to the request. In the request __Authorizatio
You can enter a Payload in `the` editor?

2023-02-14 01:08 UTC, giridharvc7 commented on src/pages/docs/sending-requests/authorization.md
> +* **Header prefix** - An optional prefix to use at the start of headers.
Cna we specifically mention that this header prefix is part of the request and not a part of JWT?

2023-02-14 01:09 UTC, giridharvc7 commented on src/pages/docs/sending-requests/authorization.md
> +* **Headers** - Any custom headers you also want to send in the JWT token.
Should We also mention that the headers pertaining to the selected algorithm is automatically added?

2023-02-14 01:09 UTC, giridharvc7 requested changes
Have added some comments, LGTM otherwise

2023-02-15 15:53 UTC, merged