[TW-954] Doc customizable Oauth
postmanlabs/postman-docs pull request #4597
Opened 2023-02-21 22:41 UTC by mark-anthony-postman

2023-02-21 22:46 UTC, MatthewPinsker-postman approved these changes
Looks good to me!

2023-03-08 19:28 UTC, jkonrath-postman approved these changes
LGTM

2023-04-10 14:14 UTC, giridharvc7 requested changes

2023-04-10 14:20 UTC, mark-anthony-postman commented on src/pages/docs/sending-requests/authorization.md
> +* **Auth Request**, **Token Request**, and **Refresh Request** - Define any custom parameters you want to send with auth requests, token requests, or refresh requests. For each key-value pair you def
I added the following:
> If you add multiple keys with same key name, they will be sent with the request as an array.

2023-04-10 14:27 UTC, mark-anthony-postman commented on src/pages/docs/sending-requests/authorization.md
> +When the configuration is complete, select __Get New Access Token__.
I added the following:
> The configuration information is saved along with the access token and will be used every time the token is refreshed.

2023-04-11 15:08 UTC, giridharvc7 approved these changes

2023-04-17 15:47 UTC, merged