[TW-948] use messages from examples
postmanlabs/postman-docs pull request #4601
Opened 2023-02-22 22:31 UTC by petewitcher-postman

2023-02-23 12:30 UTC, skatikia requested changes

2023-02-23 12:30 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +1. Create a gRPC request with the URL `grpc.postman-echo.com` and the `SayHello` method, and add it to a collection.
I don't think we need so many steps for this simple idea. This can be a continuation from the walkthroughs on the top. You need an example saved in a request saved in a collection -> Open the request, invoke, select payload, send, select another payload, send, end streaming

2023-02-23 12:30 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +When you want to add an example message to your gRPC request, you can select from a list that shows all the messages in all the examples associated with that request. This is much easier and faster t
Let's not call it 'Saved' example. Just 'example' is fine and consistent with our product messaging.

2023-02-23 15:25 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +When you want to add an example message to your gRPC request, you can select from a list that shows all the messages in all the examples associated with that request. This is much easier and faster t
Thanks Shobhit, I replaced the first sentence with your suggestion and removed `saved` from the second sentence.

2023-02-23 21:59 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +This walkthrough creates two gRPC saved examples with different request messages and shows how to add the messages to a gRPC request.
Thanks for the insight, I've rewritten the procedure based on your suggestions.

2023-02-23 22:00 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +1. Create a gRPC request with the URL `grpc.postman-echo.com` and the `SayHello` method, and add it to a collection.
I've rewritten the procedure based on your suggestions.

2023-02-27 21:10 UTC, jkonrath-postman approved these changes
A few little things, but LGTM

2023-02-27 21:10 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +You can see how this simplifies things when you're invoking a client streaming method and you need to send multiple message payloads in one go.
```suggestion
This simplifies things when you're invoking a client streaming method and you need to send multiple message payloads in one go.
```

2023-02-27 21:10 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +You can see how this simplifies things when you're invoking a client streaming method and you need to send multiple message payloads in one go.
No "you can see" (in style guide)

2023-02-27 21:10 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +This walkthrough shows how to easly add messages to a client-streaming request.
```suggestion
This walkthrough shows how to easly add messages to a client-streaming request:
```

2023-02-28 14:35 UTC, skatikia reviewed
@petewitcher-postman love the updates. They convey the story exactly how we want. Suggested a few minor fixes.

2023-02-28 14:35 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +While invoking a request, you can work with message payloads stored in the examples. This not only enables you to test the example scenarios by yourself, but also speeds up your debugging workflow. T
@petewitcher-postman we can drop the last line. The purpose of this action is not to review example messages anyway. That can be a use case for request documentation.

2023-02-28 14:35 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +This walkthrough shows how to easly add messages to a client-streaming request:
Typo- easly

How about- This walkthrough shows how you can invoke a client streaming request with messages stored in the examples

2023-02-28 14:35 UTC, skatikia commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +This simplifies things when you're invoking a client streaming method and you need to send multiple message payloads in one go.
Not only simplifies things for 'client streaming', but all method types. But 'Client streaming' and 'bidirectional streaming' is where it shines the best. BTW we don't have to be so granular. Can remove this line also.

2023-02-28 14:38 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +This simplifies things when you're invoking a client streaming method and you need to send multiple message payloads in one go.
Done

2023-02-28 14:39 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +While invoking a request, you can work with message payloads stored in the examples. This not only enables you to test the example scenarios by yourself, but also speeds up your debugging workflow. T
Deleted `This is much easier and faster than opening and reviewing each example’s messages individually.`

2023-02-28 14:40 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/using-grpc-examples.md
> +This walkthrough shows how to easly add messages to a client-streaming request:
Done

2023-02-28 14:47 UTC, merged