[TW-921] Doc file-less API definitions
postmanlabs/postman-docs pull request #4604
Opened 2023-02-24 17:58 UTC by mark-anthony-postman

2023-02-24 18:11 UTC, MatthewPinsker-postman commented on src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md
> +> **About definition IDs** When you add a definition to an API, Postman assigns a definition ID to the API. You can view the definition ID by opening an API and selecting the information icon <img al
This is minor, but what do you think about using a character to separate "**About definition IDs**" from the rest of the note? Something like, "**About definition IDs:** When you add a definition to..." or "**About definition IDs.** When you add a definition to..."

My thinking is that the separating character helps clarify that **About definition IDs** is an intro/title, and not part of the first sentence.

2023-02-24 18:13 UTC, MatthewPinsker-postman approved these changes
Looks good!

2023-02-24 18:16 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md
> +> **About definition IDs** When you add a definition to an API, Postman assigns a definition ID to the API. You can view the definition ID by opening an API and selecting the information icon <img al
Thanks for spotting that Matthew! My intention was to have a period there, but my fingers forgot to type it 😅

2023-02-24 18:53 UTC, petewitcher-postman approved these changes
LGTM!

2023-02-26 12:40 UTC, raghumurthy-jayandran requested changes

2023-02-26 12:40 UTC, raghumurthy-jayandran commented on src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md
> +To delete a definition file or folder, select the more actions icon <img alt="More actions icon" src="https://assets.postman.com/postman-docs/icon-more-actions-v9.jpg#icon" width="16px"> next to the
With the file-less definition you will now be able to restore a deleted file.

2023-02-28 05:14 UTC, raghumurthy-jayandran commented on src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md
> +You can restore a deleted definition file use the [Changelog](/docs/designing-and-developing-your-api/managing-apis/#using-the-changelog). Select the changelog icon <img alt="Changelog icon" src="htt
@mark-anthony-postman Shouldn't the sentence  say `You can restore a deleted definition file using [Changelog]`

2023-02-28 14:40 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md
> +You can restore a deleted definition file use the [Changelog](/docs/designing-and-developing-your-api/managing-apis/#using-the-changelog). Select the changelog icon <img alt="Changelog icon" src="htt
Yes, it should be "using the [Changelog]". Thanks so much for catching that mistake!

2023-02-28 16:22 UTC, raghumurthy-jayandran approved these changes

2023-02-28 16:27 UTC, merged