[TW-693] Doc GraphQL
postmanlabs/postman-docs pull request #4607
Opened 2023-02-27 19:19 UTC by petewitcher-postman

2023-02-27 20:26 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +## Next step
```suggestion
## Next steps
```

2023-02-27 20:32 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +Create a new GraphQL request by selecting the **New** button in the sidebar, which brings up the **Create new** dialog. Select **GraphQL request** from the list to open a blank gRPC request in a new
This is minor, but the style guide says we should avoid using "dialog" if possible. See https://postmanlabs.atlassian.net/wiki/spaces/TW/pages/3346170709/A-Z+word+list#D

Instead, we could write the instructions similar to [here](/docs/collaborating-in-postman/using-workspaces/creating-workspaces/#creating-a-new-workspace) or [here](https://learning.postman.com/docs/sending-requests/requests/#creating-requests).

2023-02-27 20:40 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Query explorer** - Once the schema is loaded, the available data fields, arguments to be passed, and their respective descriptions appear in this section. The schema query also doubles as an inte
It looks like we point out the "Query editor" in the screenshot, but we don't mention it in the bulleted list. Should we also mention "Query editor" in the bulleted list?

2023-02-27 20:43 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Query builder** - Explore and build your queries, mutations, fragments, and subscriptions here.
Is the "Query builder" everything shown in the screenshot? I'm asking because we don't point out the "Query builder" in the screenshot, but a user might want to look for it after reading this list item.

2023-02-27 20:48 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Authorization** - Enter authorization credentials here. You can choose from a list of auth types including API Key, Basic auth, and Bearer token. Learn more about authorizing requests [here](http
```suggestion
* **Authorization** - Enter authorization credentials here. You can choose from a list of auth types including API Key, Basic auth, and Bearer token. Learn more about [authorizing requests](https://learning.postman.com/docs/sending-requests/authorization/).
```

2023-02-27 20:53 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Schema** - The **Schema** tab lets you configure a GraphQL schema to make the client aware of the data fields available from the server. A GraphQL schema can be loaded directly using the URL thro
For the Authorization, Headers, and Scripts list items, should we clarify that we're referring to the tabs in the UI, similar to the Schema list item ("The Schema tab lets you ..."). I think this helps clarify what we're referring to in the UI.

2023-02-27 20:56 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Response** - Displays the response from the highlighted query/mutation/subscription.
It might be helpful to point to this section `#understanding-the-response`. I'm suggesting this because I was looking for the Response section in the above screenshot.

2023-02-27 21:02 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Test results** - The results for assertions you write in the scripts section appear here. Based on the test script, the results can be one of three types: Passed, Failed, or Skipped.
Same feedback mentioned above about mentioning that these are tabs.

2023-02-27 21:04 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Response stream** - The response stream has the request and the responses arranged in reverse chronological order (latest appears on the top).
Is this the same as the "Message stream"? I'm asking because I don't see "Response stream" in the screenshot.

2023-02-27 21:04 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Search for response** - You can use the high-level search input to search for particular responses.
Is this the same as the "Search for messages"? I'm asking because I don't see "Search for response" in the screenshot.

2023-02-27 21:11 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +The GraphQL request interface enables you to create multiple queries in the query builder and execute them one at a time. You can select a query from the query editor and select **Query** to execute
When we say "You can select a query from the query editor...", are we referring to the box on the left (with the check boxes) or the box on the right (where you can write the query)? Using "select" leads me to think we're referring to the box on the left, but according to the screenshot at `#understanding-parts-of-the-request-interface` this box is called the "Query explorer".

2023-02-27 21:12 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +You can also use the **Send** button dropdown to browse and select queries.
Should this be called the "Query button dropdown"?

2023-02-27 21:14 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Documentation** - View the request's description. You can add descriptions by selecting the edit icon <img alt="Edit icon" src="https://assets.postman.com/postman-docs/documentation-edit-icon-v8-
```suggestion
* **Documentation** - View the request's description. You can add descriptions by selecting the edit icon <img alt="Edit icon" src="https://assets.postman.com/postman-docs/documentation-edit-icon-v8-10.jpg#icon" width="18px"> next to the description, then write your content using [Postman's built-in editing tools](https://learning.postman.com/docs/publishing-your-api/authoring-your-documentation/).
```

2023-02-27 21:16 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Documentation** - View the request's description. You can add descriptions by selecting the edit icon <img alt="Edit icon" src="https://assets.postman.com/postman-docs/documentation-edit-icon-v8-
Also should we update the "Postman's built-in editing tools" link to this one instead? `/docs/publishing-your-api/authoring-your-documentation/#writing-descriptions-in-the-postman-editor`

2023-02-27 21:17 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Comments** - Select the comments icon to collaborate with your teammates as you work on an API. You can use `@` to tag others to ask a question, give feedback, and discuss your API.
Should we add the comments icon image here?

2023-02-27 21:18 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +After learning about the basic interface elements, try [making your first GraphQL query](/postman-api-client/graphql-client/first-graphql-request/).
Is the link supposed to point here instead? `/docs/sending-requests/graphql/graphql-client-first-request/`

2023-02-27 21:26 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +**Subscription** - For a live data source with frequently-changing data, you can subscribe to the data available on different fields. This enables the server to send the data requested over a persist
Should we organize these using an unordered list?

2023-02-27 21:27 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +**Mutation** - Mutation-type queries allow you to manipulate the data available on the server. You can create, update and delete data records by selecting the fields and passing the values as argumen
```suggestion
**Mutation** - Mutation-type queries allow you to manipulate the data available on the server. You can create, update, and delete data records by selecting the fields and passing the values as arguments.
```

2023-02-27 21:37 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-overview.md
> +    Postman's GraphQL client enables you to easily explore schemas with introspection and quickly build queries, mutations, and subscriptions to get the data you need. See the [GraphQL client overvie
What do you think about point to the About GraphQL Requests section in case users was definitions for the terms we introduce here.

For example, `... and quickly build [queries, mutations, and subscriptions](/docs/sending-requests/graphql/graphql-client-first-request/#about-graphql-request) to get the data you need.`

2023-02-27 21:40 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +1. In the query explorer on the left, select the `hello` field and select `person` and `name` as arguments.
```suggestion
1. In the query explorer on the left, select the `hello` field and select `person`, `age`, and `name` as arguments.
```

2023-02-27 21:41 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +1. Enter your name and age in the input boxes next to `name` and `age`. You should also see a fully-formed query based on your selections on the right.
```suggestion
1. Enter your age and name in the input boxes next to `age` and `name`. You should also see a fully-formed query based on your selections on the right.
```

2023-02-27 21:41 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +1. Enter your name and age in the input boxes next to `name` and `age`. You should also see a fully-formed query based on your selections on the right.
This is really minor, but `age` comes before `name` in the GIF.

2023-02-27 21:41 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +1. In the query explorer on the left, select the `hello` field and select `person` and `name` as arguments.
The GIF and next step both include `age`.

2023-02-27 21:42 UTC, jkonrath-postman reviewed
A few comments. Let's talk about the naming situation and wait to see if there's any more input from the team.

2023-02-27 21:42 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +## About GraphQL Request
```suggestion
## About GraphQL Requests
```

2023-02-27 21:42 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +* [About GraphQL request](#about-graphql-request)
```suggestion
* [About GraphQL requests](#about-graphql-requests)
```

2023-02-27 21:42 UTC, jkonrath-postman commented on src/components/LeftNav/LeftNavItems.jsx
>          name: 'Querying with GraphQL',
```suggestion
        name: 'Using GraphQL requests',
```

2023-02-27 21:42 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/graphql/graphql-overview.md
> +title: "Using GraphQL requests"
```suggestion
title: "GraphQL overview"
```

2023-02-27 21:42 UTC, jkonrath-postman commented on src/components/LeftNav/LeftNavItems.jsx
> +            name: 'Using the GraphQL client interface',
Let's talk about a better name for this page. It's too weird having two overview topics in the top of the section.

2023-02-27 21:42 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +Every GraphQL request requires a URL and a query. The URL is the endpoint where the data is hosted, and the query defines what exactly needs to be retrieved from this data source. A GraphQL request c
```suggestion
Every GraphQL request requires a URL and a query. The URL is the endpoint where the data is hosted, and the query defines what exactly needs to be retrieved from this data source. A GraphQL request can also have a schema configured to inform you of the data fields available from the server that can be included in the query. The request can also contain additional information such as authentication, headers, and settings based on the requirements specified by the API.
```

2023-02-27 21:42 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +**Mutation** - Mutation-type queries allow you to manipulate the data available on the server. You can create, update and delete data records by selecting the fields and passing the values as argumen
```suggestion
**Mutation** - Mutation-type queries allow you to manipulate the data available on the server. You can create, update, and delete data records by selecting the fields and passing the values as arguments.
```

2023-02-27 21:42 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/graphql/graphql-overview.md
> +Postman can make HTTP calls using GraphQL, an open-source data query and manipulation language for APIs, in addition to REST.
```suggestion
Postman can make HTTP calls using GraphQL, an open-source data query and manipulation language for APIs.
```

2023-02-27 21:42 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-overview.md
> +GraphQL is schema driven, which means more transparency in terms of API functionality and lower dependency between teams building the client and the server. So, a client can introspect the schema fro
```suggestion
GraphQL is schema-driven, which means more transparency in terms of API functionality and lower dependency between teams building the client and the server. A client can introspect the schema from the server to get an idea about the available data fields, and then send queries specifying fields to retrieve or manipulate the stored data. The server does exactly what was asked from it and returns only the data requested in the query. Combining these features, GraphQL provides users with a flexible, fast, and predictable API experience, making it one of the most popular API technologies.
```

2023-02-27 21:42 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +**Queries** - Queries retrieve data from the server by specifying data fields and passing required arguments.
For these three, make this an unordered list to make it easier to scan.

2023-02-27 21:47 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +Try making a mutation and a subscription type query using the same endpoint and observe the difference in behavior.
In this section `#making-a-graphql-query-with-postman`, should we clarify how users can ensure they are creating an query type query? I'm asking because it isn't clear how to change the query type to mutation or subscription.

2023-02-27 21:48 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-http.md
> +> You can also use GraphQL with [the GraphQL client](/docs/sending-requests/graphql/graphql-client/).
Should this link point here? `/docs/sending-requests/graphql/graphql-client-interface/`

2023-02-27 22:28 UTC, MatthewPinsker-postman approved these changes
Looks good! I added a few suggestions.

2023-02-28 18:06 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +Create a new GraphQL request by selecting the **New** button in the sidebar, which brings up the **Create new** dialog. Select **GraphQL request** from the list to open a blank gRPC request in a new
Agreed, thanks.

2023-02-28 18:40 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +You can also choose to load a GraphQL API from Postman or import a schema from your local system to use in the request.
Done

2023-02-28 18:47 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Query explorer** - Once the schema is loaded, the available data fields, arguments to be passed, and their respective descriptions appear in this section. The schema query also doubles as an inte
Good catch, thanks. I think `Query builder` in the doc is referring to `Query editor` in the screenshot. I'll change `Query builder` to `Query editor` in the doc.

2023-02-28 18:57 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Response** - Displays the response from the highlighted query/mutation/subscription.
In the lede I changed `This document highlights the parts of the request interface and explains how to use them` to `This document highlights the parts of the request interface and the response and explains how to use them`. Does that work, or should I point to the `#understanding-the-response` section from somewhere else?

2023-02-28 19:01 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Response** - Displays the response from the highlighted query/mutation/subscription.
I think that should work. Thanks!

2023-02-28 19:18 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Response** - Displays the response from the highlighted query/mutation/subscription.
Oh I see now, there's a bullet item for `Response` in the `Request` section. That IS confusing, and I think it was a mistake. Deleted.

2023-02-28 19:26 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Test results** - The results for assertions you write in the scripts section appear here. Based on the test script, the results can be one of three types: Passed, Failed, or Skipped.
Done

2023-02-28 19:36 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +Try making a mutation and a subscription type query using the same endpoint and observe the difference in behavior.
Rather than create content to support this I'm going to delete this `Next steps` section.

2023-02-28 19:42 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Documentation** - View the request's description. You can add descriptions by selecting the edit icon <img alt="Edit icon" src="https://assets.postman.com/postman-docs/documentation-edit-icon-v8-
Link updated. I'm leaving `then writing` stet because it jibes with `by selecting`.

2023-02-28 20:31 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-http.md
> +> You can also use GraphQL with [the GraphQL client](/docs/sending-requests/graphql/graphql-client/).
`graphql-client-overview` actually. Thanks Matthew!

2023-02-28 20:33 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Response stream** - The response stream has the request and the responses arranged in reverse chronological order (latest appears on the top).
Changed to `Message stream`.

2023-02-28 20:34 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Search for response** - You can use the high-level search input to search for particular responses.
Yes it is. Fixed.

2023-02-28 20:36 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Clear Messages** - Hides all the messages exchanged from the view, cleaning up the response area so that you can focus on the new messages. You can restore the messages using the **Restore** butt
Negative, it's always **Clear Messages**.

2023-02-28 20:37 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +You can also use the **Send** button dropdown to browse and select queries.
Yes it should. Fixed.

2023-02-28 20:37 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Clear Messages** - Hides all the messages exchanged from the view, cleaning up the response area so that you can focus on the new messages. You can restore the messages using the **Restore** butt
Thanks for confirming!

2023-02-28 20:38 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +* **Comments** - Select the comments icon to collaborate with your teammates as you work on an API. You can use `@` to tag others to ask a question, give feedback, and discuss your API.
Done

2023-02-28 20:43 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-overview.md
> +    Postman's GraphQL client enables you to easily explore schemas with introspection and quickly build queries, mutations, and subscriptions to get the data you need. See the [GraphQL client overvie
Good suggestion. Done.

2023-03-01 15:20 UTC, petewitcher-postman commented on src/components/LeftNav/LeftNavItems.jsx
> +            name: 'Using the GraphQL client interface',
How about `The GraphQL client`?

2023-03-01 15:36 UTC, jkonrath-postman commented on src/components/LeftNav/LeftNavItems.jsx
> +            name: 'Using the GraphQL client interface',
`About the GraphQL client` ?

2023-05-12 15:59 UTC, timhall reviewed
Reviewed the content closely and it all looks great! Just a little copy-paste fix for gRPC in one place and I think this is good to go

2023-05-12 15:59 UTC, timhall commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +You can create a new gRPC request from the Postman home screen, by using **New > gRPC**, or by selecting **+** to open a new tab.
```suggestion
You can create a new GraphQL request from the Postman home screen, by using **New > GraphQL**, or by selecting **+** to open a new tab.
```

2023-05-12 15:59 UTC, timhall commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +![Create a new gRPC request](https://assets.postman.com/postman-docs/v10/graphql-create-new-2-v10.jpg)
The screenshot shows selecting a gRPC request and the alt tags needs to be updated.

```suggestion
![Create a new GraphQL request](https://assets.postman.com/postman-docs/v10/graphql-create-new-2-v10.jpg)
```

2023-05-12 16:30 UTC, jkonrath-postman requested changes
A couple of small changes - also I asked around on Slack, but do we need to add anything for mocks?

2023-05-12 16:30 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +updated: 2023-02-24
```suggestion
updated: 2023-05-15
```

2023-05-12 16:30 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +1. In Postman, select **New > GraphQL Request** to open a request in a new tab. (In the Postman desktop app, you can also select **⌘+N** or **Ctrl+N**, then select **GraphQL Request**.)
```suggestion
1. In Postman, select **New > GraphQL** to open a request in a new tab. (In the Postman desktop app, you can also select **⌘+N** or **Ctrl+N**, then select **GraphQL**.)
```

2023-05-12 16:30 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +1. In Postman, select **New > GraphQL Request** to open a request in a new tab. (In the Postman desktop app, you can also select **⌘+N** or **Ctrl+N**, then select **GraphQL Request**.)
```suggestion
1. In Postman, select **New > GraphQL** to open a request in a new tab. (In the Postman desktop app, you can also select **⌘+N** or **Ctrl+N**, then select **GraphQL**.)
```

2023-05-12 16:30 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +updated: 2023-02-24
```suggestion
updated: 2023-05-15
```

2023-05-12 16:30 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-overview.md
> +updated: 2023-02-24
```suggestion
updated: 2023-05-15
```

2023-05-12 16:30 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/graphql/graphql-overview.md
> +updated: 2023-02-24
```suggestion
updated: 2023-05-15
```

2023-05-15 13:59 UTC, jkonrath-postman approved these changes
LGTM

2023-05-15 13:59 UTC, merged