[TW-962] Environment variable sorting
postmanlabs/postman-docs pull request #4625
Opened 2023-03-02 17:09 UTC by petewitcher-postman

2023-03-08 19:12 UTC, jkonrath-postman approved these changes
LGTM

2023-03-13 14:17 UTC, missy-turco requested changes

2023-03-13 14:17 UTC, missy-turco commented on src/pages/docs/sending-requests/managing-environments.md
> +You can edit variables either by opening an environment from __Environments__ on the left, or by selecting the environment quick look icon <img alt="Environment quick look icon" src="https://assets.p
`a handle and a plus sign on the left, then select the handle to drag the variable.`

Not sure about putting so much focus on the drag feature here. Our hypothesis is that sorting _should_ replace the use of drag and drop in most cases where the user wants the variables A-Z for easier scan-ability. 

What if instead we highlighted the sorting interaction of clicking a heading? (not sure if the term "selecting" should be used since it is a click and toggle action)

```suggestion
You can edit variables either by opening an environment from __Environments__ on the left, or by selecting the environment quick look icon <img alt="Environment quick look icon" src="https://assets.postman.com/postman-docs/icon-environment-quick-look.jpg#icon" width="16px"> next to the [environment selector in the workbench](/docs/getting-started/navigating-postman/#environment-selector-and-environment-quick-look) and selecting __Edit__. You can sort the list of variables by clicking any column heading to toggle between alphabetical ascending or descending order and custom order. To sort the list by a custom order, clear the active sort then drag rows to reorder using the handle on the left-hand side.
```

Just a suggestion above as to what I am thinking we could write based on the new features, but feel free to move words around as you see fit and LMK what you think!

2023-03-13 15:30 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/managing-environments.md
> +You can edit variables either by opening an environment from __Environments__ on the left, or by selecting the environment quick look icon <img alt="Environment quick look icon" src="https://assets.p
Great suggestion, thanks Missy! Our style guide uses `select` instead of `click` so I'll leave that term as-is, but the rest is spot-on.

2023-03-13 18:25 UTC, missy-turco approved these changes
Awesome, LGTM!

2023-03-14 21:24 UTC, merged