Governance TW-905 TW-910
postmanlabs/postman-docs pull request #4635
Opened 2023-03-07 02:13 UTC by claireriley

Draft docs for:

* Ability to import additional libraries
* Switch security warnings count on or off

2023-03-07 19:05 UTC, akinard-postman approved these changes
Just one suggestion, but LGTM! 👍

2023-03-07 19:11 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> +The rule library contains Postman's API governance guidelines, Stoplight's style guide, and Zalando's RESTful API and event guidelines. You can select **View all** below a set of guidelines to view a
It's my understanding that you must ensure you select the **Rules** tab. What do you think about adding the following steps towards the beginning: "Select the **Rule Library** tab, and then select the **Rules** tab."

Also, to get to the rule library screen, I think you need to first select **Explore Library**, next to the **Create Rule** button. What do you think about mentioning this here?

2023-03-07 19:20 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> +Select **Edit**. To turn a governance rule on for the workspace group, select the checkbox next to the rule name. To turn a governance rule off for the workspace group, clear the checkbox next to the
It's my understanding that you need to select a group before you can see the Edit button. What do you think about updating this to something like, `To turn a governance rule on or off for a workspace group, select an existing group, and then select **Edit**. To turn a governance rule on, select the checkbox next to the rule name. To turn a governance rule off, clear the checkbox next to the rule name.`

2023-03-07 19:22 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/roles-and-permissions.md
> +* **Community Manager** ([Professional and Enterprise plans only](https://www.postman.com/pricing)) - Manages the public visibility of workspaces and team profile .
```suggestion
* **Community Manager** ([Professional and Enterprise plans only](https://www.postman.com/pricing)) - Manages the public visibility of workspaces and team profile.
```

2023-03-07 19:26 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/roles-and-permissions.md
> +
I think this extra space is causing a lint error.

2023-03-07 20:30 UTC, MatthewPinsker-postman approved these changes
Looks good!

2023-03-08 19:11 UTC, jkonrath-postman approved these changes
LGTM

2023-03-08 19:21 UTC, akinard-postman approved these changes
Looks good! :)

2023-03-10 11:11 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/configurable-rules-overview.md
> +<img alt="API governance dashboard" src="https://assets.postman.com/postman-docs/api-governance-dashboard-10.12.0.jpg"/>
nit : Let's update the asset once functions is removed.

2023-03-10 11:25 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> +[Super Admins](/docs/collaborating-in-postman/roles-and-permissions/#team-roles) and [API Governance Managers](/docs/collaborating-in-postman/roles-and-permissions/#team-roles) can configure rules an
Can we use something like "can configure rules for your team and enforces them on different workspaces with the help of Workspace Groups"?

2023-03-10 11:28 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> +In addition to the rules turned on by default in Postman, you can add other rules to your API Governance configuration from the rule library. You can also create your own custom rules.
Suggestion "In addition to the rules imported by default for your team's rule library you can use the import button to choose additional rules from the Postman API Governance Guidelines or Zalando RESTful API and Event Guidelines"

2023-03-10 11:30 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> +The rule library contains Postman's API governance guidelines, Stoplight's style guide, and Zalando's RESTful API and event guidelines. Navigate to the [governance dashboard](#accessing-the-configura
Please remove the Stoplight style guide. We will not be releasing that.

2023-03-10 11:31 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> +You can select **View all** below a set of guidelines to view all of the rules available to your team. Details and API format requirements are available under the rule name. Select **Import** next to
suggestion : "to view all of the rules of the respective guideline" or "to view all of its rules"

2023-03-10 11:32 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> +Once you import new rules from the library, you need to [turn them on](#turning-configured-rules-on-and-off) in the API Governance dashboard.
Instead of "turning them on" we should highlight the fact that these rules need to be added to a workspace group so that they can be enforced on respective workspaces.

2023-03-10 11:35 UTC, savageCoder55 commented on src/pages/docs/collaborating-in-postman/roles-and-permissions.md
> +* **API Governance Manager** ([Enterprise plans only](https://www.postman.com/pricing)) - Manages API governance within a team.
We're also adding the API Security Manager role. This will require a few changes to the API security specific sections of the LC as well.

2023-03-10 11:36 UTC, savageCoder55 requested changes
A few small comments. Nothing too drastic.

2023-03-11 02:47 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/configuring-api-security-rules.md
> +[Super Admins](/docs/collaborating-in-postman/roles-and-permissions/#team-roles) and [API Security Managers](/docs/collaborating-in-postman/roles-and-permissions/#team-roles) can configure rules and
nit : For the ending here - I would suggest `...can configure rules and turn them on and off for your team's API Security configuration`
The current state is good to go as well.

2023-03-11 02:53 UTC, savageCoder55 approved these changes
LGTM

2023-03-14 18:42 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> -[Super Admins](/docs/collaborating-in-postman/roles-and-permissions/#team-roles) and [API Governance Managers](/docs/collaborating-in-postman/roles-and-permissions/#team-roles) can configure rules an
Hey @claireriley can we try to add this banner at the top, and have it say that Team Admins with the developer role can do so and so.
Asking since there are a few sections on this page which need a similar banner and do not contain them.

2023-03-14 21:05 UTC, merged