[TW-906] API Governance and Security rule editor updates
postmanlabs/postman-docs pull request #4641
Opened 2023-03-08 16:47 UTC by MatthewPinsker-postman

* Updated "Adding custom rule" instructions for API Governance and Security pages
* Updated screenshots in the API Governance page
* Mentioned the new boilerplate rule, snippets, and autocomplete suggestions
* In API Governance, mentioned that you can also write and use custom functions. Pointed to the new page about custom functions, which is part of ticket `907`

*** API Security screenshots aren't updated yet

2023-03-08 17:28 UTC, mark-anthony-postman approved these changes
Looks great! Just one link to check 😀

2023-03-08 17:28 UTC, mark-anthony-postman commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> +> You can write and add custom functions to your custom rules. For more information, see [Configuring custom functions](/docs/api-governance/configurable-rules/configuring-custom-functions/).
Link not working - not sure what section this is supposed to point to

2023-03-08 17:32 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> +> You can write and add custom functions to your custom rules. For more information, see [Configuring custom functions](/docs/api-governance/configurable-rules/configuring-custom-functions/).
Thanks for catching this! This link points to a page that I'm working on in branch `tw-907-governance-custom-functions`.

2023-03-08 19:00 UTC, jkonrath-postman approved these changes
LGTM

2023-03-09 22:36 UTC, claireriley approved these changes
LGTM! 🌟

2023-03-09 22:36 UTC, claireriley commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> +    <img alt="Create a custom API Governance rule" src="https://assets.postman.com/postman-docs/v10/api-governance-create-custom-rule-v10-2.jpg" width="800px"/>
Since the text is a bit hard to read here, I'd recommend removing the width value so users can select it to open up the larger viewing pop-up
```suggestion
    <img alt="Create a custom API Governance rule" src="https://assets.postman.com/postman-docs/v10/api-governance-create-custom-rule-v10-2.jpg"/>
```

2023-03-09 22:36 UTC, claireriley commented on src/pages/docs/api-governance/configurable-rules/configuring-api-security-rules.md
>      <img alt="Create a custom API Security rule" src="https://assets.postman.com/postman-docs/v10/api-security-create-new-custom-rule-v10.jpg" width="800px"/>
To allow users to select to open the larger view
```suggestion
    <img alt="Create a custom API Security rule" src="https://assets.postman.com/postman-docs/v10/api-security-create-new-custom-rule-v10.jpg"/>
```

2023-03-10 11:06 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
>  > Only Team Admins with a [Developer role](/docs/collaborating-in-postman/roles-and-permissions/#team-roles) can create custom API Governance rules.
Let's rephrase this to say that "Only members with an API Governance Manager role can..."

2023-03-10 11:08 UTC, savageCoder55 commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> +1. Find your new rule under the **Rules** tab and turn it on.
Should we add the fact that this is available in the "Created by you" section.
Also we shouldn't say turn it on - rather say that add it to the workspace group on which you want the respective rule enforced.

2023-03-10 11:09 UTC, savageCoder55 requested changes
Couple comments added. Should be easy to fix.

2023-03-10 16:48 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
>  > Only Team Admins with a [Developer role](/docs/collaborating-in-postman/roles-and-permissions/#team-roles) can create custom API Governance rules.
This is now updated in both the API Governance and API Security pages. For the API Security page, I wrote "API Security Manager" instead.

2023-03-10 18:25 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
> +1. Find your new rule under the **Rules** tab and turn it on.
This is now updated in both the API Governance and API Security pages.

2023-03-10 18:56 UTC, savageCoder55 approved these changes

2023-03-14 14:37 UTC, MatthewPinsker-postman commented on src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
>  > Only Team Admins with a [Developer role](/docs/collaborating-in-postman/roles-and-permissions/#team-roles) can create custom API Governance rules.
It's my understanding that we're no longer releasing the API Security Manager and API Governance manager team-level roles. I reverted the content back to its previous version.

2023-03-14 15:57 UTC, savageCoder55 approved these changes

2023-03-14 19:49 UTC, merged