TW-918 Live Collections
postmanlabs/postman-docs pull request #4647
Opened 2023-03-10 18:53 UTC by jkonrath-postman

2023-03-10 20:43 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +_Postman Live Collections_ enable you to keep your collections up-to-date based on the usage of your endpoint. By observing your application, Live collections automatically creates and updates your c
Do we want to treat "Live Collections" as the feature's name, or do we want to consider this in its plural form?

I'm asking because the first sentence assumes the name is plural, `_Postman Live Collections_ enable you to keep your collections up-to-date ...`. Then the second sentence assumes the ending "s" is part of the name, `... Live collections automatically creates and updates your collections.`

2023-03-10 20:46 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +Postman Live Collections can be enabled by developers by self-instrumenting their code using the Postman SDK. Once enabled, Live collections:
Is there a different word we can use other than "self-instrumenting"? I'm asking because this might increase the page's readability score.

2023-03-10 20:47 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +* Empowers developers to automatically create and maintain collections
```suggestion
* Empower developers to automatically create and maintain collections
```

2023-03-10 20:47 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +* Empowers developers to automatically create and maintain collections
I removed the ending "s" to align with the other two list items. Depending on our answer to my first question, this could change.

2023-03-10 20:49 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-sdk-install.md
> +To start using Live collections, create a collection, then install the Postman SDK in your application.
Should we define "SDK" the first time we use it?

2023-03-10 21:03 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-sdk-install.md
> +1. Create a new collection. Select **New**, then select **Live Collection**. Or in an existing collection, select the <img alt="Live collections icon" src="https://assets.postman.com/postman-docs/v10
What about something like: 

`To create a new Live collection, select **New**, then select **Live Collection**. To enable Live collections for an existing collection, select a collection, select the Live collections icon <img alt="Live collections icon" src="https://assets.postman.com/postman-docs/v10/icon-live-collections.jpg#icon" width="16px"> in the right sidebar, then select **Enable Live**.`

2023-03-10 21:09 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-sdk-install.md
> +1. Configure the Postman SDK by adding a code snippet to your application. For example, for Node.js and Express.js, paste the given code into your app's main `index.js` file:
```suggestion
1. Configure the Postman SDK by adding a code snippet to your application. For example, for a Node.js application using the Express.js framework, paste the given code into your app's main `index.js` file:
```

2023-03-10 21:09 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-sdk-install.md
> +    ![Live Collections configure SDK](https://assets.postman.com/postman-docs/v10/live-collections-configure-sdk.jpg)
Should we blur the collection ID in the screenshot?

2023-03-10 21:42 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-sdk-install.md
> +    1. Select **Generate Key** to create a new key, or **Use Existing Key** to use one you've previously created.
If my understanding is correct, you can either add the Postman API key to the code snippet using a variable in your application, or add the key directly to the code snippet. Either way, it seems like we want users to select the **Add API Key** button so they can get their key.

Also, it seems like we want users to get their API key before pasting the code snippet into their `index.js` file.

What if we make updates similar to the following:

```
5. Configure the Postman SDK by adding a code snippet to your application. First, add a Postman API key to the code snippet. You can do this with a variable in your application, or add it to the code snippet. Select **Add API Key**. Then select **Generate Key** to create a new key, or **Use Existing Key** to use one you've previously created.

    ![Live Collections configure SDK](https://assets.postman.com/postman-docs/v10/live-collections-add-api-key.jpg)

6. Add the code snippet into your app's main `index.js` file. For example, for a Node.js application using the Express.js framework, copy the following code:

    ![Live Collections configure SDK](https://assets.postman.com/postman-docs/v10/live-collections-configure-sdk.jpg)

7. Restart your application if it's already running.
```

2023-03-10 21:57 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +When the first request is detected by the Live Collection, you'll see a notification next to the collection. By default, the request will automatically be added to the collection. You can also choose
It seems like this section is about selecting the **Automatically update collection** radio button. What if we update this to something like:

`When the first request is detected by the Live Collection, you'll see a notification next to the collection. By default, the request will automatically be added to the collection. To automatically update a Live collection as it detects updates, select **Automatically update collection**, and then select **Save**.`

The content in this sentence might be a good candidate for the intro: `You can also choose to either automatically update the collection or to manually review updates before making them.`

2023-03-10 22:00 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +1. Select manual updates from the first request popup shown above, or in [Live Collections settings](/docs/collections/live-collections/live-collections-settings).
To align with my above suggestion, what if we update this to something like:

`1. In the notification next to the collection, select **Review before updating**, and then select **Save**. You can also do this in [Live Collections settings](/docs/collections/live-collections/live-collections-settings).

2023-03-10 22:01 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +1. When the live collections icon <img alt="Live collections icon" src="https://assets.postman.com/postman-docs/v10/icon-live-collections.jpg#icon" width="16px"> next to the collection name is orange
Instead of "orange", what if we wrote something like "solid". I'm suggesting this because I'm not sure how using a color name might impact folks who are colorblind.

2023-03-10 22:03 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +1. Select **Update Collection** to accept the changes and update the collection, or **Reject all** to ignore them.
```suggestion
1. Select **Update Collection** to accept the changes and update the collection, or select **Reject all** to ignore them.
```

2023-03-10 22:04 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +To see the changelog, open the collection and select the changelog icon <img alt="Changelog icon" src="https://assets.postman.com/postman-docs/icon-changelog-v9.jpg#icon" width="18px"> on the right.
```suggestion
To see the changelog, open the collection and select the changelog icon <img alt="Changelog icon" src="https://assets.postman.com/postman-docs/icon-changelog-v9.jpg#icon" width="18px"> in the right sidebar.
```

2023-03-10 22:04 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +<img alt="Changelog view" src="https://assets.postman.com/postman-docs/v10/changelog-view.jpg" width="250px"/>
What do you think about increasing the images width? It's a little difficult to read the text in the image.

2023-03-10 22:06 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +To see the changelog, open the collection and select the changelog icon <img alt="Changelog icon" src="https://assets.postman.com/postman-docs/icon-changelog-v9.jpg#icon" width="18px"> on the right.
This suggestion is based on instructions at `/docs/collections/live-collections/live-collections-sdk-install/`. When we reference the live collections icon, we mention that it's in the right sidebar.

2023-03-10 22:08 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +Select the <img alt="Live collections icon" src="https://assets.postman.com/postman-docs/v10/icon-live-collections.jpg#icon" width="16px"> in the right sidebar of a Live Collection to view configurat
What if we write something like:

`To view configuration options, select a collection, and then select the live collections icon <img alt="Live collections icon" src="https://assets.postman.com/postman-docs/v10/icon-live-collections.jpg#icon" width="16px"> in the right sidebar.`

2023-03-10 22:08 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +<img alt="Live collections settings page" src="https://assets.postman.com/postman-docs/v10/live-collections-settings-page.jpg" width="250px">
What if we increase the image width? The text in the image is a little difficult to read.

2023-03-10 22:09 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +* Select **Status** to enable or disable data collection for the Live Collection.
```suggestion
* Select **Status** to turn data collection on or off for the Live Collection.
```

2023-03-10 22:14 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +* Choose how updates are performed. You can select if the Live Collection is automatically updated, or if you must review changes before updating. For more information, see [Updating Live Collections
What if we updated this to something like:

`Choose how updates are performed. You can choose whether changes to a Live Collection are automatically updated, or changes must be reviewed before updating. For more information, see [Updating Live Collections](/docs/collections/live-collections/update-live-collections/).`

2023-03-10 22:16 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +```
Code block needs a syntax label. `shell` might work

2023-03-10 22:34 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +Data redaction and truncation settings can be configured directly in the service that was instrumented. This ensures that sensitive data does not reach Postman. The data redaction rule takes in a reg
Is there a word we could use other than "instrumented"? My concern is that this might increase the page's readability score.

2023-03-10 22:35 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +Data redaction and truncation settings can be configured directly in the service that was instrumented. This ensures that sensitive data does not reach Postman. The data redaction rule takes in a reg
Is "regex" shorthand for something? I'm asking in case we're able to define this here.

2023-03-10 22:38 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +The above rules for data redaction obfuscate values for those fields
What if we update this to something like: `The data redaction and truncation rules hide values for the fields.`

2023-03-10 22:38 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +The data truncation option in the configuration truncates the actual values for the different fields
```suggestion
The data truncation option in the configuration truncates the actual values for the different fields.
```

2023-03-10 22:39 UTC, MatthewPinsker-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +<img alt="Live collections data truncation" src="https://assets.postman.com/postman-docs/v10/live-collections-data-truncation.jpg" width="250px">
What if we increase the image width? The text in the image is a little difficult to read.

2023-03-13 14:04 UTC, jkonrath-postman commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +_Postman Live Collections_ enable you to keep your collections up-to-date based on the usage of your endpoint. By observing your application, Live collections automatically creates and updates your c
Reworded this slightly. I've had some input from marketing on the exact terminology and we'll add it in the next style guide cycle.

2023-03-13 14:19 UTC, jkonrath-postman commented on src/pages/docs/collections/live-collections/live-collections-sdk-install.md
> +To start using Live collections, create a collection, then install the Postman SDK in your application.
It's fine

2023-03-13 14:20 UTC, jkonrath-postman commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +Postman Live Collections can be enabled by developers by self-instrumenting their code using the Postman SDK. Once enabled, Live collections:
It's their term, so we should keep it.

2023-03-13 16:38 UTC, jkonrath-postman commented on src/pages/docs/collections/live-collections/live-collections-sdk-install.md
> +    ![Live Collections configure SDK](https://assets.postman.com/postman-docs/v10/live-collections-configure-sdk.jpg)
That's a fake collection. (Star Wars fans might see the easter egg here...)

2023-03-13 16:39 UTC, jkonrath-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +Data redaction and truncation settings can be configured directly in the service that was instrumented. This ensures that sensitive data does not reach Postman. The data redaction rule takes in a reg
Fixed, but GH isn't letting me mark this as resolved for some reason...

2023-03-13 17:03 UTC, MatthewPinsker-postman approved these changes
Looks good! I added a few suggestions.

2023-03-13 17:43 UTC, mark-anthony-postman approved these changes
Looking good! Made some suggestions

2023-03-13 17:43 UTC, mark-anthony-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +This page shows when a Live Collection was last updated. The following options are available:
```suggestion
The following configuration options are available:
```

2023-03-13 17:43 UTC, mark-anthony-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +* Choose how updates are performed. You can choose whether changes to a Live Collection are automatically updated, or changes must be reviewed before updating. For more information, see [Updating Liv
```suggestion
* Select how updates are performed. You can choose whether changes to a Live Collection are automatically updated, or if changes must be reviewed before updating. For more information, see [Updating Live Collections](/docs/collections/live-collections/update-live-collections/).
```

2023-03-13 17:43 UTC, mark-anthony-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +Data redaction and truncation settings can be configured directly in the service that was instrumented. This ensures that sensitive data does not reach Postman. The data redaction rule takes in a reg
```suggestion
You can configure data redaction and truncation settings for your application. This ensures that sensitive data does not reach Postman. The data redaction rule uses a regular expression to identify the text to be redacted.
```

2023-03-13 17:43 UTC, mark-anthony-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +The data redaction and data truncation rules can be set up by adding the following lines of code in the service that was instrumented:
```suggestion
To set up the data redaction and data truncation rules add the following lines of code in your application:
```

2023-03-13 17:43 UTC, mark-anthony-postman commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +The data redaction rules obfuscate values for those fields.
```suggestion
The data redaction rules obfuscate values for the specified fields.
```

2023-03-13 17:43 UTC, mark-anthony-postman commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +Every time a new update comes in, you will be notified by the live Collections icon <img alt="Live collections icon" src="https://assets.postman.com/postman-docs/v10/icon-live-collections.jpg#icon" w
```suggestion
Every time the collection is updated, you will be notified by the Live Collections icon <img alt="Live collections icon" src="https://assets.postman.com/postman-docs/v10/icon-live-collections.jpg#icon" width="16px"> next to the collection name turning solid orange.
```

2023-03-13 17:43 UTC, mark-anthony-postman commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +1. When the Live Collections icon <img alt="Live Collections icon" src="https://assets.postman.com/postman-docs/v10/icon-live-collections.jpg#icon" width="16px"> next to the collection name is orange
```suggestion
1. When the Live Collections icon <img alt="Live Collections icon" src="https://assets.postman.com/postman-docs/v10/icon-live-collections.jpg#icon" width="16px"> next to the collection name is solid orange, select it, then select **Review changes**.
```

2023-03-13 18:27 UTC, jkonrath-postman commented on src/pages/docs/collections/live-collections/live-collections-sdk-install.md
> +    1. Select **Generate Key** to create a new key, or **Use Existing Key** to use one you've previously created.
I had to reword this slightly - it's not always the index.js file depending on language, and you wouldn't necessarily need to go to the API key page if you already have it set in your app for some other reason. (This is an advanced situation and we shouldn't explain it all here.)

2023-03-13 20:15 UTC, shubhbhargav requested changes

2023-03-13 20:15 UTC, shubhbhargav commented on src/components/LeftNav/LeftNavItems.jsx
> +            name: 'Live Collections overview',
This plural `Live Collections` seems weird across the page names.

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +_Postman Live Collections_ enable you to keep your collections up-to-date based on the usage of your endpoint. By observing your application, Live Collections automatically create and update your col
usage of your endpoint -> usage of your application

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +_Postman Live Collections_ enable you to keep your collections up-to-date based on the usage of your endpoint. By observing your application, Live Collections automatically create and update your col
Also `Live Collections` does not create / update collections. `Postman SDK` does. 
In addition, it does NOT create the collections, just updates them

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +* **Faster development** - A Postman Live Collection streamlines the development process by enabling developers to quickly and easily test their changes. This can help identify and fix issues early o
The content seems to be the same as `Better testing`

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +* **Improved quality** - By using a Postman Live Collection, developers and testers can catch issues and bugs earlier in the development process. This can lead to higher quality APIs and a better ove
Same as `Better testing`

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +* Automatically create and maintain collections
Remove `create`. Rather than `maintain`, we can say `Automatically keep collections up-to-date`

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +* Get insights from usage patterns to help build high-quality, efficient, and secure APIs
What kind of insights are we referring to @aravind-arun ?

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +* Automate testing and troubleshoot workflows
How are we automating the testing workflow with Live Collections? @aravind-arun

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +To get started with Live Collections, see [Live Collections SDK installation](/docs/collections/live-collections/live-collections-sdk-install/).
It is not just SDK installation right? Its the overall Live Collection Setup.

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +You can configure Live Collections from the right sidebar in Postman. You can also configure data redaction within your service.
>  You can also configure data redaction within your service.
We can't do that from the Sidebar right? @aravind-arun

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +* [Redacting data in the service code](#redacting-data-in-the-service-code)
`Redacting sensitive data`

Also we are not redacting data in the service code.

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +* Select **Status** to turn data collection on or off for the Live Collection.
What does `off` mean here? We should mention that.

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +dataTruncation: true,
@aravind-arun This is outdated. Can we get the latest config from @piyush-daga ?

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +The data redaction rules obfuscate values for the specified fields.
It doesn't obfuscate for specific fields. It does it for all the fields, basically wherever the regex matches.

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +The data truncation option in the configuration truncates the actual values for the specified fields.
Data Truncation is not field specific.

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +Whenever Live Collections detect a new event from the API traffic, it will trigger an update workflow. Updates can apply to existing requests or result in new requests being added to the collection.
@aravind-arun Aren't we avoiding Traffic terminology?

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +When the first request is detected by the Live Collection, you'll see a notification next to the collection. By default, the request will automatically be added to the collection. To automatically up
> you'll see a notification next to the collection
It won't happen for all the collections. It only happens once in the onboarding workflow.

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +Selecting automatic updates will result in requests getting automatically created or updated anytime they are observed in the API traffic.
Same comment as the above related to Traffic terminology.

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +Every time the collection is updated, you will be notified by the Live Collections icon <img alt="Live collections icon" src="https://assets.postman.com/postman-docs/v10/icon-live-collections.jpg#ico
This doesn't happen for auto updates. User can check the updates on the Changelogs but there is no UI indication for auto updates.

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +1. In the notification next to the collection, select **Review before updating**, and then select **Save**. You can also do this in [Live Collections settings](/docs/collections/live-collections/live
We haven't explained what this notification refers to. We should add some info around that.

2023-03-13 20:15 UTC, shubhbhargav commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +To see the changelog, open the collection and select the changelog icon <img alt="Changelog icon" src="https://assets.postman.com/postman-docs/icon-changelog-v9.jpg#icon" width="18px"> in the right s
User can also go to the Changelogs from the hover over information on top of the lightning / Live Collection icon.

2023-03-13 20:39 UTC, jkonrath-postman commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +* **Improved quality** - By using a Postman Live Collection, developers and testers can catch issues and bugs earlier in the development process. This can lead to higher quality APIs and a better ove
@aravind-arun - let me know what you want here and in the next one.

2023-03-13 22:59 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +* **Faster development** - A Postman Live Collection streamlines the development process by enabling developers to quickly and easily test their changes. This can help identify and fix issues early o
We can remove the 'Improved Quality' line

2023-03-14 03:43 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +* **Faster development** - A Postman Live Collection streamlines the development process by enabling developers to quickly and easily test their changes. This can help identify and fix issues early o
Suggesting the following text for the 'faster development' description
Faster development: A Postman Live Collection can streamline the development process by allowing developers to quickly and easily set up their collection and maintain it. This can help automate the manual process of creating and updating collections which can result in an incomplete collection.

2023-03-14 03:58 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +* Get insights from usage patterns to help build high-quality, efficient, and secure APIs
These insights would be the actual examples(with payload) and the status codes that we are adding to the collection. Clarified that now
"Bring insights such as error codes and examples from usage patterns for developers to build quality, efficient and secure APIs"

2023-03-14 04:01 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +* **Improved quality** - By using a Postman Live Collection, developers and testers can catch issues and bugs earlier in the development process. This can lead to higher quality APIs and a better ove
Removed the 'Improved Quality' benifit

2023-03-14 05:32 UTC, piyush-daga commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +dataTruncation: true,
```
truncateData: true,
redactSensitiveData: {
	enable: true,
  	rules: {
    		api_key: '\\b\\w{32}\\b',
	        email_rule: '([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})',
        	bearerToken: '[bB]earer ([a-zA-Z]+[0-9]|[0-9]+[a-zA-Z]])[a-zA-Z0-9/+_.-]{15,1000}(?![a-zA-Z0-9/+.-])',
	}
}
```

2023-03-14 07:34 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/live-collections-overview.md
> +* Automate testing and troubleshoot workflows
This does not apply to the current iteration of live collections. We can remove it

2023-03-14 07:37 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +Whenever Live Collections detect a new event from the API traffic, it will trigger an update workflow. Updates can apply to existing requests or result in new requests being added to the collection.
Yes. I propose changing it to 'Whenever Live Collections observes a new API event in the service that was instrumented'

2023-03-14 07:43 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +You can configure Live Collections from the right sidebar in Postman. You can also configure data redaction within your service.
@jkonrath-postman - We need to make it explicit that there are two different configuration options available. One from the sidebar and the other in the instrumentation code similar to what was capture here - https://postmanlabs.atlassian.net/wiki/spaces/AO/pages/4404184006/Postman+Live+Collection+Settings
I suggest changing that sentence to
"You can configure Live Collections settings such as update preference or status from the right sidebar in Postman. You can configure data redaction and data truncation settings only within the instrumentation code in your service. "

2023-03-14 07:45 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +Selecting automatic updates will result in requests getting automatically created or updated anytime they are observed in the API traffic.
We can change it to "Selecting automatic updates will result in requests getting automatically created or updated anytime the API events are observed in the service"

2023-03-14 07:51 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +Every time the collection is updated, you will be notified by the Live Collections icon <img alt="Live collections icon" src="https://assets.postman.com/postman-docs/v10/icon-live-collections.jpg#ico
@jkonrath-postman - Can we follow a structure similar to automatic updates section mentioned here - https://postmanlabs.atlassian.net/wiki/spaces/AO/pages/4404053133/Automatic+Updates+to+the+Postman+Live+Collection
"Whenever the first request is detected by the live collection, it will automatically add it to the collection. This will also provide a choice to either automatically update the collection or to manually review before updating. Setting automatic updates will result in requests getting automatically created or updated anytime they are observed in the API traffic without any user notification"

2023-03-14 07:53 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +* Select **Status** to turn data collection on or off for the Live Collection.
Let me know if this works
"Turning off data collection ensures that the Postman SDK does not send any data to the Postman cloud. This will also stop detecting any changes to the request along with the automatic or manual updates to the collection"

2023-03-14 08:05 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +1. In the notification next to the collection, select **Review before updating**, and then select **Save**. You can also do this in [Live Collections settings](/docs/collections/live-collections/live
@jkonrath-postman - By notification here, do you mean the following notification that was called out in the automatic updates section? "When the first request is detected by the Live Collection, you'll see a notification next to the collection..."

2023-03-14 08:08 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +To see the changelog, open the collection and select the changelog icon <img alt="Changelog icon" src="https://assets.postman.com/postman-docs/icon-changelog-v9.jpg#icon" width="18px"> in the right s
@jkonrath-postman - The lightning icon next to the collection name can also serve as an entry point for 2 workflows
1. Viewing the change log
2. Live settings page
Lets add this as an entry point in both these places
<img width="781" alt="Screen Shot 2023-03-14 at 1 07 28 AM" src="https://user-images.githubusercontent.com/119476416/224936020-9952f851-2ae8-4749-9419-3076c6a0e21e.png">

2023-03-14 14:38 UTC, jkonrath-postman commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +1. In the notification next to the collection, select **Review before updating**, and then select **Save**. You can also do this in [Live Collections settings](/docs/collections/live-collections/live
I just meant that the lightning bolt turns from hollow and gray to full and orange. (Although we shouldn't say orange because we try not to refer to color in the docs because of accessibility.

2023-03-14 21:22 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +The data truncation option in the configuration truncates the actual values for the matched fields.
The data truncation rule in the configuration truncates the actual values for the all fields. It is not based on the regex matching. Can you update the text to "The data truncation option in the configuration truncates the actual values for all the fields"

2023-03-14 21:35 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +Selecting automatic updates will result in requests getting automatically created or updated any time the API events are observed in the service.
can we add that no notifications will be received for this - "Selecting automatic updates will result in requests getting automatically created or updated any time the API events are observed in the service without any notifications being sent"

2023-03-14 21:35 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +1. Hover over the Live Collections icon <img alt="Live Collections icon" src="https://assets.postman.com/postman-docs/v10/icon-live-collections.jpg#icon" width="16px"> and select **Review changes**.
Can we also call out the other entry point from the settings page to set the option to manually review changes

2023-03-14 21:35 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/update-live-collections.md
> +1. Review the incoming changes. These can be an addition of a new request or changes to an existing request. Postman also creates new examples based on the response received from the API traffic.
We wanted to remove mentions of traffic. Can we change this to "examples based on the response received from the API events on the application"

2023-03-14 21:42 UTC, aravind-arun approved these changes

2023-03-15 15:21 UTC, aravind-arun commented on src/pages/docs/collections/live-collections/live-collections-settings.md
> +
There are 2 changes here

1. We need to add a note at the top recommending users to not deploy on production without turning on data truncation and data redaction
"Do not deploy on production systems without enabling the data truncation and data redaction rules as this could result in sensitive data being sent to Postman"
2. We need to separate out the data truncation and data redaction settings with details on what they mean and how to turn each of them on. Here is my proposal for that

"Data truncation - Data truncation removes the fields from the request and response body. This will result in only the types being sent
Enabling data truncation - The following option needs to be added in the code to enable data truncation <add code snippet>
Example request body after enabling data truncation"

"Data redaction - Data redaction removes sensitive data from the request header, response header, request body, response body and query params. The data redaction rules obfuscate values for the fields matched by the regular expression
Enabling data redaction - Data redaction can be enabled by adding the following option in the code and specifying the regex to match and obfuscate the data <code snippet for data redaction>
Example request header after enabling data redaction <insert image for data redaction>

2023-03-15 23:43 UTC, merged