[TW-974] Reorganize uptime monitor content
postmanlabs/postman-docs pull request #4671
Opened 2023-03-21 15:22 UTC by mark-anthony-postman

2023-03-21 16:33 UTC, postfrzero requested changes
Mostly LGTM, just a minor change and a suggestion.

2023-03-21 16:33 UTC, postfrzero commented on src/pages/docs/monitoring-your-api/intro-monitors.md
> +Because monitors run in the cloud, there are some differences compared to sending requests and running collections in Postman. To learn more, see the [Monitoring FAQs](/docs/monitoring-your-api/faqs-
*monitors and scheduled collection runs

The limitations apply to both since they use the same underlying platform.

2023-03-21 16:33 UTC, postfrzero commented on src/pages/docs/monitoring-your-api/intro-monitors.md
> +## Uptime monitors
I think we can remove this section altogether?

2023-03-21 17:15 UTC, mark-anthony-postman commented on src/pages/docs/monitoring-your-api/intro-monitors.md
> +## Uptime monitors
It's gone now! 💥

2023-03-21 17:17 UTC, mark-anthony-postman commented on src/pages/docs/monitoring-your-api/intro-monitors.md
> +Because monitors run in the cloud, there are some differences compared to sending requests and running collections in Postman. To learn more, see the [Monitoring FAQs](/docs/monitoring-your-api/faqs-
Cool, I added scheduled collection runs to this statement as you suggested

2023-03-21 17:37 UTC, postfrzero approved these changes
LGTM! Added one comment, but it's just me being curious.

2023-03-21 17:37 UTC, postfrzero commented on src/pages/docs/monitoring-your-api/faqs-monitors.md
> +For collection-based monitors, there is no limit to the number of requests, but the total runtime can't exceed 10 minutes (Postman Free plans) or 15 minutes (Postman paid plans).
I get confused between "runtime" and "run time". Should this be "run time" instead, since it's not being used as a noun here but rather as "time taken for the run"?

2023-03-21 17:50 UTC, mark-anthony-postman commented on src/pages/docs/monitoring-your-api/faqs-monitors.md
> +For collection-based monitors, there is no limit to the number of requests, but the total runtime can't exceed 10 minutes (Postman Free plans) or 15 minutes (Postman paid plans).
I think it's a bit of personal preference, but the Oxford Dictionary defines "runtime" as a noun meaning:

- the length of time a program takes to run.
- the time at or during which a program is run.
- a cut-down version of a program that can be run but not changed.

So i think keeping it as "runtime" is okay 😅

2023-03-21 18:13 UTC, postfrzero commented on src/pages/docs/monitoring-your-api/faqs-monitors.md
> +For collection-based monitors, there is no limit to the number of requests, but the total runtime can't exceed 10 minutes (Postman Free plans) or 15 minutes (Postman paid plans).
Cool cool cool. I just asked because I'm never sure myself when I'm writing. I'll keep this mind. 😄

2023-03-24 17:37 UTC, jkonrath-postman approved these changes
LGTM

2023-03-24 17:38 UTC, merged