PAPI-1649 Update Postman API intro-api title for SEO optimization
postmanlabs/postman-docs pull request #4778
Opened 2023-05-04 20:00 UTC by akinard-postman

Per feedback from marketing, this updates the page title to optimize its SEO presence and visibility.

2023-05-04 20:18 UTC, mark-anthony-postman requested changes

2023-05-04 20:18 UTC, mark-anthony-postman commented on src/pages/docs/developer/postman-api/intro-api.md
> +title: "Postman API documentation"
You also need to change the title in the left nav by editing `src/components/LeftNav/LeftNav.jsx`

2023-05-04 20:50 UTC, jkonrath-postman approved these changes
LGTM! Add my one suggestion on the search keyword and 🚢

2023-05-04 20:50 UTC, jkonrath-postman commented on src/pages/docs/developer/postman-api/intro-api.md
>  search_keyword: "postman-api"
```suggestion
search_keyword: "Postman API docs"
```

2023-05-04 21:24 UTC, akinard-postman commented on src/pages/docs/developer/postman-api/intro-api.md
> +title: "Postman API documentation"
Thanks for catching this @mark-anthony-postman @jkonrath-postman !

2023-05-04 21:26 UTC, akinard-postman commented on src/pages/docs/developer/postman-api/intro-api.md
> +title: "Postman API documentation"
I'm going to resolve this as the update in LeftNav was addressed. Thanks for that, @jkonrath-postman !

2023-05-05 00:34 UTC, mark-anthony-postman approved these changes
Updates look good!

2023-05-05 12:30 UTC, merged