[TW-1028] Doc offline API Client (Scratch Pad v2)
postmanlabs/postman-docs pull request #4779
Opened 2023-05-08 20:06 UTC by mark-anthony-postman

- Added new page: Getting Started > Using the Postman API Client
- Updated page: Getting Started > Using the Scratch Pad
- Updated other references to Scratch Pad

2023-05-08 21:01 UTC, petewitcher-postman commented on src/pages/docs/getting-started/using-api-client.md
> +If you don't have a Postman account, or want to use a new account, select **Create Account** in the header. Follow the onscreen instructions, or learn more about [signing up for Postman account](/doc
```suggestion
If you don't have a Postman account, or want to use a new account, select **Create Account** in the header. Follow the onscreen instructions, or learn more about [signing up for a Postman account](/docs/getting-started/postman-account/#signing-up-for-a-postman-account).
```

2023-05-08 21:06 UTC, petewitcher-postman approved these changes
LGTM! I made one minor suggestion.

2023-05-09 13:52 UTC, giridharvc7 requested changes

2023-05-09 13:52 UTC, giridharvc7 commented on src/components/LeftNav/LeftNavItems.jsx
> +        name: 'Using the API Client',
Calling this offline API Client would make even more sense here. 
Using just "API Client" can be confusing.

2023-05-11 05:50 UTC, giridharvc7 requested changes

2023-05-11 05:50 UTC, giridharvc7 commented on src/components/LeftNav/LeftNavItems.jsx
> +        name: 'Using the offline API Client',
Can we get a concensus on of the `O` in `Offline API Client` should be capitalized?

2023-05-11 05:50 UTC, giridharvc7 commented on src/pages/docs/getting-started/using-offline-api-client.md
> +> You can also use the offline API Client to write and execute [test scripts](/docs/writing-scripts/pre-request-scripts/) and to [visualize response data](/docs/sending-requests/visualizer/).
Should we also mention about changing protocols of a request if needed?

2023-05-11 13:36 UTC, jkonrath-postman commented on src/components/LeftNav/LeftNavItems.jsx
> +        name: 'Using the offline API Client',
@giridharvc7 @mark-anthony-postman I just raised this question in Slack - let's find out there.

2023-05-11 13:42 UTC, jkonrath-postman commented on src/components/LeftNav/LeftNavItems.jsx
> +        name: 'Using the offline API Client',
Answer: It is lowercase o.

2023-05-11 15:04 UTC, mark-anthony-postman commented on src/pages/docs/getting-started/using-offline-api-client.md
> +> You can also use the offline API Client to write and execute [test scripts](/docs/writing-scripts/pre-request-scripts/) and to [visualize response data](/docs/sending-requests/visualizer/).
I added a note about using the protocol switcher

2023-05-12 13:38 UTC, giridharvc7 approved these changes

2023-05-12 17:08 UTC, jkonrath-postman approved these changes
LGTM

2023-05-12 19:48 UTC, merged