[TW-964] Breadcrumb redesign
postmanlabs/postman-docs pull request #4818
Opened 2023-05-22 22:06 UTC by MatthewPinsker-postman

To edit the name if Postman elements, you select the name in this release. We're removing the edit icon that appears on hover.

2023-06-06 10:27 UTC, devanSAGA commented
Just FYI, the same rename interaction is also integrated in renaming workspace name - the edit icon is removed and we need to click the workspace name to edit it inside the Workspace Overview page ([postman-app track for reference](https://go.postman-beta.co/?_track=br-feature-AETHER-1841-migrate-to-breadcrumb-v2))

Does this change also requires any change in docs?

2023-06-06 10:28 UTC, devanSAGA commented
Do this changes gets deployed somewhere? on a preview track or something? Is there a link that I can compare with existing docs to better understand the changes visually? 

Or do I need to clone the repo and check it locally?

2023-06-06 10:28 UTC, devanSAGA requested changes

2023-06-06 10:28 UTC, devanSAGA commented on src/pages/docs/collections/using-collections.md
> +1. Select the collection name to give your new collection a name.
Would it make sense to replace Select with Click here?

2023-06-28 18:06 UTC, mark-anthony-postman approved these changes
LGTM! 🌟

2023-07-05 06:39 UTC, devanSAGA approved these changes
LGTM 👍

2023-07-14 14:17 UTC, jkonrath-postman approved these changes
LGTM

2023-07-17 13:24 UTC, merged