[TW-1198] Doc Runner response/request body is not available for team members
postmanlabs/postman-docs pull request #4883
Opened 2023-06-21 15:42 UTC by mark-anthony-postman

2023-06-21 16:02 UTC, petewitcher-postman approved these changes
LGTM

2023-06-21 16:06 UTC, postfrzero approved these changes

2023-06-21 16:19 UTC, nerminamiller-postman reviewed
@mark-anthony-postman left you a bit of feedback, more as an exercise. Feel free to reject any and all comments.

2023-06-21 16:19 UTC, nerminamiller-postman commented on src/pages/docs/collections/running-collections/intro-to-collection-runs.md
> +        > Request and response details are persisted locally during your current Postman session and aren't saved permanently. Signing out of Postman, signing into another device with the same accoun
```suggestion
        > During your current Postman session, request and response details are persisted locally and not saved permanently. Your session will end and your logged data will be removed when you sign out of Postman, sign in to another device with the same account, or refresh your browser.
```

2023-06-21 16:19 UTC, nerminamiller-postman commented on src/pages/docs/collections/running-collections/intro-to-collection-runs.md
> +        > Response and request details are available for the person who started the collection run. Other team members can't view details for collection runs that you start.
```suggestion
        > Only the person who started the collection run can view response and request details. 
```

2023-06-22 15:04 UTC, malvikach requested changes
Can we also add how users can enable persistence for their sessions? (the configuration on runner allows it and maybe couple it with a screenshot)

2023-06-22 16:03 UTC, mark-anthony-postman commented
> Can we also add how users can enable persistence for their sessions? (the configuration on runner allows it and maybe couple it with a screenshot)

@malvikach Already added! There is a procedure with a screenshot that shows users how to configure a collection run, including using the persist option. This updated date is part of the procedure. You should be able to see the whole procedure in the rich diff: https://github.com/postmanlabs/postman-docs/pull/4883/files?short_path=08a20f7#diff-08a20f766a7df607f27d588aac9cdb7dae0c1d0402796a9ddeb5b3b45566f6dd

2023-06-23 06:36 UTC, malvikach approved these changes
Looks good!

2023-06-23 09:05 UTC, beatrixSze approved these changes

2023-06-23 15:34 UTC, merged