[TW-1219] Apply template during workspace creation
postmanlabs/postman-docs pull request #4915
Opened 2023-07-10 21:24 UTC by MatthewPinsker-postman

* Added that you can choose a workspace template when you create a new workspace
* Updated relevant screenshots

**To do:**
* Update screenshot of selecting a Partner workspace (I need access to this feature in an Enterprise team)

2023-07-11 15:53 UTC, mark-anthony-postman approved these changes
LGTM!

2023-07-12 12:57 UTC, ramji367 requested changes
Added one request to update a screenshot. Otherwise everything else looks good!

2023-07-12 12:57 UTC, ramji367 commented on src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md
> +    <img alt="Create new workspace" src="https://assets.postman.com/postman-docs/v10/create-workspace-and-apply-template-v10.jpg" width="400px"/>
For this screenshot can we show the whole screen - the list of templates on the left along with the preview of the template on the right?

2023-07-12 17:56 UTC, ramji367 approved these changes
Looks good to me!

2023-07-13 21:25 UTC, jkonrath-postman approved these changes
LGTM

2023-07-17 12:31 UTC, merged