TW-1223 easy auth publisher flow
postmanlabs/postman-docs pull request #4924
Opened 2023-07-13 03:37 UTC by claireriley

2023-07-13 07:11 UTC, gitThingsDone requested changes
Added some comments, looks good overall

2023-07-13 07:11 UTC, gitThingsDone commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +You can onboard your public API consumers quickly and efficiently by setting up guided API authentication in Postman. This feature enables you to communicate the steps users need to take to successfu
can we also mention that this helps your consumers to send their First successful request faster

2023-07-13 07:11 UTC, gitThingsDone commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +To set up guided API authentication, open Postman and select **Team** in the upper right, then **Team Settings > Set Up API authorization**. Or, select **API Network** from the Postman header, then s
Don't want to use the "guided" API authentication name right now, can we instead just say to set up authentication for your public APIs

2023-07-13 07:11 UTC, gitThingsDone commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +To set up guided API authentication, open Postman and select **Team** in the upper right, then **Team Settings > Set Up API authorization**. Or, select **API Network** from the Postman header, then s
> select **API Network** from the Postman header, then select **Public API Network >

Here, can we say something like, open your public profile, by clicking on API network -> public api network, and select set up api auth

2023-07-13 07:11 UTC, gitThingsDone commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +<img alt="Postman API set up new authorization" src="https://assets.postman.com/postman-docs/v10/postman-api-easier-auth-v10-2.jpg"/>
I am curious is it possible to add a gif here ?

2023-07-13 07:11 UTC, gitThingsDone commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +    > You can use standard [Markdown syntax](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to structure your content and add links to relevant resources.
Not everything in markdown is supported we only support bold, italics, underline, links and bullet points

2023-07-13 07:11 UTC, gitThingsDone commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +12. [Verify your domain](#verifying-your-domain) to complete adding authorization.
we should mention that this is a required step

2023-07-13 07:11 UTC, gitThingsDone commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +<img alt="Verify domain for API authentication" src="https://assets.postman.com/postman-docs/v10/domain-verification-v10.16.jpg"/>
we should mention that this is a required step for your configuration to show up for all users

2023-07-13 07:11 UTC, gitThingsDone commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +Add the copied value to your domain as a DNS TXT record. Then, select **Verify Domain** in Postman to confirm. After your domain is verified, Postman will recognize newly created requests to your API
should we include an example screenshot for how users can add a DNS record (on any DNS server)

2023-07-13 07:11 UTC, gitThingsDone commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +13. Select **Save** to save your API authorization settings.
we can also include an Optional point for advanced configurations available

2023-07-13 18:42 UTC, mark-anthony-postman approved these changes
The new page and changes look good! Made a few suggestion you can consider 😀

2023-07-13 18:42 UTC, mark-anthony-postman commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +Select **Set Up API authorization**.
I think you can delete this line, as they select this in both flows described in the paragraph above

2023-07-13 18:42 UTC, mark-anthony-postman commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +    <img alt="Enter base URL of your API" src="https://assets.postman.com/postman-docs/v10/enter-base-url-api-v10.16.jpg"/>
Add a line of whitespace above and below each `<img>` tag for correct spacing in the output. Also, this should fix the problem with the screenshot in step 2 appearing on the same line as the text

2023-07-13 18:42 UTC, mark-anthony-postman commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +    > You can use basic Markdown syntax like bold, italics, underline, bullet points, and links to structure your content.
Also add a line of whitespace above and below the note

2023-07-13 18:42 UTC, mark-anthony-postman commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +### Verifying your domain
Maybe make this a heading 2? If so, adjust in the Contents section as well

2023-07-13 18:42 UTC, mark-anthony-postman commented on src/components/LeftNav/LeftNavItems.jsx
> +        name: 'Setting up authentication for public APIs',
Curious as to why this page is located here instead of in Collaborating in Postman > Sharing to the Public API Network. Is it because "Using Custom Domains" is also in this section? If so, maybe this topic should follow "Using Custom Domains". Right now it breaks up the flow of Writing --> Publishing --> Viewing docs.

2023-07-13 19:30 UTC, claireriley commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +Select **Set Up API authorization**.
It's actually two buttons unfortunately 😅 one in the left sidebar in both places, then you have to select the second button within the page

2023-07-13 19:52 UTC, claireriley commented on src/components/LeftNav/LeftNavItems.jsx
> +        name: 'Setting up authentication for public APIs',
It was requested to be in the documentation section as it's more publisher-focused. I'm not sure it fits as well into the public API network section as its functionality within the product is larger in scope.

I could change the order, I started with this as it seemed like a logical flow to me for a publisher to write > publish > add auth for consumers, then later be viewing docs, but I could shift it lower. @gitThingsDone any thoughts on this?

2023-07-13 19:55 UTC, claireriley commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +### Verifying your domain
I'd like to keep this as a heading 3 as it's a part of the flow and more of a continuation of setup with specifics vs a completely separate item. It's all on the same page for the user

2023-07-13 21:45 UTC, nerminamiller-postman approved these changes
LGTM! A couple of small suggestions.

2023-07-13 21:45 UTC, nerminamiller-postman commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +    > You can use basic Markdown syntax like bold, italics, underline, bullet points, and links to structure your content.
```suggestion
    > You can use basic Markdown syntax for bold, italics, underline, bullet points, and links to structure your content.
```

2023-07-13 21:45 UTC, nerminamiller-postman commented on src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md
> +9. (Optional) Enter **Authentication scopes** as a comma separated list to restrict what Postman users can access.
```suggestion
9. (Optional) Enter **Authentication scopes** as a comma-separated list to restrict what Postman users can access.
```

2023-07-14 14:15 UTC, jkonrath-postman approved these changes
LGTM

2023-07-14 14:15 UTC, jkonrath-postman commented on src/components/LeftNav/LeftNavItems.jsx
> +        name: 'Setting up authentication for public APIs',
I'd vote to put it right under custom domains. This won't be a common use case for everyone, just like custom domains isn't.

2023-07-17 13:31 UTC, merged