[TW-1224] Update screenshots in Editing an API definition
postmanlabs/postman-docs pull request #5017
Opened 2023-08-21 15:52 UTC by nerminamiller-postman

Updates the create definition screenshot and surrounding text in defining-an-api.md

2023-08-21 17:49 UTC, MatthewPinsker-postman commented on src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md
> +1. From the API's menu, select **Add definition > Author from scratch**. Alternatively, select **create** in the sidebar under the API.
```suggestion
1. From the API's overview, next to **Definition**, select **+** and select **Author from scratch**. Alternatively, select **create** in the sidebar under the API.
```

2023-08-21 18:02 UTC, MatthewPinsker-postman commented on src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md
> +1. Select the definition type and format. We are using OpenAPI and YAML in this example.
Do we want to mention "We are using OpenAPI and YAML in this example."? My concern is that this sentence is dependent on the screenshot loading for the user. We could maybe say "The default selections are ...", but we might run the risk of the UI changing, and then the docs becoming a little out of date.

2023-08-21 18:03 UTC, petewitcher-postman commented on src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md
> +1. Select the definition type and format. We are using OpenAPI and YAML in this example.
```suggestion
1. Select the definition type and format. This example uses OpenAPI and YAML.
```

2023-08-21 18:04 UTC, petewitcher-postman commented on src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md
> +1. Select the definition type and format. We are using OpenAPI and YAML in this example.
Style guide says to avoid using we and our in the core docs (as opposed to tutorials and blog posts).

2023-08-21 18:08 UTC, petewitcher-postman approved these changes
LGTM!

2023-08-21 18:09 UTC, MatthewPinsker-postman commented on src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md
> +    <img alt="Generating an API definition" src="https://assets.postman.com/postman-docs/v10/api-builder-author-definition-v10.17.jpg" width="323px"/>
What do you think about making the screenshot a little bigger? I'm suggesting this because the text in the screenshot is a little difficult to read. I tested the image at `400` and I think it's easier to read.

2023-08-21 18:10 UTC, MatthewPinsker-postman approved these changes
LGTM!

2023-08-21 19:40 UTC, mark-anthony-postman requested changes
I'm not seeing the new screenshot--do you need to upload it?

2023-08-21 19:40 UTC, mark-anthony-postman commented on src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md
> +    <img alt="Generating an API definition" src="https://assets.postman.com/postman-docs/v10/api-builder-author-definition-v10.17.jpg" width="400px"/>
The screenshot link is broken for me. I checked the S3 bucket and don't see `api-builder-author-definition-v10.17.jpg` in it

2023-08-22 14:58 UTC, nerminamiller-postman commented on src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md
> +    <img alt="Generating an API definition" src="https://assets.postman.com/postman-docs/v10/api-builder-author-definition-v10.17.jpg" width="400px"/>
Uploaded and fixed the border!

2023-08-22 15:58 UTC, mark-anthony-postman approved these changes
LGTM!

2023-08-22 16:17 UTC, petewitcher-postman approved these changes
LGTM!

2023-08-22 21:51 UTC, merged