TW-1344 doc MQTT
postmanlabs/postman-docs pull request #5046
Opened 2023-09-08 20:47 UTC by jkonrath-postman

2023-09-08 20:52 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/first-mqtt-request.md
> +    url: "https://www.postman.com/downloads/"
Did we remove prerequisites from all page in the LC? I have the same question for all MQTT pages.

2023-09-08 20:53 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-client-overview.md
> +    name: "Additional resources"
Should we remove this section header since there isn't anything under it?

2023-09-08 20:57 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-client-overview.md
> +MQTT (Message Queuing Telemetry Transport) is a messaging protocol for the Internet of Things (IoT). Its usage spans from simple devices for home automation and wearables, to automating large scale i
```suggestion
MQTT (Message Queuing Telemetry Transport) is a messaging protocol for the Internet of Things (IoT). Its usage spans from simple devices for home automation and wearables, to automating large-scale industrial machineries. It's a lightweight technology modeled on the publish/subscribe pattern where clients connected to a single broker can publish messages to different topics and subscribe to topics to receive messages from other connected clients. The messages are transferred with low-bandwidth usage, low-power consumption, and efficient distribution of information to one or many receivers, all adding to the popularity of MQTT.
```

2023-09-08 20:58 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +MQTT requests in Postman include a variety of tools, views and controls to help you debug and document your MQTT APIs. This topic highlights the parts of the request interface and explains how to use
```suggestion
MQTT requests in Postman include a variety of tools, views, and controls to help you debug and document your MQTT APIs. This topic highlights parts of the request interface and explains how to use them.
```

2023-09-08 20:59 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +MQTT requests in Postman include a variety of tools, views and controls to help you debug and document your MQTT APIs. This topic highlights the parts of the request interface and explains how to use
Also, should we define the MQTT acronym on first use?

2023-09-08 20:59 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/first-mqtt-request.md
> +In this example of an MQTT request, you will connect to a public broker, subscribe to topics, and publish messages.
Should we define the MQTT acronym on first use?

2023-09-08 21:04 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +You can also create a new MQTT request by selecting the **New Tab** icon <img alt="New Tab icon" src="https://assets.postman.com/postman-docs/v10/icon-pin-collection-v10.14.0.jpg#icon" width="16px">
For the plus icon, we usually write something like `Select **+** to open a new tab.`. I don't think we've been using an icon. Not sure if we want to make this change all at once, or incrementally.

Also, we usually don't style icon names in bold. We'd usually write something like `the new tab icon <img alt="New Tab icon" src="https://assets.postman.com/postman-docs/v10/icon-pin-collection-v10.14.0.jpg#icon" width="16px">`.

2023-09-08 21:08 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +You can also create a new MQTT request by selecting the **New Tab** icon <img alt="New Tab icon" src="https://assets.postman.com/postman-docs/v10/icon-pin-collection-v10.14.0.jpg#icon" width="16px">
For the protocol selector, we could also point users here for more information: https://learning.postman.com/docs/sending-requests/requests/#selecting-protocols

We have several instances of referring to the `**Request type** button  next to the request name` as the `protocol dropdown menu to the left of the request's name`. Not sure if we want to use the latter in this instance.

2023-09-08 21:09 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +In the request interface, you can add configuration to connect to an MQTT broker, subscribe to topics, and publish messages. Additionally, you can add last will details, authorization details, custom
```suggestion
In the request interface, you can add a configuration to connect to an MQTT broker, subscribe to topics, and publish messages. Additionally, you can add last will details, authorization details, custom properties, and settings along with the request.
```

2023-09-08 21:09 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +In the request interface, you can add configuration to connect to an MQTT broker, subscribe to topics, and publish messages. Additionally, you can add last will details, authorization details, custom
Not sure if this is correct, but it seemed like a word is missing.

2023-09-08 21:11 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +- **Enter URL** - This is where you enter the broker's address, such as `test.mosquitto.org`. Some MQTT services also require you to define a port number. You can define a port number in the URL by a
Instead of `test.mosquitto.org`, should we use something like `test.example.org`? Asking because our Example Domains and IPs guidelines instruct us to use `example` in domains.

2023-09-08 21:12 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +    > For connecting to the broker over TLS, you need to use `mqtts://` as your URL scheme. For example, `mqtts://test.mosquitto.org`.
```suggestion
    > To connect to the broker over TLS, you need to use `mqtts://` as your URL scheme. For example, `mqtts://test.mosquitto.org`.
```

2023-09-08 21:13 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +    - **MQTT Version** - Every MQTT version has some distinctions in terms of the protocol features. Postman supports two major versions of MQTT; 3.1.1 and 5.0. Version 5.0 is selected by default.
```suggestion
    - **MQTT Version** - Every MQTT version has some distinctions in terms of the protocol features. Postman supports two major versions of MQTT: 3.1.1 and 5.0. Version 5.0 is selected by default.
```

2023-09-08 21:14 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +    - **Client ID** - Client ID is an identifier differentiating each client connected to the broker. By default, Postman generates a random client ID for each request. You can override this by selec
```suggestion
    - **Client ID** - Client ID is an identifier differentiating each client connected to the broker. By default, Postman generates a random client ID for each request. You can override this by selecting **Client ID** and entering a custom client ID.
```

2023-09-08 21:14 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +- **Message** - This is where you compose and Publish messages to the broker. You can write your message in the text area, enter a topic name and select **Send** to publish the message.
```suggestion
- **Message** - This is where you compose and publish messages to the broker. You can write your message in the text area, enter a topic name, and select **Send** to publish the message.
```

2023-09-08 21:16 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +    - **Topic** - You can define the topic name for the message here. The topic name is used by the broker to route the message to the appropriate subscribers.
```suggestion
    - **Topic** - You can define the topic name for the message. The broker uses the topic name to route the message to the appropriate subscribers.
```

2023-09-08 21:18 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +    - **QoS** - QoS defines the guarantee of delivery for the message. You can configure the Quality of Service (QoS) level for the message by selecting the <img alt="More actions icon" src="https://
```suggestion
    - **QoS** - Quality of Service (QoS) defines the guarantee of delivery for the message. You can configure the QoS level for the message by selecting the more actions icon <img alt="More actions icon" src="https://assets.postman.com/postman-docs/icon-more-actions-v9.jpg#icon" width="16px"> and selecting a QoS level.
```

2023-09-08 21:21 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +    - **Retain** - Retain is a flag that asks the broker to retain the last message sent on the topic and send it to the new subscribers even if they join the network after the message was sent from
```suggestion
    - **Retain** - Retain is a flag that asks the broker to retain the last message sent on the topic and send it to the new subscribers. The broker will retain the last message even if the new subscribers join the network after the message was sent from the client. You can configure the retain flag for the message by selecting the more actions icon <img alt="More actions icon" src="https://assets.postman.com/postman-docs/icon-more-actions-v9.jpg#icon" width="16px"> and toggling the **Retain** switch.
```

2023-09-08 21:21 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +    - **Send** - Once you have configured the payload, select the **Send** button to publish the message to the broker.
```suggestion
    - **Send** - Once you have configured the payload, select **Send** to publish the message to the broker.
```

2023-09-08 21:22 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +- **Topics** - This is where you can list down and document multiple topics, and subscribe to them. You can also configure the QoS level for each topic listed.
```suggestion
- **Topics** - This is where you can list and document multiple topics, and subscribe to them. You can also configure the QoS level for each topic listed.
```

2023-09-08 21:30 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +- **Last Will** - Last Will is a message that's sent by the broker to the subscribers when the client disconnects from the broker. You can configure the Last Will message by going to the **Last Will*
```suggestion
- **Last Will** - Last Will is a message that's sent by the broker to the subscribers when the client disconnects from the broker. You can configure the Last Will message by going to the **Last Will** tab, entering the message, and configuring additional settings such as topic name, QoS level, and retain flag. You can also configure the delay interval by selecting the more actioncs icon <img alt="More actions icon" src="https://assets.postman.com/postman-docs/icon-more-actions-v9.jpg#icon" width="16px"> and entering the delay interval in milliseconds.
```

2023-09-08 21:31 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +- **Authorization** - Authorize your connection with Basic Auth. You can pass your credentials in the form of username and password to the broker using the **Authorization** tab.
```suggestion
- **Authorization** - Authorize your connection with Basic Auth. You can pass your credentials in the form of a username and password to the broker using the **Authorization** tab.
```

2023-09-08 21:32 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +- **Settings** - You can configure additional settings for your request by going to the **Settings** tab. You can configure the request timeout, enable/disable SSL certificate verification, clean ses
Just confirming that "auto reconnect etc" is a setting, and that it shouldn't be just "auto reconnect"

2023-09-08 21:33 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +- **Messages**- The message stream shows the published and received messages in a timeline. You can expand the message to view the message details such as topic name, QoS level, retain flag, and mess
```suggestion
- **Messages** - The message stream shows the published and received messages in a timeline. You can expand the message to view the message details such as topic name, QoS level, retain flag, and message type. You can search for specific messages using the search bar, filter messages by received and sent, and clear the message stream using **Clear Messages**.
```

2023-09-08 21:34 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +- **Visualization**- The **Visualization** tab shows the message stream in a graphical format, a more comprehensible way to view telemetry data. The interface is divided into multiple windows per top
```suggestion
- **Visualization** - The **Visualization** tab shows the message stream in a graphical format, a more comprehensible way to view telemetry data. The interface is divided into multiple windows per topic you have received messages for. For JSON responses, the values for the first field are plotted on the graph. You can change the selected field, and add more fields to compare the values side by side. You can also change the visualization style from line to bar chart.
```

2023-09-08 21:35 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +- **Request documentation**- Select the documentation icon to view description of a request. You can add description by selecting the edit icon next to the description, then writing your content usin
```suggestion
- **Request documentation** - Select the documentation icon <img alt="Documentation icon" src="https://assets.postman.com/postman-docs/documentation-icon-v8-10.jpg#icon" width="16px"> to view the description of a request. You can add a description by selecting the edit icon <img alt="Edit icon" src="https://assets.postman.com/postman-docs/documentation-edit-icon-v8-10.jpg#icon" width="18px"> next to the description, then writing your content using [Postman's built-in editing tools](https://learning.postman.com/docs/publishing-your-api/authoring-your-documentation/).
```

2023-09-08 21:36 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +- **Comments**- Select the comments icon to collaborate with your teammates as you work on an API. You can use `@` to tag others to ask a question, give feedback, and discuss your API.
```suggestion
- **Comments** - Select the comments icon <img alt="Comments icon" src="https://assets.postman.com/postman-docs/icon-comments-v9.jpg#icon" width="18px"> to collaborate with your teammates as you work on an API. You can use `@` to tag others to ask a question, give feedback, and discuss your API.
```

2023-09-08 21:36 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +- **Request information** - Select the information icon to view more details about a request, like the request ID and creation date.
```suggestion
- **Request information** - Select the information icon <img alt="Information icon" src="https://assets.postman.com/postman-docs/icon-information-v9-5.jpg#icon" width="16px"> to view more details about a request, like the request ID and creation date.
```

2023-09-08 21:37 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/first-mqtt-request.md
> +2. Select the **Connect** button to connect to the broker.
```suggestion
2. Select **Connect** to connect to the broker.
```

2023-09-08 21:38 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/first-mqtt-request.md
> +A message in the response area indicates that you are connected to the broker.
```suggestion
A message in the response area indicates that you're connected to the broker.
```

2023-09-08 21:38 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/first-mqtt-request.md
> +> If you are using the Postman web app, Use the Postman desktop agent to connect to an MQTT broker. See [About the Postman Agent](https://learning.postman.com/docs/getting-started/about-postman-agent
```suggestion
> If you're using the Postman web app, use the Postman desktop agent to connect to an MQTT broker. See [About the Postman Agent](https://learning.postman.com/docs/getting-started/about-postman-agent/) for more information.
```

2023-09-08 21:39 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/first-mqtt-request.md
> +While connected to the broker, select the **Topics** tab. This interface enables you to create, document, and subscribe to multiple topics.
```suggestion
While connected to the broker, select the **Topics** tab. This enables you to create, document, and subscribe to multiple topics.
```

2023-09-08 21:40 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/first-mqtt-request.md
> +2. Select the **Subscribe** button to subscribe to the topic.
```suggestion
2. Select **Subscribe** to subscribe to the topic.
```

2023-09-08 21:40 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/first-mqtt-request.md
> +You will see a message in the response area indicating that you are subscribed to the topic.
```suggestion
You will see a message in the response area indicating that you're subscribed to the topic.
```

2023-09-08 21:41 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/first-mqtt-request.md
> +Now that you have subscribed to a topic and published a few messages, you can use the response visualizer to view the messages in a more comprehensible format.
```suggestion
Now that you've subscribed to a topic and published a few messages, you can use the response visualizer to view the messages in a more comprehensible format.
```

2023-09-08 21:42 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/first-mqtt-request.md
> +3. Select **Send** to publish the message.
```suggestion
1. Select the **Message** tab and enter `{"age": 2, "number of toys": 5}` as the message.
1. Enter `my-toys` as the topic name.
1. Select **Send** to publish the message.
```

2023-09-08 21:44 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/first-mqtt-request.md
> +4. Select the <img alt="Chart icon" src="https://assets.postman.com/postman-docs/v10/mqtt/chart-icon-v10.jpg#icon" width="16px"> icon next to any of the field names to change the chart type.
```suggestion
1. Switch to the **Visualization** tab in the response area. You'll see the messages for the `age` field visualized as a line chart.
1. Select the field name dropdown to select the field you want to visualize.
1. Select **+** to add more fields to the chart and view the changes in their values together.
1. Select the <img alt="Chart icon" src="https://assets.postman.com/postman-docs/v10/mqtt/chart-icon-v10.jpg#icon" width="16px"> icon next to any of the field names to change the chart type.
```

2023-09-08 21:46 UTC, MatthewPinsker-postman commented on src/pages/docs/sending-requests/mqtt-client/first-mqtt-request.md
> +4. Select the <img alt="Chart icon" src="https://assets.postman.com/postman-docs/v10/mqtt/chart-icon-v10.jpg#icon" width="16px"> icon next to any of the field names to change the chart type.
In the third step, I think there's a typo but I'm not positive. The part I'm concerned about is `view the changes in their values together.`

In the last step, what should we call this icon? Usually, we following the format `the icon-name icon`.

2023-09-08 21:54 UTC, MatthewPinsker-postman approved these changes
LGTM! I mostly left feedback related to style.

2023-09-12 04:20 UTC, skatikia commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +    - **Message type** - You can define the message type as **Text**, **JSON**, **Base64**, or **Hexadecimal** for Postman to convert the message to the selected type before sending it to the broker.
```suggestion
    - **Message type** - You can define the message type as **Text**, **JSON**, **Base64**, or **Hexadecimal** for Postman to render it correctly.
```

2023-09-12 04:23 UTC, skatikia requested changes
@jkonrath-postman I had made a tiny mistake. I have commented it out. Do have a look

2023-09-12 14:15 UTC, petewitcher-postman approved these changes
LGTM!

2023-09-13 17:11 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +In the request interface, you can add configuration to connect to an MQTT broker, subscribe to topics, and publish messages. Additionally, you can add last will details, authorization details, custom
"a configuration" makes it sound like you're adding a config file or object, or a configuration is a thing like an environment or variable.

2023-09-13 17:12 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +- **Enter URL** - This is where you enter the broker's address, such as `test.mosquitto.org`. Some MQTT services also require you to define a port number. You can define a port number in the URL by a
It would be best to use postman-echo, but it doesn't work for MQTT. Using this is fine because it's a working example.

2023-09-13 17:19 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/mqtt-client/first-mqtt-request.md
> +In this example of an MQTT request, you will connect to a public broker, subscribe to topics, and publish messages.
It's actually not an acronym...

2023-09-13 17:32 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/mqtt-client/first-mqtt-request.md
> +    url: "https://www.postman.com/downloads/"
There's no real standard for what pages get this link. We'll have to go through this later (but it doesn't matter as much after we redesign and push these further down.)

2023-09-13 17:35 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +You can also create a new MQTT request by selecting the **New Tab** icon <img alt="New Tab icon" src="https://assets.postman.com/postman-docs/v10/icon-pin-collection-v10.14.0.jpg#icon" width="16px">
Changed the icon name to not bold. I'm going to leave the rest of this as cleanup for later.

2023-09-15 11:43 UTC, merged