[TW-2396] Page title updates
postmanlabs/postman-docs pull request #5094
Opened 2023-09-28 05:46 UTC by nerminamiller-postman

Updates page headings based on the style guide updates

* Partial update 1 (up to Live Collections)

2023-09-28 14:56 UTC, petewitcher-postman commented on src/pages/docs/getting-started/first-steps/exploring-public-api-network.md
> +title: "Explore and use the public network of APIs, workspaces, collections, and flows"
```suggestion
title: "Explore and use the public network of APIs, workspaces, collections, and Flows"
```

2023-09-28 14:57 UTC, petewitcher-postman commented on src/pages/docs/getting-started/installation/proxy.md
> +title: "Using Postman to use a proxy server"
"Using ... to use" seems awkward to me, maybe "Using a proxy server with Postman"?

2023-09-28 15:00 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/capturing-request-data/interceptor.md
> +title: "Capture traffic from browser using Postman Interceptor"
I would go with "Capture traffic from the browser...", just seems like the article is missing to me.

2023-09-28 15:01 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +title: "Send request using GraphQL client"
I'd go with "Send a request" or "Send requests"

2023-09-28 15:02 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +title: "Manage GraphQL queries using Postman HTTP request interface"
I'd change it to "using the Postman", but maybe the article is omitted deliberately.

2023-09-28 15:02 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-overview.md
> +title: "Manage GraphQL APIs using Postman GraphQL client"
I'd change it to "using the Postman", but maybe the article is omitted deliberately.

2023-09-28 15:03 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/graphql/graphql-http.md
> +title: "Send GraphQL query using the HTTP request interface"
I would use "Send a GraphQL" or "Send GraphQL queries" here.

2023-09-28 15:04 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/grpc/understanding-grpc-types.md
> +title: "Read and write data using Postman JSON interface"
I'd suggest "using the Postman".

2023-09-28 15:06 UTC, petewitcher-postman approved these changes
LGTM! I made a few suggestions.

2023-09-28 15:54 UTC, nerminamiller-postman commented on src/pages/docs/getting-started/installation/proxy.md
> +title: "Using Postman to use a proxy server"
Yeah, I goofed here. Thank you!

2023-09-28 15:58 UTC, nerminamiller-postman commented on src/pages/docs/sending-requests/capturing-request-data/interceptor.md
> +title: "Capture traffic from browser using Postman Interceptor"
```suggestion
title: "Capture traffic from the browser using Postman Interceptor"
```

2023-09-28 15:58 UTC, nerminamiller-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-first-request.md
> +title: "Send request using GraphQL client"
```suggestion
title: "Send requests using GraphQL client"
```

2023-09-28 15:58 UTC, nerminamiller-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-interface.md
> +title: "Manage GraphQL queries using Postman HTTP request interface"
```suggestion
title: "Manage GraphQL queries using the Postman HTTP request interface"
```

2023-09-28 15:58 UTC, nerminamiller-postman commented on src/pages/docs/sending-requests/graphql/graphql-client-overview.md
> +title: "Manage GraphQL APIs using Postman GraphQL client"
```suggestion
title: "Manage GraphQL APIs using the Postman GraphQL client"
```

2023-09-28 15:58 UTC, nerminamiller-postman commented on src/pages/docs/sending-requests/graphql/graphql-http.md
> +title: "Send GraphQL query using the HTTP request interface"
```suggestion
title: "Send GraphQL queries using the HTTP request interface"
```

2023-09-28 15:58 UTC, nerminamiller-postman commented on src/pages/docs/sending-requests/grpc/understanding-grpc-types.md
> +title: "Read and write data using Postman JSON interface"
```suggestion
title: "Read and write data using the Postman JSON interface"
```

2023-09-28 23:14 UTC, mark-anthony-postman requested changes
I absolutely LOVE the new approach to page titles! These are so much more descriptive that what we had before and will give users a way better idea of what each page is about 🧡

I've made a whole bunch of comments, but hopefully they are all in the spirit of this new direction. Please take them as you will. Thanks so much for this epic undertaking--it's going to be a huge lift to LC docs 🎈

P.S. I'm curious about the rule of when to use "About <whatever>" for a concept topic. Sometimes you use "About" and sometimes just a noun phrase. Any guidance to offer here?

2023-09-28 23:14 UTC, mark-anthony-postman commented on src/pages/docs/writing-scripts/pre-request-scripts.md
> +title: "Add code to the Pre-request Script tab"
```suggestion
title: "Write pre-request scripts"
```

2023-09-28 23:14 UTC, mark-anthony-postman commented on src/pages/docs/writing-scripts/pre-request-scripts.md
> +title: "Add code to the Pre-request Script tab"
Feel like this is the task that users are trying to accomplish--adding code to the tab is just the UI mechanics

2023-09-28 23:14 UTC, mark-anthony-postman commented on src/pages/docs/writing-scripts/test-scripts.md
> +title: "Write test scripts for Postman APIs"
```suggestion
title: "Write API test scripts in Postman"
```

2023-09-28 23:14 UTC, mark-anthony-postman commented on src/pages/docs/writing-scripts/test-scripts.md
> +title: "Write test scripts for Postman APIs"
Need to make it clear we're not talking about writing tests for the Postman API, but for your own API

2023-09-28 23:14 UTC, mark-anthony-postman commented on src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
> +title: "Manage API data and workflows using Postman objects"
```suggestion
title: "Postman JavaScript reference"
```

2023-09-28 23:14 UTC, mark-anthony-postman commented on src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
> +title: "Manage API data and workflows using Postman objects"
As this is a reference rather than task topic, I felt the original title was appropriate--same for the other two topics in this section

2023-09-28 23:14 UTC, mark-anthony-postman commented on src/pages/docs/writing-scripts/script-references/test-examples.md
> +title: "Write scripts using test examples"
```suggestion
title: "Test script examples"
```

2023-09-28 23:14 UTC, mark-anthony-postman commented on src/pages/docs/writing-scripts/script-references/variables-list.md
> +title: "Use predefined variables to return values"
```suggestion
title: "Dynamic variables"
```

2023-09-29 01:42 UTC, nerminamiller-postman commented on src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
> +title: "Manage API data and workflows using Postman objects"
I’m leaving this one as is does contain examples and also because the title would duplicate the leftnav. Ditto on next two.

2023-09-29 04:07 UTC, nerminamiller-postman commented on src/pages/docs/collections/running-collections/running-collections-overview.md
> +title: "Testing your API functionality"
```suggestion
title: "Test your API functionality"
```

2023-09-29 04:07 UTC, nerminamiller-postman commented on src/pages/docs/sending-requests/authorization/authorization-types.md
> +title: "About authorization types supported by Postman"
```suggestion
title: "Authorization types supported by Postman"
```

2023-09-29 04:07 UTC, nerminamiller-postman commented on src/pages/docs/sending-requests/authorization/authorization.md
> +title: "About request authorization in Postman"
```suggestion
title: "Request authorization in Postman"
```

2023-09-29 19:09 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/roles-and-permissions.md
> +title: "Define user permissions within a Postman team"
I feel like this needs the word "role" in here. "Define roles and permissions within a Postman team"?

2023-09-29 20:12 UTC, mark-anthony-postman approved these changes
More amazing work! These page titles are all way more descriptive than before and will give users a better sense of what's on each page.

Once again I made a bunch of comments—use as you see fit! 😄

2023-09-29 20:12 UTC, mark-anthony-postman commented on src/pages/docs/postman-cli/postman-cli-overview.md
> +title: "Explore Postman’s command-line companion"
```suggestion
title: "The Postman CLI"
```

2023-09-29 20:12 UTC, mark-anthony-postman commented on src/pages/docs/postman-cli/postman-cli-run-collection.md
> +title: "Run a collection with the Postman CLI"
```suggestion
title: "Run a collection using the Postman CLI"
```

2023-09-29 20:12 UTC, mark-anthony-postman commented on src/pages/docs/postman-cli/postman-cli-run-collection.md
> +title: "Run a collection with the Postman CLI"
"With" is fine, but it seems like you more typically say "using"

2023-09-29 20:14 UTC, mark-anthony-postman commented on src/pages/docs/writing-scripts/script-references/variables-list.md
> +title: "Use predefined variables to return values"
Could we get "dynamic" in there?
> Use predefined variables to return dynamic values

2023-09-29 20:15 UTC, mark-anthony-postman commented on src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
> +title: "Manage API data and workflows using Postman objects"
Could we get "JavaScript" in there?
> Manage API data and workflows using Postman objects in JavaScript

2023-09-29 21:39 UTC, petewitcher-postman approved these changes
LGTM!

2023-09-29 21:47 UTC, jkonrath-postman approved these changes
I'll approve, but resolve all the comments and let me know if you have questions. Also, pull develop back into this - you're going to get a few new titles from today's merge.

2023-09-29 21:47 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/partner-workspaces.md
> +title: "Collaborate with external partners in Postman"
For things like this where the old item was a branded term, do you think it would make more sense to say "Collaborate with external partners using Partner Workspaces?" or is that too much? My thought is then you're mapping what you want to do with the branded thing you use in Postman.

2023-09-29 21:47 UTC, jkonrath-postman commented on src/pages/docs/collections/using-newman-cli/installing-running-newman.md
> +title: "Install Newman and run it with your collection"
Maybe just "Install and run Newman" - you don't run it with a collection; you run a collection with it.

2023-09-29 21:47 UTC, jkonrath-postman commented on src/pages/docs/collections/using-newman-cli/newman-custom-reporters.md
> +title: "Create custom reporters for specific use cases using Newman"
Maybe "Create Newman custom reporters"?

2023-09-29 21:47 UTC, jkonrath-postman commented on src/pages/docs/collections/using-newman-cli/newman-file-uploads.md
> +title: "Run Newman on a collection file you uploaded"
It's a little different than this - the file is a random data file, like maybe you have a POST request that's uploading an image, and the image is the file. So maybe something like "Upload files with Newman"?

2023-09-29 21:47 UTC, jkonrath-postman commented on src/pages/docs/designing-and-developing-your-api/versioning-an-api/using-on-prem-git-repo.md
> +title: "Connect your API to an on-prem Git repository"
```suggestion
title: "Connect your API to an on-premises Git repository"
```

2023-09-29 21:47 UTC, jkonrath-postman commented on src/pages/docs/developer/collection-sdk.md
> +title: "Create and manage collections using Collection SDK"
```suggestion
title: "Create and manage collections using the Collection SDK"
```

2023-09-29 21:47 UTC, jkonrath-postman commented on src/pages/docs/developer/echo-api.md
> +title: "Test requests in Postman using Echo API"
```suggestion
title: "Test requests in Postman using the Echo API"
```

2023-09-29 21:47 UTC, jkonrath-postman commented on src/pages/docs/developer/runtime-library.md
> +title: "Configure request and collection runs using Postman Runtime library"
```suggestion
title: "Configure request and collection runs using the Postman Runtime library"
```

2023-09-29 21:47 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/capture-with-proxy.md
> +title: "Capture traffic using the Postman built-in proxy for macOS (Postman v10.17 or later) and Windows (Postman v10.18 or later)"
Too long and the platform support in the title is a bit much. Maybe "Capture traffic using the built-in Postman proxy"?

2023-09-29 21:47 UTC, jkonrath-postman commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +title: "Capture traffic using the Postman built-in proxy for macOS (Postman v10.16 or earlier), Windows (Postman v10.17 or earlier), and Linux"
too long

2023-10-02 13:43 UTC, mark-anthony-postman commented on src/pages/docs/sending-requests/capturing-request-data/capture-with-proxy.md
> +title: "Capture traffic using the Postman built-in proxy for macOS (Postman v10.17 or later) and Windows (Postman v10.18 or later)"
Nermina was trying to come up with a solution for the fact that we have two pages about the proxy, but one is the new UX and one is the old UX. The old UX remains for Linux and previous Postman versions on macOS and Windows.

Maybe it's best to just go back to the previous titles? Name this page "Capture traffic using the Postman built-in proxy" and name the older page "Capture HTTP requests" and let the notes at the top of each page sort out the version requirements.

2023-10-02 13:55 UTC, jkonrath-postman commented on src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
> +title: "Manage API data and workflows using Postman objects"
You could also save a word with just "Manage API data and workflows using Postman JavaScript objects"

2023-10-02 13:57 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/private-api-network/organizing-private-network.md
> +title: "Add elements to your Private API Network"
We should be consistent, but PAPI might be a special case where we want to use "your" to emphasize it's _your_ network, and not some global one.

2023-10-02 14:24 UTC, nerminamiller-postman commented on src/pages/docs/writing-scripts/script-references/variables-list.md
> +title: "Use predefined variables to return values"
@mark-anthony-postman using predefined variables implies a dynamic response but I’m happy to change it

2023-10-02 14:29 UTC, nerminamiller-postman commented on src/pages/docs/developer/runtime-library.md
> +title: "Configure request and collection runs using Postman Runtime library"
@mark-anthony-postman I’ll default to my original suggestion for length. We use the word _run_ in the context of requests. [Reference](https://learning.postman.com/docs/postman-flows/tutorials/running-requests-in-sequence/)

2023-10-02 14:31 UTC, nerminamiller-postman commented on src/pages/docs/postman-cli/postman-cli-overview.md
> +title: "Explore Postman’s command-line companion"
@mark-anthony-postman the leftnav title will repeat. Stet.

2023-10-02 14:31 UTC, nerminamiller-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/partner-workspaces.md
> +title: "Collaborate with external partners in Postman"
```suggestion
title: "Collaborate with external partners in Postman using Partner Workspaces“ 
```

2023-10-02 14:32 UTC, nerminamiller-postman commented on src/pages/docs/collections/using-newman-cli/installing-running-newman.md
> +title: "Install Newman and run it with your collection"
```suggestion
title: "Install and run Newman"
```

2023-10-02 14:35 UTC, nerminamiller-postman commented on src/pages/docs/collections/using-newman-cli/newman-custom-reporters.md
> +title: "Create custom reporters for specific use cases using Newman"
```suggestion
title: "Create Newman custom reporters"
```

2023-10-02 14:36 UTC, nerminamiller-postman commented on src/pages/docs/sending-requests/capturing-request-data/capture-with-proxy.md
> +title: "Capture traffic using the Postman built-in proxy for macOS (Postman v10.17 or later) and Windows (Postman v10.18 or later)"
```suggestion
title: "Capture traffic using the Postman built-in proxy"
```

2023-10-02 14:37 UTC, nerminamiller-postman commented on src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
> +title: "Capture traffic using the Postman built-in proxy for macOS (Postman v10.16 or earlier), Windows (Postman v10.17 or earlier), and Linux"
```suggestion
title: "Capture HTTP requests in Postman"
```

2023-10-02 14:39 UTC, nerminamiller-postman commented on src/pages/docs/developer/runtime-library.md
> +title: "Configure request and collection runs using Postman Runtime library"
I am going to add an article though

2023-10-02 14:54 UTC, nerminamiller-postman commented on src/pages/docs/designing-and-developing-your-api/developing-an-api/validating-elements-against-schema.md
> +title: "Ensure consistency between your collection and the API definition"
@mark-anthony-postman I think ensuring consistency may cover both?

2023-10-02 14:56 UTC, nerminamiller-postman reviewed
@jkonrath-postman and @mark-anthony-postman I believe I responded to all of your comments and accepted most of your suggestions. I left a few comments for you. Let me know what you think and I’ll review again. Thank you!

2023-10-02 17:36 UTC, nerminamiller-postman reviewed
Resolves previous conversations

2023-10-02 17:37 UTC, mark-anthony-postman commented on src/pages/docs/writing-scripts/script-references/variables-list.md
> +title: "Use predefined variables to return values"
I'll leave it up to you, but my preference would be "Use predefined variables to return dynamic values"

2023-10-02 17:39 UTC, nerminamiller-postman commented on src/pages/docs/writing-scripts/script-references/variables-list.md
> +title: "Use predefined variables to return values"
```suggestion
title: "Use predefined variables to return dynamic values"
```

2023-10-02 17:42 UTC, mark-anthony-postman approved these changes
Fantastic changes! LGTM! 🌟

2023-10-02 17:56 UTC, petewitcher-postman approved these changes
LGTMA!

2023-10-02 18:09 UTC, merged