[TW-1358] Add team members to Enterprise Essentials solutions
postmanlabs/postman-docs pull request #5113
Opened 2023-10-05 15:40 UTC by MatthewPinsker-postman

Explain how to add team members to Enterprise Essentials solutions, and explain the impact of adding users to a solution.

2023-10-05 20:51 UTC, mark-anthony-postman approved these changes
LGTM! 😄

2023-10-11 13:16 UTC, malvikach requested changes

2023-10-11 15:34 UTC, MatthewPinsker-postman commented on src/pages/docs/administration/managing-your-team/managing-your-team.md
> +You can add team members to the API Test Automation solution for more access to the [Collection Runner](/docs/collections/running-collections/intro-to-collection-runs/), [CI/CD integrations](/docs/in
This is now updated.

2023-10-12 03:41 UTC, taehoshino commented on src/pages/docs/billing/billing.md
> +> **[Enterprise solutions are available for Enterprise Essentials plans.](https://www.postman.com/pricing)**
I would suggest adding this section immediately after "Purchasing add-on products" section (that is to be added as part of https://github.com/postmanlabs/postman-docs/pull/5136

2023-10-12 03:43 UTC, taehoshino commented
@jkonrath-postman Are we also adding a section to explain how to manage Postbot access from Product Access page?

2023-10-12 13:10 UTC, MatthewPinsker-postman commented
> @jkonrath-postman Are we also adding a section to explain how to manage Postbot access from Product Access page?

Hi @taehoshino! Are we adding Postbot to the Product access page in the October release?

2023-10-12 13:12 UTC, MatthewPinsker-postman commented on src/pages/docs/billing/billing.md
> +> **[Enterprise solutions are available for Enterprise Essentials plans.](https://www.postman.com/pricing)**
Thanks! Once https://github.com/postmanlabs/postman-docs/pull/5136 is merged with the `develop` branch, I'll pull the changes into this branch and look at updating/reorganizing the Enterprise solutions content.

2023-10-12 13:38 UTC, jkonrath-postman commented
> @jkonrath-postman Are we also adding a section to explain how to manage Postbot access from Product Access page?

We can after we ship on Oct 16. This PR is going to have to get the changes from the other one merged into it first. (@MatthewPinsker-postman this will make more sense after you merge develop back into here on Monday.)

2023-10-13 11:49 UTC, taehoshino commented
> > @jkonrath-postman Are we also adding a section to explain how to manage Postbot access from Product Access page?
> 
> Hi @taehoshino! Are we adding Postbot to the Product access page in the October release?

Yes.

2023-10-13 13:14 UTC, shashankawasthi88 approved these changes
looks good

2023-10-16 23:33 UTC, taehoshino commented on src/pages/docs/administration/managing-your-team/managing-your-team.md
> +> **[Product access is available for Enterprise Essentials plans.](https://www.postman.com/pricing)**
Postbot section is available for Basic and Prof as well

2023-10-19 15:31 UTC, MatthewPinsker-postman commented
@taehoshino asked me to include Shivam Sharma in this review. Shivam reviewed the Postbot-related changes and approved them via Slack on 10/19/2023.

2023-11-03 15:57 UTC, merged