[TW-1458] Doc new pm.execution.skipRequest() method
postmanlabs/postman-docs pull request #5196
Opened 2023-11-03 19:48 UTC by mark-anthony-postman

Adds the `pm.execution.skipRequest()` method to the Postman JavaScript reference.

View the beta docs here: [Skip request execution from pre-request scripts](https://tw-1458-skip-request-method.learning.postman-beta.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#skip-request-execution-from-pre-request-scripts)

2023-11-03 20:31 UTC, petewitcher-postman approved these changes
LGTM!

2023-11-06 05:47 UTC, giridharvc7 requested changes
Left some comments overall on the Tests section usage of this. 
TLDr of this is users get a 
```
TypeError: pm.execution.skipRequest is not a function
```
error when using `pm.execution.skipRequest();` in Test scripts

2023-11-06 05:47 UTC, giridharvc7 commented on src/pages/docs/collections/running-collections/building-workflows.md
> +> You can also skip the execution of a request and any test scripts using the `pm.execution.skipRequest` method. Learn more about [skipping request execution from pre-request scripts](/docs/writing-s
The script doesn't work in Test scripts

2023-11-06 05:47 UTC, giridharvc7 commented on src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
> +When `pm.execution.skipRequest()` is encountered, the request isn't sent. Any remaining scripts on the **Pre-request Script** tab are skipped, and all scripts on the **Tests** tab are skipped. Also,
Again here, the tests part this script has no effect. 
Rather you get a console error
```
TypeError: pm.execution.skipRequest is not a function
```

2023-11-06 21:24 UTC, mark-anthony-postman commented on src/pages/docs/collections/running-collections/building-workflows.md
> +> You can also skip the execution of a request and any test scripts using the `pm.execution.skipRequest` method. Learn more about [skipping request execution from pre-request scripts](/docs/writing-s
To make this more clear, I updated the text to:
You can also skip the execution of a request from the **Pre-request Scripts** tab using the `pm.execution.skipRequest` method.

2023-11-06 21:51 UTC, mark-anthony-postman commented on src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
> +When `pm.execution.skipRequest()` is encountered, the request isn't sent. Any remaining scripts on the **Pre-request Script** tab are skipped, and all scripts on the **Tests** tab are skipped. Also,
To make this more clear, I updated the text to:

> You can use the `pm.execution.skipRequest` method on the **Pre-request Script** tab of a request, collection, or folder. When `pm.execution.skipRequest()` is encountered, the request isn't sent. Any remaining scripts on the **Pre-request Script** tab are skipped, and no tests are executed. Also, a message that the request was skipped is logged in the Postman Console.

I also added the following note:

> Using the `pm.execution.skipRequest` method isn't supported on the **Tests** tab and will have no effect there. You will also get the following Console error: `TypeError: pm.execution.skipRequest is not a function`.

2023-11-07 04:43 UTC, giridharvc7 approved these changes

2023-11-08 22:28 UTC, jkonrath-postman approved these changes
LGTM

2023-11-15 13:45 UTC, merged