[TW-1455] Update group info not supported in Okta
postmanlabs/postman-docs pull request #5203
Opened 2023-11-07 19:58 UTC by MatthewPinsker-postman

* Explained that "Update group information" (i.e. group push) isn't supported in the Postman Okta app. Confirmed that this feature is supported in OneLogin and Entra ID.
* Linked to another Okta app that supports group push. Users can use this app instead if they want the group push provisioning feature.

2023-11-07 21:22 UTC, petewitcher-postman approved these changes
LGTM!

2023-11-08 15:40 UTC, jkonrath-postman approved these changes
LGTM - make sure I got that link right in the suggestion, I didn't test it.

2023-11-08 15:40 UTC, jkonrath-postman commented on src/pages/docs/administration/scim-provisioning/scim-provisioning-overview.md
> +    > Updating group information from your IdP to Postman isn't supported in [SCIM provisioning through Okta](http://localhost:8000/docs/administration/scim-provisioning/configuring-scim-with-okta/).
```suggestion
    > Updating group information from your IdP to Postman isn't supported in [SCIM provisioning through Okta](/docs/administration/scim-provisioning/configuring-scim-with-okta/). If you're using Okta and you want to use this provisioning feature, use the [SCIM 2.0 Okta app](https://www.okta.com/integrations/scim-2-0-test-app-header-auth/).
```

2023-11-15 05:15 UTC, PriyambadaMadala requested changes

2023-11-15 05:15 UTC, PriyambadaMadala commented on src/pages/docs/administration/scim-provisioning/configuring-scim-with-okta.md
> +> Updating group information from your IdP to Postman isn't supported in SCIM provisioning through Okta. If you're using Okta and you want to use this provisioning feature, use the [SCIM 2.0 Okta app
`Updating group information from your IdP to Postman`

Apologies for confusion in our previous discussion . 
We need to mention `Updating group information from Postman to your IdP`

2023-11-15 05:15 UTC, PriyambadaMadala commented on src/pages/docs/administration/scim-provisioning/scim-provisioning-overview.md
> +    > Updating group information from your IdP to Postman isn't supported in [SCIM provisioning through Okta](/docs/administration/scim-provisioning/configuring-scim-with-okta/). If you're using Okta
Same as above we need to change the message `Updating group information from Postman to your IdP`

2023-11-15 09:28 UTC, ArjunSingh-PM requested changes
Thanks for sharing the changes. I have left a comment that needs to be addressed before pushing this change. Thanks.

2023-11-15 09:28 UTC, ArjunSingh-PM commented on src/pages/docs/administration/scim-provisioning/configuring-scim-with-okta.md
> +> Updating group information from your IdP to Postman isn't supported in SCIM provisioning through Okta. If you're using Okta and you want to use this provisioning feature, use the [SCIM 2.0 Okta app
Updating group information from Postman to your IdP via the official [Postman Okta app](https://www.okta.com/integrations/postman/) isn't supported at the moment. We are working with Okta to have the official [Postman Okta app](https://www.okta.com/integrations/postman/) updated to support the same. 

However, you can use the generic [SCIM 2.0 Okta app](https://www.okta.com/integrations/scim-2-0-test-app-header-auth/) to unblock updating groups from Postman to your IdP as well.

2023-11-15 09:28 UTC, ArjunSingh-PM commented on src/pages/docs/administration/scim-provisioning/scim-provisioning-overview.md
> +    > Updating group information from your IdP to Postman isn't supported in [SCIM provisioning through Okta](/docs/administration/scim-provisioning/configuring-scim-with-okta/). If you're using Okta
Updating group information from Postman to your IdP via the official [Postman Okta app](https://www.okta.com/integrations/postman/) isn't supported at the moment. We are working with Okta to have the official [Postman Okta app](https://www.okta.com/integrations/postman/) updated to support the same.

However, you can use the generic [SCIM 2.0 Okta app](https://www.okta.com/integrations/scim-2-0-test-app-header-auth/) to unblock updating groups from Postman to your IdP as well.

2023-11-16 22:39 UTC, MatthewPinsker-postman commented on src/pages/docs/administration/scim-provisioning/configuring-scim-with-okta.md
> +> Updating group information from your IdP to Postman isn't supported in SCIM provisioning through Okta. If you're using Okta and you want to use this provisioning feature, use the [SCIM 2.0 Okta app
This is now updated. Thanks!

2023-11-16 22:39 UTC, MatthewPinsker-postman commented on src/pages/docs/administration/scim-provisioning/scim-provisioning-overview.md
> +    > Updating group information from your IdP to Postman isn't supported in [SCIM provisioning through Okta](/docs/administration/scim-provisioning/configuring-scim-with-okta/). If you're using Okta
This is now updated. Thanks!

2023-11-21 08:45 UTC, ArjunSingh-PM approved these changes
Looks good!

2023-11-28 16:44 UTC, merged