[TW-1484] Doc Enable cloud automation of requests that accept a file input
postmanlabs/postman-docs pull request #5262
Opened 2023-12-04 17:03 UTC by mark-anthony-postman

- Adds section to requests page about uploading test data files
- Adds section to resource usage page about managing test data files
- Updates working directory section with information about uploading test data files
- Adds notes about uploading test data files to scheduled requests, monitors, Flows, and CLI sections

View the beta docs here:
- [Upload files for shared requests and cloud runs](https://tw-1484-file-uploads-for-cloud-runs.learning.postman-beta.com/docs/sending-requests/requests/#upload-files-for-shared-requests-and-cloud-runs)
- [Test data usage](https://tw-1484-file-uploads-for-cloud-runs.learning.postman-beta.com/docs/billing/resource-usage/#test-data-usage)
- [Working directory](https://tw-1484-file-uploads-for-cloud-runs.learning.postman-beta.com/docs/getting-started/installation/settings/#working-directory)
- Also added notes about uploading test data files to [scheduled collection runs](https://tw-1484-file-uploads-for-cloud-runs.learning.postman-beta.com/docs/collections/running-collections/scheduling-collection-runs/), [monitors](https://tw-1484-file-uploads-for-cloud-runs.learning.postman-beta.com/docs/monitoring-your-api/setting-up-monitor/#configuring-a-collection-based-monitor), [Postman Flows](https://tw-1484-file-uploads-for-cloud-runs.learning.postman-beta.com/docs/postman-flows/concepts/requests-and-variables/#requests), and [Postman CLI](https://tw-1484-file-uploads-for-cloud-runs.learning.postman-beta.com/docs/postman-cli/postman-cli-run-collection/#running-a-collection-that-uses-test-data-files)

2023-12-04 18:50 UTC, MatthewPinsker-postman commented on src/pages/docs/billing/resource-usage.md
> +You can check your test data usage on the [Resource Usage dashboard](https://go.postman.co/billing/add-ons/overview). You can view the amount of test data storage your team is using and the number of
```suggestion
You can check your test data usage on the [Resource Usage dashboard](https://go.postman.co/billing/add-ons/overview). You can view the amount of test data storage your team is using and the number of times test data has been retrieved from the cloud. Test data is retrieved each time a request that uses an uploaded file is sent manually or automatically from a [scheduled collection run](/docs/collections/running-collections/scheduling-collection-runs/), [monitor](/docs/monitoring-your-api/intro-monitors/), [Postman Flow](/docs/postman-flows/gs/flows-overview/), or the [Postman CLI](/docs/postman-cli/postman-cli-overview/). Multiple instances of the same file in a collection run or monitor run count as a single retrieval.
```

2023-12-04 18:52 UTC, MatthewPinsker-postman commented on src/pages/docs/billing/resource-usage.md
> +* To filter the list by who uploaded the file, select a team member in the dropdown list.
```suggestion
* To filter the list by who uploaded the file, select a team member in the **Uploaded by** dropdown list.
```

2023-12-04 20:01 UTC, MatthewPinsker-postman approved these changes
LGTM!

2023-12-06 13:01 UTC, giridharvc7 requested changes

2023-12-07 22:25 UTC, jkonrath-postman approved these changes
LGTM

2023-12-08 03:24 UTC, postfrzero commented on src/pages/docs/billing/resource-usage.md
> +Once you're reached your test data retrieval limit, you won't be able to send requests that use data files. This includes sending files manually or automatically from a scheduled collection run, moni
Just need to clarify one thing -- @aman-postman Will the request/run fail altogether, or will it run but without the file being loaded? I believe it's the latter.

2023-12-08 03:34 UTC, postfrzero commented on src/pages/docs/postman-flows/concepts/requests-and-variables.md
> +> Postman Flows can't run requests that use files in your local [working directory](/docs/getting-started/installation/settings/#working-directory) to send [body data](/docs/sending-requests/requests
Flows do work correctly with a working directory configured, when running locally. Using uploaded test data files just makes it easier to collaborate since the file doesn't have to be moved around manually, and gets the deployed version of Flows working correctly.

2023-12-08 03:40 UTC, postfrzero commented on src/pages/docs/sending-requests/requests.md
> +To enable sharing requests that use test data files, you can upload the files to the Postman cloud. Uploaded files are available to all members of your team and can be used to send requests that are
> ...you can upload the files to the Postman cloud.

We've been leaning towards "to your Postman team" vs. "to the Postman cloud" wherever possible.

2023-12-08 22:26 UTC, mark-anthony-postman commented on src/pages/docs/getting-started/installation/settings.md
>  **To make collaboration easier, store files in your working directory.** Storing files in your working directory ensures that requests in shared collections always work. As long as you and your teamm
I changed this to read as follows:

> **To make collaboration easier, upload test data files to your Postman team.** You can used files uploaded to your team as form data or binary data when sending a request. If you share the request in a workspace, other team members can send the shared request without needing to copy the files to their local working directory. Learn more about uploading files for shared requests.

2023-12-08 22:27 UTC, mark-anthony-postman commented on src/pages/docs/sending-requests/requests.md
> +To enable sharing requests that use test data files, you can upload the files to the Postman cloud. Uploaded files are available to all members of your team and can be used to send requests that are
I changed all instanced of "upload files to the Postman cloud" to "upload files to your Postman team"

2023-12-08 22:39 UTC, mark-anthony-postman commented on src/pages/docs/getting-started/installation/settings.md
> +When you send a form-data or binary file with a request body, Postman saves a path to the test file as part of the collection. The file path is relative to your working directory. Postman uses `~/Pos
I updated this to:

> On macOS and Linux, you can find the default working directory at `~/Postman/files`. On Windows, you can find the default working directory at `%userprofile%\Postman\files` (File Explorer and Command Prompt) or `~/Postman/files` (PowerShell).

2023-12-08 22:48 UTC, mark-anthony-postman commented on src/pages/docs/billing/resource-usage.md
> +Once you're reached your test data retrieval limit, you won't be able to send requests that use data files. This includes sending files manually or automatically from a scheduled collection run, moni
I changed this to:

> Once you're reached your test data retrieval limit, requests that use uploaded data files won't be able to retrieve those files before being sent. This includes requests that are sent manually or automatically from a scheduled collection run, monitor, Postman Flows, or the Postman CLI.

2023-12-08 22:53 UTC, mark-anthony-postman commented on src/pages/docs/postman-flows/concepts/requests-and-variables.md
> +> Postman Flows can't run requests that use files in your local [working directory](/docs/getting-started/installation/settings/#working-directory) to send [body data](/docs/sending-requests/requests
I changed this to:

> Postman Flows can run requests that use files in your local working directory to send body data. To make collaboration and deploying your Flow easier, upload your test data files to your Postman team.

2023-12-12 18:45 UTC, postfrzero approved these changes
LGTM!

2023-12-15 12:25 UTC, merged