[TW-1591] Doc Read path of request including Collections and folders
postmanlabs/postman-docs pull request #5279
Opened 2023-12-07 16:54 UTC by mark-anthony-postman

Adds new section to the Javascript reference describing the new `pm.execution.location` and `pm.execution.location.current` properties.

View the beta docs here: [Get the path and name of a request](https://tw-1591-read-request-path.learning.postman-beta.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#get-the-path-and-name-of-a-request)

2023-12-07 17:13 UTC, mark-anthony-postman commented on src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
> +The `pm.execution.location` property enables you to get the complete path of a request, including the folder and collection, in array format. For example, for a request name **R1** in folder **F1** i
Thanks for catching that!

2023-12-07 20:55 UTC, jkonrath-postman approved these changes
LGTM

2023-12-11 15:37 UTC, giridharvc7 requested changes

2023-12-11 15:37 UTC, giridharvc7 commented on src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
> +```
We should also add what the output of this looks like.

2023-12-11 15:37 UTC, giridharvc7 commented on src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
> +```
Same here, may be we can add what the output looks like for quick understanding

2023-12-11 15:50 UTC, giridharvc7 approved these changes

2023-12-11 15:51 UTC, mark-anthony-postman commented on src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
> +```
I changed this to:
```
console.log(pm.execution.location);
// Returns the full path of a request in array format, for example:
// ["C1", "F1", "R1"]
```

2023-12-11 15:52 UTC, mark-anthony-postman commented on src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
> +```
I changed this to:
```
console.log(pm.execution.location.current);
// Returns the name of the current element, for example:
// F1
```

2023-12-13 05:31 UTC, vedkribhu approved these changes

2023-12-15 12:46 UTC, merged