[TW-1622] MQTT response topic support
postmanlabs/postman-docs pull request #5338
Opened 2024-01-08 22:54 UTC by petewitcher-postman

Adds the MQTT properties users can add to MQTT requests.

2024-01-08 23:06 UTC, nerminamiller-postman approved these changes
LGTM!

2024-01-09 16:32 UTC, jonathanhaviv requested changes

2024-01-09 16:32 UTC, jonathanhaviv commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +        - sessionExpiryInterval
Ah I think I misunderstood in our slack conversation. The properties tab is just for the userProperties. In the message tab we added the publish properties. Those are the standard properties that are supported by MQTT 5.

2024-01-09 21:36 UTC, petewitcher-postman commented on src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md
> +        - sessionExpiryInterval
Thanks for the feedback, it was my mistake. I've updated the page accordingly.

2024-01-09 23:50 UTC, jonathanhaviv approved these changes
lgtm 👍

2024-01-10 21:50 UTC, jkonrath-postman approved these changes
LGTM

2024-01-16 15:26 UTC, merged