[TW-1663] Doc multi-partner workspaces (EA)
postmanlabs/postman-docs pull request #5381
Opened 2024-01-24 21:34 UTC by nerminamiller-postman

Adds an EA page on multipartner workspaces

2024-01-25 15:23 UTC, jkonrath-postman approved these changes
LGTM, made a few comments

2024-01-25 15:23 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +_Multipartner mode is a beta capability and is only available to select Postman Enterprise customers who want to try it out. As you use the feature, please share any feedback or issues you encounter
Check if we should not have Ramji's email in there

2024-01-25 15:23 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +Partner Workspaces enable you to collaborate with your external partners and customers. You can use them to demo your API products to customers, onboard external developers faster, and reduce the tim
```suggestion
Partner Workspaces enable you to collaborate with your external partners and customers. You can use Partner Workspaces to demo your API products to customers, onboard external developers faster, and reduce the time-to-first-call for your consumers.
```

2024-01-25 15:23 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +To enable multipartner mode, open any Partner Workspace and follow these steps:
```suggestion
To enable multipartner mode, do the following:
```

2024-01-25 15:23 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +Use the fork feature to share collections and environments from your internal Team workspaces to the Partner workspace. Partners can be invited as Viewers to this workspace. However, team members can
```suggestion
Use the fork feature to share collections and environments from your internal Team workspaces to the Partner workspace. Partners can only be invited as Viewers to this workspace. However, team members can be invited as Viewers, Editors, or Admins.
```

2024-01-25 16:05 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +Partner Workspaces enable you to collaborate with your external partners and customers. You can use Partner Workspaces to demo your API products to customers, onboard external developers faster, and
What do you think about adding a link to the main Partner Workspaces page in the intro section? `/docs/collaborating-in-postman/using-workspaces/partner-workspaces/`

2024-01-25 16:06 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +* Share and update Postman collections with multiple partners without having to update a separate workspace for each partner.
```suggestion
* Share and update Postman Collections with multiple partners without having to update a separate workspace for each partner.
```

2024-01-25 16:08 UTC, nerminamiller-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +Partner Workspaces enable you to collaborate with your external partners and customers. You can use Partner Workspaces to demo your API products to customers, onboard external developers faster, and
```suggestion
[Partner Workspaces(/docs/collaborating-in-postman/using-workspaces/partner-workspaces/) enable you to collaborate with your external partners and customers. You can use Partner Workspaces to demo your API products to customers, onboard external developers faster, and reduce the time-to-first-call for your consumers.
```

2024-01-25 16:08 UTC, nerminamiller-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +Partner Workspaces enable you to collaborate with your external partners and customers. You can use Partner Workspaces to demo your API products to customers, onboard external developers faster, and
Good catch, Matthew! Meant to add. Done!

2024-01-25 16:09 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +By enabling multipartner mode in a Partner Workspace, you can create a private, restricted-access workspace that's intentionally designed for publishing Postman collections to multiple external partn
```suggestion
By enabling multipartner mode in a Partner Workspace, you can create a private, restricted-access workspace that's intentionally designed for publishing Postman Collections to multiple external partners. Partners can be invited to this workspace as Viewers only, see all the workspace content, and send API requests. Team members can make edits to the workspace, which are then available to the partners in real time.
```

2024-01-25 16:12 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +By enabling multipartner mode in a Partner Workspace, you can create a private, restricted-access workspace that's intentionally designed for publishing Postman collections to multiple external partn
Also, instead of calling this a "private, restricted-access workspace", what do you think about just calling it a "restricted-access workspace"? My concern is differentiating between workspaces where the visibility is set to private.

2024-01-25 16:15 UTC, nerminamiller-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +As your partner programs grow, so does your need to create, maintain and update multiple workspaces with nearly the same content in each one. A _multipartner_ mode within Partner Workspaces simplifie
```suggestion
As your partner programs grow, so does your need to create, maintain, and update multiple workspaces with nearly the same content in each one. A _multipartner_ mode within Partner Workspaces simplifies this workflow and helps you share your APIs easily with multiple customers and partners.
```

2024-01-25 16:15 UTC, nerminamiller-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +By enabling multipartner mode in a Partner Workspace, you can create a private, restricted-access workspace that's intentionally designed for publishing Postman Collections to multiple external partn
```suggestion
By enabling multipartner mode in a Partner Workspace, you can create a restricted-access workspace that's intentionally designed for publishing Postman Collections to multiple external partners. Partners can be invited to this workspace as Viewers only, see all the workspace content, and send API requests. Team members can make edits to the workspace, which are then available to the partners in real time.
```

2024-01-25 16:15 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +The goal of this workspace is to provide a sandbox where customers and partners evaluate, onboard, and consume your APIs by sending successful requests quickly. A Partner user can't see other Partner
```suggestion
The goal of this workspace is to provide a sandbox where customers and partners evaluate, onboard, and consume your APIs by sending successful requests quickly. A Partner user can't see other Partners and their activities in the workspace. They can see only your team members, while comments and other collaborative features are turned off to maintain isolation between Partners.
```

2024-01-25 16:16 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +1. In the Workspace Overview page, select **Workspace Settings**.
```suggestion
1. In the Workspace Overview page, select <img alt="Workspace settings icon" src="https://assets.postman.com/postman-docs/v10/icon-sliders-v10.jpg#icon" width="24px"> **Workspace Settings**.
```

2024-01-25 16:19 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +1. Select **Enable multipartner mode**.
In the GIF, it looks like the CTA is `Enable multi-partner mode`. I think we usually match the CTA label in this instance even though we're not using the en dash in the LC doc content.

2024-01-25 16:21 UTC, nerminamiller-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +1. Select **Enable multipartner mode**.
@MatthewPinsker-postman they’re planning to remove the hyphen in the UI

2024-01-25 16:22 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +Use the fork feature to share collections and environments from your internal Team workspaces to the Partner workspace. Partners can only be invited as Viewers to this workspace. However, team member
```suggestion
Use the fork feature to share collections and environments from your internal team workspaces to the Partner Workspace. Partners can only be invited as Viewers to this workspace. However, team members can be invited as Viewers, Editors, or Admins.
```

2024-01-25 16:24 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +Use the fork feature to share collections and environments from your internal Team workspaces to the Partner workspace. Partners can only be invited as Viewers to this workspace. However, team member
"Team workspace" isn't a branded term so it's always lowercase. Since "Partner Workspace" is a branded term, it's my understanding that we always use uppercase.

2024-01-25 16:24 UTC, MatthewPinsker-postman approved these changes
LGTM!

2024-01-25 16:24 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +1. Select **Enable multipartner mode**.
Thanks for clarifying!

2024-02-02 22:40 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +
What do you think about adding a TOC to the page?

2024-02-02 22:42 UTC, nerminamiller-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +
Good idea! Will add!

2024-02-02 22:51 UTC, nerminamiller-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +    The confirmation modal describes the key capabilities of the multi-partner mode.
I added the sentence about the confirmation modal to avoid duplication. I think the UI is intuitive enough but this is a good editorial catch.

2024-02-02 22:54 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +1. In the **Workspace Settings**, select the **Invite** button, then select _Partners_.
I think we style radio button options the same as buttons. [Example](https://learning.postman.com/docs/getting-started/basics/about-postman-agent/#selecting-a-postman-agent-for-requests)

2024-02-02 22:58 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +1. Enter the partner's name or email. Alternatively, you can select **Add from file** to insert a .csv or .txt file containing contact information.
```suggestion
1. Enter the partner's name or email. Alternatively, you can select **Add from file** to insert a csv or txt file containing contact information.
```

2024-02-02 22:59 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +1. Enter the partner's name or email. Alternatively, you can select **Add from file** to insert a .csv or .txt file containing contact information.
I double checked the style guide, and we don't typically include the `.`

2024-02-02 22:59 UTC, nerminamiller-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +1. Enter the partner's name or email. Alternatively, you can select **Add from file** to insert a .csv or .txt file containing contact information.
Stet. File extensions take lowercase plus dot or all caps format.

2024-02-02 23:02 UTC, MatthewPinsker-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +    > You can optionally select a Partner Lead role checkbox, to enable the partner to invite other partners to the workspace. However, Partner Leads can only invite other partners from their domain.
What do you think about mentioning something in the intro or about section about how partners are grouped by domain? Suggesting this because I wasn't sure what "domain" meant in this context until I continued to the next section.

2024-02-02 23:04 UTC, nerminamiller-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +1. Enter the partner's name or email. Alternatively, you can select **Add from file** to insert a .csv or .txt file containing contact information.
```suggestion
1. Enter the partner's name or email. Alternatively, you can select **Add from file** to insert a CSV or TXT file containing contact information.
```

2024-02-02 23:08 UTC, nerminamiller-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +1. Enter the partner's name or email. Alternatively, you can select **Add from file** to insert a .csv or .txt file containing contact information.
Ok, I didn’t realize we defaulted to one option. Will make sure to check the style guide more often. I capitalized the file types according to our style.

2024-02-02 23:16 UTC, MatthewPinsker-postman approved these changes
LGTM! I added a few suggestions.

2024-02-03 00:41 UTC, ramji367 commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +Use the fork feature to share collections and environments from your internal team workspaces to the Partner Workspace.
Can we say 'We recommend that you fork collections and environments from your internal team workspaces to the Partner workspace' ?

2024-02-03 00:56 UTC, ramji367 commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +title: "Publish your APIs to multiple partners using a single Postman workspace"
Let's change the title to 'Collaborate with multiple partners using multi-partner mode'. In future this will be a sub-page under Partner workspaces.

2024-02-03 01:46 UTC, nerminamiller-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +Use the fork feature to share collections and environments from your internal team workspaces to the Partner Workspace.
Done!

2024-02-03 01:47 UTC, nerminamiller-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +title: "Publish your APIs to multiple partners using a single Postman workspace"
I’ve applied your feedback, but I’d like @jkonrath-postman’s feedback on the word choice.

2024-02-05 14:52 UTC, jkonrath-postman commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +Use the fork feature to share collections and environments from your internal team workspaces to the Partner Workspace.
I'll explain in slack...

2024-02-05 17:04 UTC, ramji367 requested changes
Looks good! Added some last comments

2024-02-05 17:04 UTC, ramji367 commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +1. Select **Limit Partner Visibility**.
@nerminamiller-postman - We don't need this line about 'Select Limit Partner Visibility'. This was the old name for Multi-partner mode button, which we have changed.

2024-02-05 17:04 UTC, ramji367 commented on src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
> +    Now the partners in this workspace can't see each other or make any edits. They can view all workspace resources, send API requests, and see responses.
@nerminamiller-postman - Can you include 'run collections' here before 'see responses'?

2024-02-05 17:28 UTC, ramji367 approved these changes
Looks good. Thank you for addressing all the comments!

2024-02-06 21:41 UTC, jkonrath-postman approved these changes

2024-02-09 16:42 UTC, merged