[TW-1862] Live Insights onboarding update
postmanlabs/postman-docs pull request #5438
Opened 2024-03-08 15:33 UTC by nerminamiller-postman

Updates all Insights topics for 3/11 release

2024-03-08 21:37 UTC, mgritter approved these changes

2024-03-08 23:06 UTC, liujed requested changes
Looks good, though there are a few places where we've missed the LCA → Insights Agent conversion. I've indicated which feedback items I think are blocking vs. non-blocking.

2024-03-10 04:10 UTC, mgritter commented on src/pages/docs/insights/insights-overview.md
> +* Postman generates a maximum of 10 folders per Insights Project, and 300 requests per folder. The Insights team is working on expanding this.
Hm... I think we should probably delete this bullet point.  I think that I did not put a limit for curated collections (though it came up in review).

https://github.com/akitasoftware/superstar/blob/af3447302d49a96d72758ffdd51ad13182714830/lib/api-transformer/http_rest/convert/postman_collection_converter.go#L398

2024-03-11 13:42 UTC, jkonrath-postman approved these changes
LGTM

2024-03-11 13:44 UTC, merged